### ISSUE TITLE
VRO code handoff: Camel routes

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1025]
**User Story**

As a VRO engineer, I want to learn about and document the Camel routes that have been built in VRO iMVP, so that I and my teammates can maintain and iterate on this code going forward.

- Coordinate with **Alan Thompson** on the Amida team to complete this handoff (you can reach out to Alan on slack in the #benefits-virtual-regional-office channel)
- Set up one or more meetings to walk through the Camel routes with Alan, or someone he delegates 
- - When sessions are scheduled, post in #benefits-virtual-regional-office with the details of the session so that other teammates can join if interested and available
- - Record any sessions you hold for future reference
- Update or create written documentation of the Camel routes in the Github wiki so that future VRO engineers can get up-to-speed and complete any standard tasks related to Camel routes. 
- - If documentation has been created already by Dimitri/other Amida engineers, review the documentation and comment or reach out to Dimitri with any questions or clarifications. Amida should then make updates and pass it back to you for review.

**Acceptance Criteria**

1. Camel routes walk through(s) have been scheduled, announced to the team at large, and recorded when held
2. Camel routes documentation has been created/updated to a sufficient level of detail to enable future VRO engineers to get up-to-speed and pick up work on the Camel routes

**Not included in this work**

If you identify necessary improvements to the Camel routes code in the course of these handoff activities, that enhancement work is out of scope for this ticket. **Please create new tickets to capture any code improvement needs you identify**

**Comment by ioarash** [comment]
I am in contact with Alan, he is going to share a walkthrough video for me to get prepare for our conversation and we will schedule the first session this week.

**Comment by ioarash** [comment]
Here are the link to the handoff sessions for Camel routes.
[Session one](https://drive.google.com/file/d/1QQ7-kYBOBCh7N4ulXUKp8EQEvNIXo0PO/view?usp=share_link)
[Session two](https://drive.google.com/file/d/1BMtSjDao8x_JPoz-q1d2tFWOelo0XqBM/view?usp=share_link)

Also updating Camel Routes wiki.
