### ISSUE TITLE
VRO code handoff: BIP API integrations

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1028]
**User Story**

As a VRO engineer, I want to learn about and document the BIP API integrations that have been built in VRO iMVP, so that I and my teammates can maintain and iterate on this code going forward.

The BIP API integrations include:
- The Claims API, used for making updates to claim status and contention special issues
- The Claim Evidence API, used for uploading documents (pdf) to the VBMS eFolder associated with the claim record

- Coordinate with **~~Warren Lin~~ Afsin Ustundag** on the Amida team to complete this handoff (you can reach out to ~~Warren~~ Afsin on slack in the #benefits-virtual-regional-office channel)
- Set up one or more meetings to walk through the BIP API integrations with ~~Warren~~ Afsin
- - When sessions are scheduled, post in #benefits-virtual-regional-office with the details of the session so that other teammates can join if interested and available
- - Record any sessions you hold for future reference
- Update or create written documentation of the BIP API integrations in the Github wiki so that future VRO engineers can get up-to-speed and complete any standard tasks related to the BIP API integrations. 
- - If documentation has been created already by ~~Warren~~Afsin/other Amida engineers, review the documentation and comment or reach out to ~~Warren~~ Afsin with any initial questions or clarifications. Warren should then make updates and pass it back to you for review.

**Acceptance Criteria**

1. BIP API integration walk through(s) have been scheduled, announced to the team at large, and recorded when held
2. BIP API integration documentation has been created/updated to a sufficient level of detail to enable future VRO engineers to get up-to-speed and pick up work on the BIP API integrations

**Not included in this work**

If you identify necessary improvements to the BIP API integration code in the course of these handoff activities, that enhancement work is out of scope for this ticket. **Please create new tickets to capture any code improvement needs you identify**

**Comment by dianagriffin** [comment]
@sethdarragile6 heads up that these BIP API integrations have faced a number of sticky challenges in implementation. @amprokop and Steve Albers have both been involved in supporting at various points and may be able to offer pointers/support for this handoff effort.

**Comment by sethdarragile6** [comment]
Link to [folder](https://drive.google.com/drive/folders/1Tln8y5zpiCaNOv7-a_0XJ-xytV9keT-l?usp=sharing) and [video](https://drive.google.com/file/d/1BBiODuDmLpcRFyVgXwSSiQTMi-XfWgX9/view?usp=sharing)
