### ISSUE TITLE
VRO code handoff: Database tables and columns

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1030]
**User Story**

As a VRO engineer, I want to learn about and document the database tables and columns that have been built in VRO iMVP, so that I and my teammates can maintain and iterate on this code going forward.

- Coordinate with **Afsin Ustundag** on the Amida team to complete this handoff (you can reach out to Afsin on slack in the #benefits-virtual-regional-office channel)
- Set up one or more meetings to walk through the database tables and columns with Afsin 
- - When sessions are scheduled, post in #benefits-virtual-regional-office with the details of the session so that other teammates can join if interested and available
- - Record any sessions you hold for future reference
- Update or create written documentation of the database tables and columns in the Github wiki so that future VRO engineers can get up-to-speed and complete any standard tasks related to the database. 
- - If documentation has been created already by Afsin/other Amida engineers, review the documentation and comment or reach out to Afsin with any questions or clarifications. Afsin should then make updates and pass it back to you for review.

**Acceptance Criteria**

1. Database tables and columns walk through(s) have been scheduled, announced to the team at large, and recorded when held
2. Database tables and columns documentation has been created/updated to a sufficient level of detail to enable future VRO engineers to get up-to-speed and pick up work on the database

**Not included in this work**

If you identify necessary improvements to the database code in the course of these handoff activities, that enhancement work is out of scope for this ticket. **Please create new tickets to capture any code improvement needs you identify**

**Comment by yoomlam** [comment]
There's a [set of DB changes](https://dsva.slack.com/archives/C01Q7979Z7D/p1674237329439659?thread_ts=1674144499.310049&cid=C01Q7979Z7D) requested of Amida. Ensure changes are captured in the documentation, ask for instructions to run manual tests, run the tests, and check the DB contents for the expected data.

**Comment by yoomlam** [comment]
[Slack](https://dsva.slack.com/archives/C01Q7979Z7D/p1678737616802549?thread_ts=1678207065.568629&cid=C01Q7979Z7D):
> Whenever the DB documentation is updated, please let me know so I can schedule a good time when most OCTO folks are available.

**Comment by yoomlam** [comment]
Amida intends to add [DB comments](https://www.postgresql.org/docs/current/sql-comment.html) that explain each DB column and table, so remember to look for that.
