### ISSUE TITLE
Document Platform team's technical vision

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#1053]
Related to [these thoughts](https://dsva.slack.com/archives/C03JRKKD11B/p1675697238276689?thread_ts=1675372038.653119&cid=C03JRKKD11B), we should document what VRO software is expected to look like technically so that we can come to a consensus.
The documentation will impact how VRO is presented to other teams who want to add to VRO and substantiate code refactoring needed to get VRO into a mature state.

**Comment by yoomlam** [comment]
Created Google docs:
- VRO Team: Onboarding - will be shared once reviewed
- [VRO Software Conventions
](https://docs.google.com/document/d/1w962R2kFlepq-AcwaOcgNmgtS2a_lBUB91AzesoCTkU/edit#)

**Comment by dianagriffin** [comment]
@dianagriffin review the responsibilities doc and unassign yourself here when done

**Comment by yoomlam** [comment]
Review responsibilities doc with Diana and Tom, and [re-shared conventions](https://dsva.slack.com/archives/C04QLHM9LR0/p1677273315805269)

**Comment by dianagriffin** [comment]
Identified https://github.com/department-of-veterans-affairs/abd-vro/issues/1202 as the next step for refining and socializing VRO software Conventions
