### ISSUE TITLE
HTN exploratory research - review secondary research

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#1055]
As part of the HTN exploratory research, we want to review previous research that could yield insights into veteran wait time and RVSR touch time. 

## Activities may include 

- [x] Review ABD design and research index for relevant studies
- [x] Review OCTO research repo
- [ ] #1124
- [x] Review VEO benefits application research

## Sources

- [x] [VSR Journey Map](https://app.mural.co/t/nava4113/m/nava4113/1629127127393/79eff6cd37a254993bb9907aa80a50fcc47716a3?sender=carolyn1198)
- [x] [VEO benefits claims research](https://dsva.slack.com/archives/C0NGDDXME/p1675706769573009?thread_ts=1675692008.464739&cid=C0NGDDXME)(DSVA Slack 🔒)
- [x] [RVSR Journey map](https://app.mural.co/t/nava4113/m/nava4113/1671823366868/5650ebd05099fb643e9f48b49704a2eee8aad3b7?sender=carolyn1198)

**Comment by amylai-nava** [comment]
@carodew would you consider this "done for now" or should we move it to Sprint Otter, Sea? 🦦

**Comment by carodew** [comment]
Can we move to Sprint Otter, Sea please?

**Comment by carodew** [comment]
@amylai-nava Ok I finished the reviews that I could, and the only thing left at this point is to review the LA Site visit findings, and that's dependent on the findings being available. would it make sense to call this done for now and I can roll the LA site visit stuff into another ticket (either on it's own or, more likely, as part of a different ticket)?

**Comment by amylai-nava** [comment]
@carodew that makes sense to me!
