### ISSUE TITLE
write iMVP pilot shadowing research plan

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#1065]
We want to shadow RVSRs using the iMVP PDF to rate real claims to ensure that it is working as intended, and to be able to rapidly fix any major issues that come up. To do that we need a plan! This ticket is to create that plan.

**Comment by carodew** [comment]
[Draft plan](https://docs.google.com/document/d/19ajcGRhUXKkjootZ3n6kVqatQ-T8CrxJ4o9zi9gafm4/edit#).

**Comment by amylai-nava** [comment]
@carodew I'm going to move this to "done" even though I haven't had a chance to review it, because @KimLadin has! It's on my to-do list though, and I'll do it before the end of this week.
