### ISSUE TITLE
VRO code handoff: RRD logic & PDF generator

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1075]
**User Story**

As a VRO/HTN engineer, I want to learn about and document the RRD logic & PDF generator that have been built in VRO iMVP, so that I and my teammates can maintain and iterate on this code going forward.

- Coordinate with **Tony Velasquez and Julian Bregstone** on the Amida team to complete this handoff (you can reach out to them on slack in the #benefits-virtual-regional-office channel)
- Set up one or more meetings to walk through the logic and PDF generator with Tony/Julian
- - When sessions are scheduled, post in #benefits-virtual-regional-office with the details of the session so that other teammates can join if interested and available
- - Record any sessions you hold for future reference
- Update or create written documentation of the logic and PDF generator in the Github wiki so that future VRO/HTN engineers can get up-to-speed and complete any standard tasks related to the database. 
- - If documentation has been created already by, review the documentation and comment or reach out to Tony/Julian with any questions or clarifications. They should then make updates and pass it back to you for review.

**Acceptance Criteria**

1. RRD logic and PDF generator walk through(s) have been scheduled, announced to the team at large, and recorded when held
2. RRD logic and PDF generator documentation has been created/updated to a sufficient level of detail to enable future VRO engineers to get up-to-speed and pick up work on the database

**Not included in this work**

If you identify necessary improvements to the RRD logic and PDF generator code in the course of these handoff activities, that enhancement work is out of scope for this ticket. **Please create new tickets to capture any code improvement needs you identify**

**Comment by amylai-nava** [comment]
[Recording and notes](https://dsva.slack.com/archives/C01Q7979Z7D/p1675983691120879?thread_ts=1675972569.033039&cid=C01Q7979Z7D) for the PDF Generator 101 session held on 2/9/23

**Comment by nanotone** [comment]
[Recording](https://dsva.slack.com/archives/C01Q7979Z7D/p1677696097349709) for the PDF Generator 102 session held on 3/1/23
