### ISSUE TITLE
Gather materials in support of Next Gen proposed changes

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1078]
**User Story**

Gather/create materials for Paul + Andrew so that they can socialize the proposed Next Gen changes with MAS and VBA, backed by research insights.

**Acceptance Criteria**

1. Materials summarizing the proposed Next Gen changes and supporting research insights have been produced shared to Paul and Andrew

**Notes about work**
- [Relevant slack thread](https://dsva.slack.com/archives/C01AXBZA3QR/p1675968060841719?thread_ts=1675958980.472449&cid=C01AXBZA3QR)
- A continuation of https://github.com/department-of-veterans-affairs/abd-vro/issues/1024

**Comment by amylai-nava** [comment]
materials + discussion in slack: https://dsva.slack.com/archives/C03JRKKD11B/p1676396585480229
