### ISSUE TITLE
Scope Next Gen updates for HTN, asthma, and RRD design system

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1079]
**User Story**

Based on [engineering estimates](https://github.com/department-of-veterans-affairs/abd-vro/issues/1091), ~define the scope of Next Gen design updates that will be applied to HTN, asthma, and the RRD design system before asthma goes live in VRO, so that we can plan the Next Gen implementation~ determine how we will phase in Next-gen updates for each condition in coordination with the launch of the evidence summary generator in VRO.

**Acceptance Criteria**

1. ~Create a succinct list of updates for HTN, asthma, and the RRD design system. Leave out updates that would take longer than a few weeks or so, after scoping with engineering team.~
2. Document implementation timing of design updates + the evidence summary generator — [see Mural](https://app.mural.co/t/nava4113/m/nava4113/1664488162003/7f243e26ee7553cf9b0c3703200224ca635274ae?wid=0-1677021882888)

**Notes about work**
- [relevant slack thread](https://dsva.slack.com/archives/C01AXBZA3QR/p1675968060841719?thread_ts=1675958980.472449&cid=C01AXBZA3QR)

**Comment by amylai-nava** [comment]
@KimLadin This ticket has evolved since it was first written so the AC is not relevant anymore, but I consider it "done" because of this conversation and [decision](https://dsva.slack.com/archives/C03JRKKD11B/p1677198795389769?thread_ts=1676999603.606409&cid=C03JRKKD11B). What do you think?
