### ISSUE TITLE
Create a runbook for handling failures that block claims during processing in VRO

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1081]
**User Story**

As a VRO engineer, I want an easy to follow runbook for claim error handling, so that I can effectively respond to resolve an incident in prod.

In VRO, we have a manual process that allows us to remove the claim from being held for automated processing and send it back into manual processing in the event of an automation failure. This runbook will document that process.

Include:
- What triggers this event and how you can identify/verify that it is happening
- What systems access a person needs to diagnose & resolve the issue
- The steps to resolve the issue
- How to verify the problem is resolved
- After-action steps

We have a [VRO Console](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Console) that can query Redis and the DB. Data values in these resources can be used to determine the state of the claim and to retrieve the original payload request in case it needs to be manually resubmitted to VRO.
The VRO Console is not full featured, so the instructions in the runbook may require new features or automation be added to VRO or the Console.

**Acceptance Criteria**

1. Runbook has been created, reviewed by the team, refined based on feedback as necessary, and published in the VRO wiki

**Comment by dianagriffin** [comment]
Dependent on the database changes

**Comment by dianagriffin** [comment]
@yoomlam mentioned: "It would be good to ask Amida [about this error handling], in case they've thought about it and somehow incorporated it into the code."

**Comment by dianagriffin** [comment]
Yoom's take on an expedient solution would be that the runbook looks something like:
- go into the DB to determine the state of the claim (did VRO call external systems to change its state?)
- from that state, we need to transition it into the state were it can be processed manually (outside of VRO) (we know what this target state of the claim needs to be)

**Comment by dianagriffin** [comment]
@dianagriffin document here what the target state of the claim needs to be

**Comment by ioarash** [comment]
Updated Wiki
https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-failure-runbooks

**Comment by dianagriffin** [comment]
@pshahVA Please review for operational/comms pieces

**Comment by pshahVA** [comment]
I think this is a really solid start and is inline with what we are looking for. In addition let's all appreciate the fact that this document will probably evolve and change over time as we refine our processes.
