### ISSUE TITLE
Define VRO production support model

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1082]
[Placeholder -- will capture considerations and activities to define the support model here]

- scope for this prod support model is limited to the VRO application (not infrastructure, since we use the Lighthouse Delivery Infrastructure services which have their own support model)
  - We need to make the "tier 1" assessment to determine the source of the problem 
- document SLO & confirm no expectation for 24/7 support because low impact to Veterans
- contacts: @dianagriffin @pshahVA (VA Product Owner) @va-albers (OCTO engineering lead)

AC:
Link https://github.com/department-of-veterans-affairs/abd-vro/wiki/Support-Model-(-Draft-)

 1. Where this Document will be created.
 2. Who/Which team can have access to Document created above.
 3. Identify Software Components that Requires Support
 4. Determine Critical Escalation path for components Identified in step 1
 5. Tools (Like, Servicenow, Pagerduty) Required for Incident management
 6. Access Required for Tools and Environment
 7. Standard Operating Process for Escalation Policy ( Placeholder )
 8. Common Known Error and Troubleshooting steps ( placeholder )
 9. Oncall Rotation Process ( placeholder )
 10. Access to Supporting Environment and Necessary troubleshooting knowledge guide for Engieering oncall ( placeholder )

**Comment by dianagriffin** [comment]
Questions & things to figure out:
- What does VRO team monitor vs. what do contention teams monitor? 
- Does deploying to VRO cause any downtime once we're in production?

**Comment by dianagriffin** [comment]
What's an "MVP" production support model? 
- would be valuable to have at least a wiki page outlining the expectations
- what level of support is expected? how will we meet that?

**Comment by dianagriffin** [comment]
@tcraghu will take a first pass at drafting acceptance criteria for an MVP production support model

**Comment by smythe5** [comment]
@dianagriffin

**Comment by dianagriffin** [comment]
Are there general devops procedures/policies that should be in place regardless of the product being supported? (ex. set up PagerDuty and/or other tools)
