### ISSUE TITLE
Document JWT Bearer Token use in Swagger UI instructions

### ISSUE THREAD

**Issue by greene858** [department-of-veterans-affairs/abd-vro#1108]
**User Story**

As a VRO engineer I would like to test the JWT authentication functions with the Swagger UI test tools
, so that I can maintain the authentication functions and confirm that they are working as expected.

- Update Swagger UI instructions for the iMVP (v2): https://github.com/department-of-veterans-affairs/abd-vro/wiki/Testing-using-Swagger-UI, specifically providing instructions on how to create a JWT Bearer token

- Utilize existing notes here https://github.com/department-of-veterans-affairs/abd-vro/issues/591#issuecomment-1302594447

**Acceptance Criteria**

1. Swagger UI documentation includes instructions on creating and using a JWT token
2. Created token passes authentication

**Comment by dianagriffin** [comment]
@greene858 to write up specific instructions for @yoomlam to follow for his review

**Comment by engineer-plus-plus** [comment]
What's the best way to provide feedback and suggestions for the documentation that is the object of this story?  If this were google docs, I'd use the comments functionality.  But I don't think github offers it.  And branching merge requesting seems like overkill.
