### ISSUE TITLE
VRO code handoff: Initial unit test review

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1171]
**User Story**

As a VRO engineer, I want to confirm that unit tests written for iMVP functionality provide high code coverage and are small, fast, understandable in isolation, so that I and my teammates can maintain and iterate on them going forward.

For a small enough area of the code to be able to confirm all 5 bullet points within 2-3 days, confirm that:
- Tests are well named (concise not generic names)
- Unit tests focus on testing only one class at a time
- Identify tests that could be improved
- Are there tests that we expect to fail, e.g., a test that depends on a timestamp?
- Explicitly exclude code that is not covered by a test (https://stackoverflow.com/questions/29887805/filter-jacoco-coverage-reports-with-gradle) to get coverage to 100%

Review the unit tests in the VRO codebase. As necessary, 
- Meet with **TBD contacts from Diana** on the Amida team to complete this handoff (you can reach out to Alan and Ian on slack in the #benefits-vro-support channel): ask the Amida engineers on the status to complete the test suite
- If you think it would be helpful, schedule walk throughs and post in #benefits-virtual-regional-office with the details of the session, and record any sessions you hold for future reference
- Update or create any documentation you deem necessary

**Acceptance Criteria**

1. Unit tests have been confirmed to provide high code coverage and be small, fast, understandable in isolation according to the criteria noted above.
2. Identify subsequent tickets for further areas to examine unit test implementation

**Not included in this work**

If you identify necessary improvements to the unit tests in the course of these handoff activities, that enhancement work is out of scope for this ticket. **Please create new tickets to capture any code improvement needs you identify**

**Comment by dianagriffin** [comment]
@dianagriffin spin off a time boxed ticket for evaluating a portion of the unit test implementation (looking for a go/no-go in terms of adequacy for completing handoff of this unit tests topic)

**Comment by ioarash** [comment]
- Reviewed the test cases available, the naming is concise and descriptive of the performed test.
- I can confirm that we have happy path and failure path as well, but this is an overall review and need to get into more details with the code coverage.
- I have a list of the coverage percentages which I am going to share with Amida team to improve to 100%
- Will reach out to the Amida team again today.
