### ISSUE TITLE
Allow PDFGenerator to be called from command line

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1175]
Placeholder task for the related PR: https://github.com/department-of-veterans-affairs/abd-vro/pull/712

**Comment by amylai-nava** [comment]
@nanotone should I move this to Sprint Q or the backlog?

**Comment by nanotone** [comment]
@amylai-nava Yeah good call, I do still want to get this done but I wouldn't commit to it for Sprint Q. I'll move it to the backlog.

**Comment by amylai-nava** [comment]
Closing as not planned.
