### ISSUE TITLE
Create iMVP evidence summary designs to handle multi-issue claims

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1194]
**User Story**

As an engineer, I want to know what the iMVP evidence summary designs are for multi-issue claims ~and MAS~ so I can build it according to the design spec.

**Acceptance Criteria**

1. iMVP evidence summary designs for multi-issue claims (with and without Hypertension)
2. ~iMVP evidence summary designs for single-issue claims for MAS conditions~

**Notes about this work**

- [Content architecture (Mural)](https://app.mural.co/t/nava4113/m/nava4113/1664488162003/7f243e26ee7553cf9b0c3703200224ca635274ae?wid=0-1677118110054)
- [Figma file](https://www.figma.com/file/gENy7VJcPxq35DmqCit5av/iMVP-designs?node-id=509%3A269&t=CEzF0pnNYODxntbH-1)
- [Google doc file ](https://docs.google.com/document/d/1RAu4IW8N9OtBVsLh9InOu3pSsUnqa-sgHV99C9CGDu0/edit?usp=sharing)

**Comment by amylai-nava** [comment]
@KimLadin I created this placeholder task to track design tasks related to multi-issue claims. Feel free to edit this or break it up into smaller tasks.

**Comment by amylai-nava** [comment]
Notes from sprint planning:
- @ChristineRoseSteiffer and @carodew  are going to pair on this task, with Christine driving it and Carolyn providing guidance
- Christine/Carolyn/Yang/Amy will meet this week to review the initial draft of the design and discuss what's needed for eng tickets

cc: @KimLadin

**Comment by carodew** [comment]
Update – In sprint review, Shannon had some questions / feedback on how we're displaying the flash information. Here's a summary: 

**Question:**

- How will we display corporate flashes when >1 condition in the PDF has a relevant flash?

**What we know:**

- Current ARSD shows flash information in the table with other service history keywords

- We think we have an example of this in some of the HDR examples in SharePoint

**Open question:**

- What kind of data are we getting for flashes and how are we getting it? (I believe we said we know they’re coming in as attached to the veteran, not a specific condition)

**Next steps:**

- HTN design team to take this question back for further exploration

**Comment by amylai-nava** [comment]
@carodew @ChristineRoseSteiffer cc: @KimLadin  I updated the description of the ticket to better reflect the scope of work (evidence summary design for multi-issue claims, and not MAS claims).

I think we can consider this done, and create new tickets for any additional design updates that came out of last week's meetings with MAS. Does that sound good to y'all?

**Comment by amylai-nava** [comment]
**4/12 update:** will pick this back up next week after further conversations with OBA/MAS on 4/18 about the condition history and service connection sections.

**Comment by amylai-nava** [comment]
Closing as completed, even though usability testing was postponed.
