### ISSUE TITLE
Remove asynchronous Collection Status check prior to retrieving a claim's Annotations

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1215]
**User Story**

As a VRO engineer, I want to reduce the complexity of the RRD workflow in VRO by removing the asynchronous processing around calling the MAS Collection Status API, so that the VRO code is simplified and easier to maintain and test. 

**Context** 
Originally MAS proposed a workflow in which they would notify VRO of automation eligible claims while OCR is still running on the claim. The assumption was that OCR processing would take some time (~ an hour), so VRO implemented an asynchronous call to the MAS Collection Status API so that VRO could check if annotations for the claim were complete prior to calling the Annotations API to retrieve the annotations data. 

However, MAS ended up implementing a different work flow where they notify VRO of automation eligible claims only after OCR processing has completed, meaning the asynchronous handling is unnecessary. 

**Acceptance Criteria**

1. _Acceptance criteria 1_
2. _Acceptance criteria 2_
3. _Acceptance criteria 3_

**Not included in this work**

A note about things that should not be considered necessary.

**Notes about work**
- _(links to documentation, resources, code, etc that might inform the person doing the work)_

**Comment by yoomlam** [comment]
OBE
