### ISSUE TITLE
[Amida] Update Lighthouse API call to retry on failure.

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/abd-vro#1253]
**User Story**

As a VSR/RVSR, I want the VRO system to retry API calls, to increase the number of automated processed claims.

**Acceptance Criteria**

1. The team and product leadership agrees on a API retry pattern.
2. Team wiki is updated with explanation of the implementation
3. The team implements API retry for the current Lighthouse API call.
4. Tests include the API retry case.
5. Retry behavior is surfaced in logs for observability
6. Other APIs are reviewed as candidate for future updates.
7. Plan is in place to review the results after launch (how many failures occurred, how often the retry pattern addressed the issue)

**Not included in this work**

This initial ticket focus specifically on the Lighthouse API call only

**Notes about work**

**Comment by yoomlam** [comment]
To be assigned to Amida

**Comment by dianagriffin** [comment]
Implemented in https://github.com/department-of-veterans-affairs/abd-vro/pull/1393
