### ISSUE TITLE
Ensure VRO completes processing on invalid claims sent from MAS.

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/abd-vro#1258]
**User Story**

As a VA Veterans Benefit Administration official, I want to verify that all VRO-handled claims are processed in a timely way to avoid delays in veteran claims adjudication.

As a VRO maintainer, I want to reduce the amount of toil spent monitoring for, and manually resolving, "stuck" claim cases caused by invalid claims sent to the VRO system

**Acceptance Criteria**

1. Document cases where invalid claims sent to VRO cannot be handled (claims that fall outside the range of acceptable inputs for processing).
2. Validate the state that rejected claims should be left in (remove RRD, special issue and station assignment.  Verify what to do for automation indicator) 
3. The system properly updates invalid claims as documented in points 1 and 2 above.
4. Tests to validate cases written and passed.  
5. The system logs exception cases for review.

**Not included in this work**

**Notes about work**
- [Error_scenarios checklist spreadsheet, line 3](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B38A7304F-D531-410D-892D-C4733FDB09FA%7D&file=error_scenarios.xlsx&_DSL=1&action=default&mobileredirect=true&cid=6e1edd1d-3aae-4015-9da8-ca5c056dfc8f)

**Comment by dianagriffin** [comment]
> 1. Document cases where invalid claims sent to VRO cannot be handled (claims that fall outside the range of acceptable inputs for processing).
- Afsin documented this here: https://lighthouseva.slack.com/files/U03GVR68Q6L/F04UB2LNA86/mas-mcp_automated_claim_contract.docx

> 2. Validate the state that rejected claims should be left in (remove RRD, special issue and station assignment. Verify what to do for automation indicator)
- Documented on wiki here: https://github.com/department-of-veterans-affairs/abd-vro/wiki/iMVP-claim-and-contention-update-scenarios
- Related ticket here, being worked by Amida: https://github.com/department-of-veterans-affairs/abd-vro/issues/1286
