### ISSUE TITLE
Automatically process claims with no exam ordering confirmation from MAS

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/abd-vro#1259]
**User Story**

As a VA Veterans Benefit Administration official, I want to verify that all VRO-handled claims are processed in a timely way to avoid delays in veteran claims adjudication.

As a VRO maintainer, I want to reduce the amount of toil spent monitoring for, and manually resolving, "stuck" claim cases caused by claims sent from MAS with no exam ordering confirmation.

**Acceptance Criteria**

1. Document process for automatically handling this case (remove RRD, special issue and station assignment, check on automation indicator).
2. The system properly updates invalid claims as documented in points 1 above.
3. Tests to validate cases written and passed.  
4. The system logs exception cases for review.

**Not included in this work**

**Notes about work**
- [Error_scenarios checklist spreadsheet, line 4](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B38A7304F-D531-410D-892D-C4733FDB09FA%7D&file=error_scenarios.xlsx&_DSL=1&action=default&mobileredirect=true&cid=6e1edd1d-3aae-4015-9da8-ca5c056dfc8f)

**Comment by dianagriffin** [comment]
These requirements are now covered by #1314; closing this one as a duplicate.
