### ISSUE TITLE
Plan usability testing for Multi-issue PDF design

### ISSUE THREAD

**Issue by KimLadin** [department-of-veterans-affairs/abd-vro#1280]
Here is a link to the draft research plan + discussion guide - 

https://docs.google.com/document/d/1CaS3jNk7yZ28OlPbhXF9YWED9tOtNHQbWOcJZ1QlQG8/edit#heading=h.hhevn0icya3z

**Comment by amylai-nava** [comment]
@KimLadin @ChristineRoseSteiffer can you link the research plan and add any other relevant info to the description? ty!

**Comment by ChristineRoseSteiffer** [comment]
@amylai-nava @KimLadin Here is the link to the draft research plan + discussion guide - thanks!

https://docs.google.com/document/d/1CaS3jNk7yZ28OlPbhXF9YWED9tOtNHQbWOcJZ1QlQG8/edit#heading=h.hhevn0icya3z

**Comment by amylai-nava** [comment]
**4/12 update:** will pick this back up next week after further conversations with OBA/MAS on 4/18 about the condition history and service connection sections.

**Comment by amylai-nava** [comment]
Closing as completed. Although usability testing was postponed due to TERA, the preparation for it was done ✅
