### ISSUE TITLE
Automatically handle claim cases when exam ordering fails

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/abd-vro#1282]
**User Story**

As a VA Veterans Benefit Administration official, I want to verify that all VRO-handled claims are processed in a timely way to avoid delays in veteran claims adjudication.

As a VRO maintainer, I want to reduce the amount of toil spent monitoring for, and manually resolving, "stuck" claim cases caused by failures while ordering exams.

**Acceptance Criteria**

1. Document process for automatically handling this case (remove RRD, special issue and station assignment, verify action for automation indicator).
2. The system properly handles the case (manual ordering and agreed-upon ticket resolution)
3. Tests to validate cases written and passed.  
4. The system logs exception cases for review.

**Not included in this work**

**Notes about work**
- [Error_scenarios checklist spreadsheet, line 5](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B38A7304F-D531-410D-892D-C4733FDB09FA%7D&file=error_scenarios.xlsx&_DSL=1&action=default&mobileredirect=true&cid=6e1edd1d-3aae-4015-9da8-ca5c056dfc8f)

**Comment by dianagriffin** [comment]
These requirements are now being tracked under #1288 and #1312. Closing this ticket as a duplicate now that those tickets have been broken out.
