### ISSUE TITLE
HTN exploratory research: file hygiene

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#1291]
@carodew Move files into their appropriate locations: 

- [x] @ChristineRoseSteiffer Move Google docs >> Sharepoint (add Sharepoint links to research report) 
- [x] @carodew Move Nava Murals >> [VA Mural](https://app.mural.co/t/departmentofveteransaffairs9999/r/1613770853903?folderUuid=ff0d00ad-9148-4204-bdaa-08cf9c0c94fa)
- [x] @carodew Move Videos >> Sharepoint (Share with Lesley!) (they may all be there already)
- [x] @ChristineRoseSteiffer find/replace research participant names in transcripts / notes
- [x] @ChristineRoseSteiffer delete or schedule deletion of videos
- [x] @ChristineRoseSteiffer Delete (or schedule deletion) the one video in Sharepoint that contains veteran PII
- [x] Move transcripts >> Sharepoint (they may all be there already)
- [X] update ABD research tracker 
- [x] @ChristineRoseSteiffer update design and research index (both in [Google docs](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit#heading=h.ajia8sm4jjwm) / Sharepoint)

**Comment by amylai-nava** [comment]
moving from Sprint T --> Sprint U
