### ISSUE TITLE
Limit access to K8s and its secrets

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#1322]
Anyone in the [VA-ABD-RRD GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/va-abd-rrd/members) has access to secrets used by VRO for all deployment environments. This is how LHDI is set up.
Currently, we add contributing members and Partner team members to VA-ABD-RRD. This does not follow the [least privilege principle](https://csrc.nist.gov/glossary/term/least_privilege) for security.

Possible solution: reserve the VA-ABD-RRD GitHub team for VRO DevOps and VRO admins. Create separate GitHub team(s) for contributing to the code and other purposes.

**Comment by dianagriffin** [comment]
one procedure option: 
- create a new team, give that team the same access to the repo as the original team (an eng can do this) 
- slowly start removing members from the original team, check up with people that they haven't been disrupted as we make the change (PM can do this)

**Comment by dianagriffin** [comment]
Note: look at the secret management doc from OCTO.

**Comment by greene858** [comment]
AC This is done when only VRO Admins (TBD) can access K8s secrets. Current GitHub team will be reduced to only VRO admins. All other devs working with VRO will be moved to new GitHub Team. Onboarding docs updated.

**Comment by yoomlam** [comment]
[Progress](https://dsva.slack.com/archives/C04QLHM9LR0/p1687366852209809?thread_ts=1687363797.127479&cid=C04QLHM9LR0)

**Comment by yoomlam** [comment]
Updated wiki pages:
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/Github-Actions
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/Local-Setup
- https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki

**Comment by msnwatson** [comment]
This all LGTM
