### ISSUE TITLE
Onboard Meg

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1325]
Welcome, Meg! We are excited to have you on the team! 

This ticket exists to lay out some logistical to-do's alongside areas of focus for getting up to speed on the VRO team and our work. 

**To be done for you** - @dianagriffin 

- [x] Invite Meg to DSVA, Lighthouse Slack spaces
- [x] Add Meg to VA Github Org ([form here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new/choose))
- [x] Add Meg to [abd-vro Github team](https://github.com/orgs/department-of-veterans-affairs/teams/va-abd-rrd/members?add=true)
- [x] Introduce Meg in #benefits-onboarding channel
- [x] Add Meg to recurring team meeting invites
- [x] Add to the VA ABD Sharepoint site as an Owner -- _once Meg has a VA email address_
- [x] Invite to the VA ABD Team Calendar in Google
- [x] Invite to the OCTO Benefits Delivery Team room in the VA Mural Workspace (as a guest)

**To do** -- Meg

- [x] Join relevant [slack channels](https://docs.google.com/spreadsheets/d/1c3e6SVuhVz3q4bh1qf5jj25EmusCd3NVXhDjSIpr9yk/edit#gid=1020923043) -- _you don't have to join ALL these channels; start with the #benefits-vro-* and #benefits-cft-* and you can expand from there as you get more involved in the work. Feel free to ask the team in #benefits-vro if you're wondering about whether to join a particular channel._
- [x] Join [recurring team meetings](https://docs.google.com/document/d/12oaUy0vmv--BFdUhoXk69FtLkhb5Bp0_woOWoD5P3iY/edit#heading=h.p2uqu6tmjnaw) -- _they should be on your calendar!_
- [x] Go through Benefits Portfolio onboarding materials and onboarding buddy meetings (see #benefits-onboarding channel in Slack) 
- [x] Have a 1:1 meet & greet with our VA Product Owner, Premal Shah! _note Premal is OOO 4/3-4/7 and has an offsite the week of 4/10, so scheduling for the week of 4/17 might work best. See Premal's slack profile for a calendar URL where you can find available times_
- [x] Set up a meet & greet with OCTO design leads, Shannon Ford and Lesley Ropp! See their slack profiles for a calendar URL where you can find available times
- [x] When you get a VA email address, add it to your Github account
- [ ] _more to come..._

**Non-prioritized ideas for work/tasks to get involved in when initial onboarding wraps up**
- [ ] Take ownership of Next-Gen design system (get history & context from Kim, take ownership of the Figma file, do the necessary updates/tidying to get it in a state we can come back to later)
- [ ] Facilitate VRO ["team API" discussion](https://github.com/TeamTopologies/Team-API-template) 
- [ ] Collab with Diana to pick up synthesis/next steps from [What is VRO?](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1653424407090/46c1aff7e984db50fc9a436b5f647199b31f14a8?wid=0-1680039295735) lightweight visioning sessions
- [ ] Take handoff of platform onboarding research from Carolyn & consider next steps for developer experience

**Comment by megameg** [comment]
Adding a couple more so they're all in one place:

- [ ] Get fingerprinted
- [ ] fill out all forms for background check
- [ ] scan & save all forms for background check
- [ ] send encrypted forms

**Comment by megameg** [comment]
- [ ] Once I get va.gov email address, inform Diana

**Comment by megameg** [comment]
- [ ] eQip form
- [ ] TMS training (by Fri)
