### ISSUE TITLE
Update VRO workflow to use BGS service to add automation outcome notes to claims processed by VRO

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1341]
### **User Story**
As a RVSR, I want to use the claim notes to understand what was completed by automation so I know how to proceed with claim processing.

As a member of PA&I, I want to use the claim notes to report off of the effectiveness/deferral rate of the program overall.

### **Acceptance Criteria**
VRO adds a note(s) to all single issue hypertension claims (new and increase) that VRO assesses for automation.
- If the claim and contention is set to RFD, add a:
  >**Veteran-level note**: "Hypertension automated review summary document uploaded MM/DD/YYYY" (datetime the ARSD was uploaded to the eFolder)

  >**Claim-level note**: "Claim status updated to RFD via automation"

  >**Claim-level note**: "Please note, the automated review summary document (ARSD) has been completed in full. One or more contentions were determined to be RFD by current rating criteria. Necessary exams were requested or drafted."

- If an exam is requested, add a:
  >**Veteran-level note**: "Hypertension automated review summary document uploaded MM/DD/YYYY" (datetime the ARSD was uploaded to the eFolder)

  >**Claim-level note**: "Please note, the automated review summary document has been completed in full with the necessary exam(s) requested or drafted based on automation eligible contention(s). This claim/contention has been placed in the Open Status Development Life Cycle for further review by a claims processor."

- If the claim is OFFRAMPED with either offrampReason `newClaimMissingFlash266` (we've assessed the claim, and we can't confirm presumptive service connection) or offrampReason `insufficientHealthDataToOrderExam`, add:
  >**Claim-level note**: "Automation-eligible contentions reviewed, but no action taken based on existing evidence. This claim has been removed from the automation program and placed in Open status for development by a claims processor."

- If claim is offramped due to ARSD upload failure, add a: 
  >**Claim-level note**: "Claim was offramped from VBA automation platform when ARSD could not be uploaded to eFolder."

### **Assumptions**
All other notes related to eligibility, automation exam request issues, and HDR records will be handled by MAS, because it occurs before the claim is handed off to VRO or it's related to exam requests.

### **Not included in this work**
- Connectivity to BGS and creation of VRO Ruby microservice to make BGS calls (#1289)
- Retry logic in case initial call to BGS fails (#1343)
- Error handling in case BGS service is unavailable or fails (#1342)

### **Notes about work**
- Relevant [slack thread](https://dsva.slack.com/archives/C03JRKKD11B/p1678816174826579)

**Comment by yoomlam** [comment]
To support the note:
> "Hypertension automated review summary document uploaded MM/DD/YYYY"

We should add a `uploadedAt` field to `EvidenceSummaryDocumentEntity`.

**Comment by dianagriffin** [comment]
Requested confirmation of our assumptions about which notes MAS will continue to be responsible for, [here](https://dsva.slack.com/archives/C0309PZT20Z/p1679949939986209?thread_ts=1679949931.615969&cid=C0309PZT20Z)

**Comment by dianagriffin** [comment]
#1341, #1342, #1343 = Yoom (workflow & retries/error handling)
create unit tests
create BGS mock service 
^ creating automated integration testing (dependent on above)
Add image to build workflow
^ Ensure the new Ruby image can pass SecRel (dependent on above)

**Comment by dianagriffin** [comment]
Investigating [here](https://dsva.slack.com/archives/C04QLHM9LR0/p1679955342277259?thread_ts=1679334550.312949&cid=C04QLHM9LR0) whether the ARSD upload datetime can be appended to a single note with the RFD-specific or exam-specific text

**Comment by yoomlam** [comment]
Implemented to the extent possible in #1361. Waiting for the BGS API client microservice from Yang.
