### ISSUE TITLE
Unit testing for VRO to use BGS service to add automation outcome notes

### ISSUE THREAD

**Issue by ioarash** [department-of-veterans-affairs/abd-vro#1348]
**User Story**

Create unit test for VRO BSG  note service.

**Acceptance Criteria**

See #1341 ACs

**Notes about work**

a new BgsApiService under [gov.va](http://gov.va/).vro.service.provider.bgs.service
a new Camel route [gov.va](http://gov.va/).vro.service.provider.camel

This is the parent ticket:
https://github.com/department-of-veterans-affairs/abd-vro/issues/1341

**Comment by dianagriffin** [comment]
Yoom's suggestion for handling uncertainty in the data for testing:
- run end-to-end test and see what it's feeding to the new route
- use that data as the input data in the unit test
