### ISSUE TITLE
create BGS mock service

### ISSUE THREAD

**Issue by greene858** [department-of-veterans-affairs/abd-vro#1354]
**User Story**

Create BGS mock service; as an engineer I want a mock of the BGS service so that I can test the VRO system on a local environment without connectivity to the actual BGS service

**Acceptance Criteria**

A microservice responded with mock results to all BGS api calls

**Notes about work**

a new MockBgs under [gov.va](http://gov.va/)vro.mockbgs.MockBgs

This is the parent ticket:
https://github.com/department-of-veterans-affairs/abd-vro/issues/1341

**Comment by yoomlam** [comment]
I believe this is almost done, so I think we should wrap it up since it can be useful for any VRO interaction with BGS.
