### ISSUE TITLE
Investigate our capability to add Veteran-level notes via the BGS microservice

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1359]
This should be a time-boxed investigation to confirm/deny whether we can relatively easily add Veteran-level notes via BGS in addition to claim-level notes. If the answer is no, let the POs/PMs know so that we can advocate for a different approach to the necessary stakeholders! If the answer is yes, great. :) 

_Note: this is lower priority than setting up certs and building the microservice._

**Acceptance Criteria**

1. Test adding notes at the Veteran level in UAT and provide a summary of findings/LOE to inform product decision about whether or not to include this requirement in our current notes implementation.

**Comment by nanotone** [comment]
My investigation in UAT indicates that we do have the ability to create Veteran-level notes. However, unlike claim-level notes which can be created in bulk using the `createNotes` API method, Veteran-level notes must be added one at a time.
