### ISSUE TITLE
Address SecRel issues with vro_db-init

### ISSUE THREAD

**Issue by greene858** [department-of-veterans-affairs/abd-vro#1377]
Aqua scan shows
3 highs with FLYWAY_ARTIFACT_URL resolve these findings either upgrade flyway, or remove package if not needed.

**Comment by dianagriffin** [comment]
@tcraghu @ioarash the input I'm looking for on this ticket:
- Do we need this ticket at all? (does the issue still exist?)
- If yes, is it urgent?
- If not urgent, help me understand: what is the impact of the issue? and, how much effort will it take to address it? (you could add story points!)

Thanks!

**Comment by dianagriffin** [comment]
- We need to do this because of the risk of DDOS (very minimal)
- We need to have a workaround or wait for the official image to be released

**Comment by tcraghu** [comment]
Image scanning has detected 3 critical issue, one of them is JsonSmart.
Current version of json smart in the docker image is 2.4.8.
Flyway team has fixed it and released new core version 9.16.2.
Issue is , Flyway team has not officially released 9.16.2 image yet. we have to work around this fix

**Comment by dianagriffin** [comment]
@dianagriffin to confirm risk acceptance with Premal/Steve

**Comment by dianagriffin** [comment]
Need a ticket to capture SecRel policies around acknowledging issues and how/when we will address the issue before the alert resurfaces - @greene858 to create this ticket

**Comment by dianagriffin** [comment]
Closed as no longer relevant
