### ISSUE TITLE
[Post-iMVP priority] Use service history keywords to assess presumptive service connection

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1381]
As a VA stakeholder, I want service history keywords to be used, in addition to Veteran flashes, to evaluate whether a Veteran is service connected to hypertension

**Acceptance Criteria**

For Hypertension NEW claims that VRO receives from MAS:
- The claim passes the presumptiveCheck if:
  - the Agent Orange Exposure Verified (ID: 266) flash is present (current state), OR
  - at least one of the following service history keywords are found (new requirement): **check requirements doc or request list from MAS**
 - If the claim passes the presumptiveCheck, proceed to the assessment step
 - If the claim does not pass the presumptiveCheck, offramp the claim

**Comment by amylai-nava** [comment]
[Deemed non-launch-blocking](https://dsva.slack.com/archives/C01BVF2A3V0/p1680273214710029?thread_ts=1680228020.563879&cid=C01BVF2A3V0) and moved to the post-iMVP backlog.

**Comment by shannonkford** [comment]
I would caution us to check the current false positive rate on service keywords before relying on them to onramp the claim, especially if we are trying to reduce the deferral rate.

**Comment by dianagriffin** [comment]
Closing as won't do due to TERA policy
