### ISSUE TITLE
[Post-iMVP priority] Use ITF date to determine claim period of review

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1397]
Current behavior:
- CFI logic: VRO examines evidence 1 year from claim
- CFI PDF: VRO displays evidence 2 years from claim
- New claim logic: VRO examines evidence 2 years from claim
- New claim PDF: VRO displays evidence from all time

New behavior:
- (to be filled out)

To-do:
- Figure out how VRO will get the ITF date (VRO team)
- Incorporate ITF date into assessment logic (HTN team)
- Applies to all contentions

Other notes:
- There is a unique ITF attribute in CorpDB similar to the date of claim attribute: `ITF_STATUS_DT`. vets-api has access to CorpDB indirectly via BGS, so it might be available through that path [(slack thread)](https://dsva.slack.com/archives/C01BVF2A3V0/p1667496414200029)

**Comment by dianagriffin** [comment]
Dependent on #1481
