### ISSUE TITLE
[Post-iMVP priority] Add secondary assessment step of checking for active hypertension medications

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1401]
Reference slack thread: https://dsva.slack.com/archives/C01BVF2A3V0/p1673281790716729?thread_ts=1673280870.087129&cid=C01BVF2A3V0

In the sufficiency logic, incorporate a check for active hypertension medications.

**Comment by dianagriffin** [comment]
Dependent on #1398 and #1399
