### ISSUE TITLE
Use Veteran Verification V2 API for retrieving Veteran flashes

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1404]
Reference slack thread: https://dsva.slack.com/archives/C03JRKKD11B/p1667928674058379

**Comment by dianagriffin** [comment]
Need to recall/validate that the driver of this is our general preference for relying on LH APIs where possible

**Comment by msnwatson** [comment]
@dianagriffin checking in on this to see if this issue is still relevant for the platform since i remember flashes being related to RRD

**Comment by dianagriffin** [comment]
@msnwatson good catch! Not relevant. Closing as won't do.
