### ISSUE TITLE
[Post-iMVP priority] Enhance de-duplication logic for BP readings (or stop querying for BP readings from LH)

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1419]
Based on observations from: https://github.com/department-of-veterans-affairs/abd-vro/issues/1373 (whether BP readings from HDR and LH are duplicate 100% of the time)

VRO team: ask MAS to include the observation time
HTN team: incorporate into de-duplication logic

**Comment by dianagriffin** [comment]
Example: enhance by checking timestamp in addition to date

**Comment by dianagriffin** [comment]
Consider whether the request to MAS could be combined with getting them to update the datetime format they're sending us ([slack thread](https://dsva.slack.com/archives/C0309PZT20Z/p1676558132593019))
