### ISSUE TITLE
Brainstorming session based on exploratory research findings

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#1436]
## Context

We'd like to have a brainstorming session based on the exploratory research findings about what we want to do next. This could be: 
* dive deeper into a specific area (add'l research)
* Form a hypothesis we can test (and test it) 
* Sense make
* other things too!

Dependent on #1292 

## Open questions
- [ ]  who should be invited? 

```[tasklist]
### Tasks
- [ ] come up with invite list
- [ ] schedule meeting
- [ ] create mural
```

**Comment by amylai-nava** [comment]
Because of the pivot, we decided to turn this brainstorming session into a [HTN exploratory research shareout ](https://dsva.slack.com/archives/C01BVF2A3V0/p1682458168320339). Brainstorming and ideating sessions will be happening in the next sprint.
