### ISSUE TITLE
Runbook for responding when traffic stops in the vets-api<>MAS integration in production

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1438]
**User Story**

As an engineer responsible for maintaining this integration, I want to have a documented set of actions to take when there are blocking issues with the vets-api<>MAS integration in production, so that I am prepared to quickly and effectively respond to the incident.

Include:

- What triggers this event and how you can identify/verify that it is happening
- What systems access a person needs to diagnose & resolve the issue
- The steps to resolve the issue
- How to verify the problem is resolved
- After-action steps

**Acceptance Criteria**

1. Runbook has been created, reviewed by the team, refined based on feedback as necessary, and published in the VRO wiki

**Notes about work**
- a [slack thread](https://dsva.slack.com/archives/C0519PXPUCR/p1681140318642929) from a recent production incident for this integration
- Our most recent point of contact on the MAS side for this integration was Lindsay Elliot-Foose ([lvelliot@us.ibm.com](mailto:lvelliot@us.ibm.com)) and we used the (private) #rating_automation_collaboration slack channel to connect.

**Comment by dianagriffin** [comment]
@yoomlam not immediately OBE since we need to keep the traffic running on this for now. TBD on the long-term ownership/maintenance of this integration though

**Comment by msnwatson** [comment]
just checking in on this to see if this issue is still relevant @dianagriffin

**Comment by dianagriffin** [comment]
@msnwatson thanks for checking! Yes, it is still relevant. I _think_ @nanotone might be the only one who could author it, since that code lives in vets-api. It's a tough one to prioritize over other work streams, but @nanotone @amylai-nava, this might be something to slot in next time there's a moment of light capacity for Yang?

**Comment by amylai-nava** [comment]
@nanotone, now might be a good time to pick this up. what do you think?

**Comment by nanotone** [comment]
Draft runbook is in this [HackMD document](https://hackmd.io/aozCBmu_QOeimUGR38N37w). Requesting comment from @dfitchett and moving this ticket into In Review.

**Comment by dfitchett** [comment]
> Draft runbook is in this [HackMD document](https://hackmd.io/aozCBmu_QOeimUGR38N37w). Requesting comment from @dfitchett and moving this ticket into In Review.

Looks good to me!

**Comment by nanotone** [comment]
@amylai-nava Do you want to stick to the last clause in the original AC, i.e. publish this runbook in the VRO wiki? The biggest reason not to, in my mind, is that the VRO team no longer has any overlap with the original RRD team, and there isn't any other non-VRO content on the VRO wiki.

**Comment by amylai-nava** [comment]
@nanotone, agree that the VRO wiki doesn't seem like the right place for the runbook to be published anymore. Is there another place in Github that you think this could go? 🤔

**Comment by nanotone** [comment]
As per this [Slack thread](https://dsva.slack.com/archives/C01BVF2A3V0/p1705520074003279), I've added the runbook [here in va.gov-team-sensitive](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/526/RRD-to-MAS-incident-response.md). Calling this ticket done for good.
