### ISSUE TITLE
Address BGS Notes tech debt

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#1442]
Capturing unfinished work regarding BGS Notes:

- Camel routes workflow unit tests (#1348) 
- Test against Mock BGS service (#1354 ?) 
- Add (automated) integration tests for the 5 scenarios (#1450) 
- Manually test in different deployment environments (in progress under other tickets + E2E testing)

(Some of these are already in a ticket, but I wanted to capture my thoughts here.)

**Comment by yoomlam** [comment]
Engineering reminders:
- call Ruby rspec test when `gradle test` is called
- remove [workaround](https://github.com/department-of-veterans-affairs/abd-vro/blob/566695e109686df661d951fb3af042283256a707/service/provider/src/main/java/gov/va/vro/service/provider/camel/BgsApiClientRoutes.java#L49) once Mock is available

**Comment by dianagriffin** [comment]
@greene858 @yoomlam Can y'all confirm: is `Test against Mock BGS service` implicit in #1354 or do we need a separate ticket to represent the testing effort? 

@yoomlam I updated the top comment to link bullet points to tickets/ongoing activities. Can the Engineering reminders you posted above be linked to one or more of those specific tickets? If yes, I'm thinking we can close this ticket

**Comment by dianagriffin** [comment]
Tasks covered in other tickets; closing as dupe
