### ISSUE TITLE
Log & notify slack if a claim's temporary station of jurisdiction has changed during VRO processing

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1470]
**User Story**

As a VA Product Owner, I want to be notified if a claim's Temporary Station of Jurisdiction changes to something other than `398` before VRO has completed processing, so that I can investigate that edge case and determine if/how it needs to be addressed.

**Acceptance Criteria**

1. VRO logs and notifies Slack in an edge case where it finds the claim's Temporary Station of Jurisdiction is no longer `398` when VRO completes processing. 
2. The Slack notification includes the claim ID, collection ID, and a human-readable description of the issue, e.g. "Station changed to [value] before VRO completed processing" _(If it's complex to include the value in the message, then just "Station changed before VRO completed processing" is fine)_

**Notes about work**
- [slack thread](https://dsva.slack.com/archives/C01Q7979Z7D/p1679956241696929?thread_ts=1678379519.587409&cid=C01Q7979Z7D)

**Comment by yoomlam** [comment]
OBE
