### ISSUE TITLE
Notify slack if VRO does not receive confirmation of successful exam order within 24 hours of processing the claim

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1473]
**User Story**

As a VRO Product Owner, I want to be notified when an exam request made by VRO to MAS is not successful or does not receive confirmation of success, so that I can work with VBA stakeholders to ensure those claims are processed correctly.

**Acceptance Criteria**

1. If VRO does not receive confirmation to the exam order status endpoint within 24 hours of processing the claim, a notification is sent to #benefits-vro-alerts that includes the claim ID, collection ID, and a human readable description of the issue, e.g. "Exam order status not received within 24 hours"
2. If VRO receives a call the exam order status endpoint at any time that indicates a non-successful result for the exam order, a notification is sent to #benefits-vro-alerts that includes the claim ID, collection ID, and a human readable description of the issue, e.g. "Exam order status was [value]" (or, "Exam order status was not success" if it's complicated to include the actual value)

**Comment by yoomlam** [comment]
OBE
