### ISSUE TITLE
Track outcomes for claims offramped with reason=insufficientHealthDataToOrderExam

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1480]
**User Story**

As a VA PO, I want to use data to validate a hypothesis about the outcomes for claims with insufficient data to order an exam, so that I can determine whether to proceed with iterating on the functionality for how we handle those claims in RRD processing.

The hypothesis is that if we set these claims to RFD, it could speed up the process of getting a claim decision, with the assumption that the decision would be a denial. We don't want to take the step of implementing that change (in #1400) without first validating that these claims are indeed consistently resulting in a denial decision after manual processing.

Note that this ticket will likely require a PA&I request -- figuring how to get the tracking data is part of this ticket.

**Acceptance Criteria**

1. Data has been gathered about the ultimate decision made on at least X number [TBD based on volume post-launch] of claims that were offramped by VRO with reason=insufficientHealthDataToOrderExam

**Notes about work**
- Depended on by #1400 and will inform its priority

**Comment by yoomlam** [comment]
OBE
