### ISSUE TITLE
Update hostnames for BIP Claims API  and Claim Evidence API before 5/21/23

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1488]
**User Story**

As a VRO engineer, I want to ensure that VRO is updated to point to the new hostnames for the BIP Claims API and Claim Evidence API before the DNS override expires on 5/21/23, so that VRO avoids any issues connecting to these services.

**Acceptance Criteria**

By Sunday, May 21, 2023:
1. Update VRO configurations to point to the BIP APIs’ new EKS hostnames (see tables below)
2. Verify that the changes are deployed and tested to make sure the new URLs work

**BIP Claims API hostnames**
| Environment | Current Hostname  | New EKS Hostname |
| ------------- | ------------- | ------------- |
| `dev`  | claims-dev.dev8.bip.va.gov | claims-dev.dev.bip.va.gov |
| `test`  | claims-test.dev8.bip.va.gov | claims-test.dev.bip.va.gov |
| `int`  | claims-int.dev8.bip.va.gov | claims-int.dev.bip.va.gov |
| `ivv`  | claims-ivv.stage8.bip.va.gov | claims-ivv.stage.bip.va.gov |
| `uat`  | claims-uat.stage8.bip.va.gov | claims-uat.stage.bip.va.gov |
| `pat`  | claims-pat.stage8.bip.va.gov | claims-pat.stage.bip.va.gov |
| `pdt`  | claims-pdt.stage8.bip.va.gov | claims-pdt.stage.bip.va.gov |
| `demo`  | claims-demo.stage8.bip.va.gov | claims-demo.stage.bip.va.gov |
| `perf`  | claims-perf.prod8.bip.va.gov | claims-perf.prod.bip.va.gov |
| `preprod`  | claims-preprod.prod8.bip.va.gov | claims-preprod.prod.bip.va.gov |
| `prodtest`  | claims-prodtest.prod8.bip.va.gov | claims-prodtest.prod.bip.va.gov |
| `cola`  | claims-cola.prod8.bip.va.gov | claims-cola.prod.bip.va.gov |
| `prod`  | claims-prod.prod8.bip.va.gov  | claims-prod.prod.bip.va.gov |

**BIP Claim Evidence API hostnames**
| Environment | Current Hostname  | New EKS Hostname |
| ------------- | ------------- | ------------- |
| `ivv`  | vefs-claimevidence-ivv.stage8.bip.va.gov | vefs-claimevidence-ivv.stage.bip.va.gov |
| `uat`  | vefs-claimevidence-uat.stage8.bip.va.gov | vefs-claimevidence-uat.stage.bip.va.gov |
| `pat`  | vefs-claimevidence-pat.stage8.bip.va.gov | vefs-claimevidence-pat.stage.bip.va.gov |
| `pdt`  | vefs-claimevidence-pdt.stage8.bip.va.gov | vefs-claimevidence-pdt.stage.bip.va.gov |
| `prodtest`  | vefs-claimevidence-prodtest.prod8.bip.va.gov | vefs-claimevidence-prodtest.prod.bip.va.gov |
| `prod`  | vefs-claimevidence.prod8.bip.va.gov | vefs-claimevidence.prod.bip.va.gov |

_Note: I (Diana) was also given prodtest and prod URLs for `docgen-svc.*` and `docgen-genstore.*` hostnames; let me know if we use those and need the updated versions of them!_

**Notes about work**

> If you have any questions or run into any issues connecting with these APIs after the 4/23/23 EKS migration, please send an email to [BIA_BIP_System_Team@va.gov](mailto:BIA_BIP_System_Team@va.gov) and [BIP_Platform_Prod_Leads@bah.com](mailto:BIP_Platform_Prod_Leads@bah.com).

**Comment by yoomlam** [comment]
Need an AC to verify that the changes are deployed and to have VRO tested to make sure the new URLs work.

**Comment by dianagriffin** [comment]
Last step: test URLs in dev environment

**Comment by tcraghu** [comment]
PROD claims working ok 
2023-05-15 16:19:15.676  INFO 1 --- [nio-8080-exec-7] g.v.v.s.p.bip.service.BipApiService      : Call https://claims-prod.prod.bip.va.gov/api/v1/contentions/special_issue_types to get special_issue_types

Evidence throwing error. Need to be troubleshooted

**Comment by tcraghu** [comment]
Validation Complete in Prod. I can hit URL. I do get token error. which is expected. but end point is working fine
Sample Curl
curl -X POST https://vefs-claimevidence.prod.bip.va.gov/api/v1/rest/documenttypes --cacert vafull.crt --cert le
ns-tls_bip.crt  --key lens-tls.key -H "X-API-KEY: myapikey" 
{"messages":[{"timestamp":"2023-05-19T19:56:31.441","key":"UNAUTHORIZED","severity":"ERROR","status":"401","text":"No JWT Token in Header.","httpStatus":"UNAUTHORIZED"}]}

Cert Generation Doc is https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-APIs

**Comment by tcraghu** [comment]
curl -X POST https://claims-prod.prod.bip.va.gov/api/v1/contentions/special_issue_types --cacert vafull.crt --c
ert lens-tls_bip.crt  --key lens-tls.key -H "X-API-KEY: 13df85ef-635c-4ae7-ba63-d4d44aa14501" -k 
{"messages":[{"timestamp":"2023-05-22T19:46:12.141","key":"UNAUTHORIZED","severity":"ERROR","status":"401","text":"No JWT Token in Header.","httpStatus":"UNAUTHORIZED"}]}
