### ISSUE TITLE
Replicate MAS logic for 5103 notices

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1489]
### User Story

As a VRO PO, I want to ensure that claims processed in VRO appropriately handle logic around 5103 notices in a way that is consistent with how MAS handles it, so that all claims of a given contention are treated consistently when automated.

### Acceptance Criteria

1. TBD once scope/solution is determined

### Not included in this work

Similar logic applies to 4142 notices and Private DBQs; these cases will be covered by other tickets.

### Notes about work

**[MAS Documentation of APCAS logic for this scenario](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/VRO%20-%20Virtual%20Regional%20Office/VRO%20Integrations/MAS%20Integrations/VRO%20Integration%20-%20APCAS%20Standardized%20Automation%20(March%202023).docx?d=w6780247c75fd48f898ad4ff60959fddb&csf=1&web=1&e=JghK6F)**
- [MAS Approved logic requirements](https://dvagov.sharepoint.com/:b:/r/sites/vaabdvro/Shared%20Documents/VRO%20-%20Virtual%20Regional%20Office/VRO%20Integrations/MAS%20Integrations/5103%20logic%20ticket%20approval%20-%20APCAS-6817%20(3).pdf?csf=1&web=1&e=0hBRZM)

> As a Claims Processor, if a 5103 is required, I want exams to be ordered and drafted per normal outcomes, but only want an RFD outcome if the condition reviewed has interpretive logic enabled for that condition AND the schedular evidence was greater than the Veteran’s current rating %. If a condition is not for a interpretive logic condition and review type and there is schedular evidence within the review period, that condition should instead lead to “open” status. If a condition is for an interpretive logic condition, but the schedular evidence leads to equal to current rating, then that condition should lead to “open” status.

_Note that according to the included Interpretive Logic Table, hypertension is not interpretive_

2 relevant acceptance criteria for **single issue hypertension claims**:
> IF a 5103 letter is required AND schedular evidence is not found within review period, order or draft exam (no change)
> IF a 5103 letter is required AND a condition is not interpretive for that basis of claim AND schedular evidence was found within review period, leave open (change)

For the latter scenario (leave open), when an ARSD is generated:

> ARSD Notice/VBMS Note:
> For when a Standard 5103 Notice must be generated, we propose the following to be generated on the ARSD and a VBMS note entered at the claim level:
> · “Please note, the automated review summary document (ARSD) has been completed in full with no further action taken based on automation eligible contention(s). This claim/contention has been placed in the Open Status Development Life Cycle for further review by the claims processor. The automation system has sent the Standard 5103 Notice letter to the Veteran/Claimant via package manager.”

Further relevant acceptance criteria for **asthma/rhinitis claims for increase** _(Note that CFI for these contentions are considered interpretive)_:

> - IF a 5103 letter is required AND a condition is interpretive for that basis of claim AND schedular evidence was found within review period leading to a greater than current rating %, mark RFD
> - IF a 5103 letter is required AND a condition is interpretive for that basis of claim AND schedular evidence was found within review period leading to a equal to current rating %, leave Open

**Thoughts on solutions**
- **Assumption**: VRO should not try to replicate the functionality of triggering the sending of a 5103 notice (which MAS currently achieves using an RPA bot)
- **Potential approach**
   - Have MAS continue to run the logic to determine if a 5103 notice is required, before notifying VRO of automation eligible claims
   - For claims where a 5103 letter is required, have MAS send the notice (via the RPA bot) before notifying VRO of automation eligible claims
   - After sending the 5103 letter, have MAS notify VRO of the claim, including in the payload for that claim an indicator that a 5103 was sent (e.g. add a boolean field to the endpoint for `5103required`)
   - When receiving a claim where (e.g.) `5103required`=`True` each contention team incorporates new logic to handle those claims appropriately according to criteria for the given contention -- ie. for single issue hypertension claims, add logic to offramp, generate an ARSD, and add a VBMS note to that claim if it has sufficient evidence for RFD. (VRO's existing logic would cover the exam order case.)

**Comment by yoomlam** [comment]
OBE
