### ISSUE TITLE
Get clarity on the future state of the va.gov <> MAS claims passing integration

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1523]
### Question
What changes, if any, do we anticipate for the va.gov <> MAS claims passing integration? will we continue to maintain it?

### **Decision (5/3/2023)** 
OCTO team is having conversations about the future of this integration. We should de-couple this from any RRD vets-api tech debt we need to do and move forward with what we can in the meantime.

-----

### To do's

- [ ] ~Identify hypothetical scenarios for the future of the va.gov <> MAS claims passing integration **(Diana, Amy)**~
- [ ] ~Provide LOE for the hypothetical scenarios **(Yang)**~

### Potential scenarios [based on conversations in mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1682435312762/32295eab336430640d091cf64dbf3effc531487b?wid=0-1682616961621)
- 1: no change to existing integration, address issues as they arise
  - **note**: “no change” still has an LOE because there’s a bit of tech debt in vets-api’s RRD code we could (should) pay off
- 2: make change to existing integration so that we're sending **new** claims and **CFI** for **x conditions**, add additional conditions when MAS requests them, address issues as they arise
- 3: make change to existing integration so that we're sending **CFI** for **x conditions**, add additional conditions when MAS requests them, address issues as they arise
- 4: make change to existing integration to a) turn it off for now, and b) enable us to later turn on sending of **CFI** and/or **new** claims for **x condition**, address issues as they arise
- 5: turn off the existing integration and leave the code/documentation in a state that another team could pick up ownership of it later
- 6: other

**Comment by dianagriffin** [comment]
Added some additional potential scenarios that perhaps reveal my biases ;)

**Comment by amylai-nava** [comment]
@dianagriffin @nanotone I'm going to close this ticket and create a new one specifically for RRD vets-api tech debt work, given that our VA friends are still working through this question and we want to move forward with what we can in the meantime.
