### ISSUE TITLE
Extract BIP integrations from RRD specific code

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#1534]
Followup ticket from https://github.com/department-of-veterans-affairs/abd-vro/issues/1509

In the previous ticket, we consolidated all of the code that had previously been used for the RRD system including integrations with VA systems like BIP and MAS outside VRO inside the `domain-rrd` folder.

This was a useful step; however, to support VRO's functionality as a platform, it will be useful to maintain VA-system integrations at the platform level, rather than for a specific domain, so that it can be used by other users of the VRO platform going forward.

To achieve this, integrations with VA systems like BIP should be maintained as a service in the top-level directory. This will promote visibility of what systems VRO is integrated with and avoid duplication of integration work by specific domains. 

This ticket covers extraction of integrations with VA systems from the `domain-rrd` folder, including BIP.

This ticket does not cover extraction of the integration with MAS as this is a VA-external system.

**Comment by dianagriffin** [comment]
See comments on #1172 as a reference point for this ticket

**Comment by engineer-plus-plus** [comment]
As per suggestion from Tom, I am evaluating the implementations of microservices in the VRO project in hope to determine the pattern of how they are done.  The idea is that we will copy it as we create the microservice for BIP API.

**Comment by engineer-plus-plus** [comment]
After further discussion with @greene858 , I'm gonna do it this way.  Delete everything that's not BIP related from RRD directories.  That way  we preserve the package structure and all the Docker and Gradle setups.

**Comment by dianagriffin** [comment]
@engineer-plus-plus @greene858 Sorry if I'm misinterpreting, but deleting everything not BIP related from the RRD directories sounds like a drastic step that I'm not sure we want to take. Can you clarify if this would be truly deleting everything else so that we no longer have an archive of the RRD implementation?

**Comment by engineer-plus-plus** [comment]
@dianagriffin please ignore my previous comment as they were the result of a misunderstanding.  The approach that I was describing would solve something that's already solved by 1509

**Comment by engineer-plus-plus** [comment]
This ticket is to be replaced by these two: 

- https://github.com/orgs/department-of-veterans-affairs/projects/871/views/8?pane=issue&itemId=28826971&pane=issue&itemId=28826971
- https://github.com/orgs/department-of-veterans-affairs/projects/871/views/8?pane=issue&itemId=27158149&pane=issue&itemId=28826934

**Comment by dianagriffin** [comment]
@greene858 @engineer-plus-plus Could you add a comment to capture what progress (if any) was made on this ticket in Sprint U that isn't covered by #1593 and #1594?

**Comment by greene858** [comment]
#1593 almost all of the changes needed to the code to complete the story are done, a few small refinements are in progress to be completed in the next day or two. 

#1594 we have started designing the solution, coding and testing still to be done

**Comment by engineer-plus-plus** [comment]
This  story should be "canceled" not "done"

**Comment by dianagriffin** [comment]
Closing as canceled, replaced by the tickets linked above.

**Comment by engineer-plus-plus** [comment]
I'm not sure why this story is in "need refinement" state.  It was done a long time ago.  I'm unasigning myeself from it becauese of I have no plans to work on it again.
