### ISSUE TITLE
Share exchange names between Python and Java services as environment variables

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1539]
_This is a ticket we took over from Amida's VRO tech debt backlog_

> We had an idea to consolidate the exchange names as environment variables. 
> 
> For example, the {{health-assess-exchange}} is declared in {{service-python/assessclaimdc7101/src/lib/queues.py}} and {{service/provider/src/main/java/gov/va/vro/service/provider/camel/SlipClaimSubmitRouter.java}}

**Comment by yoomlam** [comment]
We could implement something in code (enforces using correct names but unclear how this can be done cleanly/elegantly) or declare some software conventions (faster but relies on folks to follow it).
