### ISSUE TITLE
Update VRO API to point to Contention Classification (CC) API

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1556]
**User Story**

As a CC team engineer, I want to be able to publish my API and API spec within VRO, so that external systems like `vets-api` can call it.

As a VRO engineer, I want to make the Contention Classification API the single API available under the VRO API URL, so that I don't have to solve for serving up multiple APIs in VRO right now. 

**Context** 
We have an existing (Java) VRO API that was built to support the RRD product. The Contention Classification team has now built their own (Python) API that needs to be available in VRO. We briefly considered building an API Gateway (see #1512) or other solution to solve for serving up multiple APIs from VRO ([Slack post](https://dsva.slack.com/archives/C04QLHM9LR0/p1683753781530959?thread_ts=1683747566.779289&cid=C04QLHM9LR0)), but since the RRD-centric VRO API is no longer relevant, we don't want to invest in solving that problem yet. Instead, we want to make the CC API the single active API in VRO, by redirecting access from the VRO API to the CC API instead of to the existing VRO API. 

**Acceptance Criteria**

1. Accessing the VRO API will go to the Contention Classification (CC) API
2. External systems (i.e., vets-api) can successfully connect to the CC API via the VRO API URL

**Comment by dianagriffin** [comment]
@yoomlam please review and edit this ticket as needed, please & thank you!

**Comment by yoomlam** [comment]
I think this is a few lines of change to the Helm config. Most of the work will be testing to make sure it works.

**Comment by lukey-luke** [comment]
vets-api will call `https://<DOMAIN_NAME>/contention-classification/<endpoint>`, which should call CC docker container at `https://<CC-hostname>:18000/<endpoint>`.

**Comment by yoomlam** [comment]
If #1512 is completed, this ticket will no longer be needed.

**Comment by yoomlam** [comment]
This ticket is not needed if #1512 is completed.

**Comment by dianagriffin** [comment]
Closing as unnecessary based on #1512
