### ISSUE TITLE
Define VRO release process for partner product teams to prepare for CC team's launch

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1574]
**User Story**

Follows #1498 

As a partner product team engineer, I want to know how to release my product on VRO, so that I have autonomy over my product's releases.

As a VRO engineer, I want to pair with my teammates to define the release creation process for partner product teams, so that we can provide guidance and support to the CC team for their June launch as well as future product teams.

**Acceptance Criteria**

1. Schedule a working session with VRO engineers & Diana to discuss & define the process of creating a release.
2. Document the process
3. This release process supports the CC team's launch plan.

**Comment by dianagriffin** [comment]
Assumption: they need to deploy to staging/UAT and prod. @dianagriffin will confirm.

**Comment by lukey-luke** [comment]
Mason is currently working to get images available for use in staging. Flagging here, that we need our docker images signed prior to deployment to prod environment in LHDI.

See:
 https://animated-carnival-57b3e7f5.pages.github.io/container-platform/signed-images/#what-happens-when-an-unsigned-or-unofficial-image-is-used
and: 
https://github.com/department-of-veterans-affairs/abd-vro/wiki/Deploying-VRO#ghcr-images

**Comment by yoomlam** [comment]
Will be completed by end of sprint.
