### ISSUE TITLE
Draft software conventions for RDS in VRO

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1575]
**User Story**

As a partner team engineer, I want to understand what software conventions I should follow in using RDS for my application's needs, so that I can appropriately design and implement my database needs.

**Dependent on**
- #1845 

**Acceptance Criteria**

1. Produce an initial version VRO's software conventions for RDS with sufficient detail and context for VRO engineers to guide CC's & EE's implementation of RDS

**Context** 
Both the EE and CC teams are ready to start building functionality that requires database storage. LHDI is expected to release RDS to their customers within 1-2 weeks. We have ticket #1845 to adopt LHDI's RDS solution.

**Comment by yoomlam** [comment]
For diagnostic purposes, be aware of ticket #1248.

**Comment by dianagriffin** [comment]
@lukey-luke @yurenanava I captured this ticket based on discussion with Yurena about post-launch metrics and the type of info you'll be storing in log files but would ideally like to store in a database. _I'll be honest, I think it was related to measuring [classification coverage](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1680558709105/f43983d60a4703a24ffbccd1ebdbeff94103fad7?wid=0-1682963528593), but I don't fully remember - I just have a post-it on my desk that says: "CC - What can they store in the VRO database?" so this ticket is my way of following up on that question._

Can you both:
- confirm that this is a real need/question that you have (not something I misheard or made up!)? 
- if yes, share your thoughts/notes about what you need/wish you had for storing metrics info in a database?

**Comment by yurenanava** [comment]
Hey @dianagriffin, I think we are good enough on MVP for tracking coverage for our service and came up with a way to monitor accuracy. 

Ideally, it would be great to store our current coverage log in a DB at some point, so we can query against that more easily. Probably you could help us with that, but it is not an immediate need and we can work with log files for a while.

Now we need your support to track system/performance metrics to respond to questions such as:

- is our service up and running?
- What's our response time?
- for tracking errors and exceptions.
- ...

We are going to start covering a very small amount of claims and we need to know if our service is performing well before increasing the amount of claims we route to VRO and our service.


Does it make sense to you?

@lukey-luke do you want to add something else?

**Comment by yurenanava** [comment]
Regarding using a DB to track our product metrics...

This are the types of fields I'm envisioning to work work with for our product to track our coverage:
- A main classification record, where we track the contention we received, the response we provided and ideally we could use this record to track other things like if the claim was resolved or if there were updates in the classification during the claim lifecycle (once we connect to the appropriate Kafka events...)
<img width="270" alt="image" src="https://github.com/department-of-veterans-affairs/abd-vro/assets/106626863/f4295954-1f8b-4890-aa1c-bd7f34a28ce7">

- In that same record, we could also store the VBMS ID and the contention ID or have a separate table with this information, so once we want to track our accuracy querying what's going on in VBMS, we can identify the contentions that we classified
<img width="260" alt="image" src="https://github.com/department-of-veterans-affairs/abd-vro/assets/106626863/53bb6314-1567-46cf-9d31-f2db237daf62">

- We may also want to store classification changes in a new table to analyze what changed more easily
<img width="310" alt="image" src="https://github.com/department-of-veterans-affairs/abd-vro/assets/106626863/a8e212fb-6505-4976-af37-e14fb7b46198">

I drafted how I envision this monitoring piece to work in [this section of my big Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1680558709105/f43983d60a4703a24ffbccd1ebdbeff94103fad7?wid=0-1683148986273)

**Comment by dianagriffin** [comment]
@greene858 This was never needed for initial launch, but was intended to capture what might be a next priority for the CC team post-launch (see Yurena's comment above). I don't believe the priority has changed, although we should revisit the need with the CC team after they launch to confirm they're still thinking about metrics tracking in the same way.

**Comment by msnwatson** [comment]
Update on this from discussion with @lukey-luke  on Jun 27:

In the future, it seems like there might be a feature with a small risk of potential PII being included. This should shape the structure of this work. To try to minimize duplicated work, we should consider building this into the requirements for a data store used by the CC team in general, unless there is significant technical reasons why data stores suitable for potential PII would not be used for more general data as well.

**Comment by dianagriffin** [comment]
[Notes](https://docs.google.com/document/d/1-neDXhKl-NOl32KoG8kNereAXi49s29m884NuVbXwRI/edit#heading=h.6jdeev7vwbpv) from VRO/CC discussion on CC database needs, 7/26

Updating this ticket based on next steps identified in this meeting.

**Comment by dianagriffin** [comment]
Breaking this out:
1. Help CC get their database needs met in the short term
2. Software conventions for RDS in VRO

**Comment by dianagriffin** [comment]
Notes from Sprint B planning: We could achieve this ticket by pairing with CC and documenting the steps we take together as rough notes, to be polished up in the following sprint.

**Comment by dianagriffin** [comment]
Update ticket description to call out that EE team is now also looking into data storage in VRO, so these software conventions should provide the necessary guidance for both teams' needs. See [this Slack thread](https://dsva.slack.com/archives/C01Q7979Z7D/p1697060760098069) for further context on EE's needs.

**Comment by msnwatson** [comment]
I made changes at https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Database and will continue to polish this based on partner team feedback during some upcoming collaboration sessions.
