### ISSUE TITLE
Add Python test code coverage checking for PRs

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#158]
The current codebase uses `jacoco` to check for Java code coverage of tests. Given the current PRs with Python code, let's add a similar tool for Python code.

Should be able to run python test coverage with the `pytest` extension : https://pytest-cov.readthedocs.io/en/latest/reporting.html

In order to trigger `pytest` from a `./gradlew test`, this may be useful: https://github.com/PrzemyslawSwiderski/python-gradle-plugin.

[CircleCI runs](https://github.com/department-of-veterans-affairs/abd-vro/blob/ba999df3bfc4a1314ef738dee130f0fd8b48e839/.circleci/config.yml#L41) `./gradlew check`, which triggers or includes `./gradlew test`, so if we can hook the Python subprojects into `./gradlew test`, then we won't have to change anything else in the CI/CD pipeline.

[Slack thread](https://dsva.slack.com/archives/C01Q7979Z7D/p1657310251148059)

**Comment by yoomlam** [comment]
@anthonyvelazquez @jbregstone Can this ticket be closed? Is the `pytest` check working (i.e., failing when there is insufficient test coverage)? Which PR implemented this?

**Comment by jbregstone** [comment]
Hello Yoom, I don’t believe that the code coverage check will cause a build
to fail as it currently functions. It only provides a report. I’ll take a
look at this and write a ticket.

**Comment by yoomlam** [comment]
We can continue to make improvements outside of this ticket.
