### ISSUE TITLE
Ongoing Dependabot monitoring

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1580]
This is a recurring ticket assigned by rotation to represent ongoing/ad hoc monitoring and maintenance of Dependabot issues.

https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot

**Comment by dianagriffin** [comment]
Because we will have an assigned person on rotation, we will increase Dependabot to run daily.

**Comment by greene858** [comment]
When addressing Dependabot PRs, follow the [Dependabot Processing Guide](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot#dependabot-processing-guide)
