### ISSUE TITLE
Collaborate with CC team engineers to define a solution to meet their initial system monitoring needs

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1581]
**User Story**

As a CC team engineer, I want to set up basic system monitoring for my product, so that I can monitor application health and performance when my product goes live in production.

@lukey-luke and @yurenanava are CC team points of contact for this effort. 

**Acceptance Criteria**

1. VRO team and CC team have defined requirements for initial system monitoring solution for the CC MVP.
2. Requirements that must be completed by the VRO team are either completed within scope of this ticket (if 1-2 points) or captured in new tickets (if 3+ points)

**Comment by dianagriffin** [comment]
Potentially related to #998 -- ideally we can get Datadog set up for VRO and show it to the CC team as an example of Datadog as a monitoring solution.

**Comment by dianagriffin** [comment]
Noting that I put this ticket down as medium (2 story points) based on AC2 -- the intention is to set some guardrails so that this ticket doesn't expand beyond medium scope. For the assignee on this ticket, if you find that the ticket is at risk of becoming large or complex, please surface that risk for team discussion ASAP so we can align on a course of action.

**Comment by dianagriffin** [comment]
Initial meeting scheduled 5/24 to discuss monitoring needs. 

Ahead of that conversation, cross-posting for reference that @yurenanava share these notes about monitoring on another thread:

> we need your support to track system/performance metrics to respond to questions such as:
> 
> is our service up and running?
> What's our response time?
> for tracking errors and exceptions.
> ...
> We are going to start covering a very small amount of claims and we need to know if our service is performing well before increasing the amount of claims we route to VRO and our service.

**Comment by dianagriffin** [comment]
@yurenanava, @lukey-luke, @msnwatson I don't want to assume this is the only possible solution to CC monitoring needs, but it seems very likely we will consider Datadog as a possible solution, so sharing a link to [LHDI's Datadog documentation](https://animated-carnival-57b3e7f5.pages.github.io/platform-tools/datadog/) in case y'all haven't seen it before.

**Comment by dianagriffin** [comment]
Notes from discussion 5/24:

Priority is system health/monitoring, but also interested in how Datadog can (or can't) support viewing logging audit events for product metrics analysis. 

- Datadog allows us to do container monitoring and have a view of the logs piped in from the container
- Datadog most likely provides support for liveness/health check, if not K8s does
- Deployment infra already supports Datadog so it's a matter of config 
- Luke will continue with the assumption that the application logs will go to STDOUT and we'll go from there. 

VRO side next steps: 
- getting as far as we can on VRO's Datadog config will help us inform how to customize and config for CC team
- Mason will try to understand what configurations to wire up ahead of time

**Comment by msnwatson** [comment]
Update here as we near the end of VRO's sprint, both VRO DevOps engineers have pending access requests to Datadog that have currently not been fulfilled, making it very difficult to dig into the details here. Hoping we can get this access in the week of 06/05

**Comment by dianagriffin** [comment]
@msnwatson given the ambiguity built into AC2 on this ticket, does it seem reasonable to close this ticket as complete because we've settled on Datadog as the solution we'll go with for CC team initial monitoring needs, and to spin up a new ticket for Sprint W to cover actual setup/configuration of Datadog for CC's needs?

**Comment by dianagriffin** [comment]
^ Assuming that makes sense, I spun up #1653 to include in Sprint W. Wave a red flag if you disagree with this breakdown of the work!

**Comment by dianagriffin** [comment]
Closing, with next steps captured in #1653
