### ISSUE TITLE
sever coupling between bip and app

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1593]
Move all the bip-related code from `app` to `svc-bip-api`.  Make all the tests pass.  This is 1 of 2 stories replacing [1534](https://github.com/department-of-veterans-affairs/abd-vro/issues/1534)

**Comment by dianagriffin** [comment]
@greene858 and @engineer-plus-plus 
- Can you provide more detail in the ticket description and specify acceptance criteria? 
- And, can you help me understand how much of this overlaps with what has been completed so far in working on #1534? 
- I see you've given it 3 points, can you add a comment to explain the thinking there?

**Comment by engineer-plus-plus** [comment]
Acceptance criteria:

- :app doesn't have any mention of bip in it
-  all the bip-related code is only in :svg-bip-app
-  all the existing bip tests pass 

with regards to #1534, according to mason, that ticket's scope was limited to :domain-RRD subproject.  This ticket deals with :app subproject.

I assumed that a point is roughly
 equal to a day of work.  I've already spent couple of days on it.  And it's almost done.

**Comment by engineer-plus-plus** [comment]
[Pull request with the solution](https://github.com/department-of-veterans-affairs/abd-vro/pull/1601)
[The latest build](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5065847471)
