### ISSUE TITLE
Determine what/if existing services are available that might support combining claims

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1610]
## Question for discovery
Are there any existing services that might be able to support combining claims? If so, what are they? Can we use them? Pros/cons of each?

### Problem space
If a Veteran submits a second disability compensation claim (new or increase) while a claim is still being worked, that second claim is established as a temporary end product: an EP400. A VSR or RVSR has to combine the temporary EP400 with the existing EP020 in order to move forward with claim development.

### Solution opportunity
We could reduce the burden of manually combining EP400s with current 020s in a few ways:
- When a va.gov claim is submitted, check if there are any pending 020s and, if there are, append new va.gov contentions to the existing 020 claim. (Maybe *especially* if the claims were submitted within a certain amount of time, or if the first claim is early in its lifecycle. We can research whether auto-combining is riskier in some circumstances compared to others.)
- When a va.gov claim is submitted, still establish “secondary” claims as EP400s, but then programmatically close + combine to a single 020
- Investigating the feasibility and implications of creating two 020s rather than relying on the EP400 framework (maybe out of our control) 

## Potential outputs
- Documenting what can be handled by an API and what cannot
- Documenting pros/cons of each service
- Any other insights that might help us evaluate our solution opportunity

**Comment by nanotone** [comment]
Jotting down my learnings about a few endpoints of the BIP Claims API that may support a combine+close operation:

## Fetching data about an EP 400 and its contention(s)

**GET /claims/{claimId}**
- Access claim summary information for a claim, using the claimId

**GET /claims/{claimId}/contentions**
- List summaries for contentions associated with a given claim

## Copying contention data to an EP 020

**POST /claims/{claimId}/contentions**
- Creates one or more Contentions for a claim
- Additional arguments: a whole bunch! Most of these can probably just be taken from the existing contention data verbatim, but need to do some research.

## Removing the EP 400

**PUT /claims/{claimId}/close**
- Operation to close an existing claim
- Additional arguments: closeReasonText (string)

**PUT /claims/{claimId}/cancel**
- Operation to cancel an existing claim
- Additional arguments: closeReasonText (string) [need to verify that this is correct]

Need to refresh my knowledge about the difference between closing and cancelling a claim, but I assume one of these will work for removing the EP 400 after copying its contention(s) to the EP 020.

References (accessible only on VA network)
- [Github page](https://github.ec.va.gov/EPMO/bip-vetservices-claims)
- [Swagger page](https://claims-test.dev8.bip.va.gov/swagger-ui.html)
