### ISSUE TITLE
Onboard Teja

### ISSUE THREAD

**Issue by greene858** [department-of-veterans-affairs/abd-vro#1622]
Welcome, Teja! We are excited to have you on the team! 

This ticket exists to lay out some logistical to-do's alongside areas of focus for getting up to speed on the VRO team and our work. These tasks should follow on the general OCTO Benefits Portfolio onboarding process that will be coordinated for you in the #benefits-onboarding channel in DSVA slack (after we complete the third checklist item below!). 

### To be done for you - @dianagriffin / @smythe5
- [x] Invite Teja to DSVA, Lighthouse Slack spaces
  - [x] Add Teja to slack groups (@vro-team, @vro-eng)
- [x] Introduce Teja in #benefits-onboarding channel (to kick off OCTO onboarding steps) and #benefits-vro team channel
- [x] Add Teja to recurring team meeting invites
- [x] Add to the VA ABD Sharepoint site as an Owner (pending Teja getting a VA email assigned)
- [x] Invite to the VA ABD Team Calendar in Google
- [x] Invite to the OCTO Benefits Delivery Team room in the VA Mural Workspace (as a guest)
- [x] Add Teja to VA Github Org ([form here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new/choose))
  - [x] Add Teja to [abd-vro Github team](https://github.com/orgs/department-of-veterans-affairs/teams/va-abd-rrd/members?add=true)
- [x] Request an Okta account w/ Datadog access (standard role) for Teja (pending Teja getting a VA email assigned)(https://jira.devops.va.gov/servicedesk/customer/portal/1/group/252?groupId=252) -(pending VA email)

###  To do - Teja
- [x] Join relevant [slack channels](https://docs.google.com/spreadsheets/d/1c3e6SVuhVz3q4bh1qf5jj25EmusCd3NVXhDjSIpr9yk/edit#gid=1020923043) -- _you don't have to join ALL these channels; start with the #benefits-vro-* and #benefits-cft-* and you can expand from there as you get more involved in the work. Feel free to ask the team in #benefits-vro if you're wondering about whether to join a particular channel._
    - [x] **Most relevant channels for you**: #benefits-vro (our team channel for coordination across the VRO team), #benefits-vro-engineering (engineering-specific collaboration for the VRO team), #benefits-cft (cross-team collaboration channel for the 3 teams in the Claims Fast-Tracking Crew) 
- [x] Join [recurring team meetings](https://docs.google.com/document/d/12oaUy0vmv--BFdUhoXk69FtLkhb5Bp0_woOWoD5P3iY/edit#heading=h.p2uqu6tmjnaw) -- _they should be on your calendar!_
- [x] Watch ["The Way We Work" presentation](https://us06web.zoom.us/rec/share/sHRSblAbF229tQpj7-Nqmmdi7Zb5bWclCd0lqMMdGAttuaJZDByZy8C7vi1BO9Mo.7XuVLn108mwIpnQj?startTime=1680030182000) recording
- [ ] Go through Benefits Portfolio onboarding materials and onboarding buddy meetings (see #benefits-onboarding channel in Slack; you'll be tagged there with your onboarding buddy assignments and materials to review) 
- [x] Set up a 1:1 meet & greet with our VA Product Owner, Premal Shah! -- _See Premal's slack profile for a calendar URL where you can find available times_
- [x] Set up a 1:1:1 meet & greet with OCTO engineering leads, Steve Albers and Cory Sohrakoff! _See their slack profiles for a calendar URL where you can find available times_
- [x] Review the [VRO Engineering Onboarding doc](https://docs.google.com/document/d/1SnJOqDtlb2UkO9DNczZHCVTTQURiCvp81hBJhrlv6Xs/edit#heading=h.evapdsgdnk78) (and help us improve it by pointing out what's missing our out-of-date, and adding to it with other useful info you come across!)
- [x] Review the materials on [this wiki page](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Amida-Hand-off-Resources) for walkthroughs of the code
- [x] Watch [this demo](https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1681744096244719?thread_ts=1681304404.488959&cid=C03UA9MV1EH) from the Lighthouse Delivery Infrastructure (LHDI) team on the SecRel pipeline and SD Elements
- [x] Use our daily scrum meeting to find opportunities to pair with other engineers on the team and start getting familiar with our current work
- [x] When you get a VA email address, add it to your Github account

**Comment by tejans24** [comment]
@dianagriffin / @smythe5 - I do have a VA email now teja.naraparaju@va.gov for a few tasks requiring VA email above.

**Comment by dianagriffin** [comment]
Okta/Datadog account requested - ticket here: https://jira.devops.va.gov/servicedesk/customer/portal/1/DOTSD-29561

**Comment by tejans24** [comment]
@dianagriffin I still don't see any email regarding Okta/Datadog in my VA email inbox, anything else I need to do on my end?

**Comment by dianagriffin** [comment]
@tejans24 I've just hit the "escalate" button on the request ticket. Hoping that will prompt a response this week. 🤞
