### ISSUE TITLE
Automate testing for Dependabot PRs

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#1641]
**User Story**

As an engineer in the rotation for handling Dependabot PRs, I would like to reduce my time spent in testing those PRs consequently reducing the complexity of the rotation and allowing more impactful work to be completed.

**Acceptance Criteria**
* Tests needed to be confident to merge the PR run automatically when dependabot creates the PR:
   * `./gradlew clean build check docker`
   * SecRel
   * `dockerComposeUp` with passing health checks to ensure healthy containers
* If all the tests pass, the engineer would feel confident in merging the PR without further action.

**Notes**
[Old GitHub Workflow for running E2E tests for RRD](https://github.com/department-of-veterans-affairs/abd-vro/blob/develop/.github/workflows/rrd-end2end-test.yml)

**Comment by dianagriffin** [comment]
"All the tests needed" 
- In the processing guide there are some additional tests on top of running secrel
- Make sure the tests we're currently running in the dependabot processing guide are either already covered or newly covered in scope of this ticket

**Comment by dianagriffin** [comment]
@msnwatson will add 3 things to the AC

**Comment by msnwatson** [comment]
There is an overlap here with the ask for basic fidelity checks around docker build steps and container health checks from Team CC such that the remainder of this ticket would be very small so it probably makes sense to go ahead and include it in sprint W @dianagriffin

**Comment by dianagriffin** [comment]
I'm down if you feel good about capacity to wrap it up in Sprint W, @msnwatson! Not sure if the remainder on this ticket is in a state that someone else could pick it up and help out with it, but please bring it up in standup if you want help on it!

**Comment by msnwatson** [comment]
Updates to the Wiki page in support of automated testing:
* https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot/_compare/50beaa6ece650d531866a4cfda2991aa58e5b144...66577e9a4de15f23561399438d9375a41edb3216
* https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot/_compare/66577e9a4de15f23561399438d9375a41edb3216...3fab251420946302ac3de249ac933dbab30cd524
* https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot/_compare/3fab251420946302ac3de249ac933dbab30cd524...ee5c97820012989e3b2203ed89992422e2103da7

**Comment by msnwatson** [comment]
Updated Pull Requests guidelines to add some explanation about skipped actions on PRs
https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests/_compare/3889786e232b8bc566373712cf0c708e2a3e8623...269a6af59aac6f1691dbc822e457cbbcf08f5ea4
