### ISSUE TITLE
Improve wiki documentation around deployment

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1644]
**User Story**

As a VRO or partner team developer, I want to clearly understand deployment processes on VRO, so that I can easily follow the process to deploy in non-prod and prod environments.

**Context**
The following wiki pages have recently been created/updated:

- https://github.com/department-of-veterans-affairs/abd-vro/wiki/Deploying-VRO
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/Deploy-to-Prod
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/Quick-Deploy-Instructions
- https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Release-Process

They can be further improved, reorganized, merged, and cleaned up. This may be a good task for new team members with fresh eyes.

**Acceptance Criteria**

1. Deployment related wiki pages have been reviewed and suggestions for improvement have been shared with the team for feedback
2. With team consensus, suggestions for improvement have been implemented as updates/reorganization of the wiki pages.
3. Updated documentation is validated through an actual release/deployment

**Comment by dianagriffin** [comment]
Running through the instructions to actually do a deployment is not a requirement of this ticket, but should the opportunity arise within the sprint, that's a bonus. 👍

**Comment by tejans24** [comment]
Made some WIP changes to Deploying VRO docs - https://github.com/department-of-veterans-affairs/abd-vro/wiki/WIP:-Deploying-VRO It would be great for the team to review and see if they understand.

**Comment by tejans24** [comment]
It also seems like some of the Release Process steps are shared with Deploying Vro steps. I think we can consolidate some of those steps together. So the docs aren't scattered with repetitive information.
