### ISSUE TITLE
Set up DataDog charts and alerts with CC team to support their initial system monitoring needs

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1653]
**User Story**

As a CC team engineer, I want basic system monitoring for my application set up in DataDog by the time my application launches to production, so that I am ready and able to monitor application health and basic performance metrics upon launch of my product.

**Acceptance Criteria**

1. DataDog is set up and configured for the CC's team's initial system monitoring needs, such that the CC team is enabled to monitor the CC application when their MVP launches.

**Notes about work**
- Per comment below, @lukey-luke already has access to Datadog, while our team is working on getting access
- This ticket continues work begun in #1581 ; see comment thread on that ticket for additional context.

**Comment by lukey-luke** [comment]
fyi, I do have access to https://lighthousedi.ddog-gov.com/

^ I think this is where VRO datadog logs would live? Maybe I just need instructions on how to view them?

**Comment by dianagriffin** [comment]
@lukey-luke that's great! yes, that's where we're pending access for VRO datadog setup. I think that means that worst case scenario we can pair with you on setting it up via your access -- although we're escalating our access requests and hope to get them resolved shortly!

**Comment by dianagriffin** [comment]
Cross-linking the relevant CC team ticket: https://app.zenhub.com/workspaces/contention-classification-640a24db5dcd08457cebbc79/issues/gh/department-of-veterans-affairs/vagov-claim-classification/168

**Comment by dianagriffin** [comment]
CC team would like this available by Thurs 6/15 when they are targeting deploying to staging/sandbox. VRO to ensure we can meet this timeline.
