### ISSUE TITLE
Begin prod release process on/around 6/14 for CC team's MVP launch planned for 6/21

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1661]
### User Story
As a VRO team engineer, I want to manage the production release process for the CC team's MVP launch, so that I can ensure the stability of the VRO platform and provide the CC team confidence in their release.

### Acceptance Criteria
- CC application is successfully released to prod on their desired timeline.

**Comment by yoomlam** [comment]
Refer to [Release Process](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Release-Process) and [Partner Team Deploy Process](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Deploy-Process).
