### ISSUE TITLE
Classification Service should return proper status codes

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/abd-vro#1667]
**User Story**

As a consumer of the Contention Classification service , I want meaningful http status codes, so that I know what is coming back more easily.

**Acceptance Criteria**

1. POST requests that match a code, or are valid, but do not match a code, come back with `200`
2. POST requests with malformed input payloads (either invalid syntax, missing keys, or incorrect/unacceptable key values) comes back with `422`

**Comment by lukey-luke** [comment]
Thanks for submitting a ticket @kylesoskin 
For reference, including status codes here:
 https://www.rfc-editor.org/rfc/rfc9110#name-200-ok
