### ISSUE TITLE
Implement a platform (domain-independent) Kafka client to connect to mock Kafka service

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1676]
**User Story**

As a VRO client dev, I want connect to Kafka events though standard VRO micro services, so that I can develop against them within the VRO platform without learning Kafka.

**Dependent on**
- Depends on #1675 in order to complete (but can be started with no dependencies)

**Context**
- Create a new microservice in a new svc-bie-kafka Gradle subproject
- It needs to interface with other VRO microservices via RabbitMQ
- To implement using Spring, check out https://www.baeldung.com/spring-kafka

**Acceptance Criteria**

1. A domain independent kafka client connects to the mock kafka service created in #1675 
2. Upon startup, the Kafka client microservice subscribes to Kafka topics.
3. When each Kafka topic event comes in, the Kafka client microservice adds an event payload to a RabbitMQ exchange.

**Notes about work**
- This ticket is part of epic #1642

**Comment by dfitchett** [comment]
Initial thoughts for design: 
* Create `svc-bie-kafka` gradle project in `abd-vro` directory
* Create `BieKafkaApplication` with dependencies for Spring amqp and kafka
  * `application.yml` will set up connections to RabbitMq and Kafka on default connections
  * `KafkaConsumerConfig` will set up a kafka consumer to listen to topic as part of groupId, both topic and groupId are set in `application.yml`.
    *  this listener will use a service class to use camel to start a simple workflow to send the msg to the corresponding rabbitMq, or use a simple service that sends the msg directly to rabbitMq without camel.
