### ISSUE TITLE
Update the mock general Kafka service to be like BIE's Kafka service in regards to Schema Registry (for testing and dev)

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1678]
**User Story**

As  an Engineer, I want to send messages to BIE Kafka Consumer using Avro Serializer, so that  I can perform all of the BIE kafka functionality end-to-end.

**Dependent on** 

**Context**
You will need to:
- Investigate options to integrate schema registry to support the Kafka consumer
   - Option 1: Create Schema Registry container to support BIE avro schemas
   - Option 2: ?

**Acceptance Criteria**

1. VRO's mock kafka service mimics BIE's kafka service that includes schema registry to Serialize and Deserialize Avro messages to Kafka

**Notes about work**
- This ticket is part of epic #1642

**Comment by dianagriffin** [comment]
Further refinement may not be necessary -- pending engineering conversation on whether or not to mock the schema registry pieces in lower envs

**Comment by smythe5** [comment]
Engineers need to discuss this ticket.  Maybe since this is only local, we don't need.

**Comment by dianagriffin** [comment]
Team discussed and determined this ticket won't provide sufficient value for the effort.
