### ISSUE TITLE
Update the platform BIE Kafka client to connect to the mock BIE Kafka service with authentication

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1679]
**User Story**

As an engineer, I want exercise the client on my local machine, so that I can develop without connecting to the VA network.

**Dependent on** 
- #1676 
- #1678 (the authentication portion, which will be broken out)

**Context**
You will need to:
- Authenticate to mock BIE's Kafka service; only this microservice holds the credentials and is responsible for authenticating

**Acceptance Criteria**

1. The platform BIE kafka client microservice connects to the mock BIE kafka service with authentication (as close to production as possible)
2. Confirm that when each BIE topic event comes in, the Kafka client microservice adds an event payload to a RabbitMQ exchange with the appropriate routing key.

**Notes about work**
- This ticket is part of epic #1642

**Comment by dfitchett** [comment]
Some bitnami kafka configuration stuff can be found [here](https://hub.docker.com/r/bitnami/kafka/).

**Comment by yoomlam** [comment]
Waiting for Cheng to fix CI tests before posting my PR
