### ISSUE TITLE
Update Helm configs and Vault secrets with BIE credentials, and deploy to LHDI and test in each relevant env

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1682]
**User Story**

As , I want , so that .

**Depends on**
- #1680 

**Context**
- Only the platform BIE Kafka client microservice needs these secrets (in order to authenticate)
- Deploy to LHDI and test in each relevant env

**Acceptance Criteria**

1. Example domain code is tested and deployable across VRO environments. 

**Notes about work**
- This ticket is part of epic #1642

**Comment by chengjie8** [comment]
we need 

- truststore string (decoded from base64 string from vault)
- truststore password
- keystore string 
- keystore password

**Comment by yoomlam** [comment]
I recommend you add the following keys to Vault under a new `VRO_SECRETS_BIE_KAFKA` folder:
```
BIE_KAFKA_TRUSTSTORE_BASE64
BIE_KAFKA_TRUSTSTORE_PASSWORD
BIE_KAFKA_KEYSTORE_BASE64
BIE_KAFKA_KEYSTORE_PASSWORD
```

Refer to `VRO_SECRETS_BIP` Vault folder for similar examples.
Search for `_BASE64` in https://github.com/department-of-veterans-affairs/abd-vro/wiki/Secrets-Vault and read its usage.

**Comment by chengjie8** [comment]
I am waiting for BIE team to provide answers to our kafka consumer group permission. Currently, our consumer group is blocked 

<img width="730" alt="image" src="https://github.com/department-of-veterans-affairs/abd-vro/assets/89034346/a0683d28-6b27-422d-bfb2-13f1f0627950">
