### ISSUE TITLE
VSR research synthesis & writeup

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1707]
### Goal
Complete VSR research synthesis & writeup by the end of Sprint X.

### To-do's
- [x] Complete synthesis
- [x] Complete writeup
- [ ] Share with team!

**Comment by ChristineRoseSteiffer** [comment]
Ready to share [the report](https://docs.google.com/document/d/1SSJ87rYRG0DuRYbTSqz9TUuhTNqh_dxUlpUwCCTG6EI/edit?usp=sharing) out on Wednesday's sprint review :)
