### ISSUE TITLE
Automate PR review assignment

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1711]
**User Story**

As a VRO engineer, I want all PRs within our codebase to be automatically assigned to the VRO engineering team for review, so that my team is aware of new PRs awaiting review and able to provide reviews in a timely fashion.

**Acceptance Criteria**

1. When a PR is created in abd-vro, it is automatically assigned to a Github team that includes only the VRO engineers.

**Comment by tejans24** [comment]
Add instructions to the Wiki here: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests#reviewers-auto-assignment

**Comment by tejans24** [comment]
Update docs here: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests#codeowners
