### ISSUE TITLE
 ∞ loop over "Listener Threw Exception"

### ISSUE THREAD

**Issue by engineer-plus-plus** [department-of-veterans-affairs/abd-vro#1738]
The exception with highly useful message "Listener Threw Exception" as described in [this issue](https://github.com/department-of-veterans-affairs/abd-vro/issues/1737) is printed over and over again in an infinite loop

**Comment by yoomlam** [comment]
See https://github.com/department-of-veterans-affairs/abd-vro/issues/1737#issuecomment-1609691914

**Comment by dianagriffin** [comment]
Is this issue resolved by the process described in the comment on #1737 ?

**Comment by engineer-plus-plus** [comment]
I suspect the problem was that, under certain conditions, the default error handler was throwing an exception.  Than catching it, processing it, failing again, throwing exception, etc forever.  In svc-bip-api, I fixed this by termination the process in case the default error handler errors.  maybe it would be a good ide to do same in the example.

**Comment by engineer-plus-plus** [comment]
> Is this issue resolved by the process described in the comment on #1737 ?

It is unclear since the described process uses a bunch of components that seem to be outside of scope of this issue.

**Comment by engineer-plus-plus** [comment]
I can no longer recreate the problem.
