### ISSUE TITLE
Detect hypertension new claims on va.gov

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#176]
As a member of the Automated Benefits Delivery team, I want to know when a hypertension NEW claim is submitted on VA.gov (single or multi issue) so that we can assess eligibility of the claim for PACT Act presumptive service connection.

**Acceptance Criteria**
* We are notified in the `#hypertension-claims-tracking` Slack channel when a claim is submitted on VA.gov with `disability classification code` = **3460 (hypertension)** or **3370 (high blood pressure)** AND `disability action type` = **new**
* The Slack notification should include:
-- Benefit Claim ID | Submission Date | Submission Time | Submission ID 
-- Single or multi issue: xx 
-- Service history dates: xx 
-- # of BP readings: xx 
-- # of active medications: xx 
* **Note**: ^The first 3 items come from the claim; the last 2 come from [Lighthouse's Patient Health API](https://developer.va.gov/explore/health/docs/fhir?version=current)
* **Note**: the Slack notification will eventually evolve into 3 different notifications - 1) PDF is generated; 2) PDF is not generated due to insufficient health data; 3) PDF is not generated due to no Agent Orange Exposure Verified flash
* The notifications can be turned on/off with a flipper flag

Mural reference: [link](https://app.mural.co/t/nava4113/m/nava4113/1657583510044/4f9cd029d98fce3c1513055889f1b9d0d6871eb1?wid=0-1658358757375)

**Comment by yoomlam** [comment]
@amylai-nava Can this requirement for the Slack notification:
> -- Single or multi issue: xx

be changed to 
> -- Number of claimed issues: xx

**Comment by amylai-nava** [comment]
@yoomlam yes 👍
