### ISSUE TITLE
Research story: Document and identify improvements in GH workflows/actions/CI

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#1760]
**User Story**

As a VRO DevOps engineer, I want to have a clear understanding of what GitHub actions/workflows run for what events, so that I can feel confident that actions are not running multiple times and better make changes in a modular way.

**Acceptance Criteria**

1. High-level documentation of our GitHub actions/workflows, linking out to the components of our CI infrastructure like SecRel/Dependabot/Release Process
2. Follow-up tickets with recommendations for improvements (issue author is expecting >=2 tickets to results from this effort)
     a. Tickets should also address the accrued tech debt of upgrading springboot/gradle/spring

**Not included in this work**

* This is not meant to cover the scope of making improvements identified through developing a better understanding of the GitHub actions/workflows. Though, if it is easier to simplify things so that documentation is easier then this can be done in tandem.

**Comment by yoomlam** [comment]
Refer to:
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/Deploying-VRO
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/CI-CD-Workflows
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/Github-Actions
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/Secrets-Vault

**Comment by meganhicks** [comment]
Is this still needed?

**Comment by msnwatson** [comment]
Stale. Closed as won't do
