### ISSUE TITLE
BipApi Loose Ends

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1777]
This is continuation of story #1594.  There is a number of things that have to be accomplished in order the service to become fully prod ready.  Following is the list of them.  It can be considered the acceptance criteria for this story:

- ~~The integration test doesn't work right because Mockito doesn't seem to get along with Spring's dependency injection.  Mocking of of BIP-true-api doesn't work.  This has to be resolved.~~
- The test needs RMQ broker running in order to test the integration with it.  We need to figure out a way to programmatically stand up the RMQ container before the test.
- ~~Derek [pointed out a bunch](https://github.com/department-of-veterans-affairs/abd-vro/pull/1774/files/e8d47285597ff42922ded663d407d03afb8dd272) of defects in the the code of RMQ integration test.  They should be addressed.~~
- ~~More granular error reporting needs to be implemented in contrast to current crude error handling that returns 500 for any kind of error.~~
- The condition of BIP mocs has to be evaluated in order to see if they are useful for testing.
- ~~add README file documenting usage~~
- Test coverage meets jacoco_minimum_coverage of 0.5 (commit 9f1d10d)

In addition to the above, the following items should be completed.  But they are recommendations and not required for this story.  Each deserves their own story.

- refactor BipService class and its test
- write an automated test that verifies the integration of the service with the true Bip api.  Currently all interactions with it are mocked in tests.

**Comment by engineer-plus-plus** [comment]
Solution to the part quoted below[ here](https://github.com/department-of-veterans-affairs/abd-vro/pull/1836).


Test coverage meets jacoco_minimum_coverage of 0.5 (commit https://github.com/department-of-veterans-affairs/abd-vro/commit/9f1d10d24bd5c43a628f6236e67d6ed1c224ab03)

**Comment by engineer-plus-plus** [comment]
[The buld including apparently sufficent coverage. ](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5624751953
)

**Comment by engineer-plus-plus** [comment]
[Here is the latest build with all tests passing](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5650576310/job/15307165874?pr=1836
)

**Comment by dianagriffin** [comment]
Replaced by #1974
