### ISSUE TITLE
Fill in missing sections in Research index

### ISSUE THREAD

**Issue by shannonkford** [department-of-veterans-affairs/abd-vro#179]
Research Index is currently in [Google Docs](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit?usp=sharing) for onboarding purposes.

A couple of lower priority sections remain to be documented:
- [x] Early work on the VRO
- [x] VRO idea bank
- [x] Early work with RVSRs (pre-July 2021)
- [x] Contention selection work

**Comment by carodew** [comment]
@shannonkford is there more left to do on this card?

**Comment by shannonkford** [comment]
@carodew We appear to be missing a link to the VRO idea bank and the pre-Shannon and Carolyn work. The latter is low priority so we could probably close it.

**Comment by carodew** [comment]
Let's leave it open for now so I have a reminder to take care of that.
