### ISSUE TITLE
Make Lighthouse data transform code consistent

### ISSUE THREAD

**Issue by erogray** [department-of-veterans-affairs/abd-vro#18]
low-priority refactoring task

`LighthouseMedicationRequestData` creates a `Struct` and returns a hash with `with_indifferent_access`, while `LighthouseObservationData` does not. Let’s make them consistent so we can follow a pattern for future transforms of external data.

**Comment by amylai-nava** [comment]
Closing since this ticket is related to RRD in vets-api and is no longer applicable. cc: @dianagriffin
