### ISSUE TITLE
Update rated disabilities in 526 form to include max for tinnitus

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#1804]
**Acceptance Criteria**

The API endpoint `GET /disability_compensation_form/rated_disabilities` returns a list of rated disabilities, where
- a tinnitus disability includes a field indicating a maximum rating of 10%
- any other disability omits this field

**Not included in this work**
- The 10% should be hard-coded into `vets-api`. Future work will include replacing this with a call to a new Max CFI API in VRO.

**Comment by amylai-nava** [comment]
note to self: moved from sprint y to z
