### ISSUE TITLE
Establish BIE<>VRO connectivity in prod

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1806]
**Dependency**
- #1682
- #1683 
- Note that BIE will not issue prod certs until we've confirmed that we've tested our overall kafka functionality in lower environments (staging)

**Acceptance Criteria**

1. VRO and BIE prod environments are successfully connected and relevant information about establishing that connectivity is documented. 

**Notes about work**
- This is part of #1642

**Comment by chengjie8** [comment]
We have verified `svc-bie-kafka` microservice in `prod-test` and `prod` environments are fully functional and kafka topic messages show up in the pod logs.
