### ISSUE TITLE
Ongoing EE team development support

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1816]
This is a recurring, placeholder ticket to represent capacity put towards support needs for the Employee Experience (EE) team that come up during the sprint.

Please add a comment here linking to relevant slack threads/PRs/other context if you need to spend time supporting the EE team for more than half a day on something that is not represented by another specific ticket.

**Comment by tejans24** [comment]
Created this for enabling deployments: https://github.com/department-of-veterans-affairs/abd-vro/issues/1852

**Comment by dianagriffin** [comment]
@tejans24 I saw that the EE launch plan includes a VRO task of setting up Datadog monitoring; would you consider that in-scope for this general support ticket? Or, should it be captured in its own ticket?

**Comment by dianagriffin** [comment]
Closing this ticket since we have not been actively updating it to track partner team support work. Instead, when partner team support needs arise within a sprint we will capture them in a dedicated ticket and follow our usual prioritization process (sharing the ticket and discussing priority with the team) to address them.
