### ISSUE TITLE
Finalize max CFI design for MVP

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1827]
## to do
[x] decide which version of the design we are going to launch our pilot with
[x] finalize design

## decision
- Insert one line of text in the tinnitus box: "You're already rated at the maximum rating for tinnitus"
- [link to sketch file](https://www.sketch.com/s/7b704520-bd67-4e58-8187-2164d7616bd4/prototype/a/5CCE9A0B-B19C-4E0C-AFE2-A90821E70893)

**Comment by amylai-nava** [comment]
@carodew @KimLadin @ChristineRoseSteiffer, I remember my question from standup now. I was going to ask if we should move this to "done"? I updated the ticket with our decision & the link to the prototype. I'm assuming no additional design work is needed but wanted to check with y'all.

**Comment by carodew** [comment]
I think there will be some working with the engineering team when it comes time for implementation to define spacing and other design details, but I think that should be captured in a separate ticket.

**Comment by amylai-nava** [comment]
agree! #1858 is the ticket for that.
