### ISSUE TITLE
Create DataDog monitors for high resource usage of containers

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#1839]
**User Story**

As a VRO engineer, I want to know quickly if there are any containers that are approaching their CPU/memory resource requests from Helm, so that I can respond with proper scaling as needed to prevent container downtime and disruption. This will ensure I address critical issues before they happen and make the platform more reliable for the VRO Team and it's partners. 

**Acceptance Criteria**

1. Ensure that all containers specify their resource requests and confirm that the requested resources are relatively similar to resource consumption being seen in production.
    - Kubernetes Memory and CPU
2. Create monitors for each container in DataDog to alert if a container reaches actual utilization of >(80 or 90%) of the requested resources
    * Leverage pods down alerting
    *Leveraging Pager Duty mechanism once on-call rotation is rolled out- removed this AC

**Notes about work**
- Slack thread where this was first mentioned: https://dsva.slack.com/archives/C04QLHM9LR0/p1689264000171649

**Comment by meganhicks** [comment]
@agile-josiah can you confirm after the tech spec if this is needed?

**Comment by tejans24** [comment]
Providing a link to the dashboard associated to the containers with an alert is created will be useful.

**Comment by tejans24** [comment]
Memory Usage Monitor: https://lighthousedi.ddog-gov.com/monitors/205812?view=spans
CPU Usage Monitor: https://lighthousedi.ddog-gov.com/monitors/206559?view=spans
