### ISSUE TITLE
Write quick one-pager on max CFI veteran research

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#1843]
Bullet points!

See suggested topics to cover here https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689302928811/cb963247dbd1c9f4aa9842439693d513510069ad?wid=0-1689362846223&sender=carolyn1198

**Comment by amylai-nava** [comment]
closing as done based on [this thread](https://dsva.slack.com/archives/C01BVF2A3V0/p1690916107312099)!
