### ISSUE TITLE
Investigate false positives in Datadog Logs for VRO CC

### ISSUE THREAD

**Issue by lukey-luke** [department-of-veterans-affairs/abd-vro#1844]
**User Story**

As an engineer, I want error messages to accurately indicate issues with the system, so that it is clear when action is needed.

The goal of this ticket is to investigate the reason why this issue is happening. 
**Acceptance Criteria**
- [ ] Investigate potential issues causing these errors
- [ ] Create upcoming tickets to fix the issue/s

Potential tasks to fix it once investigation:

1. messages for starting up container do not trigger an alert in alerts channel
2. We may want to include "shutting down" if something is tripping up workers and forcing the system to keep restarting??

**Not included in this work**
n/a

**Notes about work**
- [example false positive](https://dsva.slack.com/files/USLACKBOT/F05J30ZPDKR/triggered__errors_in_vro_cc_application_logs_for_prod_environment)
- Evaluate if we should migrate these alerts to the va.gov alerts slack channel and create tickets if so (ask Steve Albers)

**Comment by verdance-luke** [comment]
Ideally, we pipe production alerts to [#slack-benefits-alerts-notifications](https://join.slack.com/share/enQtNjEyNDgxMjUwMDM4Ni1jZjVkZTBkMWUzZmFkODUyN2Y2YzAxNWJmNjFiZjJhMTRkNDQwMzMzODcwMDM4MzM1YzU3ZWQxZjNiMTVkNDEy) in DSVA.

Looks like existing monitor for VA.gov datadog use @slack-benefits-datadog-alerts user, so maybe we need to get that email added to LHDI datadog

**Comment by verdance-luke** [comment]
looks like we can send them to this email:
benefits-alerts-notif-aaaakykaasixjiip63rmi7nubi@dsva.slack.com

**Comment by verdance-luke** [comment]
<img width="914" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1piQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--645b889a8f549690a79f63f38c47e1b819c359fe/Screenshot%202023-12-13%20at%201.54.05%20PM.png" alt="Screenshot 2023-12-13 at 1.54.05 PM.png" />


<img width="997" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e98d480965c5dba040c2b3beb966323515b046d0/Screenshot%202023-12-13%20at%201.54.09%20PM.png" alt="Screenshot 2023-12-13 at 1.54.09 PM.png" />



After digging into the [production monitor](https://lighthousedi.ddog-gov.com/monitors/139085/edit) that has been triggered by false positives, it looks like there's not a straightforward way to just exclude based on content.

It seems that it is triggered by queries filtered by tag, so figuring out how to tag these types of messages as `Info` or `Warn` is the only fix I can see for handling this at this time.

**Comment by verdance-luke** [comment]
nvm, @msnwatson figured out that you can use `-` to exclude log entries
e.g.

<img width="998" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkpjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--410fcdc66d11af7abe1fc6a75f91f2f4932b2c7d/Screenshot%202023-12-13%20at%203.36.14%20PM.png" alt="Screenshot 2023-12-13 at 3.36.14 PM.png" />

**Comment by verdance-luke** [comment]
Updated monitors for both the prod and sandbox channels to exclude the server startup strings
```
INFO:     Shutting down
INFO:     Uvicorn running on http://0.0.0.0:8120 (Press CTRL+C to quit)
INFO:     Application startup complete.
INFO:     Waiting for application startup.
INFO:     Started server process [1]
INFO:     Finished server process [1]
INFO:     Application shutdown complete.
INFO:     Waiting for application shutdown.
```

Let's observe the next couple days and see if will be a sufficient workaround for the false positives

**Comment by verdance-luke** [comment]
fyi, prod monitor [here](https://lighthousedi.ddog-gov.com/monitors/139085) and sandbox monitor [here](https://lighthousedi.ddog-gov.com/monitors/138625)

**Comment by verdance-luke** [comment]
after discussing w/ Sam, I removed `INFO:     Application shutdown complete.` from both monitors

**Comment by verdance-luke** [comment]
shutting down still shows up in the logs, posted in #vro-support on alternative way to check on desired behavior [here](https://dsva.slack.com/archives/C01Q7979Z7D/p1703009761417959)

**Comment by verdance-luke** [comment]
Today after standup, I spoke w/ Tyler + Sam on ways to get around this. I think if we have a health check to ensure the system is alive, we can exempt the shutting down line and improve our alert accuracy.

In doing so, I've been investigating how this might be achieved in datadog. It looks like this can be done via a [Network Check](https://docs.datadoghq.com/monitors/types/network/?tab=checkalert) monitor. This requires a [datadog agent](https://docs.datadoghq.com/monitors/types/network/?tab=checkalert) to do, which requires an API key.

Assuming the proper access, it seems fairly straightforward to set this up. See attached.
<img width="1213" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1039828d4a32e61e4cb3d35dac6f71b0ab137e93/Screenshot%202023-12-21%20at%202.00.57%20PM.png" alt="Screenshot 2023-12-21 at 2.00.57 PM.png" />

**Comment by lukey-luke** [comment]
Posted an inquiry in LHDI slack [HERE](https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1703196339126399).

**Comment by verdance-luke** [comment]
Looks like a synthetic API test might be able to cover this, but if it's in LHDI datadog, how will I give access to the API?

**Comment by verdance-luke** [comment]
I added a health check alert for the va.gov datadog [HERE](https://vagov.ddog-gov.com/synthetics/details/xgr-469-k9a?from_ts=1703882788171&to_ts=1703886388171&live=true).

I will exempt the shutting down message to cut out the remaining false positives.

**Comment by verdance-luke** [comment]
The IP address for the above API test appears to resolve the same each time (10.249.60.252). However, it fails to make an HTTP/2 request intermittently and falls back on HTTP/1.1. I posted a question in the LHDI support slack [here](https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1704214199574909?thread_ts=1703196339.126399&cid=C03UA9MV1EH).

**Comment by verdance-luke** [comment]
New test in LHDI datadog here:
https://lighthousedi.ddog-gov.com/synthetics/details/2au-x3r-xnt?from_ts=1704214137711&to_ts=1704217737711&live=true

**Comment by verdance-luke** [comment]
^ I think the above test will capture the signal @raudabaugh is looking for in terms of ensuring service uptime. And I ignored the false positives with the `"-"` syntax as shown in earlier screenshots. 

This doesn't cover E2E as in VA.gov being able to contact the service. That would be a good enhancement for future work that would help other VRO partner teams as well.

**Comment by verdance-luke** [comment]
seeing some 502 bad gateway messages from failed synthetic API test [HERE](https://lighthousedi.ddog-gov.com/synthetics/details/2au-x3r-xnt?monitorStatus=fail&resultId=4153402398269932516&from_ts=1702251136828&to_ts=1704843136828&live=true). Moving back to backlog to investigate later.

**Comment by yurenanava** [comment]
@verdance-luke Can you close this ticket and create a new follow up ticket in our board with the remainder of the work?

**Comment by lukey-luke** [comment]
Yeah I'll take a look during refinement
