### ISSUE TITLE
Update vets-api to use VRO's max CFI API

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1848]
As a VA product owner, I want to store the maximum ratings for each disability in VRO to enable the max CFI project and potentially other claims-fast tracking efforts in the future.

## Acceptance Criteria
- Update vets-api to use VRO's max CFI API rather than use local ruby code 
- Put this behind a feature flag

notes:
- this task is dependent on: https://github.com/department-of-veterans-affairs/abd-vro/issues/1821
- and replaces this: https://github.com/department-of-veterans-affairs/abd-vro/issues/1804

**Comment by dfitchett** [comment]
Carried over from Sprint Agave. Item was still in PR.
