### ISSUE TITLE
By 8/21: Setup a deployment process/plan for domain-ee in nonprod

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#1852]
Based on the work done here in this [PR](https://github.com/department-of-veterans-affairs/abd-vro/pull/1851), configure a deployment process for `domain-ee`.

Work with @dfitchett and @nanotone for additional details if needed.

Due date: (08/21)

What's does it consist?
- `max-cfi-app` using the APIGateway
- domain-ee test suite
- deployments enabled in nonprod envs

**Comment by yoomlam** [comment]
Refer to [previous PRs](https://dsva.slack.com/archives/C04QLHM9LR0/p1689186062306059) as examples.

**Comment by dianagriffin** [comment]
Please add story points to this ticket when you start it! Thanks :)

**Comment by tcraghu** [comment]
Current state:- 
- Pipelien build domain-ee applications and publishing to ghcr
-  Pending deployment and testing

**Comment by tcraghu** [comment]
- Build and Deploy of EE to DEV,QA and Sandbox Completed
- PR 1 https://github.com/department-of-veterans-affairs/abd-vro/pull/1922
- PR 2 https://github.com/department-of-veterans-affairs/abd-vro/pull/1932

Document link https://github.com/department-of-veterans-affairs/abd-vro/wiki/Deploying-VRO#verify-and-fix-secrel:~:text=EE%20%E2%80%90%20Build%20and%20Deploy%20Process
