### ISSUE TITLE
Discovery on va.gov claims data visibility needs across the Benefits Portfolio

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1855]
**Context**

As an OCTO product owner / VRO product manager, I need a thorough understanding of the needs for va.gov data visibility across the Benefits Portfolio teams, so that I can shape OCTO's approach and solution(s) in this problem space.

**Acceptance Criteria**

1. A lightweight research plan is devised that allows us to move as nimbly as possible to discover needs for va.gov data visibility across the Benefits Portfolio teams. Note that methods can be quant/qual or both; valuing speed over rigor. 
2. The research plan is executed in Sprint A (by Aug 15th) to result in an unprioritized list of needs from the Benefits Portfolio teams. Any open questions surfaced from the research or synthesis process should be noted in the research findings documentation.

**Notes about work**
- Context on the problem space and needs uncovered so far: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689805673860/562838f00f27c06b8ff311f6d15da3da839b1bb2?sender=uae60665e239c35f86ce44265

**Comment by megameg** [comment]
We can update the [existing research plan](https://docs.google.com/document/d/1m-gAYE15R7Zsmy2u9QO8Sy-1aDZph8G16Hjgf32LK_E/edit?usp=sharing) to reflect 'data visibility' needs

**Comment by megameg** [comment]
- [ ] Write survey for Benefits Portfolio teams
- [ ] Get feedback from Emily & Premal
- [ ] Figure out best way to share survey internally at the VA (ie. can we use Google Forms?)

**Comment by megameg** [comment]
- Survey created and shared with benefits-portfolio teams (on slack)
- PACT Act deadline coincided with posting, which may have lead to lack of response
- Contacted teams directly about the survey
- As of end of sprint A - we have 3 responses

**Contacted teams & their Product Managers**

- [ ] Benefits management tools - Jacob Worrell
- [ ] Dependant management - Laura Steele
- [ ] Non-disability teams - Laura Steele
- [ ] CC team - Yurena Garcia
- [ ] EE team - Amy Lai


**Responses from at least one person on the team**

- [ ] Benefits management tools - Jacob Worrell
- [ ] Dependant management - Laura Steele
- [ ] Non-disability teams - Laura Steele
- [ ] CC team - Yurena Garcia
- [ ] EE team - Amy Lai

**Comment by megameg** [comment]
[Mural for synthesis](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692204081217/71371e6750bcf85ebe2683060ba477f8a920a852?sender=u28d78ff735355312dd6c9422)

[Spreadsheet responses](https://docs.google.com/spreadsheets/d/1AwWudmz-U808DgfxuWsPhJTdQ0-m_DGgyXmbFAucsj0/edit?usp=sharing)

**Comment by megameg** [comment]
Reassigning to Diana due to start of Parental Leave

**Comment by megameg** [comment]
Initial findings/ themes: 
• There are broad questions that every team is likely to have at the beginning of
a project (ie. How many claims are submitted per [time]? How many are
submitted online? How many involve a particular condition or other variable?)
• This data can be more static
• Next, they’ll have follow up questions. This will lead to very specific data for
their project. > this data will probably need to be more responsive/dynamic
• Data should be presented to match Veteran’s & (R)VSR’s points of view since
that’s who we’re designing for.
