### ISSUE TITLE
Add max ratings education to 526 flow on va.gov

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1858]
As a Veteran, I want to know if I'm at the maximum rating for tinnitus when I'm filing a disability claim on VA.gov so that I can make a more informed decision on what to submit a claim for.

## Acceptance Criteria
- If a Veteran is already at the maximum rating for tinnitus (10%), display the following text in the tinnitus box on the Rated Disabilities screen within the 526 disability compensation flow:
- `You're already rated at the maximum rating for tinnitus.`
- [link to sketch file](https://www.sketch.com/s/7b704520-bd67-4e58-8187-2164d7616bd4/prototype/a/5CCE9A0B-B19C-4E0C-AFE2-A90821E70893)
- If a Veteran is not at the maximum rating for tinnitus (0%), do not display this message

### Notes:
- The diagnostic code for tinnitus = 6260

**Comment by carodew** [comment]
It might not be as simple as 'dropping' a sketch file. I'll also need to update it with notations for @nanotone based on what he needs, and there's probably a hand off conversation (or several). Might be worth setting up a time for the three of us to talk through what annotations are needed? 

We also did not design a desktop version but I think that might be unnecessary at this stage, given how minimal the change is and the fact that there's an existing design system, but happy to talk it through.

**Comment by amylai-nava** [comment]
@carodew, setting up time for the 3 of us to chat sounds good! I had made a bunch of assumptions that even though we didn't design a desktop version, it would be okay for the reasons you stated.

@nanotone, let us know when would be a good time to chat, and I'll set it up.
