### ISSUE TITLE
Domain Setup Updates 

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1873]
#### User Story
As a member of the VRO Team or a customer of the VRO Platform, I require dependable documentation to enable efficient self-service and rapid issue resolution
#### Why
The VRO wiki currently contains many pages that are out-of-date or incomplete in terms of providing sufficient detail and guidance to VRO teammates to maintain and expand platform capabilities, as well as to partner teams to understand what VRO offers them and implement those solutions in service of their applications.

#### AC:
Review this and make any edits needed. Share updates with the team: 
https://github.com/department-of-veterans-affairs/abd-vro/wiki/New-Domain-Setup

**Comment by msnwatson** [comment]
This could obviously be a pretty labor-intensive task if done manually.

However, we should look at how we can leverage GitHub actions to interact with the wiki as a repo and provide through CLI manipulation with Git or other tools. There may even be existing actions written by the community which can help with this task while also providing a repeatable tool which can be used to keep the wiki fresh moving forward.

**Comment by msnwatson** [comment]
Did a quick cursory check and cannot find a community Github action to do this

**Comment by msnwatson** [comment]
@agile-josiah here is the ticket by the way!

**Comment by dfitchett** [comment]
This [section](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Software-Conventions#service-microservice-container-module) in the wiki is out of date and should probably just link the [RabbitMQ strategy page](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-RabbitMQ-Strategy).
