### ISSUE TITLE
Provide CC instructions for use of current VRO database

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1874]
Success = CC feels supported getting to development on their local machines

**User Story**

As a CC engineer, I want to understand how to get started using the VRO Postgres database for local development, so that I can begin designing and implementing my application's database needs.

**Acceptance Criteria**

1. Instructions for use of the current VRO database are documented and shared with the CC team.
2. When CC team has a set of tables/schemas they would like to create, it is clear to both VRO and CC who will be responsible for creating those entities.
3. There is clear guidance on how the CC team's application can interact with tables on local machines, including providing instructions for how to start all necessary containers required for local development.

**What's not included**
1. Instructions on how to integrate with RDS

**Comment by msnwatson** [comment]
CC team is seeking to model database tables within their application code as opposed to creating migration files to define table schemas. This should provide a benefit of having less code as they can use build-in validation tooling.

A wrinkle in providing this functionality is that the CC application setup code would need higher permissions than we currently offer at runtime for the VRO database. Current idea is to create a new database within the VRO Postgres instance and users which have appropriate permissions for team CC to manage creation and deletion of tables and schemas at application startup. I am going to do a run through of documentation and review the current architecture to understand what supporting this in the long-term might mean for VRO platform. Will follow up with @lukey-luke

**Comment by yoomlam** [comment]
@msnwatson For this scenario, VRO could create a DB user specifically for the Partner team. This will require some thought as to when the DB user is created (currently done by `init-db.sh` in the `postgres` container) and where the credentials for that DB user are stored (currently, we have `$POSTGRES_USER` and `$POSTGRES_PASSWORD`) and how it is propagated to containers that needed it: https://github.com/department-of-veterans-affairs/abd-vro/blob/3fb3f7e531cce2c7f12617e165137320ddc95b0b/helm/_shared/named_templates/_postgres.tpl#L8-L28, which means there will be more secrets to track and manage.
