### ISSUE TITLE
Document kafka keystore/truststore creation process on the Wiki page

### ISSUE THREAD

**Issue by chengjie8** [department-of-veterans-affairs/abd-vro#1880]

**Comment by dianagriffin** [comment]
I gave this a "small" story point given that it's documenting the process you've gone through, but please update the story points if you feel it should be more

**Comment by chengjie8** [comment]
I have modified the same section https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIE-Kafka-Client#create-keystore-and-truststore-files with the latest instructions.
