### ISSUE TITLE
Plan for max CFI post launch usability testing

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1901]
## Context

We are launching an MVP of our max CFI intervention for tinnitus to a limited number of users at the end of August 2023. In order to learn about how the intervention is working from the Veteran's perspective, we'd like to set up sessions to observe Veterans filling out the va.gov 526EZ form in real time, with real claims. There are a number of logistical problems to work out to this plan. 

## Resources

[Planning document](https://docs.google.com/document/d/1Xs_JYZ-CaoUdvg63spfp3NOTdqoNzB640QLzObqjnYo/edit#heading=h.nnuzqnw5gvun)

**Comment by amylai-nava** [comment]
@carodew @ChristineRoseSteiffer can y'all help populate this ticket with some info? thank you!

**Comment by ChristineRoseSteiffer** [comment]
There was a decision made to hold off for now on testing this feature in real time with Veterans due to a variety of factors.
