### ISSUE TITLE
Support CC's connection to kafka event streams via hoppy/RabbitMQ

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1904]
**User Story**

As a CC team engineer, I want VRO engineers to provide documentation & pair on establishing a pattern for using hoppy to implement domain-cc's use of the BIE event streams, so that I can successfully use this integration in accordance with VRO software conventions.

**Acceptance Criteria**

1. Create user guide(s) for partner teams to follow to implement against the VRO BIE integration. User guides should include data samples to represent what to expect from different event types. Include guidance on how to test & set expectations about the limitations of testing based on BIE's service. Include guidance on how to use the mocks and test locally (potentially using kcat).

**Comment by yoomlam** [comment]
Refer to #1701 for sample usage of hoppy

**Comment by dianagriffin** [comment]
Note that CC team needs to set up their use of VRO's database _before_ they will start using the kafka integration, so #1575 is a higher priority for Sprint C than this ticket. They are planning to set up database stuff in Sprint D and start using BIE data in Sprint E. 

cc/ @chengjie8 @msnwatson as this notes relates to your current work

**Comment by chengjie8** [comment]
a short user guide has been created [here](https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIE-contention-events-User-Guide), which includes sample code, including Python examples.

**Comment by dianagriffin** [comment]
@chengjie8 The link in your comment above no longer works (it's taking me to create a new wiki page) -- if you changed the page title since you posted it, that would have broken the link. Can you share a new link here?

**Comment by chengjie8** [comment]
@dianagriffin i updated the title and forgot to update the url here. I have corrected the url. Thanks!
