### ISSUE TITLE
Encrypt RabbitMQ messages

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#191]
Camel messages can contain PII. RabbitMQ has the capability to [persist message queue contents to disk](https://www.rabbitmq.com/persistence-conf.html) (useful for restoring system state in case of system failure). When messages are persisted on disk, PII data must be encrypted. 
(Note VRO version 1.0 does not persist message to disk but future versions will likely have this message queue persistence enabled for system robustness and resilience.)

**Options:**

A. have RabbitMQ persist ALL messages to an encrypted file system
  - seems like the simplest solution since it is transparent to message producers and consumers

B. augmenting `CamelDtoConverter` to encrypt and decrypt ALL messages sent to RabbitMQ
  - message consumers reading directly from RabbitMQ will have to decrypt messages
  - debugging *may* be hard since the messages require decrypting

C. building a Camel component, which is used selectively only for messages with PII
  - inconsistent processing by message consumers, where some messages must be decrypted and others do not

D. (other ideas?)

**Comment by yoomlam** [comment]
From other discussion, we agree with option A as a quick and easy solution.

**Comment by dianagriffin** [comment]
Blocked pending VA inputs in terms of the impact of storing PII on our ATO/categorization

**Comment by yoomlam** [comment]
[Asked](https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1669663600659569) for LHDI's opinion on options for an encrypted file system.

**Comment by yoomlam** [comment]
We need to wait for LHDI to provide the encrypted file system before closing this ticket.
I'll update the code to create an unencrypted file system and write claims data to it by Tuesday. The code will not run in PROD until we have the encrypted file system in place (and the approved new ATO).

**Comment by dianagriffin** [comment]
Thanks for ^ this update, @yoomlam !  I believe you're saying that there's a bit more work you can do on it (creating unencrypted file system), but once that's done this ticket will be blocked pending [LHDI providing the encrypted file system](https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1669663600659569) -- if I'm understanding that correctly, please just add the `blocked` label once you've taken it as far as you can without LHDI and we can put it in the sprint backlog until it's unblocked.

**Comment by yoomlam** [comment]
From LHDI:
> We have created a story for this work and will pull it in this sprint. Level of effort is fairly low; I would expect this to be completed this week or next.
> There will be two new storage classes for EFS - both with encryption - one with Retain and one with Delete ReclaimPolicy so you can make the choice based on your needs.

Assigning this to Sprint L

**Comment by yoomlam** [comment]
[Slack update](https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1670531387750429?thread_ts=1669663600.659569&cid=C03UA9MV1EH)
> found that our EBS and EFS volumes are already provisioned with encryption at rest and in transit. I've updated the documentation with a note about encryption, but you can use either of the two available EFS StorageClasses (efs-sc or efs-sc-retain based on your desired reclaim policy).

Updated helm configuration. Now to watch deploys to see if it works.

**Comment by yoomlam** [comment]
[Updates](https://dsva.slack.com/archives/C04CA47HV96/p1671058797549319?thread_ts=1670468543.753259&cid=C04CA47HV96):
1. No luck on removing `helm del` even with some help from LHDI
2. Will need to create a StatefulSet
