### ISSUE TITLE
Datadog Dashboard(s) for VRO Microservices- Immediate monitoring needs

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#1927]
**User Story**

As the VRO Team we want to have clear visibility into the health of deployed microservices, so that I can quickly respond to issues and debug any unexpected behavior with integrations with other VA systems.

**Acceptance Criteria**

1.  Each microservice within VRO has a dashboard displaying request volume, request status, error rates, request latency to corresponding VA systems.- we have this but it has to be custom filtered. 
2. Each microservice within VRO has a dashboard displaying request volume, request status, error rates, request latency for requests originating within VRO. -we have this but it has to be custom filtered
3. Baseline metrics are established so that Monitors are created so that if there are spikes in error rates in the communication from VRO microservices to VA systems or between VRO microservice consumers and VRO microservices, the team will know quickly. - yes 
4. If there are any code changes required in order to emit the necessary metrics, this work should also be covered by this ticket.- none needed
5. there is a graph showing a heatmap of the deployments - yes

**Comment by agile-josiah** [comment]
Add a dashboard that shows a heatmap of the deployments

**Comment by agile-josiah** [comment]
[Datadog dashboard link](https://lighthousedi.ddog-gov.com/dashboard/pvw-4a2-2s5/vro-on-lhdi?view=spans
)
