### ISSUE TITLE
Document partner team deployment plan setup as a repeatable process for team onboarding

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1951]
### User story
✅ ~As a VRO DevOps engineer, I want a repeatable process to follow when setting up partner team deployments, so that I don't reinvent the wheel each time we onboard a partner team, and can ensure each partner team's deployment process is set up consistently.~

As a VRO Product Owner, I want to be able to set expectations about what the deployment setup stage of onboarding will look like for partner teams, so that I can plan onboarding timelines appropriately in collaboration with partner teams.

### Acceptance criteria
- The process followed for #1852 and #1896 is documented as repeatable steps in the VRO wiki, including:
   - which steps are to be completed by VRO and which to be completed by the partner team
   - a rough estimate of how long each step to be completed by VRO can be expected to take

**Comment by yoomlam** [comment]
I'll leave it to @tcraghu and @tejans24 to "Document partner team deployment plan setup".

**Comment by dianagriffin** [comment]
Thanks @yoomlam -- I'm going to pop this back to the backlog, queued up for Sprint C
