### ISSUE TITLE
Track and set reminders for secrets rotation based on expiration date

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1959]
**User Story**

As a VRO engineer, I want to track and manage secrets expiration dates, so that I can rotate secrets well ahead of their expiration, preventing any disruption to VRO services.

**Acceptance Criteria**

1. Expiration dates for all relevant secrets are documented in the VRO Secrets docs in the internal repo wiki.
2. Early reminders to rotate the secret are set for each secret with an expiration date, visible to the full team.
3. Any secrets that are nearing their expiration date have been rotated (_this may not currently apply to any secrets; please verify_)

**Comment by meganhicks** [comment]
not needed- tech spec ticket created to automate
