### ISSUE TITLE
Require automated unit/integration tests of platform domain code to pass when a PR is merged

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1962]
**User Story**

As a VRO engineer, I want to enforce testing of platform code at the point of merging code in any given environment, so that we ensure the reliability of the platform and have a safeguard in place that builds our confidence to enable more frequent, flexible, autonomous deployments by partner teams.

**Context**

Currently, we run automated tests at the point of merging PRs, but don't require the tests to pass before the merge can be completed. In order to have confidence increasing the flexibility of our deployment process, we want to update our process such that we enforce that those tests must pass before the merge can be completed. If the tests fail, the merge is blocked.

Since these tests currently take minutes to run, this effort should include evaluation of ways to make the tests faster. 

**Acceptance Criteria**

1. Across VRO environments, failing automated unit/integration tests block PR merge
2. Deployment process documentation has been updated to reflect this change
3. This change has been communicated to partner team engineers who will be affected by it, referencing the relevant documentation.
4. Options to speed up the tests have been evaluated and either implemented (if <2 points of effort/complexity) or written up as new tickets

**Comment by msnwatson** [comment]
Can we split this into two tickets one for unit tests and one for integration tests? 

The unit tests is easier to achieve in the short-term and committing code which breaks the unit tests actually blocks deployments at the image publishing step.

Integration tests will still require a great deal of effort and improvement before they can be blockers for PR merge i think.

**Comment by meganhicks** [comment]
we determined most of this work was done .
