### ISSUE TITLE
Get BIP API microservice and documentation ready for partner team use

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1974]
### User Story
As an EE team engineer, I want to have VRO's existing BIP API microservice available for use by my domain application code, supported by documentation that lets me know how the microservice works and what endpoints it makes available, so that I can begin designing and developing my application's use of the BIP API.

### Acceptance Criteria
- As follow up to #1594 and #1777, take any remaining steps necessary to ensure that the BIP API microservice is ready for use by partner teams
- Update relevant wiki pages/Swagger docs (e.g. ([BIP APIs](https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-APIs), [BIP Claim Evidence API](https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-Claim-Evidence-API), [BIP Claims API](https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-Claims-API)) as needed for accuracy and to provide an adequate summary of VRO's feature offering around the BIP APIs

### Not included in this work
The EE team will need access to additional BIP Claims API endpoints that VRO has not previously connected to, however, those new endpoint connections will be handled in future tickets. This ticket is focused solely on VRO's existing BIP API integrations.

**Comment by pshahVA** [comment]
Following up on this, I've started the conversation with the BIP team to get a meeting setup with the correct folks to get us access to these new services.

**Comment by pshahVA** [comment]
@greene858 I looked at the request that we referenced on the call with BIP, and I want to make sure we don't already have access to some of the fields that they need in [this ](https://github.com/department-of-veterans-affairs/abd-vro/issues/1610) ticket.

**Comment by dianagriffin** [comment]
@greene858 Following up from Sprint Planning -
- Please create a ticket to split up the remaining work necessary to provide what EE needs to make use of the Claims API
- I think you're already on top of this and will include it in the new ticket(s), but just to be sure, note that there are new URLs for the Claims API in various environments (see Premal's email to your VA address on 10/2): 
   - https://claims-bat.preprod.bip.va.gov/
   - https://claims-cola.preprod.bip.va.gov/
   - https://claims-perf.preprod.bip.va.gov/
   - https://claims-preprod.preprod.bip.va.gov/
   - https://claims-prodtest.preprod.bip.va.gov/

**Comment by dianagriffin** [comment]
We'll close this after EE has had a chance to try it out in dev
