### ISSUE TITLE
Contention Classification - fix isort vs black conflicts

### ISSUE THREAD

**Issue by lukey-luke** [department-of-veterans-affairs/abd-vro#1981]
**User Story**

As an engineer, I want to use [black](https://pypi.org/project/black/), so that code is uniformly formatted in a standard way.

**Acceptance Criteria**

1. black can run on any given PR
2. isort can be run on any PR
3. black added to continuous integration

**Not included in this work**

A note about things that should not be considered necessary.

**Notes about work**
- will probably require fiddling with a config file for one of the libraries in order to avoid them stepping on top of each other
- should also include a note in developer documentation on how to set this up (e.g. `domain-cc/README.md`)

**Example**
Running `isort tests/test_api.py` yields the following code:
![Screenshot 2023-08-28 at 12 23 05 PM](https://github.com/department-of-veterans-affairs/abd-vro/assets/17188013/c676e9e4-18ca-4751-acb4-1d3d65a87b0c)

Running `black tests/test_api.py` yields the following code:
![Screenshot 2023-08-28 at 12 22 58 PM](https://github.com/department-of-veterans-affairs/abd-vro/assets/17188013/48755ef4-0de5-4c29-9f02-5c9b16535478)

**Comment by verdance-luke** [comment]
Potential blocker for:
https://app.zenhub.com/workspaces/contention-classification-640a24db5dcd08457cebbc79/issues/gh/department-of-veterans-affairs/vagov-claim-classification/283

**Comment by verdance-luke** [comment]
draft PR here:
https://github.com/department-of-veterans-affairs/abd-vro/pull/2162/files

**Comment by verdance-luke** [comment]
CI is failing, need to figure out how to ensure it will use the black profile. If it's too much finagling to read the config file, I can probably just use `--profile` flag or something

Failed job:
https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/6699942363/job/18204995537?pr=2162
