### ISSUE TITLE
Accommodate LHDI Migration to Application Load Balancers 

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#1987]
**User Story**

As a VRO engineer, I want to stay up to date with the latest changes from LHDI, so that we minimize any disruption or downtime and support new development efforts.

**Acceptance Criteria**

1. Add an additional `VirtualService` definition to all VRO deployments which receive traffic from an LHDI gateway
2. Test that updated deployments can receive traffic from LHDI gateway before deploying to `prod`

**Notes about work**
- [Originating Slack Thread](https://dsva.slack.com/archives/C04QLHM9LR0/p1692987987544629)

**Comment by dianagriffin** [comment]
Example of updated service posted in slack [here](https://dsva.slack.com/archives/C03UA9MV1EH/p1692988000681699?thread_ts=1692987928.366519&cid=C03UA9MV1EH)

**Comment by nelsestu** [comment]
Adding a link to the pull request for easier tracking: https://github.com/department-of-veterans-affairs/abd-vro/pull/2058

**Comment by nelsestu** [comment]
I've approved the associated pull request acknowledging the changes applied in the following comment: https://github.com/department-of-veterans-affairs/abd-vro/pull/2058#pullrequestreview-1651167766
