### ISSUE TITLE
Create a Datadog dashboard for EE Max CFI effort

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#1992]
## Acceptance Criteria

Based-on the conversation here: https://dsva.slack.com/archives/C01Q7979Z7D/p1693341950117069, there is a Datadog dashboard to track total requests and number of status codes (200s vs not). 

Please work with @dfitchett, @nanotone EE  team to get more information.

related to #1967

**Comment by tejans24** [comment]
I've talked to @va-albers about the DataDog implementation:

- VRO should continue to use LHDI DataDog instance to store metrics.
- VRO should help enable partner teams use DataDog APM based metrics as a baseline (which automates basic metric collection of the applications)
- VRO continues to support log based metrics and provide logging standards in the future, so teams can follow the best practices.
- VRO researches mechanisms, best practices and tools for custom DataDog metrics(DataDog API, dogstatsd, telemetrics etc) for languages and systems supported in VRO, so applications can have a consistent way to record custom metrics.

**Comment by dianagriffin** [comment]
- LHDI does not have APM enabled in Datadog, but they are looking into it and hope to enable it soon
- In the meantime we'll be given an API key to create custom metrics

**Comment by dfitchett** [comment]
**Re: VRO Partners discussion 10/6:** 
Although custom DD metrics would be awesome! I think that can be moved to a separate part. At this time the Max CFI effort does not require custom metrics. The charts for the dashboard we are looking for can be found **[here](https://lighthousedi.ddog-gov.com/metric/explorer?graph_layout=stacked&start=1696191443138&end=1696619783138&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiBQnhhOGvjaAMZKyCBoODCWVCIY6spB2lgATAYgogLE+mEgAFQgALpU8Tiq8gRJoBgwMEYwnpLSyY14Ikh8IF348k4ARjRh9SBaGAnMRHmzIAA6IAAKAPIAygAqAAQA9B7EALTavSLpW8dbBQAMzw8A1nhTcE7xaHgaBA6JxZdTINBQK7ybQ4KCXMggUaAtwdJKsHAjCigSIIaKxPAJNGpdLFUFotYAZmKpTg5VCVmqdQaTRaQJkIA6XTgPQkUmUg2GiKo4zwkxm1nmi2W7LWyi2eyOZwu11u9xAjxAABYCgUPl8fn8AUDtCDsnBwZDLtDYfChQsECj4MpGBihdiojE4ollMSMiAybkzPlNdSRGUKgyavNGs1WuzOd1enyBvhBaMRWLZlZJXAlvEVqBZcl5QcTucMFcbhI7hoHltNa89d9fv9AcCyRaoTC4QikQ6bk7ki7Me7cZ6Cd7kr7SWbAzosABWUPh+mM6MsuNEBPcpP9EACzFjGGi6ZZnN5gsgIubHalpUVlXVtXHT7Nw1tk0diFdm29qjIgc0WHRF5lcdw8Ewel2jQCAMFCEAXmeYpASwNA2hAeQMDQhA2WSLk4GkKhMOwoEnBpUhkE1UYwNUCCMDnfIij4aDYPg7Uin-OQ0PZYjEFw8AllUYpeJwn5yJQBdqLcWjMAYrAqWY+1UPQkT+LAQThKwvixLDWkUApKTwNk5I1hDHhJS4lStNE5QtA8YYIHiYoYJEH45EUWycBgqBnNEH56CYZQRGkrC7SgCB7EwLAnHctEpiWSxzJ4JF5BghAAGEpGEGAUBECC0B4IA)** and can be groomed from the log statements alone!

**Comment by dianagriffin** [comment]
@tejans24 See Derek's note above re: not needing custom metrics for EE purposes immediately. Can you take a look at the charts Derek linked and let us know if you see anything that prevents us from providing them that in a dashboard? If it looks doable, I think the next steps would be:
- set up that dashboard and meet with @dfitchett to review it together in order to close out this ticket, 
- create a new ticket to capture your thoughts about using custom metrics for a future Max CFI dashboard and put it in our backlog
   - In terms of priority, we would then focus on using custom metrics on the contention event data first, and come back around to applying it to a Max CFI dashboard later
