### ISSUE TITLE
Prepare for max CFI Veteran research

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1996]
We are planning to conduct another round of Veteran research to inform the next iteration of the max CFI project. In this sprint, we will:

- [x] Create a conversation guide (in coordination with https://github.com/department-of-veterans-affairs/abd-vro/issues/1983)
- [x] Create a research plan
- [x] When ready, submit research request and field questions from research ops team
- [x] When ready, submit research participant recruiting request

**Comment by amylai-nava** [comment]
Moving from sprint C -> D

**Comment by amylai-nava** [comment]
@ChristineRoseSteiffer I know you were planning to submit the research & recruiting tickets today. Were you able to get those submitted? If so, I'll mark this as "done". If not, I'll move it to sprint E.

**Comment by ChristineRoseSteiffer** [comment]
Tickets submitted! :)

**Comment by ChristineRoseSteiffer** [comment]
Tickets submitted! :)
