### ISSUE TITLE
Investigate BIP Claims API

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1998]
A continuation of previous BIP Claims API research we did for the EP400 project: https://github.com/department-of-veterans-affairs/abd-vro/issues/1610

## Additional questions to check
- [x] Any duplicate checking supported?
- [x] Can we migrate contentions without a classification?
- [ ] Will the contention name, date, and classification get migrated?
- [ ] Will the reason field create a claim note?

## Definition of Done
- Document findings in this ticket
- Note which questions could not be answered by reviewing the API documentation and require building out the API client

**Comment by amylai-nava** [comment]
VRO's related ticket for Sprint C: https://github.com/department-of-veterans-affairs/abd-vro/issues/1974

**Comment by dfitchett** [comment]
_[IN PROGRESS]_
## Duplicate checking:
* The endpoint for updating one or more of the contentions `PUT /claims/{claimId}/contentions` will return 400 as a result if the request has contentions with the same contentionId.

**Comment by amylai-nava** [comment]
considering this done, will track additional work in #2028
