### ISSUE TITLE
Reach out to relevant teams to our max CFI design explorations

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#2024]
In our exploration we're looking at making changes to screens that are under the purview of other teams, so we should play nice. 

```[tasklist]
### Teams to reach out to
- [x] 526 Team
```
AC: 
This is done when the meeting is scheduled. 

## Goals
- Find out if there are any upcoming changes that would conflict with our plans
- Find out if there is any previous research that is relevant 
- Build rapport

**Comment by carodew** [comment]
See Slack thread: https://dsva.slack.com/archives/C055573C508/p1694030626124729

**Comment by amylai-nava** [comment]
Adding @ChristineRoseSteiffer as an assignee on this ticket, since I believe we talked about Christine leading this effort during sprint planning.

@carodew @KimLadin feel free to unassign yourselves if/when appropriate.

**Comment by amylai-nava** [comment]
9/28: Christine to reach out to the teams next week, schedule meeting after research

**Comment by amylai-nava** [comment]
@carodew @KimLadin @ChristineRoseSteiffer, should we move this to the backlog given the decision from 9/28?

**Comment by carodew** [comment]
Reached: https://dsva.slack.com/archives/C04KW0B46N5/p1700074274421779

I'll close this ticket once I've scheduled the meeting. That meeting may not take place this sprint (likely will not)

**Comment by carodew** [comment]
Invite Emily and Steve Albers
