### ISSUE TITLE
For max CFI API metrics: work with VRO to set up a dashboard for EE's deployed application logs on LHDI Datadog

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2027]
Split from https://github.com/department-of-veterans-affairs/abd-vro/issues/1993

Status as of 9/11:
> Blocked by VRO Task: https://github.com/department-of-veterans-affairs/abd-vro/issues/1992
> 
> In the meantime, here's a temp dashboard for the metrics in [LHDI](https://lighthousedi.ddog-gov.com/metric/explorer?graph_layout=stacked&start=1694013794425&end=1694100194425&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiBQnhhOGvjaAMZKyCBoODCWVCIY6spB2lgATAYgogLE+mEgAFQgALpU8Tiq8gRJoBgwMEYwnpLSyY14Ikh8IF348k4ARjRh9SBaGAnMRHmzIAA6IAAKAPIAygAqAAQA9B7EALTavSLpW8dbBQAMzw8A1nhTcE7xaHgaBA6JxZdTINBQK7ybQ4KCXMggUaAtwdJKsHAjCigSIIaKxPAJNGpdLFUFotYAZmKpTg5VCVmqdQaTRaQJkIA6XTgPQkUmUg2GiKo4zwkxm1nmi2W7LWyi2eyOZwu11u9xAjxAABYCgUPl8fn8AUDtCDsnBwZDLtDYfChQsECj4MpGBihdiojE4ollMSMiAybkzPlNdSRGUKgyavNGs1WuzOd1enyBvhBaMRWLZlZJXAlvEVqBZcl5QcTucMFcbhI7hoHltNa89d9fv9AcCyRaoTC4QikQ6bk7ki7Me7cZ6Cd7kr7SWbAzosABWUPh+mM6MsuNEBPcpP9EACzFjGGi6ZZnN5gsgIubHalpUVlXVtXHT7Nw1tk0diFdm29qjIgc0WHRF5lcdw8Ewel2jQCAMFCEAXmeYpASwNA2hAeQMDQhA2WSLk4GkKhMOwoEnBpUhkE1UYwNUCCMDnfIij4aDYPg7Uin-OQ0PZYjEFw8AllUYpeJwn5yJQBdqLcWjMAYrAqWY+1UPQkT+LAQThKwvixLDWkUApKTwNk5I1hDHhJS4lStNE5QtA8YYIHiYoYJEH45EUWycBgqBnNEH56CYZQRGkrC7SgCB7EwLAnHctEpiWSxzJ4JF5BghAAGEpGEGAUBECC0B4IA)

**Comment by amylai-nava** [comment]
Moving from D -> E. VRO needs an API key to create custom metrics.

**Comment by dfitchett** [comment]
[Dashboard in VRO](https://lighthousedi.ddog-gov.com/dashboard/ama-szd-xn9/employee-experience-max-cfi-vro-platform?refresh_mode=sliding&tpl_var_cluster%5B0%5D=ldx-prod-1&tpl_var_namespace%5B0%5D=va-abd-rrd-prod&from_ts=1697482175909&to_ts=1697485775909&live=true)
