### ISSUE TITLE
BIP Claims API prototyping and collaboration with VRO team

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2028]
This ticket capture prototyping and collaboration efforts with the VRO team to enable the Employee Experience team to use the BIP Claims API for our EP Merge solution.

## To do's
- [x] Look at BIP API endpoints that VRO microservice currently hits & identify the ones that we don’t need/need (e.g., is there code for setting temporary station 398 and special issue? is it useful)
- [x] Work with Tom/VRO team to clarify what we need from them
- [x] Begin Prototyping VRO Application

**Comment by dfitchett** [comment]
# BIP API Notes:
## Currently Supported Endpoints:
endpoint | VRO BIP | Description
-- | -- | --
GET /claims/{claimId} | ✅ | Get claim summary for claimId
GET /claims/{claimId}/contentions | ✅ | Get contentions for claimId
PUT /claims/{claimId}/contentions | ✅ | PUT add/update contention on claim including special Issue codes
PUT /claims/{claimId}/cancel | ❌ | Cancel claim
PUT /claims/{claimId}/temporary_station_of_jurisdiction | ❌ | Set temporary station of jurisdiction

## Current Implementation Class Details:
### BipApiService.java:
* getClaimDetails(long claimId):  `GET /claims/{claimId}`
* updateClaimStatus(long claimId, ClaimStatus status): `PUT /claims/{claimId}/lifecycle_status`
    * Actually updates the claim lifecycle status with the body set to `claimLifecycleStatus: {status}`
* getClaimContentions(long claimId): `GET /claims/%s/contentions`
* updateClaimContention(long claimId, UpdateContentionReq contention): `PUT /claims/%s/contentions`
    * UpdateContentionReq takes list of UpdateContention objects
* confirmCanCallSpecialIssueTypes(): `GET /contentions/special_issue_types`
    * Get requests returns list of special issue types
    * Method returns true or false
    * Not overly useful

**Comment by dfitchett** [comment]
VRO team is currently working on cleaning up / removing RRD specific functionality from the BIP API microservice. Captured in ticket #1974.
