### ISSUE TITLE
Onboard Bianca

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2035]
Welcome, Bianca! We are excited to have you on the team! 

This ticket exists to lay out some logistical to-do's alongside areas of focus for getting up to speed on the VRO team and our work. 

### To be done for you - @dianagriffin
- [x] Invite to DSVA, Lighthouse Slack spaces 
  - [x] Add to slack groups (@vro-team) 
- [x] Introduce in #benefits-onboarding channel (to kick off OCTO onboarding steps) and #benefits-vro team channel  
- [x] Add to recurring team meeting invites   
- [x] Invite to the VA ABD Team Calendar in Google 
- [x] Invite to the OCTO Benefits Delivery Team room in the VA Mural Workspace (as a guest)  
- [x] Add to VA Github Org ([form here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new/choose)) 
  - [x] Add to [OCTO-VRO GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/octo-vro/members) to have access to VRO's GitHub repos

_Pending VA email assignment_
- [x] Add to the VA ABD Sharepoint site as a Member (pending getting a VA email assigned)
- [x] Add to VA Mural workspace as a member
- [x] Request an Okta account (https://jira.devops.va.gov/servicedesk/customer/portal/1/group/252?groupId=252)
  - Request template: _Name is a new member of the OCTO Benefits VRO team. Requesting an Okta account be created for First Last (include VA email) with the following applications assigned:_
     - _VA Jira_
     - _VA Confluence_
     - _lighthousedi-va-datadog with Standard Role assigned_

###  To do - Bianca
- [x] Join relevant [slack channels](https://docs.google.com/spreadsheets/d/1c3e6SVuhVz3q4bh1qf5jj25EmusCd3NVXhDjSIpr9yk/edit#gid=1020923043) -- _you don't have to join ALL these channels; start with the #benefits-vro-* and #benefits-cft-* and you can expand from there as you get more involved in the work. Feel free to ask the team in #benefits-vro if you're wondering about whether to join a particular channel._
    - [x] **Most relevant channels for you**: #benefits-vro (our team channel for coordination across the VRO team), #benefits-cft-design (channel for design collaboration with Claims Fast Tracking crew teams), #benefits-vro-engineering (engineering-specific collaboration for the VRO team), #benefits-vro-support (primary channel for collaboration with VRO partner teams building on the platform), #benefits-cft (cross-team collaboration channel for the 3 teams in the Claims Fast-Tracking Crew) 
- [x] Join [recurring team meetings](https://docs.google.com/document/d/12oaUy0vmv--BFdUhoXk69FtLkhb5Bp0_woOWoD5P3iY/edit#heading=h.p2uqu6tmjnaw) -- _they should be on your calendar!_
- [ ] ~Watch ["The Way We Work" presentation](https://us06web.zoom.us/rec/share/sHRSblAbF229tQpj7-Nqmmdi7Zb5bWclCd0lqMMdGAttuaJZDByZy8C7vi1BO9Mo.7XuVLn108mwIpnQj?startTime=1680030182000) recording~ _Attend new team session scheduled in mid-October_
- [x] Go through Benefits Portfolio onboarding materials and onboarding buddy meetings (see #benefits-onboarding channel in Slack; you'll be tagged there with your onboarding buddy assignments and materials to review) 
- [x] Set up a 1:1 meet & greet with our VA Product Owner, Premal Shah! -- _See Premal's slack profile for a calendar URL where you can find available times_
- [x] When you get a VA email address, add it to your Github account & let Diana know so she can add you to Sharepoint and Okta

**Comment by bianca-rivera** [comment]
@dianagriffin VA email address: bianca.riveraalvelo@va.gov

**Comment by dianagriffin** [comment]
Requested Okta account: https://jira.devops.va.gov/servicedesk/customer/portal/1/DOTSD-34244
