### ISSUE TITLE
Migrate contention data from the EP400 to the pending EP

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2054]
Once the anchors are set on the EP400 claim to prevent it from being assigned to a VSR while we process it, migrate the contention and  contention data from the EP400 to the pending EP.

## **Acceptance Criteria**
Within **EP Merge App (VRO)**
- Check whether the contention on the EP400 is a duplicate of the contentions on the pending EP. A contention is considered duplicate if:
  - The contention name is exactly the same, and
  - The contention type is the same (increase, new, etc.)
- If the contention **is not a duplicate**:
  - Migrate the contention and contention data from the EP400 to the pending EP (the 010, 110, or 020)
  - Contention data = contention classification, contention date, and all special issues added to that contention
- If the contention **is a duplicate**:
  - Do not migrate the contention and proceed to #2056 

See #2057 for error handling requirements.

**Comment by amylai-nava** [comment]
@amylai-nava will split this ticket so that the 'check for duplicate contention' is a separate task

**Comment by amylai-nava** [comment]
ready for review, moving to sprint H

**Comment by dfitchett** [comment]
#2145
