### ISSUE TITLE
Implement error handling for EP400 merge

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2057]
## Scenarios
| Error reason  | What to do after 3 retries | Outcome 
| ------------- | ------------- | ------------- |
| Get pending claim details fails | Remove special issue, send a Slack alert | EP400 is processed manually |
| Get pending claim contentions fails | Remove special issue, send a Slack alert| EP400 is processed manually |
| Get EP400 claim contentions fails | ~~Remove special issue,~~ send a Slack alert | EP400 is processed manually |
| Set Temporary Station of Jurisdiction (TSoJ) fails  | Remove special issue, send a Slack alert | EP400 is processed manually |
| Move Contentions fails | Remove special issue, set the TSoJ back to the station the EP400 claim was originally established at, and send a Slack alert | EP400 is processed manually |
| Cancel EP400 fails** | Set the TSoJ back to the station the EP400 claim was originally established at, and send a Slack alert | EE team sends the claim ID to OBA. EP400 is cancelled manually |
| VRO's BGS is unavailable (i.e., note cannot be added) | Remove special issue, send a Slack alert | EP400 is processed manually|

** Our MVP approach. Post MVP, we will add a claim note indicating that the contentions have been migrated but the EP400 claim needs to be cancelled.

## Acceptance Criteria
- The EP-Merge-App will try to execute each request to the BIP API 3 times before it fails
- If the request fails, do what's stated above for each scenario
- Slack alerts should include:
  - benefit claim ID of the EP400
  - benefit claim ID of the pending EP
  - date and time error occurred
  - error message
  - API call that was being attempted
- Store the original RO station that the claim was established at in case we need to set the TSoJ back to that station if we are unable to process the claim (the NWQ doesn't route EP400s)

## Notes
- In order to undo the setting of TSOJ, we need to add in the ability to call the getClaimDetails endpoint of the BIP API for the EP400 to get the `claimStationOfJurisdiction`.

**Comment by amylai-nava** [comment]
@raudabaugh @nanotone @dfitchett @amylai-nava to discuss options for the **3rd scenario - merge is successful but the cancellation fails**:
- **option 1**: we move the contentions from the pending EP back to the EP400, and we move the EP400 claim back to the original RO station
- **option 2**: we leave the contentions on the pending EP, add a claim note on the EP400 indicating that the contentions were moved and the EP400 needs to be canceled, and move the EP400 claim back to the original RO station so a person can cancel the EP400

**Comment by dfitchett** [comment]
PR For reverting TSOJ on failures: 
* https://github.com/department-of-veterans-affairs/abd-vro/pull/2351
