### ISSUE TITLE
Move ABD Design and Research Index into Sharepoint

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#2076]
Bringing this back into this sprint to wrap it up before the end of the year.

- [x] Create document in sharepoint in appropriate folder
- [x] Move docs into sharepoint that were converted from google docs
- [x] Convert google doc links in document to sharepoint links
- [x] Convert notion links in document to sharepoint links

**Comment by amylai-nava** [comment]
@ChristineRoseSteiffer I know you started on this in Sprint E. Do you think you'll have time to continue this in Sprint F or should we move it back to the backlog?

**Comment by amylai-nava** [comment]
**10/24 sprint planning discussion:** although work has started, we're going to move back the backlog so that we can prioritize Max CFI work in Sprint G.

**Comment by ChristineRoseSteiffer** [comment]
Split the new updates off into a new ticket - otherwise, this one is done :)
