### ISSUE TITLE
Store additional contention event fields

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2085]
### User Story
As a VRO PO, I want to ensure that the contention event data being stored in VRO represents all the fields I can predict will be useful for metrics and analysis in future, so that we get as much of a historical record of those fields as possible.

### Acceptance Criteria
- The list of fields identified in #2084 are added to the event fields that we store in VRO and make visible in Datadog

### Context

- VRO currently stores a small subset of fields on contention events
- The subset of fields we store does not provide the full picture of the contention lifecycle that we would like to be able to analyze in future
- While VRO can retrieve fields from a given contention event topic at any time, the fields retrieved will represent the most recent state of that field, not the state of that field at a given point in time. Meaning, we cannot retrieve the history of a contention field, only the current state of that field.
- In order to build our record of the history of contention events, we want to begin logging more fields to contention events so that we have the historical context that we will not be able to retrieve from the BIE topics

**Comment by chengjie8** [comment]
New columns to be added to `bie_contention_event` table 


Name | Description | Data Type
-- | -- | --
ActionName | The contention action taken | VARCHAR(255)
ActionResultName | The name of the result of the action. | VARCHAR(255)
ActorStation | An Identifier for the location (work station) from which the action was performed | VARCHAR(255)
AutomationIndicator |  | Boolean
BenefitClaimTypeCode | A representation of a finite, pre-determined value or status that applies to a type of a BENEFIT CLAIM. | VARCHAR(255)
ClaimId | Foreign Key to BNFT_CLAIM | BIGINT
ContentionClassificationName | A detailed description of the classification term as defined by the VBA medical specialists. | VARCHAR(255)
ContentionId | A system generated unique identifier of an instance of CNTNTN. | BIGINT
ContentionStatusTypeCode | Represents the current status of the contention in question. | VARCHAR(255)
ContentionTypeCode | A representation of a finite, pre-determined value or status that applies to a type of a CONTENTION. | VARCHAR(255)
CurrentLifecycleStatus | The contention lifecycle status after the event occurred. | VARCHAR(255)
DateAdded | Represents the date in which the contention was added. | Date
DateCompleted | Represents the date in which the contention was promulgated. | Date
DateUpdated | The day, month and year on which the last action took place on the record. | Date
Details | Text field for any description of the event. | VARCHAR(255)
DiagnosticTypeCode | Represents the proper medical diagnosis that has been assigned to previously rated contentions that were processed via VetsNet. | VARCHAR(255)
EventTime |  | DateTime
JournalStatusTypeCode | The alphabetic character representing the last action taken on the record. (I = Input, U = Update, D = Delete). | VARCHAR(255)
VeteranParticipantId* | Identifier of PTCPNT for a VETERAN. Part of the identifier for BNFT_CLAIM. | BIGINT
event_details* | Entire BIE contention event JSON string  | JSON

**Comment by chengjie8** [comment]
In a prior discussion with @dianagriffin , we explored two potential approaches. The first approach was to add all the additional columns as defined in the parent ticket. The second was to incorporate only the EVENT_DETAILS column, which would contain the entire Kafka message payload in JSON format.

Subsequently, I spoke with @tejans24 , and we opted to implement both approaches. One limitation of having only the JSON column is its reduced visibility during database queries, necessitating additional steps to identify specific values. With our chosen approach, we benefit from both perspectives. The data is readily visible in the table, and if any information isn't present in the added columns but is in the Kafka payload, it's still accessible in the JSON column. This eliminates the need for further Java code modifications and database migration scripts.

**Comment by dianagriffin** [comment]
@chengjie8 can you confirm which columns are already there in `bie_contention_event` table, just for reference? I'm expecting the current columns to include: 

Name | Description
-- | --
ActionName | The contention action taken
ActionResultName | The name of the result of the action
ClaimId | Unique Id assigned to each claim within VBMS
ContentionClassificationName | A detailed description of the classification term as defined by the VBA medical specialists
ContentionId | Unique Id of the contention associated to the claim
ContentionTypeCode | A representation of a finite, pre-determined value or status that applies to a type of a CONTENTION
DiagnosticTypeCode | Represents the proper medical diagnosis that has been assigned to previously rated contentions that were processed via VetsNet

**Comment by dianagriffin** [comment]
@chengjie8 confirming that it makes sense to me to add another column for:

Name | Description
-- | --
Description | A description of the claim or problem in the words of the claimant.

... even though we should not start storing values to that column until we have our updated ATO.
