### ISSUE TITLE
Integrate EP Merge app with BIP microservice

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2091]
VRO team has completed initial work on standing up BIP Microservice and Mock BIP API for testing in dev. They are working on adding the cancel claim endpoint. In the meantime, we can work on integrating the EP Merge app with the BIP microservice.

## Tasks
- [x] Docker configuration updated to better integrate with `svc-bip-api`
- [x] VRO tests written to exercise integration

**Comment by amylai-nava** [comment]
@dfitchett when you get a chance, can you help add more details to this ticket? thank you!

**Comment by dfitchett** [comment]
Blocked by #2175 and PR #2165

**Comment by amylai-nava** [comment]
blocked, moving to sprint H

**Comment by dfitchett** [comment]
The following PRs were made to facilitate integration: 
* #2247
