### ISSUE TITLE
Conduct EP Merge testing in the VA.gov staging environment

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2092]
Once all MVP features have been completed and the app has been deployed to the appropriate lower level environments, we can begin end-to-end testing!

## Acceptance Criteria
- Complete end-to-end testing for the scenarios defined in #2207 
- Identify and resolve issues according to their priority

**Comment by amylai-va** [comment]
Testing is currently blocked due to EVSS dependency. Details in [Slack](https://dsva.slack.com/archives/C01BVF2A3V0/p1708034608027529).

**Comment by amylai-va** [comment]
Testing completed. There are two non-launch blocking issues that we need to address before we enable EP Merge to 100% of eligible claims:
* https://github.com/department-of-veterans-affairs/abd-vro/issues/2782
* https://github.com/department-of-veterans-affairs/abd-vro/issues/2772
