### ISSUE TITLE
Update mock-bip-claims-api to include cancel endpoint

### ISSUE THREAD

**Issue by greene858** [department-of-veterans-affairs/abd-vro#2096]
As a VRO dev I want to test against the latest BIP API so that I can develop and test the BIP service for partner teams. Currently the mock supports the API defined in bipclaim_3.1.1.json., which does not include /claims/{claimId}/cancel; Team EE needs to call cancel to fulfill their feature.

AC: 
- mock-bip-api responds with mock results for positive and negative testing
- all existing integration tests in svc-bip-api continue to function correctly

**Comment by dianagriffin** [comment]
@greene858 could you add a link to the OpenAPI swagger doc

**Comment by dianagriffin** [comment]
@tejans24 Thanks for picking this up! The swagger docs are linked on this wiki page: https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-Claims-API
