### ISSUE TITLE
Partner team want full BIP response message, to accurately log fail reasons

### ISSUE THREAD

**Issue by greene858** [department-of-veterans-affairs/abd-vro#2107]
svc-bip-api currently only returns server error via RabbitMQ when BIP API call does not return success. We need full details of status code and messages to accurately log the reason for fail, so that partner teams can handle failures appropriately based on the reason for failure.

Implementation options should be discussed with EE team and CC team for their input.

AC.
All response from svs-bip-api contain exact status code returned from all integrated BIP API endpoints (pass-through messaging)
All response from svs-bip-api contain any and all message objects returned from all integrated BIP API endpoints (pass-through messaging)

**Comment by dfitchett** [comment]
See this PR: https://github.com/department-of-veterans-affairs/abd-vro/pull/2165 for implementing passthrough behavior for getClaimContentions endpoint
