### ISSUE TITLE
IAM assume permissions for cross account roles to put files into LHDI S3 buckets

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#2108]
Why?

Part of the solution for the data visibility is to put files with Form 526ez submitted data into an LHDI S3 bucket from vets-api rails app. This requires a custom cross-account assumable role created by LHDI.

Reference to tech spec: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Data-Visibility-MVP-Tech-spec

Acceptance Criteria:

Cross account IAM roles created for all VRO environments for vets-api environments to put files into VRO created S3 buckets in LHDI.

**Comment by tejans24** [comment]
LDHI started the process and we are waiting for this to be approved.

**Comment by meganhicks** [comment]
Thank you for the information 
[@Teja](https://dsva.slack.com/team/U05AN86MKV3)
!
[@Megan Hicks](https://dsva.slack.com/team/U05UJQVD7RC)
 from a technical perspective this shouldn't take long to complete - we would either allow you to create the buckets yourselves and we'd modify the policy to allow access, or would need to create one-off buckets and policies on our side. The main thing we'd need from you is the account ID of the other AWS account and if there are certain named users/service accounts that should have access (with their ARNs) or if we are opening it to all users.
I am attempting to get Andrew Fichter to schedule something between our teams to discuss, as the concerns/delay are more from our need to get VA PO approval to
Allow other AWS accounts access to S3 buckets in LHDI
Confirm that we can support this PHI/PII requirement as a FISMA Moderate platform

**Comment by meganhicks** [comment]
two questions we need to get confirmation (we’ll need Cory/Premal/Zach’s help):
Is [va.gov](http://va.gov/) FISMA moderate?
Is [va.gov](http://va.gov/) / VFS platform’s AWS in VAEC?

**Comment by dianagriffin** [comment]
@tejans24 to close this ticket and spin up a new one to capture the actionable next steps following coordination with VFS platform
