### ISSUE TITLE
Tech spec: Assess observability of VRO services

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2132]
### User Story
As a VRO engineer, I want to evaluate existing VRO services to determine which ones need monitoring and which ones have monitoring & alerting configured, so that we can prioritize those efforts and provide partner teams and stakeholders confidence in VRO's stability and reliability.

AC
* The scope of this user story should includes the an MVP for monitoring and alerting and will include the following: 
1. Data Access Metrics
2. Authorization attempts
3. Performance metrics
4. Resource Utilization Metrics
5. Uptime/DownTime
6. Database performance
7. Memory consumption

* The tech spec should detail what is absolutely necessary to implement immediately and the tickets needed to prioritize.

**Comment by meganhicks** [comment]
Are third parties in scope?- Yes
