### ISSUE TITLE
Hoppy Library Improvements - Make async_hoppy_client.stop async waiting for stopped state

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#2150]
# Summary

Make async_hoppy_client `stop` method async to await until the client is in a stopped state (when the async_publisher/async_consumer connections are closed, and not going to reconnect, e.g., when they are stopping and the `on_connection_closed` callback is fired by the connection
  * this could be added as `stopped` bool attribute to the instance of base_queue_client

# Acceptance Criteria

- [ ] async_hoppy_client `stop` is async and waits for client to be stopped
- [ ] unit tests
- [ ] [semantic](https://semver.org/) version is updated and merged commit hash is tagged with `shared/lib-hoppy-<version>`
  * this change would be a breaking change, and require a major version change, or this new method could be a different name, and it would be a minor version change

**Comment by amylai-nava** [comment]
ready for review, moving to sprint H
