### ISSUE TITLE
Hoppy Library Improvements - Prevent async_hoppy_client from stopping ioloop from caller

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#2151]
# Summary
Add some additional logic to prevent the base_queue_client from closing the ioloop only if the ioloop is passed into `self.connect`. If the ioloop is passed in, then the caller of the connect method should responsible for stopping the loop, not the base_queue_client. If the ioloop is not passed in the AsyncioConnection created in the connect method creates the ioloop, and when the client is stopped, should still stop the ioloop.

# Acceptance Criteria
- [ ] base_queue_client does not stop ioloops passed in by callers
- [ ] unit tests
- [ ] [semantic](https://semver.org/) version is updated and merged commit hash is tagged with `shared/lib-hoppy-<version>`

**Comment by amylai-nava** [comment]
ready for review, moving to sprint H
