### ISSUE TITLE
Hoppy Library Improvements - Add ability to declare exchanges and queues

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#2152]
# Summary
Add ability to manually declare Exchanges and Queues separately from creating a client. Declared queues should be bound to an exchange.

# Acceptance Criteria
- [ ] new functionality for declaring exchanges and queues
- [ ] unit tests
- [ ] [semantic](https://semver.org/) version is updated and merged commit hash is tagged with `shared/lib-hoppy-<version>`

**Comment by amylai-nava** [comment]
ready for review, moving to sprint H
