### ISSUE TITLE
Enable local development of the BGS Notes API service

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2172]
### Description 
- The EE team has discovered that they will need to add claim notes to claims in tandem with using the /cancel endpoint of the BIP Claims API for their [EP Merge MVP](https://github.com/department-of-veterans-affairs/abd-vro/milestone/32), in order to record the reason for cancelling the claim in a way that is visible to claim adjudicators in VBMS
- In order to add claim notes, the EE team needs VRO's BGS API microservice to be ready to support production use by a partner team application using the "Add Notes" queue
- There are a handful of tickets needed to get the BGS microservice ready for partner team use, captured in [this milestone
](https://github.com/department-of-veterans-affairs/abd-vro/milestone/37)

### User Story / Why
As a partner team engineer, I want to be able to send RabbitMQ messages to svc-bgs-api container in local environments, so that I can develop locally to build my application.

### Dependencies
Can be worked in parallel, but these tickets will need to be completed in order to complete this ticket:
- #2190 
- #2191 

### Acceptance Criteria
_Include non functional requirements_

- Integration tests publish RabbitMQ messages
- Request/response agreement for BGS service is defined and documented
- EP Merge container can send and receive RabbitMQ message to svc-bgs-api
  - The BGS service responds to 'add notes' message with the ClaimID
  - The BGS service passes success and failure information

### Notes about work
_(links to documentation, resources, code, wireframes, design docs, etc that might inform the person doing the work)_
- [BGS Web Services documentation](https://dvagov.sharepoint.com/:w:/r/sites/OITEPMOIAS/dmdocsite/Legacy%20Systems%20Modernization%20LSM/LSM%20Product/Share%20(SHARE)%20-%20%231589/Benefits%20Gateway%20Services%20(BGS)%20Web%20Services.doc?d=w9e5c89b6cc71432ca4f8800921852e24&csf=1&web=1&e=0LEgjt)
- Consider as starting points:
   - check the existing PR to determine current status
   - Explore and clarify what the Ruby and Java services do and if/how they interact

**Not included in this work**
_A note about things that should not be considered necessary_

_Remember- no ticket is ready until the team has estimated the work and everyone agrees they understand where they would start._

**Comment by dianagriffin** [comment]
![Image](https://github.com/department-of-veterans-affairs/abd-vro/assets/103531643/77120a09-e520-4585-9a60-b2a422c9e1c0)

**Comment by msnwatson** [comment]
Main thing that is left is to run integration tests in a Ruby script that runs in Gradle task rather than relying too heavily on GH actions

**Comment by msnwatson** [comment]
Kudos to @dfitchett for writing integration tests in `domain-ee/ee-ep-merge-app/integration/test_merge_request.py` to test the connection to the BGS microservice from the EP Merge app container, satisfying the final AC here.
