### ISSUE TITLE
Create VRO documentation and user guide for BGS microservice

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2174]
### User Story / Why
As a VRO team member, I want to have sufficient documentation of the BGS microservice so that 
- both the VRO team can support and iterate on the microservice ( work with Megan to detail the steps that the BIS Team made her go through so we know what to expect in the future) 
- VRO partner teams can understand what the BGS microservice offers and how to develop against it in their applications
- The way to get future support with BGS is defined, detailing members of the BIS team and how to reach out for help 

### Acceptance Criteria
- Ensure there is a distinct BGS microservice page dedicated to the VRO Team and another for Partner Teams.
- For the VRO Team page:
Clearly outline the process involved in collaborating with the team.
Specify the points of contact within the team.
Detail where approvals are stored in SharePoint.
Elaborate on how the VRO team can provide support and facilitate iterations on the microservice.

- For the Partner Team page:
Provide comprehensive instructions on how partners can independently utilize and refine the BIS.
Specify the designated contacts within the BIS team whom product managers can approach for assistance.
Outline the procedure for escalating issues effectively.
Refer to the dependency map pinned to the VRO channel for additional guidance.
- Ensure that documentation has been reviewed by at least two members of the team, who confirm its accuracy and completeness.

### Notes about work
_(links to documentation, resources, code, wireframes, design docs, etc that might inform the person doing the work)_

**Not included in this work**
_A note about things that should not be considered necessary_

_Remember- no ticket is ready until the team has estimated the work and everyone agrees they understand where they would start._

**Comment by msnwatson** [comment]
Just for clarity on this ticket, it was originally created before we recognized the limitations imposed by the BIS team in terms of use of the BIS API.

Usage of the API is much less generalizable now in terms of a guide because of the need to discuss any new integrations or method use with the BIS team for approval before continuing.
