### ISSUE TITLE
Move domain-rrd code into separate repo

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#2184]
**User Story**

As a VRO engineer, I want to eliminate any extraneous code in the repo, so that I can simplify my changes when they involve patterns across the codebase and improve deployment efficiencies. 

This work is motivated by experiences with the recent work to replace our third-party images with Bitnami images for SecRel purposes. 

I want to constrain any discussion of this ticket away from the larger discussion of whether each `domain-**` directory should be in its own repo. 

For `domain-rrd` in particular, this code is not used and only retained for historical reasons in case of future product pivots in this area. Removing this code would have no impacts to the functionality of the VRO system but would simplify development by removing a significant portion of the code and excluding it from any search within the repo, which was mentally distracting for me, and I'm sure is ripe for confusion for newer members of the team.

Furthermore, we do not have a policy of maintaining this code to ensure it remains compatible with any changes to the VRO platform so it is unclear what state it is in in terms of functionality with the current codebase.

That said, deleting the code and relying solely on git history would promote complete erasure of the code and eliminate most of the value from the work done to build the product.

**Acceptance Criteria**

1. `domain-rrd` directory is moved into a separate repo with a link exposed on the main page of the wiki so we do not lose it.
2. A README is created in the new repo explaining why the code is kept, that it is not compatible with the current state of the VRO product, and that it should not be viewed as deployable as a standalone product.
3.  Any GitHub actions specific to `domain-rrd` are also moved to the new repo

We can create our own repos. Ask the team if you need help.

**Not included in this work**

Any updates to the `domain-rrd` code to make it compatible with the current VRO platform.

**Comment by msnwatson** [comment]
https://github.com/department-of-veterans-affairs/abd-vro-domain-rrd/pull/2 PR for moving code

**Comment by meganhicks** [comment]
@msnwatson can you point me to where I can see the following: 1. a link exposed on the main page of the wiki and the readme?

**Comment by msnwatson** [comment]
https://github.com/department-of-veterans-affairs/abd-vro-domain-rrd for readme
and if you are on wiki homepage and CMD+F for RRD it should be the only result come up
