### ISSUE TITLE
A standalone SOAP mock service is available and responds to curl commands

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2190]
**Description**: Is this connected to a bigger project? Is there a deadline? Label the story as appropriate. 

**Why**
As a VRO engineer, I want to set up a local SOAP API so that I can develop the BGS service without depending on the VA environment.

**Dependencies**: none
 
**AC**: 
- I can retrieve SOAP from the mock
- The mock replicates the BGS createNote endpoint 
- The mock logs the result

**Related docs/notes**
  - [documentation of BGS service](https://dvagov.sharepoint.com/:w:/r/sites/OITEPMOIAS/dmdocsite/Legacy%20Systems%20Modernization%20LSM/LSM%20Product/Share%20(SHARE)%20-%20%231589/Benefits%20Gateway%20Services%20(BGS)%20Web%20Services.doc?d=w9e5c89b6cc71432ca4f8800921852e24&csf=1&web=1&e=0LEgjt)
  - [previous PR ](https://github.com/department-of-veterans-affairs/abd-vro/pull/1810)
  - [WSDL for BGS](https://github.com/department-of-veterans-affairs/abd-vro/blob/44aa34fbf29b11e25ee571f5d2ab46c7eed48906/mocks/mock-bgs-api/src/main/resources/bgs-castlemock.xml)

**Comment by dianagriffin** [comment]
![Image](https://github.com/department-of-veterans-affairs/abd-vro/assets/103531643/fc140550-f12b-4384-864d-bbf190b364ee)

**Comment by dfitchett** [comment]
- [ ] I can retrieve SOAP from the mock 
  - _only tested the endpoint_ `createNote`
- [ ] The mock replicates the BGS `createNote` endpoint
- [ ] The mock logs the result 
  - logs are recorded. Not in the docker logs, but rather in folder '/usr/local/tomcat/logs/`
