### ISSUE TITLE
BGS microservice connects to the SOAP mock service

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2191]
**Description**: `svc-bip-api` should be able to send requests and receive responses on the mock BGS service's createNotes SOAP endpoint.

**Why**
As a VRO engineer, I want to connect BGS microservice to the SOAP mock service, so that I can see valid test data for development on the BGS microservice utilizing the createNotes SOAP endpoint.

**Dependencies**: 
- #2190 

**Related Ticket**:
- #2172 
 
**AC**: 
- ~~A single rabbit integration test passes (proving it connects)~~ Part of #2172 
- BGS connects locally to BGS Mock service. 
- RabbitMQ returns a valid response for positive and negative unit test cases including required fields for the createNotes endpoint
- Confirmed integration with BGS mock locally by sending request through Rabbit MQ -> `svc-bgs-api` -> BGS Mock and receive response. 
- The mock's logfile confirms the test connected to the mock

**Comment by dianagriffin** [comment]
![Image](https://github.com/department-of-veterans-affairs/abd-vro/assets/103531643/bd75a390-d70b-482b-80a4-eb3073cfe5c8)

**Comment by nelsestu** [comment]
while looking up some lighthouse docs I happened across the following java based BGS client: https://github.com/department-of-veterans-affairs/lighthouse-benefits-gateway-services.  The existence of an officially supported java client for BGS feels like something we should know about and factor in to our solution if it makes sense.  From what I understand there was a Rails client implementation that we were once planning on using with RRD, but given the VRO platform's investment in java, this client seems like a much better choice.  Has anyone on the team ever encountered this bgs-client? Is there any reason why we wouldn't we want to use this? or at least fork from it? [When I posted this in Slack](https://dsva.slack.com/archives/C04QLHM9LR0/p1700522466877439), Mason was confirming that he thought we were already using this, so perhaps our implementation is already on top of this.

**Comment by dfitchett** [comment]
@nelsestu that BGS client does not seem to provide the ability to hit the DevelopmentNotesService SOAP endpoint. So four this use case that client does not work.

**Comment by dfitchett** [comment]
Updated AC to exclude integration tests from this issue. The integration tests are being completed as part of this issue: 
- #2172

**Comment by dfitchett** [comment]
See instructions in PR #2288 for sending request through rabbitMQ -> `svc-bgs-api` -> `mock-bgs-api`. 
- [x] BGS connects locally to BGS Mock service.
- [x] RabbitMQ returns a valid response for positive and negative unit test cases including required fields for the createNotes endpoint
- [x] Confirmed integration with BGS mock locally by sending request through Rabbit MQ -> svc-bgs-api -> BGS Mock and receive response.
- [x] The mock's logfile confirms the test connected to the mock
  - The logs can be viewed from within the docker container for the `mock-bgs-api` in the file `/usr/local/tomcat/logs/localhost_access_log.*.txt` where the * is replaced by the date-time. 
  - You should see an entry similar to: `172.18.0.5 - - [01/Dec/2023:19:12:35 +0000] "POST /castlemock/mock/soap/project/x5KVzK/DevelopmentNotesService/DevelopmentNotesService HTTP/1.1" 200 361`
