### ISSUE TITLE
Adding EnjoyHQ stories for MaxCFI research

### ISSUE THREAD

**Issue by KimLadin** [department-of-veterans-affairs/abd-vro#2202]
We need to take the most general/global insights from our MaxCFI Research Report and create stories in EnjoyHQ for them using the template provided.
[x] Creating "stories" in EnjoyHQ for 2 general findings
[x] Adding additional tags, labels, or properties so that the research is findable within the repository

**Comment by ChristineRoseSteiffer** [comment]
Guidance was provided on how to proceed with stories - two were added to the [report in EnjoyHQ](https://app.enjoyhq.com/projects/1o7nvamEy/overview#d234c413-1874-4855-a9cf-f532c09caa40).
