### ISSUE TITLE
Add Datadog metric for Max CFI toggle at beginning of 526 form

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#2210]
**User Story**

As a member of the EE team, I want to see the breakdown of Max CFI feature toggle buckets across vets-api users that start a 526 form, so that I can determine whether or not the unevenness of the 50/50 split is occurring as part of the 526 flow.

**Acceptance Criteria**

Fire off a `StatsD.increment` event from vets-api when
1. any user starts the 526 flow (with frontend toggle On or Off)
2. a user with tinnitus at 10% starts the 526 flow (with frontend toggle On or Off)

for a total of 4 different DataDog metrics.

**Notes about work**
- This work is a follow-up to investigation done in #2160
- Previous metrics work for Max CFI: #1911

**Comment by amylai-nava** [comment]
@nanotone this ticket looks good to me 👍🏼
