### ISSUE TITLE
Where do we find the max rating? - What system? Does the data exist anywhere we can pull from?

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2215]
In order for the EE Team to determine the feasibility of a Max rating API they need to answer the following questions:

1. Does VBMS-R hold any data that we can use to determine the max rating? 
2. If so, can we use this data? 
3. Can we estimate the effort needed to implement that source of data? 
4. If it does not exist, what would it take to build it? Who would build it?

AC: 
The questions are answered and the team understands what the LOE will be.

**Comment by KimLadin** [comment]
I heard from Amida about something called the VASRD that might have information on the rating schedule. Amida told me they used to use it but not longer have access to its front-end (and maybe it died on the vine at some point). 

A quick search of github turned up this:

- [https://github.com/department-of-veterans-affairs/vbms-dodaf](https://github.com/department-of-veterans-affairs/vbms-dodaf)
- [https://github.com/department-of-veterans-affairs/vbms-dodaf/blob/master/documents/ServiceViewpoint/SvcV-1/Ratings_svcv1.md](https://github.com/department-of-veterans-affairs/vbms-dodaf/blob/master/documents/ServiceViewpoint/SvcV-1/Ratings_svcv1.md)

**Comment by meganhicks** [comment]
Josh will look into this.

**Comment by amylai-nava** [comment]
**message from Josh and background about feasibility of getting the max rating from the eCFR:** https://dsva.slack.com/archives/C01BVF2A3V0/p1700596802588449

**Comment by amylai-nava** [comment]
**12/1 update:** we have a meeting set up with the OIT PM for VBMS Ratings on Friday 12/8 to learn more about what data VBMS uses for ratings criteria and percentage data

**Comment by amylai-nava** [comment]
I'm marking this ticket as done based on our recent discussions:
* An existing "ratings api" does not exist — VBMS uses a legacy calculator and eCFR does not provide the data in a streamlined way
* Out of the potential directions we could take, building our own max ratings api would be most viable
* Our LOE estimate for the max ratings api is 2-3 months. This includes compiling the data, verifying it, and building the api (excludes implementing the max rating notice for all conditions)
* Next steps are to present our proposal to a wider VBA audience and get feedback
