### ISSUE TITLE
Onboard Ponnia

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2218]
Welcome, Ponnia! We are excited to have you on the team! 

This ticket exists to lay out some logistical to-do's alongside areas of focus for getting up to speed on the VRO team and our work. 

### To be done for you - @dianagriffin / @meganhicks
- [x] Get fingerprinted 
- [x] After Megan will Invite to DSVA, Lighthouse and slack Channels (@vro-team, @vro-eng) 
- [x] Introduce in #benefits-onboarding channel (to kick off OCTO onboarding steps, cc/ Zach/Julie) and #benefits-vro team channel  
- [x] Provide link to fill out the **US** section (additional member to the team) on the VRO Mural page 
- [x] Add to recurring team meeting invites   
- [x] Invite to the OCTO Benefits Delivery Team room in the VA Mural Workspace (as a guest)  
- [x] Add to VA Github Org ([form here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new/choose)) 
  - [x] Add to [OCTO-VRO GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/octo-vro/members) to have access to VRO's GitHub repos
  - [x] Add to [VA-ABD-RRD GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/va-abd-rrd/members) to have access to VRO's LHDI deployment environments

###  To do - Ponnia
- [x] Share your Github username to @meganhicks so you can be added to the VA Github org and relevant Github teams
- [x] Join relevant [slack channels](https://docs.google.com/spreadsheets/d/1c3e6SVuhVz3q4bh1qf5jj25EmusCd3NVXhDjSIpr9yk/edit#gid=1020923043) -- _you don't have to join ALL these channels; start with the #benefits-vro-* channels and you can expand from there as you get more involved in the work. Feel free to ask the team in #benefits-vro if you're wondering about whether to join a particular channel._
    - [x] **Most relevant channels for you**: #benefits-vro (our team channel for coordination across the VRO team), #benefits-vro-engineering (engineering-specific collaboration for the VRO team), #benefits-vro-support (primary channel for collaboration with VRO partner teams building on the platform), #benefits-portfolio (cross-team collaboration channel for all teams in the portfolio) 
- [x] Join [recurring team meetings](https://docs.google.com/document/d/12oaUy0vmv--BFdUhoXk69FtLkhb5Bp0_woOWoD5P3iY/edit#heading=h.p2uqu6tmjnaw) -- _they should be on your calendar!_ Also crosscheck your calendar meeting invites with a team member's calendar using Google calendar to ensure you are in these recurring meetings. Please let Megan know through Slack if you weren't invited to a meeting listed. 
- [x] Go through Benefits Portfolio onboarding materials and onboarding buddy meetings (see #benefits-onboarding channel in Slack; you'll be tagged there with your onboarding buddy assignments and materials to review) 
- [x] Set up a 1:1 meet & greet with OCTO engineering lead Cory Sohrakoff _**preferrably 2-3 weeks after start date**_! _See his slack profile for a calendar URL where you can find available times. In addition, **have some questions ready in preparation for this meeting**_
- [x] Set up meetings with the following team members to discuss the following services that they are in charge of:
    - [x] RDS and Kafka Redis => @msnwatson
    - [x] BIE => @chengjie8
    - [x] BIP => @nelsestu
    - [x] VRO Architecture and integration point => @tejans24

- Review the following materials:
    - [x] The [VRO Wiki page](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Amida-Hand-off-Resources) then set up a code walkthrough meeting with @nelsestu 
    - [x] The [VRO Engineering Onboarding doc](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Engineer-Onboarding) then set up a meeting with @agile-josiah 
    - [x] The [VRO Mural page](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697222300764/071b9570f3bf4a8a678a547a8d3ccd9410e977df?sender=ua51760517335df21b3099342) then set up weekly 1:1s with Megan to discuss its contents (team meetings, their purpose, DOD, DOR, etc)
    - [x] Watch [this demo](https://lighthouseva.slack.com/files/U02U2PFQT3J/F0549C2H2D6/secrel_pipeline_and_sde.mp4) from the Lighthouse Delivery Infrastructure (LHDI) team on the SecRel pipeline and SD Elements
    - [x] While waiting for VA access, review other dropdown folders to the right of the [VRO Wiki page](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Amida-Hand-off-Resources)

- [x] Set up your [local environment](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Local-Setup) and start familiarizing yourself with the code. Please reach out to your team for assistance or post any errors you can't figure out on the #benefits-vro-engineering channel.
- [x] Ask in the daily scrum meeting where you can pair with other engineers
- [ ] When you get a VA email address, add it to your Github account & let Diana know so she can add you to Sharepoint and Okta
    - [ ] When you get an Okta account (you'll be notified to your VA email), follow [these instructions](https://dsva.slack.com/archives/C04PKJ7FQCE/p1696975026214279) to request va.gov and LHDI Datadog access 
- [x] Slack Megan if any of the items to be done for you are not done for you.
- [x] Understand how PTO is communicated within our team. There are **3 places** where we have to communicate our PTO:
    1. **Slack**
    2. **Outlook calendar** (after VA access has been granted)
    3.  Our **personal company calendar**
  
As you review all the material pointed out in this ticket, please help us improve it by pointing out what's missing, out-of-date, and adding to it with other useful info you come across!

**Comment by meganhicks** [comment]
Eric and I recommend the following: 

Partner with Eric when reading the Wiki 
Partner with Josiah on the VRO Onboarding  
Does she need to watch this video? The way we work
Walk through the VRO codebase with Tom- after Wiki is done
Walk through the team meetings and teaming agreement with Megan

**Comment by meganhicks** [comment]
### To be done for you - @dianagriffin / @meganhicks
- [ ] Get fingerprinted 
- [ ] After Megan will Invite to DSVA, Lighthouse and slack Channels (@vro-team, @vro-eng) 
- [ ] Introduce in #benefits-onboarding channel (to kick off OCTO onboarding steps, cc/ Zach/Julie) and #benefits-vro team channel  
- [ ] Add to recurring team meeting invites   
- [ ] Invite to the VA ABD Team Calendar in Google 
- [ ] Invite to the OCTO Benefits Delivery Team room in the VA Mural Workspace (as a guest)  
- [ ] Add to VA Github Org ([form here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new/choose)) 
  - [ ] Add to [OCTO-VRO GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/octo-vro/members) to have access to VRO's GitHub repos
  - [ ] Add to [VA-ABD-RRD GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/va-abd-rrd/members) to have access to VRO's LHDI deployment environments

**Comment by Ponnia-M** [comment]
This ticket is done and ready for review. The only reason two points aren't checked off is because they require I have a PIV card.

**Comment by meganhicks** [comment]
Hello- I made a few edits but overall awesome new additions @Ponnia-M [Engineering Onboarding ticket to dos.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHROQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9190192161d6ef4e0446afb786ae578c40b2e0e/Engineering%20Onboarding%20ticket%20to%20dos.docx)

**Comment by msnwatson** [comment]
@meganhicks did we create a followup ticket for getting @Ponnia-M onboarded to Datadog before the one I just created #2357
