### ISSUE TITLE
Get content approved by OBA

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#2219]
We'll need to get our content approved by OBA / policy folks somewhere in this process. It has always been a more informal process in the past but we may want to be a little more rigorous this time around. 

Initial round of content review, prior to CAIA's edits. We'll create a separate ticket for OBA review after CAIA revises the language.

**Comment by carodew** [comment]
@amylai-nava confirming that OBA doesn't have feedback or concerns on our content?

**Comment by amylai-nava** [comment]
@carodew the last I heard was that we should be hearing back from compensation services sometime this week (hopefully today/tomorrow).

**Comment by carodew** [comment]
@amylai-nava If I parsed the notes from that conversation correctly, OBA is ok with the language for tinnitus, but we need to do some more work to include for other conditions. Is that correct? And if so, I think we can close this ticket?

**Comment by amylai-nava** [comment]
@carodew Yes, that's exactly my takeaway (and Josh's) from the meeting we had with Compensation Service. Thanks for confirming and agree we can close this ticket!
