### ISSUE TITLE
Revise presumptive SC evidence summary (for initial prototype)

### ISSUE THREAD

**Issue by shannonkford** [department-of-veterans-affairs/abd-vro#222]
Make changes to the evidence summary based on concept testing recommendations. These are the minimum changes needed for the prototype.

- [x] Make updates to condition history section and table
- [x] Make updates to presumptive service connection section
- [x] Make updates to order if needed
- [x] Make suggested change to date format (after talking with engineering)
- [x] Show state for no current condition found
- [x] Find a way to clarify new claims versus CFI
- [x] add disclaimer language to the mock flash PDFs that are generated for testing.

## Resources

- [Next iteration of PDF](https://docs.google.com/document/d/15n8iaXOQljE40_ogTAyqqAdkaaAZy_INEQnDsPxpum8/edit?usp=sharing)
- https://design.va.gov/foundation/icons

**Comment by shannonkford** [comment]
Still open: Clarifying "new" (maybe in consultation with Next-gen), fontawesome icons, talk to engineering about date format.

[Next iteration of PDF](https://docs.google.com/document/d/15n8iaXOQljE40_ogTAyqqAdkaaAZy_INEQnDsPxpum8/edit?usp=sharing)

**Comment by carodew** [comment]
Summary of Carolyn's changes:

- Moved "New claim" information to a new line underneath the hypertension summary title. (also thinking about how this needs to accommodate different text)
- added Font Awesome icons (from the free set)
- removed location data from Conditions table
- added disclaimer text to not use generated documents for rating
- tweaked text about data sources and date ranges within each section. 
- tweaked 'about this document' text to remove 'claim for increase' specific language.
