### ISSUE TITLE
Fix flakey BIE kafka integration test

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#2227]
### Why?
The current https://github.com/department-of-veterans-affairs/abd-vro/actions/workflows/bie-kafka-end2end-test.yml workflow has flakey behavior. We need to make sure they consistently pass so we have more trust and reliability in our integration tests. 

**Acceptance Criteria**
* Tests are consistently passing on Github Actions
* A ticket is created to verify and confirm that the test remains consistently passing in 2-3 sprints

**Comment by agile-josiah** [comment]
https://github.com/orgs/department-of-veterans-affairs/projects/871?pane=issue&itemId=46130417

Ticket created
