### ISSUE TITLE
investigate and fix RabbitMQ container in local & CI is running out of storage and prevent it from happening again

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#2228]
### Why?
Integration tests in local & CI were failing with out of storage issue from RabbitMQ. We need to make sure this doesn't become a reoccurring issue because it blocks merges.

https://dsva.slack.com/archives/C04QLHM9LR0/p1700145743766619

### Acceptance Criteria
* Fix or prune storage RabbitMQ container is using after each test.
* Alternatively have a plan to know when it's happening and have a workaround fix to ensure progress isn't blocked.
* Document known challenges with RabbitMQ & CICD

**Comment by tejans24** [comment]
https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/7389988226/job/20104018701?pr=2410

is failing with rabbitmq issues

**Comment by paulsackley-nava** [comment]
Closing this per discussion in sprint planning for Sprint M on 2024-01-16
