### ISSUE TITLE
Design next iteration of presumptive service connection section of PDF (iMVP)

### ISSUE THREAD

**Issue by shannonkford** [department-of-veterans-affairs/abd-vro#224]
## Context 

There will be claims that come in for which the condition claimed is a PACT Act, presumptive condition, however there may not be a Flash indicating Agent Orange (or other toxic) exposure. In those cases the RVSR will need to manually establish service connection. 

AO flash is being applied to Veterans' records where the veteran already has another AO service connected issue. This means the Flash will miss Veterans who do not already have a SC issue based on AO exposure.

* Presumptive service connection for Agent Orange – Verify that the memo supporting AO exposure exists in the Veterans file? Manually find data that supports placing the Veteran in an eligible time/place service cohort? 
* Direct service connection? 

## Changes from ARSD
- [x] Add a new presumptive service connection section, which surfaces flash information, any condition history we have from lighthouse, and other pertinent information, to support PACT Act claims.
- [x] Add a new table for the blood pressure observations data, removing that data from the main schedular and non-schedular tables (note that this change has also been recently released in the MAS PDF, so we don’t need to make this an exception that needs approval).
- [x] De-duplicate the blood pressure observation data in the new table.
- [x] Add VAMC location to the lighthouse BP readings in the new table.

## Design variations

Explore design concepts for next iteration presumptive service connection evidence summary.

### Specific scenarios to design for
- [x] PACT Act contention but no exposure flash found
- [x] no qualifying service history found (this is not likely to happen when there is a Flash, but worth asking Paul or Andrew)
- [x] longest VAMC name

## Resources

- **[iMVP design decisions](https://app.mural.co/t/nava4113/m/nava4113/1664474258124/97c7b5785713700317d4d213e12d3f60cfc0c542?sender=carolyn1198)**

- [Boise shadowing findings on ARS service history](https://docs.google.com/document/d/1XHP2dHryGpu2-Yq1GWjjU2uLK3BxuKkdClzfE8CjggA/edit#heading=h.kmyo9a5n55yh)
- Sharepoint: look in ABD VRO / Documents / Design research / 2022-07 RRD New Contentions for examples for the ARS PDFs
- A few [examples exploring pulling in the locations to the PSC section and not finding a flash](https://docs.google.com/document/d/1LKZcyuJr8u7ksWXrV28-CksLBHfT09l-ssAzY3cNEO0/edit?usp=sharing)
- [Presumptive SC PDF v.1](https://docs.google.com/document/d/15n8iaXOQljE40_ogTAyqqAdkaaAZy_INEQnDsPxpum8/edit#heading=h.i450ljfahlhe)
- [Integrated iMVP flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1653424407090/46c1aff7e984db50fc9a436b5f647199b31f14a8?wid=12-1664223984610&sender=carolyn1198)
- [Links to sample data](https://docs.google.com/spreadsheets/d/1o4J9S5h1X2rmeOEE0XPdP4NVfG4zcA2S/edit#gid=1305660575)

**Comment by carodew** [comment]
Shannon had done some sketching on this for first round but not necessary for our first round of usability testing with real data.

**Comment by carodew** [comment]
rough note to clarify later: do we need hypertension to be diagnosed? Can we pull a claim in that doesn't have HTN diagnosed, but we have keywords?

**Comment by carodew** [comment]
Longest VAMC names – VA Eastern Kansas Health Care System - Colmery-O'Neil VA Medical Center and VA Eastern Kansas Health Care System - Dwight D. Eisenhower VA Medical Center

Still need to determine how they're showing up in the Lighthouse database, since that what we'd be pulling from
