### ISSUE TITLE
Resolve major deployment obstacles- defined by "do you need Mason"?

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2284]
The VRO team is currently experiencing a handful of deployment-related issues that are significantly slowing down our ability to manage deployments according to our current deployment process and standards. **We need to fix what's currently broken.** This epic represents those issues that need to be resolved to stabilize our current deployment process so that we can consistently deploy across LHDI environments as needed. 

### AC
* Any team member can use the current deployment process [without Mason]

### Notes 
- In discussing deployment obstacles the team identified a number of issues related to flakey integration tests, which have been captured in a separate epic, #2369
- This epic does **not** cover significant improvements and enhancements to the overall VRO deployment process; it simply enables the existing process to run smoothly.

**Comment by msnwatson** [comment]
Wanted to clarify that I wouldn't necessarily call #2309 a deployment "blocking" issue as there exists a known workaround as documented in the ticket. Not saying we don't need to fix it but just wanted to make sure we know that this doesn't prevent us from making deployments.

**Comment by dianagriffin** [comment]
@msnwatson Thanks for clarifying that re: #2309. I've updated the name/description of this epic -- based on that update does the inclusion of #2309 make sense?
