### ISSUE TITLE
Consistent method to generate key and trust store values for BIP

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#2293]
### Why?
We currently don't have a consistent way to generate BIP keys similar to BIE Kafka service. So we can use this script to generate keys for VRO envs across LHDI and when they expire.

Scope:
This ticket is only for DEV environment. Other environments would be addressed separately.
The script should be generic enough to be used for all environments.

### Acceptance Criteria
* A script generates Truststore and Keystore base64 strings using the certs and password provided for BIP
* Add to docs on how to use the script and where it's located
* Work with @msnwatson to set reminders on when these creds expire and to make sure they are updated as needed.

**Comment by dianagriffin** [comment]
Will be a dependency for upgrading BIP to the rest of the LHDI environments

**Comment by chengjie8** [comment]
[svc-bip-api-certgen.sh](https://github.com/department-of-veterans-affairs/abd-vro/blob/develop/scripts/svc-bip-api-certgen.sh) has been created to simplify the process of fetching secrets and creating keystore/truststore files within the same script. A output.json file is generated once the script is run, then just copy and paste the json strings from the file into our hashicorp vault.
