### ISSUE TITLE
EP Merge: Add BGS health check -- post MVP

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#2307]
### User Story
As a user of the EP Merge App, I want to perform a check to see if the VRO's BGS service is available before processing the remainder of the request, so that I can prevent adding a manual step for a VSR to add the claim note should the BGS service fail to add the note.

### Associated Tickets/Slack Threads:
- [slack](https://dsva.slack.com/archives/C01BVF2A3V0/p1701818762558239)
- https://github.com/department-of-veterans-affairs/abd-vro/issues/2057
- https://github.com/department-of-veterans-affairs/abd-vro/issues/2206

### Acceptance Criteria
Within the EP Merge App (VRO): 
- a check is performed by sending a request to the health-check endpoint of VRO's `svc-bgs-api` via RabbitMq
  - if the check fails, the merge job is ended in a `COMPLETED_ERROR` state
  - if the check succeeds, the merge job is continued
- unit tests are added
- integration tests are added

**Comment by amylai-va** [comment]
**2/7 refinement discussion**:
* Would there be value in merging the claim if BGS is down and we can't add a note? If the note needs to be manually added by a person, then probably not, as that person would likely need/want to double check that the merging took place correctly before adding the cancellation reason as a claim note.
* Is there a way to address BGS being down without manual intervention? Yes, we could retry the note if it fails.

**action item**:
* @amylai-nava will close this ticket as won't do and create a new, post-mvp ticket to set up a retrying mechanism if 'add note' fails
