### ISSUE TITLE
Request: Production Deployment for Contention Classification on Dec 14

### ISSUE THREAD

**Issue by tyler-spangler6** [department-of-veterans-affairs/abd-vro#2320]
### Requesting Team

Contention Classification

### Related product/initiative

First Redesign for dropdown list

### Problem/Need

Requesting production deployment to include the classification mappings for the new dropdown conditions list. This deployment will also include a classification edit for a diagnostic code that was merged into develop on Dec 4. 

### Why?

The Contention Classification team is currently going through the collab cycle to release the redesigned list to production in va.gov. Adding these classification mappings will allow the classification service to provide classifications for the new list and continue to include classifications for the list that is currently available in va.gov. 

### Acceptance criteria

The Contention Classification service will continue to function as it currently does, but with an increased number of mappings. 

### Priority

We have a staging review for the collab cycle on Dec 14 and would like the deployment to occur before Dec 18 or Dec 19.

**Comment by dianagriffin** [comment]
@tyler-spangler6 cc/ @yurenanava Thanks for submitting this! Confirming: can we plan to deploy the VRO side of this on or before Thursday 12/14 (the day of the collab cycle staging review), or do we need to wait until after that review is complete?

If we need to wait until after the review is complete, then are you okay planning for Friday 12/15 or would you want to wait for Monday 12/18?
