### ISSUE TITLE
Documentation on debugging failed deployments

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#2343]
As a member of the VRO Team, I want to have access to dependable documentation in the wiki that offers insights and tips on effectively debugging failed deployments. This resource will empower me to troubleshoot issues independently when they arise, contributing to a more efficient and self-sufficient troubleshooting process

AC: 
The document should be easy to read and concise (think no longer than a one pager reference guide) 
The document should answer the following questions: 

- Where do we look when a deployment fails? 
- How do we escalate deployment issues within the team and externally with LHDI? 
- Who do escalate issues to and what information should we provide?
- When we need to debug deployment issues with LHDI what are best practices for collaborating? 
- Demo documentation to the team 

- [ ] Understand the VRO deployment workflow
- [ ] Write instructions how to deploy e2e
- [ ] Define specific use cases of deployments (standalone features, grouped features etc)
- [ ] Links to logs or places to see deployment failure info (such as lens vs GA logs)
- [ ] Document any work arounds or things people should know
- [ ] Share the final product with the team

**Comment by meganhicks** [comment]
The team brought up that this should be depriortized based off argoCd work and it needs to be scoped down. 
Things to think about- include how a partner team also handles these situations. 
@Ponnia-M  can you review what we have?

**Comment by meganhicks** [comment]
might not be needed.
