### ISSUE TITLE
[Request]: Production Deployment for CC Team on Dec 18

### ISSUE THREAD

**Issue by tyler-spangler6** [department-of-veterans-affairs/abd-vro#2355]
### Requesting Team

Contention Classification

### Related product/initiative

First Redesign for dropdown list

### Problem/Need

After releasing the new redesigned dropdown options to va.gov, the contention classification team needs to update the logging statements to reflect these new terms.

### Why?

This allows the CC team to track new conditions that users select from the dropdown options which will allow us to measure the effectiveness of the new terms in the list. 

### Acceptance criteria

The logging statements in LHDI datadog will be updated to reflect the new dropdown options.

### Priority

Requesting deployment on Monday Dec 18, after releasing the revised list to production in va.gov.

**Comment by meganhicks** [comment]
@msnwatson can we close this?

**Comment by tyler-spangler6** [comment]
@msnwatson @meganhicks We are still working through the staging testing issue, so we are not ready to release this into production yet. Is it better for you all to close this ticket and open a new one after we have the testing resolved? Thanks for all the help on this.
