### ISSUE TITLE
Transition to requiring CODEOWNER reviews instead of always 2 VRO engineers

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#2360]
**User Story**

As a partner team engineer, I want to avoid needing code reviews from VRO engineers when changes only apply to my application, so that I have more autonomy in making changes to my own products.

VRO engineers may not have the necessary context and may not be adding value by reviewing. This would give partner teams more autonomy. 

**Acceptance Criteria**

1. Updating CODEOWNERS file
2. Partner teams do not require VRO engineer CR for changes to their own directories
3. Changes to directories that aren't owned by partner teams still require 2 VRO engineer reviews

**Comment by agile-josiah** [comment]
It's unclear to me what needs to be changed. As I currently understand, the CODEOWNERS file lists the owners of domain-ee and domain-cc owners as benefits-employee-exp-engineers and benefits-contention-classification-engineers respectively. 

[](https://github.com/department-of-veterans-affairs/abd-vro/blob/develop/.github/CODEOWNERS
)

Is there another directory/partner team that is missing?

**Comment by msnwatson** [comment]
Have you tested that if you made a change in their directory that there would only require a review from their team because my understanding is that is not happening? 

Also, I think we need to give partner teams the ability to manage their own codeowners which i think will require nested CODEOWNERS in their directories.

@agile-josiah

**Comment by agile-josiah** [comment]
After running a test PR with a change to the domain-cc app I noticed the benefits-contention-classification-engineers team was correctly added to the reviewers list.<img width="1554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnZxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61562af05ace709fb6267dad8e942a713ef8cd7d/Screenshot%202024-01-22%20at%203.01.24%20PM.png" alt="Screenshot 2024-01-22 at 3.01.24 PM.png" />

**Comment by agile-josiah** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews

Turns out if the folks that are reviewing don't have admin/write access they can't approve prs for merging. I don't think I have permission to check if people have read/write/admin access to va github.

@msnwatson

**Comment by msnwatson** [comment]
@agile-josiah what do we think about the second part of my comment above. Since the CODEOWNERS file currently only lives in root, I'm pretty sure if partner teams wanted to change their owners or review they'd still require us. Are you advocating for including work for nested CODEOWNERS in a different ticket?

**Comment by agile-josiah** [comment]
<img width="820" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2ozQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85b13132d7daca195909ef267ae6a1a01db19d87/Screenshot%202024-01-24%20at%2011.55.34%20AM.png" alt="Screenshot 2024-01-24 at 11.55.34 AM.png" />

**Comment by msnwatson** [comment]
@agile-josiah would you like me to create a new ticket to cover the other half of the comments i've made?

**Comment by msnwatson** [comment]
Also, @agile-josiah can you make an announcement to our partner teams that we no longer require code reviews from VRO engineers for changes to their own directories in the #benefits-vro-support channel. I think they'll be happy to hear that. I'll make a comment about expectations for major application changes on a thread there.

**Comment by agile-josiah** [comment]
Thinking about the acceptance criteria I think creating another ticket or changing the criteria is what I'd like to happen. As for the codeowner changes, the way codeowners currently works, CODEOWNERS exists in the .github/, root, or docs/ directory of the repository. And will choose the first one it finds out of that list. I don't know of any direct ways that we could have multiple codeowners and have the "correct" one selected accordingly. If partner teams want to change the CODEOWNERS file I think the on-call can address that when it comes up.

**Comment by agile-josiah** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location

**Comment by msnwatson** [comment]
Oof, I see my understanding that this feature existed was now an internal feature at my last company. Very sad.
