### ISSUE TITLE
[Request]: Custom DataDog metric for timing requests

### ISSUE THREAD

**Issue by lukey-luke** [department-of-veterans-affairs/abd-vro#2387]
### Requesting Team

Contention Classification

### Related product/initiative

All VRO tenants

### Problem/Need

I'm not sure what the vault is for LHDI datadog or where the config files live. If possible, can we configure the Helm API gateway to talk to datadog and track requests via a custom [datadog metric](https://docs.datadoghq.com/metrics/)?

### Why?

Doing it at a higher level (e.g. API gateway) allows engineers to get timing information for all requests, regardless of language/framework.

### Acceptance criteria

- [ ] Either a new metric set up for requests in the VRO platform
 - or -
- [ ] Access keys so request timing information can manually be tracked for just CC application via middleware

### Priority

7/10

### Target timeline

January 31st 2024

### Context and documentation

https://github.com/department-of-veterans-affairs/abd-vro/issues/1724

**Comment by meganhicks** [comment]
@lukey-luke is this still needed? I see it is a really outdated request.

**Comment by verdance-luke** [comment]
closed as obsolete
Whether custom metrics or APM be supported or there are other alternatives, please let me know what we can make use of in LHDI datadog
