### ISSUE TITLE
VRO/EE to set up monitoring alerts for Max CFI on the LHDI side to track when the API is not receiving requests

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2413]
context: https://docs.google.com/document/d/1IIVcC8yRXVUcGcqxgdx8DLwiAvxOz-V10x3DpVCaNJk/edit#heading=h.72acybx9j43h

**Comment by dfitchett** [comment]
Things to Add: 
- [x] Periodic Health Check to service in Prod with alert sent to slack when check fails
  - Synthetic [Test](https://lighthousedi.ddog-gov.com/monitors/194869?view=spans) Added to DD
- [x] Other Updates to Datadog Dashboards
