### ISSUE TITLE
Onboard Paul

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2416]
Onboarding for a Product Manager 
* Set up reoccurring one on ones with your teammates and key stakeholders 
* Review all the documentation Diana created for you and ensure you have a full understanding of current product priorities. Ensure you understand what you should prioritize for the next 2 sprints. 
* Review the meeting structure and purpose for all Team meetings. Pay extra attention to Sprint Planning, Backlog refinement, and shared backlog refinement. Understand what your facilitation responsibilities are and how you can be prepared for these meetings. These meetings and documentation around them can be found on the teaming agreement and roles doc Megan and Diana created together. 
	https://docs.google.com/document/d/1gk8HhZhYbhb9P7FCeX6TlRgWTwhrfrfXtuFghu-Jq94/edit#heading=h.cxczcap6mrpi
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697222300764/071b9570f3bf4a8a678a547a8d3ccd9410e977df?sender=u739128c1dfc0f4a9293a2519 
* Set up one on one with everyone on this list: https://docs.google.com/document/d/1CnX6NYiAbI9gy_JZSoejGMslXD7Z_12yzJkiB5QLaG4/edit#heading=h.445s4bqc0leh 
* Work with Bianca to proactively get an understanding of design priorities for Q1 and ensure user stories and AC are created in advance to Sprint Planning meetings. Please add her user stories to the appropriate Epic on Zenhub
* Review the Zenhub board and make any adjustments to priorities you think are valuable. Organize how you see fit. Ensure you understand the Epics and timelines.
https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/board 
* Review the communication norms to best understand what slack channels you should have and how to use them. They are on the Teaming agreement below. 
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697222300764/071b9570f3bf4a8a678a547a8d3ccd9410e977df?sender=u739128c1dfc0f4a9293a2519 
* Update your Slack profile on the VA side. Ensure to include a link to your google calendar, working hours, and timezone
* Review the team Wiki page documentation and make sure you have an understanding of the VRO platform and services. 
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697222300764/071b9570f3bf4a8a678a547a8d3ccd9410e977df?sender=u739128c1dfc0f4a9293a2519
* Review the VRO roadmap, save it, and update it. 
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692641350848/759d1c27c77f2dfe4ad238487352154f6eb0d06a?sender=u739128c1dfc0f4a9293a2519
* Complete PM role training with Dotti

**Comment by paulsackley-nava** [comment]
test
