### ISSUE TITLE
Develop Roadmap for Design/Research work for Q1 (Jan-Mar) 2024

### ISSUE THREAD

**Issue by bianca-rivera** [department-of-veterans-affairs/abd-vro#2424]
**Description**
--
Outlining the work to be accomplished for design/research track

**Why**
--
To develop a staged plan of efforts to determine how VRO functions as a service with our partner teams

**Dependencies**
-- Coordinate initiatives and timing with @paulsackley-nava 

**Acceptance Criteria**
--
- [ ] Completed Q1 and Q2 roadmap
- [ ] Coordinate with Paul on prioritization

**Resources**
--

**Comment by meganhicks** [comment]
@bianca-rivera I have this as completed last sprint? Is this not completed?
