### ISSUE TITLE
Python microservices shut down when RabbitMQ shuts down

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#243]
(not for version 1.0)

To improve robustness of Python microservices (or any VRO microservice), when the RabbitMQ service is shutdown, the microservice should continue to retry to connect to RabbitMQ over some finite time duration (5 or 10 minutes -- to be determined). This will also reduce coupling of software components.

Currently, the Python microservices shutdown when RabbitMQ shuts down. To replicate, stop the RabbitMQ docker container and notice the containers for the Python microservices stops as well.
<img width="937" alt="image" src="https://user-images.githubusercontent.com/55255674/187731302-5eb7e061-cb49-445b-942e-b152e70baa85.png">

Open to discussion and solution ideas -- post in comments below.

**Comment by yoomlam** [comment]
@anthonyvelazquez @jbregstone I haven't noticed this happening recently. Have y'all addressed the problem? If so, can this ticket be closed?

**Comment by anthonyvelazquez** [comment]
Closing, this has been addressed in another PR

**Comment by yoomlam** [comment]
Reopening for OCTO testing. Related to #565 but more specific to Python microservices.

**Comment by tjheffner** [comment]
Verified on a huddle with @nanotone and @sethdarragile6 that the various python microservices stay running and attempt to reconnect to rabbitmq every 30s when the rabbit container is killed, and do reconnect + work correctly when the rabbit container is restarted.
