### ISSUE TITLE
[Request]: Production Release for CC Service on Jan 18

### ISSUE THREAD

**Issue by tyler-spangler6** [department-of-veterans-affairs/abd-vro#2447]
### Requesting Team

Contention Classification

### Related product/initiative

First Redesign for dropdown list

### Problem/Need

We previously requested a production deployment in #2320, but ran into issues testing the front-end release in staging. We are currently finishing the staging testing, and are hoping to be ready for a production release on Jan 18. 

### Why?

This production release would include updated logging statements that will help us track usage of the new redesigned conditions list that Veterans see when utilizing the 526EZ. 

### Acceptance criteria

After a production release, we would see logs pertaining to the new redesigned dropdown list in LHDI datadog and metrics would populate on our dashboard. 

### Priority

Request deployment on Jan 18, but will communicate if we need to push this back due to testing issues.

**Comment by msnwatson** [comment]
Completed yesterday
