### ISSUE TITLE
Add feature flag (a.k.a. feature toggle) service

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#245]
Incorporate a language-agnostic feature flag (a.k.a. feature toggle) service that can be used by microservices written in various languages (such as Python, Java, Ruby, etc.). [This article](https://itnext.io/things-to-think-before-enabling-feature-toggle-in-your-application-91880373a0ed) mentions "some ready-made solutions: LaunchDarkly, fflip, Firebase Remote Config and Unleash". I'm looking for a tool that would be free for open-source or government projects. 

VRO-relevant needs:
* toggle features immediately in production
* A/B testing
* spot testing in prod

Looking for input: What feature flag tool/service are you familiar with? Which do you like and don't like? I'm also open to any advice in choosing a tool.

* [Unleash](https://www.getunleash.io/) looks promising -- [can be self-hosted for free with limited features](https://www.getunleash.io/plans), [well documented](https://docs.getunleash.io/), [SDKs for a variety of languages](https://docs.getunleash.io/sdks), [open source](https://github.com/Unleash/unleash)
* [FeatureHub](https://www.featurehub.io/) -- all features are free, open source, ...

**Comment by tjheffner** [comment]
Unleash looks like a good choice, may need a paid plan for more than two environments.

Elsewhere in the VA ecosystem ([vets-api](https://github.com/department-of-veterans-affairs/vets-api)) the [flipper](https://github.com/jnunemaker/flipper) package is used, see: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles

**Comment by tjheffner** [comment]
Initial plan is to roll our own python microservice as an initial implementation for this service, with a mind to potentially integrate with a third party provider for some sort of UI front-end in the future.

---
python microservice:
yaml config file with the different flags, similar to vets-api
listen to a rabbitmq queue, receive & reply with json cleartext (i.e. list of feature flags on/off from the config file)

java camel integration:
in the `configureRouteClaimSubmitForFull()` method, set relevant properties for environment variable (dev, prod, etc) and append feature flag data from our microservice to the existing message

**Comment by yoomlam** [comment]
@tjheffner I have a second thought -- it shouldn't change what you plan to implement; it does change how the microservice will be used and it adds storing the feature flags in Redis has a hash.

So instead of inserting a call to the new microservice into existing Camel routes (like we discussed), I'm thinking of adding a  [Camel Redis consumer](https://camel.apache.org/components/3.18.x/spring-redis-component.html) that subscribes to changes made to the feature-flag hash. This consumer will be a new Camel route that keeps a local read-only hash in sync with the Redis hash. The local hash will be marshalled into JSON and appended to Camel messages where needed (using the [Enrich Camel EIP](https://camel.apache.org/components/3.18.x/eips/enrich-eip.html)).

Advantage: Much fewer calls to the new microservice. Simpler design of Camel routes.
There may still be an initial call to get the initial flag values.
Other services may want to call the new microservice directly for whatever reason.

Thoughts?

**Comment by yoomlam** [comment]
Thoughts on how the new service will be used by the VRO app:
- The app will maintain a singleton HashMap object that contains the features flags
- The app will listen to Redis for changes to a Redis key. 
- The app will track the last timestamp it updated the feature flags. We can invalidate or force a hash refresh by setting the timestamp to null.
- Upon app startup (probably after a few seconds delay), the app queries the service to initially populate the HashMap
- Every N minutes, the service will publish a change to cause the app to refresh its HashMap. Not needed but this will ensure/test that changes to feature flags are propagated to the app.

We can discuss in our next 1:1.

**Comment by tjheffner** [comment]
new method in:
https://github.com/department-of-veterans-affairs/abd-vro/blob/develop/app/src/main/java/gov/va/vro/VroApplication.java

or perhaps here: https://github.com/department-of-veterans-affairs/abd-vro/blob/develop/controller/src/main/java/gov/va/vro/controller/VroController.java

**Comment by yoomlam** [comment]
Between the two, `VroController` makes more sense. Without more details, it's hard to tell. Start there and see how it goes as you implement it.

**Comment by tjheffner** [comment]
this ticket will roll over to sprint K... i am quickly learning i am not a java dev 😅 

remaining steps:
- java integration of feature toggle service (basically the steps yoom outlined above. need to make a call to the service, update every N minutes, listen to redis in java)

**Comment by ENeal49** [comment]
Split remaining work into tickets 803 and 802, then closed.
