### ISSUE TITLE
Support VRO in testing BIP

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2451]
The VRO team anticipates that they will be able to deploy BIP to production in this sprint (Sprint L) and could use the Employee Experience team's support in testing BIP.

## Acceptance Criteria
- to be determined after our meeting on Jan 17

**Comment by amylai-va** [comment]
Work is being tracked in #2449. We also have a ticket for #2092 when we're ready to conduct e2e testing. Closing this as won't do. cc/ @meganhicks @dfitchett
