### ISSUE TITLE
Set up ABC test for Max CFI (tinnitus only)

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2454]
As a member of the Employee Experience team, I want to set up an ABC test for the Max CFI intervention, so I can evaluate the effectiveness of our interventions (for tinnitus only to start).

**Our population = users with tinnitus at 10%**
* **A = Control group**: users who do not see any intervention
* **B = Experiment 1**: users who see the max rating notice only
* **C = Experiment 2**: users who see the max rating notice and explainer about what it means to be at the maximum rating

## Acceptance Criteria
* Two feature toggles are set up:
  * **Feature One**: controls whether any intervention is on
  * **Feature Two**: controls whether the explainer text is on
    * If `off`, only the max rating notice is displayed
    * If `on`, both the max rating notice and explainer text are displayed
* So that the three groups of users are represented by these 3 states:
  * **Control group**: Feature One is off
  * **Experiment 1**: Feature One is on, Feature Two is off
  * **Experiment 2**: Feature One is on, Feature Two is on

## Notes about work
* Experiments are happening at the same time. We will use the % setting to determine the split between the 3 groups (e.g., 50%, 25%, 25%)
* This work will enable us to track Datadog metrics like:
  * What % of Group B and Group C users still submit a CFI for tinnitus even though they are already at the max rating?
  * Compared to Groups A and B, are we seeing a % reduction in claims submitted by Group C users?
*  [Link to related slack thread](https://dsva.slack.com/archives/C01BVF2A3V0/p1705614234207349)

**Comment by amylai-va** [comment]
### **Notes from 2/8 refinement**

Work we can do before we decide what design we're implementing:
  - Set up the second feature toggle
  - Start some front end changes like setting up the accordions (check with design team)

**Comment by amylai-va** [comment]
closing as won't do, since will not be moving forward with the educational content
