### ISSUE TITLE
Get smarter about hyphenated conditions

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2456]
As a member of the Employee Experience team, I want to learn more about how maximum ratings are assigned for hyphenated conditions.

## Acceptance Criteria
- [x] Get a list of hyphenated conditions from PA&I (idea: CC team might have data we can leverage)
- [x] Identify ones we might be able to get a maximum rating for, focusing on stable, common ones
- [x] Research how hyphenated manifest on VA.gov (if capacity allows)

**Comment by amylai-va** [comment]
1/30: Per discussion in sprint planning, moving this back to the backlog
