### ISSUE TITLE
Slack Clean up

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2459]
This story is to capture the work we are doing to clean up our VRO Slack channels   

Summary: We maintain the benefits-vro-support channel to provide access to anyone requiring assistance with VRO. In this channel, partner teams can submit requests, and we welcome the participation of all stakeholders and other enablement teams. Our proposal is to preserve the current structure of this channel and focus on streamlining what we consider to be 'internal channels”. 

Benefits-vro clean up suggestions: 
Please remove the following people: 
1.	Alejandro Mendiolaflores
2.	Alex Prokop
3.	Buddhima Kurukulasuriya 
4.	Derrick Ellerbie 
5.	Diana Griffin
6.	Gabriel Zurita 
7.	Karla Leal
8.	Kim Ladin
9.	Luke short
10.	Oren Mittman
11.	Premal Shah
12.	Sade
13.	Sam Raudabaugh 
14.	Tom Greene 
15.	Steve Albers 
16.	Tyler Spangler 
17.	Yang yang
18.	Amy Lai 
19.	Yurena 
Benefits-VRO-engineering clean up suggestions:
Please remove: 
1.	Alex Porkop
2.	Amy Lai
3.	Anneliese LaTempa 
4.	Derek F
5.	Derrick Ellerbie 
6.	Diana Griffin 
7.	Gabriel Zurita 
8.	Jennifer Bertsch
9.	Luke short 
10.	Mark Chae 
11.	Oren Mittman
12.	Premal S
13.	Rocio De Santiago 
14.	Sam Raudabaugh
15.	Steve Albers
16.	Tom Greene
17.	Yang Yang 
18.	Yurena

**Comment by meganhicks** [comment]
Could 2 people review this and give me their suggestions?

**Comment by msnwatson** [comment]
have we looked at like enabling the “guest” functionality. I briefly saw this as I was poking around the channel and I think it might help keep our channels clean going forward instead of inching back toward the same situation over time.

**Comment by meganhicks** [comment]
It's on my list to ask them about Mason. I wanted to ask when I submit the request.

**Comment by msnwatson** [comment]
Alright then lgtm!
