### ISSUE TITLE
BGS Rollout to prod-test/pre-prod LHDI Env

### ISSUE THREAD

**Issue by paulsackley-nava** [department-of-veterans-affairs/abd-vro#2462]
**User Story**

As a consumer of the BGS API, I want to ensure that the svc-bgs-api container can be built and deployed using accurate configuration options.  This issue will continue the deployment process, seeing the completion of rollout to the rest of the VRO environments in LHDI except prod-test/pre-prod and prod. 

* Complete a new end-to-end test that will help validate the BGS integration as we roll it out to additional environments. This script will help drive a new directive focused on more thorough testing practices.
* Prepare environments for incoming BIP deployments by ensuring that the secrets configured in the environments are accurate and functioning properly 
* Confirm the current state of BGS
* Validate our cross environment API mapping

**Before this ticket can start**

**Acceptance Criteria**
_Note_ Please pair with another engineer on this effort
1. After validating dev, and confirming its viable state there, we'll plan to repeat the steps from AC1 for all other non-prod environments including: 
	- [ ] prod-test/pre-prod - namespace: `va-abd-rrd-prod-test` in `prod` context
2. Document secrets and how they are set up

**Additional Validation Work**

**Notes about work**
- _(links to documentation, resources, code, etc that might inform the person doing the work)_

**Comment by msnwatson** [comment]
@paulsackley-nava can we include as an AC here to create a ticket for BIS deployment in prod or does this already exist?
