### ISSUE TITLE
fix bie kafka service `eventType` null value issue

### ISSUE THREAD

**Issue by chengjie8** [department-of-veterans-affairs/abd-vro#2487]
`eventType` shows up as null value in dev environment with the most recent code changes. The event type need to match with Kafka event type so that we can easily tell the payload coming from which kafka contentional classification event type. 

**Acceptance Criteria**

1. `eventType` is not null for all kafka message payloads in `svc-bie-kafka` pod log 
2. actual `eventType` value need to match kafka contentional classification event type (e.g. topic `TST_CONTENTION_BIE_CONTENTION_UPDATED_V02` should be topic`CONTENTION_BIE_CONTENTION_UPDATED_V02`

**Not included in this work**

A note about things that should not be considered necessary.

**Notes about work**
- relevant Slack thread here: https://dsva.slack.com/archives/C01Q7979Z7D/p1705678520943719

**Comment by paulsackley-nava** [comment]
verify with Cheng that Steve Alber's ask from the above referenced Slack thread has been satisfied
