### ISSUE TITLE
Look up how example hyphenated conditions are displayed in the online 526 from

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#2500]
**User Story**
As a member of the Employee Experience team, I want to understand how a Veteran's disability that was rated with a hyphenated diagnostic code appears in the online 526 form so I can get smarter about hyphenated conditions. I want to know whether the disability is displayed as one condition or two and if the disability name matches what's in VBMS.

**Acceptance Criteria**
1. Using the benefit claim IDs provided for each Veteran, look up in production how the disability is displayed in the online 526 form
2. Insert the disability name in column E of the shared spreadsheet

**Notes about this work**
- Most disabilities within the VA rating schedule are associated with one diagnostic code. However, in certain circumstances, a claims processor may rate the disability with a hyphenated diagnostic code, such as 9423-6260.
- The benefit claim IDs and other relevant information will be shared via Sharepoint

**Comment by nanotone** [comment]
I've concluded that hyphenation data isn't available in vets-api, and therefore they wouldn't be displayed in the VA.gov 526 form.

For example, when investigating Form526Submission 1662508, we see that its 526 form contained these disabilities:
```ruby
> fsub = Form526Submission.find(1662508)
> fsub.disabilities
[{"name"=>"Hearing Loss",
  "classificationCode"=>"3140",
  "disabilityActionType"=>"NEW",
  "serviceRelevance"=>"Hearing loss with tinnitus due to... [redacted content]"},
 {"name"=>"tinnitus",
  "classificationCode"=>"6850",
  "disabilityActionType"=>"NEW",
  "serviceRelevance"=>"Hearing loss with tinnitus due to... [redacted content]"}]
```

and we know from VBMS that the tinnitus got a diagnostic code `9423 - 6260` (9423: Unspecified somatic symptom and related disorder. 6260: Tinnitus, recurrent).

However, this is what we get when going back to the rated disabilities data source for vets-api (EVSS), which is what vets-api would use to populate a subsequent 526 form:

```ruby
> service = EVSS::DisabilityCompensationForm::Service.new(fsub.auth_headers)
> service.perform(:get, 'ratedDisabilities').body
...
   {"decision_code"=>"SVCCONNCTED",
    "decision_text"=>"Service Connected",
    "diagnostic_code"=>6260,
    "diagnostic_text"=>"tinnitus with insomnia",
    "effective_date"=>"2023-02-07T06:00:00.000+0000",
    "rated_disability_date"=>"2023-07-21T21:41:24.000+0000",
    "rated_disability_id"=>"89334084",
    "rating_decision_id"=>"401034015",
    "rating_percentage"=>30,
    "special_issues"=>[{"code"=>"TERA", "name"=>"Toxic Exposure Risk Activity (TERA)"}]}
```

We can see that only DC 6260 is returned, even this tinnitus is rated at 30% (tinnitus alone normally maxes out at 10% as we know). So there is no way for the code to calculate a different max rating for this disability.

Note also, that the diagnostic text "tinnitus with insomnia" hints at something else going on, and this text would be displayed to the user in the VA.gov 526 flow if/when they use it to file for a CFI.

**Comment by nanotone** [comment]
Addendum: I mentioned in today's weekly team meeting that while it's unrealistic to expect the legacy data source (EVSS) to add new hyphenation info, there might be promise in using the new data source (LH Veteran Verification).

I went in and used the Veteran Verification implementation (currently behind a feature toggle in VA.gov prod) to fetch the same rated disability as above:

```ruby
 {"decision"=>"Service Connected",
  "effective_date"=>"2023-02-07",
  "rating_end_date"=>nil,
  "rating_percentage"=>30,
  "diagnostic_type_code"=>"6260",
  "diagnostic_type_name"=>"Tinnitus",
  "diagnostic_text"=>"tinnitus with insomnia",
  "disability_rating_id"=>"89334084"}
```

So there isn't really anything new that would indicate hyphenation. The only extra tidbit I see is the "diagnostic type name" which spells out that 6260 is Tinnitus, even though this particular rating is for tinnitus with insomnia. 🤷
