### ISSUE TITLE
Establish a Test User for BIP Production Use

### ISSUE THREAD

**Issue by nelsestu** [department-of-veterans-affairs/abd-vro#2516]
While deploying the BIP Shared Microservice to production we discussed the challenges of testing in the production environment. We don't want to interact with any real data, yet we do need to demonstrate that our code is functioning as expected.  The EE team have test users in the production environment and we need to establish the same.

**Acceptance Criteria**
1. Document a test plan, updating the informal testing documented in the following canvas: https://dsva.slack.com/docs/T03FECE8V/F06ENVBACBX
2. Document test users and how to access

**Comment by paulsackley-nava** [comment]
Follow up with @CorySohrakoffUSDS for guidance on testing in production. After speaking with EE, we learned that they don't test in prod this way, so it would be useful to get the VA viewpoint.

**Comment by meganhicks** [comment]
not needed as the EE team is owning this
