### ISSUE TITLE
Implement a scheduler that will periodically update PagerDuty

### ISSUE THREAD

**Issue by agile-josiah** [department-of-veterans-affairs/abd-vro#2546]
**User Story**

As a VRO engineer oncall, I want a scheduler that automates the oncall rotation fairly, so that the oncall work is distributed fairly and considers time off. This may be part of PagerDuty's core functionality.

**Acceptance Criteria**

1. A scheduler is created in the github repo that makes api calls to PagerDuty to update the schedule.
2. Can make calls to the team calendar to grab events data for engineer time off.

**Not included in this work**
A note about things that should not be considered necessary.
This can be developed in Python as the demands are quite lightweight. Loosely the logic design can be created considering time off and frequency of being oncall previously(both primary and secondary).

**Comment by paulsackley-nava** [comment]
Josiah to flesh this out.
