### ISSUE TITLE
Add DestinationRule k8s entities for containers running services exposed to the mesh

### ISSUE THREAD

**Issue by paulsackley-nava** [department-of-veterans-affairs/abd-vro#2557]
Why: this ticket closes a bug which would prevent our application from receiving any traffic.

As a VRO engineer, I want VRO to be able to connect to everything that we depend on and that depends on us, including our partner teams' applications.

While LHDI has communicated that there are no active plans to force ugprades from HTTP1 to HTTP2 in the Istio mesh, this ticket is still necessary as LHDI currently makes no assurances that this behavior will not happen sporadically for some reason. Our partner team services specifically have already faced two incidents in prod with downtime because of this issue.

AC:
* We have configured `DestinationRule`s alongside all of our services which expose services to the Istio service mesh in every environment. Ideally, these can be lumped into a single rule per k8s namespace; however, the ticket author is not sure that this is possible.
* It needs to be clearly documented that these `DestiantionRule`s exist, how to apply changes to them, and why they are installed.
* The k8s manifests for these entities should be committed as code (it is unclear to the ticket author where they should live).

Notes:
Relevant Slack threads
* https://dsva.slack.com/archives/C03UA9MV1EH/p1707161155974279
* https://dsva.slack.com/archives/C03UA9MV1EH/p1701202201080829
* https://dsva.slack.com/archives/C03UA9MV1EH/p1706545196857089?thread_ts=1701202201.080829&cid=C03UA9MV1EH
* Originally, the VRO team had hoped to close this bug by using an Istio sidecar; however, LHDI has since removed this as a possibility.
* You should be able to query for the existing DestinationRule entities in the `prod` namespace using `kubectl`. 
```
kubectl get destinationrule http-cc -o yaml
```
<img width="1020" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3kyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87e7729f2c9ab2abb9a63d38e90f982b69d8c01e/http-cc-destinationrule.png" alt="http-cc-destinationrule.png" />

**Comment by msnwatson** [comment]
Created this wiki page https://github.com/department-of-veterans-affairs/abd-vro/wiki/DestinationRule-for-Preventing-Forced-HTTP2-Upgrade

**Comment by msnwatson** [comment]
Today, I've deployed the changes from the PR to environments that don't require SecRel

**Comment by msnwatson** [comment]
Done, sprint overlap attributed to blocking on SecRel
