### ISSUE TITLE
Implement RBAC for `svc-bie-kafka` in our prod environment

### ISSUE THREAD

**Issue by paulsackley-nava** [department-of-veterans-affairs/abd-vro#2560]
**User Story**
As a VRO engineer, I want to update Kafka to use RBAC for authentication and authorization so that we remain compliant. The scope of this ticket is our prod environment. `dev`, `qa`, and `sandbox` were covered in #2530.

**Per Darrell Neel, our prod certs expire 2024-09-07**

**Acceptance Criteria**
* Kafka is using RBAC

**Notes about work**
* See documentation here: https://github.com/department-of-veterans-affairs/bip-tooling-confluent/wiki/Streaming-app-authentication-and-authorization-with-Confluent-RBAC
* POCs are Milton Garcia and Darrell Neel
* Slack thread here: https://dsva.slack.com/archives/C04U8GESRT7/p1706727018289089

**Comment by ponny-m** [comment]
This ticket is currently blocked due to some staging environment issues found on the BIE Team's side. Until they resolve this, we can't proceed to confirm a successful connection in Prod env. Mohietosh has added **Cheng**, **Megan**, and **myself** in a VRO/BIE weekly sync on **Wednesdays** so that we can track progress on their end and ask any questions.

**Comment by meganhicks** [comment]
Would you move this back to "in refinement/blocked" and we can pause this.

**Comment by meganhicks** [comment]
current prod cert expires:  9/7/24. This means this has to be done by this date. 

cc: @BerniXiongA6

**Comment by meganhicks** [comment]
@Ponnia-M please verify we have creds and there are not any active bugs that could block.

**Comment by ponny-m** [comment]
PROD creds were sent **05/09/24**, which were updated to both Vault and K8s environment. Then we [deployed](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/9022784428) to prod after that, but started seeing the errors Cheng mentioned in this [thread](https://lighthouseva.slack.com/archives/C04U8GESRT7/p1715285344060269?thread_ts=1715276007.845649&cid=C04U8GESRT7). So at this point, another deployment isn't necessary and we are waiting for the approval phase on the BIE team side to be cleared and hopefully start getting messages in the Kafka prod pod.

**Comment by ponny-m** [comment]
Here is evidence of Kafka prod pod starting to receive messages after BIE team deployed to Prod. 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0RUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8c2f7f531bfdebf007961030fc28d7882319b5a/Screenshot%202024-07-11%20at%209.01.41%E2%80%AFPM.png" alt="Screenshot 2024-07-11 at 9.01.41 PM.png" />
