### ISSUE TITLE
Enable the max-cfi app to support multiple diagnostic codes

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#2564]
We are expanding our Max Rating API to include the max rating percentage for all diagnostic codes (DCs) within the rating schedule (~700 DCs). Currently, the API contains the max rating percentage for one disability, Tinnitus. 

## Acceptance Criteria
- [x] Review current state of the Max Rating API
- [x] Write tech spec for expansion of the API to include all diagnostic codes
- [x] Write tickets for engineering work needed to create this API

## Notes about this work
- Link to the [max rating dataset in Google](https://docs.google.com/spreadsheets/d/1iw_i0q5OD-IDEgAEWbZaL8fgA4J88bwoCxGA4J4WUB0/edit?usp=sharing) (**Note**: this is **not** the latest dataset, but it's representative of the content that would go in the API)
- Link to the [max rating dataset in Sharepoint](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Employee%20Experience/Max%20CFIs/Max%20Ratings%20API/Max%20Ratings%20API%20data.xlsx?d=we01435ed17a7458fab226b02fe4e3c3e&csf=1&web=1&e=8fRROe&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMTAwLTAwMDAwMDAwMDAwMH0) (**Note**: some cleanup is needed, but this is the version that was reviewed by the VASRD team)
- **Current scope**: 
  - a simple way to store & retrieve the max rating for ~700 diagnostic codes
  - use the value in the max rating column, not the one in the minor/nondominant column
  - there are a few different ways that a max rating is determined, but it shouldn't impact our implementation
- **Possibilities of how this API might expand/change in the future**:
  - a way for VA to maintain and update the max rating without requiring code change
  - an API that contains all ratings for a diagnostic code, not just the maximum
  - text associated with each rating that describes in plain language how a Veteran might get to the next level

**Comment by amylai-va** [comment]
@amylai-nava will add notes about how we might phase this work. 

example:
- phase 1 = displaying the max rating for DCs that have a clear max rating
- phase 2 = handling hyphenated conditions
- etc

**Comment by amylai-va** [comment]
**Edit**: I've updated the description of this ticket and the next steps listed below to better reflect our discussion

@dfitchett @nanotone @KimLadin, jotted down the next steps that we discussed at the end of the call:
- @amylai-nava will link the spreadsheet that's in Sharepoint to this ticket ✅
- @KimLadin will clean up the spreadsheet in Sharepoint to match the current CSV columns: diagnostic code, rated issue name, and max rating in integer percentage
- @amylai-nava will create a new task for implementing the max rating notice for all conditions on VA.gov
- ~@dfitchett @nanotone will create additional technical tickets that might be needed in addition to this one~
  - I added this to the AC in this ticket

**Comment by dfitchett** [comment]
# Max CFI Tech Spec

## Current state:

### max-cfi:

Currently, the max-ratings endpoint accepts an array of diagnostic codes and returns an array of `rating` items, one for
each diagnostic code for which a max rating is found. The `rating` items that are returned include the `diagnostic_code`
and the `max-rating` mapped to it.

The max rating is mapped from the `Max Ratings DC Lookup Table v0.1.csv` data file and stored in memory from
the time the application is started. This `csv` file contains a header row and is followed by data entries. Here are the
current contents:

```
Diagnostic Code,Rated Issue Name,Max Rating(%)
6260,Tinnitus,10
```

### vets-api:

Currently, vets-api makes the call to the `max-ratings` endpoint as described above. The response's `max-rating` is then
displayed to the user on the rated disabilities page of the 526EZ using the `ClaimFastTracking.MaxRatingAnnotator`
in `max_rating_annotator.rb`. 

Metrics are logged only for tinnitus, and it is hardcoded in vets-api. If any other diagnostic codes are of interest we will have to add them. 

## Proposed Changes:

### max-cfi:

Updates include the following:

* Update the `Max Ratings DC Lookup Table v0.1.csv` to include the other diagnostic codes, rated issue name, and
  max-rating
* Update validation to check the diagnostic codes in request

#### Considerations:

* This implementation does not allow dynamic changing of max rating values. Any changes will require updating the static
  data file and redeploying.

## Future Improvements:

* Make the ratings dynamic:
    * Would require moving from a static file to a database of sorts
* Creating an architecture to update the max rating
    * Any update endpoint should be secured
    * Would be good to have some kind of design that would allow a "review" of the rating change
        * if this was just some kind of input file, then a script could be made to update the entries in database and
          would be separate from the app

**Comment by dfitchett** [comment]
Engineering tickets:
* #2748 
* #2751
