### ISSUE TITLE
Re-enable partner teams to make their own deployments to `dev` and `qa`

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#2568]
**User Story**

As a partner team engineer, I want to be able to make quick deployments to 'dev' and `qa` environments, so that I can quickly test changes in the remote LHDI environment and not be dependent on a VRO engineer for help. 

**Acceptance Criteria**

1. CC and EE team can make deployments of their respective application(s), and only their respective applications, to `dev` and `qa` w/o intervention from a VRO engineer.
2. Testing requirements, like integration tests? 
2. A comms plan defined, agreed to, and communicated - ensure to include comms on when to use the dev environment vs/ when to use QA. Partner with Bianca on this. 

**Notes about work**
There are already GH workflows setup to allow this, but we need to make sure:
- They are functional in successfully deploying
- They reflect all the current applications managed by partner teams.

**Comment by chengjie8** [comment]
new wiki page has been created with easy to follow steps and screen shots for deployment to `dev` & `qa`

https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Deployment-Guide
