### ISSUE TITLE
Develop an incident response plan

### ISSUE THREAD

**Issue by paulsackley-nava** [department-of-veterans-affairs/abd-vro#2570]
**User Story**

As a VRO engineer, I want to have an incident response plan documented, so that we can respond quickly and efficiently, and minimize the impact of the incident.

**Acceptance Criteria**

1. There is a document that defines how we will do the following as a team: 

- [ ]  assign issues by severity level, triage, and get them prioritized 
- [ ] The plan defines how we will respond to each  incident by severity level 
- [ ] the plan defines the role and responsibilities of the "on call" person and makes a recommendation for how to alert partners when there are changes to this role 
- [ ] roles and responsibilities on the team are defined so everyone understands who is responsible for what when dealing with an issue
- [ ] meet with the team to go over the proposal, make edits, and update the final draft to the wiki with the audience being the internal team only. 

Not included: Drafting comms to partners, or documenting the process for partners, separate ticket below for this

**Notes about work**

**Comment by meganhicks** [comment]
Please know that we can specify "on call responsibilities" as part of the linked ticket

**Comment by lisac** [comment]
~draft: https://github.com/department-of-veterans-affairs/abd-vro/wiki/%5Bdraft%5D-Incident-Response~

update (5/22): https://github.com/department-of-veterans-affairs/abd-vro/wiki/Incident-Response

**Comment by meganhicks** [comment]
Hey Lisa,
I reviewed this and I like it. Here are some thoughts:
I think it looks great overall. Thank you!
I love the timeboxes, but does that mean the same thing as SLA? If not, should we spell it out? For example, what is our team's standard SLA for each step? Should these differ by severity level? I think forming these standards and communicating them could help set better expectations with partner teams and the person who is on call.
Do we have a benefits-vro-on-call channel? 
Also posting on the issue itself.

**Comment by CorySohrakoffUSDS** [comment]
Nice job! Looks like it covers everything I would want to know for an IRP. Also like that it explains the "whys" for each step and provides a clear definition of SEV levels.

**Comment by lisac** [comment]
update:
- added SLA windows to the [Overview](https://github.com/department-of-veterans-affairs/abd-vro/wiki/%5Bdraft%5D-Incident-Response#overview), with caveat that specifics including on-call coverage windows (eg 24/7? 9am-5pm ET on weekdays?) will be resolved as part of [#2959](https://github.com/department-of-veterans-affairs/abd-vro/issues/2959). 
- where did the SLA windows come from? I made them up unilaterally! please share recommendations.
- the document refers to slack channel `#benefits-vro-on-call`. this does not exist but should be straightforward to create. i thought we could create it upon group's approval.
- to compare revisions to the page: https://github.com/department-of-veterans-affairs/abd-vro/wiki/%5Bdraft%5D-Incident-Response/_history

**Comment by meganhicks** [comment]
@lisac looks great. It would be great to get more of the team members agreement on the SLAs async. Thank you for this. We should also demo this Monday.

**Comment by tejans24** [comment]
Looks good @lisac, nice work.

* Should 'bot post' incidents be setup through PagerDuty if that's the tool VRO is moving forward with?
* I like and agree with the Severity Levels and the 7 steps to resolve an incident.
* Assuming there will be an on-call guide that has references to help monitor/deploy/roll back as needed.

**Comment by lisac** [comment]
Thanks, @tejans24 . From your feedback, I've updated to the document to list PagerDuty as an example source of the bot posts. Please feel free to correct if I've misunderstood. 

I like the idea of an on-call guide as you describe. Perhaps something like a run book? Wrote up #3005 for prioritization.

**Comment by nelsestu** [comment]
@lisac , first off, I love the doc and think it does a great job capturing what we need for actioning issues as they arise in production.  I have a few suggestions/thoughts to consider for making additions, and please let me know if something is already there and I've just missed it.:

1. I know you've mentioned that Bianca is running with the partner team and other stakeholder communication plan, and it would be great to reference that here.  We'll want this document to provide an easy way of locating the communication plan as well.
2. Create a visual for the steps - I love the step by step approach that you've defined, and the only thing I would recommend we add is a visual aid, in the form of a decision tree or flowchart that can help guide responders through the process.  Especially during high-pressure situations, having a visual guide can make a big difference to those who are aiming to follow the process.
3. In step 5: logging the incident, I'd love to include a section of that step that offers links, screenshots or other artifacts that will help those who are actioning the response plan to locate examples, resources or even datadog queries of relevance to incident logging.  If you have any ideas about what these links and attachments might be, then please feel free to add, but the main addition that I am suggesting here is to include some sort of placeholder in step 5's description, that will remind incident responders to make these suggestions and additions as incidents arise.

**Comment by lisac** [comment]
@nelsestu nodding along to all of these suggestions - thank you! Working on edits for the first two, and a placeholder for the 3rd item.

**Comment by lisac** [comment]
updates to [(draft) Incident Response](https://github.com/department-of-veterans-affairs/abd-vro/wiki/%5Bdraft%5D-Incident-Response#incident-response):
1. added brief content re: communicating with partner team and stakeholders; and updated AC on https://github.com/department-of-veterans-affairs/abd-vro/issues/2959 to note at minimum adding to this page a link to materials produced by 2959
2. added a flowchart
3. added placeholder in step 5 re: how to log an incident; and updated AC on https://github.com/department-of-veterans-affairs/abd-vro/issues/3005 to include a how-to on logging an incident

**Comment by lisac** [comment]
While I expect we'll find more things to correct in coming weeks, I'm going to call what we have right now sufficient for closing this Issue. 

related work: #2959 and #3005

**Comment by lisac** [comment]
updated link: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Incident-Response (removed `Draft` from the page title, which affects the url)
