### ISSUE TITLE
Enable Certificate Monitoring in Datadog

### ISSUE THREAD

**Issue by nelsestu** [department-of-veterans-affairs/abd-vro#2576]
As a VRO DevOps user, I want to track various TLS certificates and their expiration date to ensure that they aren't becoming expired causing shared services to become unavailable.  We need to ensure that the VRO team is properly notified with plenty of warning when TLS certificates are expiring. 

I stumbled onto the following datadog dashboard, which inspired me to write this issue:
<img width="1826" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjFCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52303b0b50285f2cee5a987b12ff9e49d0e53d52/lhdi-certificate-monitoring.png" alt="lhdi-certificate-monitoring.png" />

**Acceptance Criteria**

1. Enable a subscription capability that allows interested VRO engineerings to subscribe for certificate expiration warnings, most likely a datadog monitor.
2. Provide the ability to check the list of certificates that we depend on, most likely a datadog dashboard.

**Not included in this work**

We may want to create distribution lists for various subjects.  This issue doesn't cover the concept of distribution lists or managing subscriptions through that type of centralize group. Right now we are only focused on enabling individuals to subscribe and the ability to review the supported list. 

**Notes about work**
- _(links to documentation, resources, code, etc that might inform the person doing the work)_

**Comment by msnwatson** [comment]
Venafi might be another way to do this, if Datadog does not allow us to get all the functionality we want.
