### ISSUE TITLE
Discovery: Integration tests during deployments to LHDI 

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#2579]
**User Story**

As a VRO engineer, I want the ability to run integration tests in the LHDI environment as a final step before completing a deployment, so that we ensure we are always maintaining deployments of tested and functional code.

**Acceptance Criteria**

1. Determine the possible solutions to achieve the capability to run integration tests during a deployment to LHDI environments (ideally w/ automatic rollback or avoiding routing traffic to a new failing deployment).
2. If we determine this is feasible create a follow up ticket and bring it to backlog refinement to get prioritized. 
3. If we determine this is not feasible we need to have a discussion with the team on why
4. Timebox: 5 days

**Notes about work**
Think of the following when doing the discovery work: 
- Technical feasibility risk (can our engineers build what we need with the time, skills, and tech available?)
- Value risk (will customers choose to use it?)
- Usability risk (can users figure out how to use it?)
- Mason's preliminary idea is to perform this through an extension of Helm. For inspo:  https://medium.com/@zelldon91/advanced-test-practices-for-helm-charts-587caeeb4cb

**Comment by msnwatson** [comment]
I have created a chain of tickets that will get us to the point of running integration tests during our LHDI deployments in the Zenhub dependencies for this ticket. 

One is currently a stub and depends on the decision and timeline for any ArgoCD migration.

**Comment by meganhicks** [comment]
Sent a slack about how to address next steps
