### ISSUE TITLE
Get notified of successful EP400 merges in slack

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#2602]
**User Story**

When an EP400 is successfully merged with an EP020, I want to get notified in Slack to help me monitor how the launch is going. This will be especially important at the beginning of the phased EP400 rollout, since there might only be a handful of eligible claims when the feature is enabled 1% or 5% of the time.

**Acceptance Criteria**
- Send a Slack notification to a new channel (`#benefits-ee-ep400`) when an EP400 claim is successfully merged with an EP020 
- Include the Claim ID and Date of Claim in the notification, similar to our Merge errors

**Comment by dfitchett** [comment]
* Current monitors can be found [here](https://lighthousedi.ddog-gov.com/monitors/manage?q=team%3Aemployee-experience%20tag%3Aee-ep-merge&order=desc).
* Current [Dashboard](https://lighthousedi.ddog-gov.com/dashboard/unv-vap-yeb/employee-experience-ep-merge-vro-platform?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1709066630556&to_ts=1709081030556&live=true) has new streams for log output separated by fail/success of merge jobs statements.
