### ISSUE TITLE
Datadog secrets in _datadog.tpl don't seem to match - causing EE Deployment failures 

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#2618]
**What:** Derek from the EE Team is attempting to deploy but his deployments are failing. The reason is the secret name variables are incorrect. We need to have consistent secrets propagated for datadog api keys across all LHDI envs along with keys matching `DATADOG_API_KEY`, `DATADOG_API_KEY_ID` so that Derek is able to deploy and continue making progress on EP400. 

**AC:** 
consistent secrets are propagated for datadog api keys across all LHDI envs along with keys matching `DATADOG_API_KEY`, `DATADOG_API_KEY_I

more details: propagated for datadog api keys across all LHDI envs along with keys matching `DATADOG_API_KEY`, `DATADOG_API_KEY_I

https://github.com/department-of-veterans-affairs/abd-vro/blob/develop/helm/_shared/named_templates/_datadog.tpl

**Comment by tejans24** [comment]
I added two new keys to secrets matching DATADOG_API_KEY, DATADOG_API_KEY_ID as temp fix in dev.

**Comment by nelsestu** [comment]
@tejans24 thanks for patching this up in the short term. I've applied the requested changes to helm in this PR https://github.com/department-of-veterans-affairs/abd-vro/pull/2619.  Failing the deployment when required secrets are missing seems like a reasonable feedback mechanism.  I guess this is more of a problem while [our automation for secret syncing](https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/2241) is broken. Do you think we should create an issue that tracks the core issue? Or is there an SOP that we are missing?

**Comment by nelsestu** [comment]
DD Secrets have been propogated to all LHDI environments and I just double checked the values again in each environment this morning
