### ISSUE TITLE
Temporarily update which special issue the EP Merge App removes when some steps fail

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#2642]
Typically, when certain steps within the merge process fails, we need to remove the `EMP` special issue. This ticket tracks work to temporarily change the special issue that we remove from `EMP` to `RRD` so that we can proceed with EP400 e2e testing in va.gov staging / VBMS UAT.

## Acceptance Criteria
- when a step fails in the merge process and the special issue needs to be removed from the EP400 contention, the EP Merge App removes the `RRD` special issue from the contention

## Notes about work
- At the moment, EP400 claims are unable to be established in va.gov staging with the `EMP` special issue since it's not a valid special issue identifier according to EVSS
- EVSS is planning to add `EMP` as a valid special issue and estimates that it will be available in PINT/staging on February 29th
- This ticket will enable us to proceed with EP400 e2e testing in the meantime

**Comment by dfitchett** [comment]
This implementation that was completed in the workaround allows us to change the special issue code via environment variable or just default to EMP. So when we do the deployment, we can just have VRO set an env variable for us to change it to RRD. This also renders #2647 unnecessary.
