### ISSUE TITLE
Resolve SecRel Vulnerability flagged in Camel Libraries

### ISSUE THREAD

**Issue by nelsestu** [department-of-veterans-affairs/abd-vro#2693]
@chengjie8 I added you as a co-assignee to this issue because you mentioned that you might have some bandwidth to help with this.  I've approached this from a couple different angles.

1. The latest camel version 4.4.0 is apparently patched for the vulnerability that SecRel is flagging.  I initially was trying to apply the upgrade, but ultimately I got stuck trying to carry through with the camel dependency upgrade.  From everything I could see, I felt like things should have been working, but the app project was still not starting up as expected, and I didn't exactly know where to go.  You may have better luck with the upgrade, so I would encourage you to try that if you have some availability to look at this.

2. The other route I've been running with since Friday 3/1/2024, is the removal of camel from VRO.  The first part of removing camel was to review all the places it is referenced and create a list of the impacted functions.  Having done some of that analysis, I am now comfortable knowing that we have no production use cases for camel at this time. With that in mind, I've been working towards a pull request that drops all camel references and I anticipate that I'll have something to test out in a fresh SecRel run by late this morning 3/4/2024.  The effort to remove camel also touches on #2184, migrating domain-rrd to a separate repository.  domain-rrd is a significant chunk of the codebase that is still using camel, so the PR i've been working on, starts with the work required for #2184.

**Comment by msnwatson** [comment]
Resolved by https://github.com/department-of-veterans-affairs/abd-vro/pull/2703
