### ISSUE TITLE
Add ActorUserId field to RDS database

### ISSUE THREAD

**Issue by chengjie8** [department-of-veterans-affairs/abd-vro#2724]
Tyler and Yurena have requested that the `ActorUserId` field be added to our RDS database. This field will enable them to track who has made updates to the claims.

Note: the contention deleted event does not include this field. Therefore, we need to utilize the `TargetEvents` annotation to exclude the deleted event in order to avoid exceptions. For further details, refer to the BieMessagePayload documentation.

AC:

- `ActorUserId` field is visible in datadog log
- `ActorUserId` field is stored in RDS database
- test that the messages are not causing bugs in the RabbitMQ container

Notes:
An extension to existing  tests, with contention delete operation being the more complex element to test.
We don't have a mechanism to emulate events/types in LHDI envs. It's based on randomness of events being generated by BIE

Task List:

- [x] 1. Create a flyway migration - this will require decisions about data that has already been written in VRO
- [x] 2. Extend datamodel classes - Ensuring that we populate the attribute during data processing
- [x] 3. Expand Tests to include the new column
- [x] 4. Address Contention Deletes using TargetEvents - this could complicate significantly- if this needs to be pulled out talk to Megan. 
- [ ] Deploy to all environments but prod

**Comment by tejans24** [comment]
Pushing these changes to dev and testing out the functionality - since it's been unblocked by work by @agile-josiah with BIE team.

**Comment by meganhicks** [comment]
Dependency: We have to lean on BIE. Megan to talk to Darrel.

**Comment by meganhicks** [comment]
Break out BIE Argo into following Sprint.

**Comment by meganhicks** [comment]
I've confirmed with Darrel that this shouldn't pose a significant challenge for his team. He mentioned that they typically respond within 24-48 hours. Given this, let's prioritize it and address it promptly to allow for collaboration with their team during testing. If assistance is needed, he suggests reaching out on Slack at bip-support-ext-vro. Feel free to tag Darrell Neel for leadership support to expedite or escalate any issues.
