### ISSUE TITLE
Change RRD Doctype to Automated Review Summary Document

### ISSUE THREAD

**Issue by emilytheis** [department-of-veterans-affairs/abd-vro#273]
**User Story**

As an RVSR, I want the RRD evidence summary to be doctype Automated Review Summary Document instead of Medical Treatment Record-Government Facility.

**Acceptance Criteria**

1. the doctype is changed to Automated Review Summary Documented and tested in va.gov staging and VBMS UAT
2. the doctype is changed in production and monitored to ensure the documents are appearing correctly in VBMS

**Notes about work**
In this slack thread, Michael Harlow says "EVSS accepts doc uploads for Automated Review Summary Document because it is listed as "typeLabel": "L1489" in the EVSS getDocumentTypes" - https://dsva.slack.com/archives/C1VBAHWQL/p1662659771674139

However, in the past, RRD had issues when changing the doctype and receiving errors from EVSS, which is why testing in staging and monitoring in production is part of this acceptance criteria. 

More chatter about this initiative in this slack thread https://dsva.slack.com/archives/C01Q7979Z7D/p1662656937759389

**Comment by yoomlam** [comment]
We'll likely need to add the docType to https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/evss_claim_document.rb#L25

There's an existing entry:
```
  '1489' => 'Hypertension Rapid Ready For Decision Summary PDF'
```
but that's a slightly different code and description.

Other threads:
- https://dsva.slack.com/archives/C01BVF2A3V0/p1661445372704119?thread_ts=1660849294.085899&cid=C01BVF2A3V0
-
