### ISSUE TITLE
General Questions 

### ISSUE THREAD

**Issue by bianca-rivera** [department-of-veterans-affairs/abd-vro#2730]
As a partner team it is important that I understand the process for submitting a general question so that I know where to go and how long to anticipate a response. 

AC: 

- [ ] Review definitions in the Teaming Agreement Slack channel and assess the necessity of updating the VRO support channel definition: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697222300764/071b9570f3bf4a8a678a547a8d3ccd9410e977df?sender=u739128c1dfc0f4a9293a2519
- [ ]  If updates are necessary, make the revisions and share them to the team.
- [ ]  Develop documentation within the Partner Teams section of the wiki titled "How to make get help from VRO" and outline the procedure for partner teams to submit general inquiries.
- [ ]  Present a demonstration during the Sprint Review.

Resources
--
[Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705504070694/54b4ebecd924afc4261c4292db855c4df49b29df?wid=0-1710780877092)

**Comment by meganhicks** [comment]
@bianca-rivera What is the objective of sharing? Is it to foster consensus around a new process? What are the acceptance criteria (AC) in this context

**Comment by bianca-rivera** [comment]
To pair with @nelsestu on new feature request and deployment request workflow improvements to prototype for next sprint

**Comment by bianca-rivera** [comment]
Pushed back due to urgency of EE retro timing given schedule conflicts
