### ISSUE TITLE
Eliminate the distinction between dev_* and other images

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#2759]
**User Story**

As a VRO engineer, I want to avoid publishing different versions of images for dev/qa and all other environments, so that testing is performed on the same images across all environments and so that deployment processes can be simplified.

**Acceptance Criteria**

1. For a deployment, the same image is used across all LHDI environments
2. All refs to the dev_* prefixing is removed from both the code and the wiki
3. GH workflows are modified to publish (no prefix) images on merge to `develop` along with attempting Secrel image signing.

**Comment by meganhicks** [comment]
@msnwatson can you demo this to me? I trust you. I just want to learn. Free this afternoon if you want to set up 15min.

**Comment by msnwatson** [comment]
<img width="1392" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1VtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03e142f82a43631b3af3ad213bc4987684fcecca/image.png" alt="image.png" />

This shows a pod from the dev environment with the container demonstrating the image is not prefixed with dev_*
