### ISSUE TITLE
Update and clean up the VRO Diagram 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2770]
#### User Story
As a member of the VRO Team or a customer of the VRO Platform, I require dependable documentation to enable efficient self-service and rapid issue resolution

#### Why
The VRO wiki currently contains many pages that are out-of-date or incomplete in terms of providing sufficient detail and guidance to VRO teammates to maintain and expand platform capabilities, as well as to partner teams to understand what VRO offers them and implement those solutions in service of their applications.

#### AC:
Where you make the diagram use whatever tool you want 
Diagram should show: All existing services, excluding the ones we plan on removing. Include all the end points, highlight where we have partners 
audience: everyone 

<img width="519" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTd0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6ae197d094c35fed20da0336a4261ce6627d9c2/image.png" alt="image.png" />

**Comment by meganhicks** [comment]
break out dependency map

**Comment by lisac** [comment]
Created a draft, working on getting initial feedback.

Draft:
https://github.com/department-of-veterans-affairs/abd-vro/wiki/%5Bdraft%5D-VRO-Architecture-Diagram

To replace: 
https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Architecture-Diagram

Diagrams implemented in draw.io, to be uploaded as part of completing this Issue.

**Comment by lisac** [comment]
Updated the contents of the VRO Architecture Diagram wiki page with what was drafted.
