### ISSUE TITLE
Make EP Merge Metrics log asynchronously

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#2783]
## Summary
Current implementation uses a synchronous rest call to send metrics to datadog. This does not have any adverse effect, but it would be better to make the rest call a 'fire-and-forget' call by using the asynchronous rest client with asyncio support.

## Acceptance Criteria
- [x] Inside `metric_logger.py` the ApiClient is replaced with [AsyncApiClient](https://github.com/DataDog/datadog-api-client-python?tab=readme-ov-file#asyncio-support)

**Comment by dfitchett** [comment]
Not gonna do. It is not worth the effort to modify unit and integration tests to use this.
