### ISSUE TITLE
Epic: Enable EP Merge for single contention new claims

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#2785]
The [EP400 Merge MVP](https://github.com/department-of-veterans-affairs/abd-vro/milestone/32?closed=1) was narrowly scoped to work on claims for increase (with only one condition). 

As a next step, we'd like to expand this functionality to _new claims_ (but still with one condition).

## **User Story**

As a VSR, I want single contention new EP400 claims to be combined with the Veteran's existing pending claim, so that I do not have to manually combine them.

## **Acceptance Criteria**
(Pulled from: https://github.com/department-of-veterans-affairs/abd-vro/issues/2052)
1. If the claim meets all eligibility criteria, send it to VRO EP Merge and https://github.com/department-of-veterans-affairs/abd-vro/issues/2053
2. If the claim does not meet all eligibility criteria, the no action is taken and the claim will be processed normally
3. ~~[TBD] -- launch plan? (all at once? phased rollout?)~~ 🚀 [Launch Plan here](https://docs.google.com/document/d/1xqdjEAuQ0aOIvHOj8szjpgB7jDlSl5kRX5zT9ctPR1Y/edit?usp=sharing) 🚀
4. [TBD] -- comms strategy? (who needs to know? are there SME's we should consult?)
5. ~~[TBD] -- testing strategy?~~ See launch plan above

## **Eligibility Criteria**
(Pulled from: https://github.com/department-of-veterans-affairs/abd-vro/issues/2052)
- The EP400 is a single contention _**new claim**_
- The contention on the EP400 has a contention classification
- The Veteran only has 1 pending rating claim
_(relevant rating EPs are: 010, 110, 020, 030, and 040's + any incremental EPs like 031s and 041s)_
- The pending claim is an EP010, 110, or 020

## **Not included in this work**
We're not working on any claim here with multiple conditions. 
That is covered here: https://github.com/department-of-veterans-affairs/abd-vro/issues/3001

## **Notes about work**
- 

**Links**
- [Milestone: EP400 Merge MVP](https://github.com/department-of-veterans-affairs/abd-vro/milestone/32?closed=1)
- [Milestone: EP400 Merge Post-MVP](https://github.com/department-of-veterans-affairs/abd-vro/milestone/40)

## Tasks
```[tasklist]
### Linked Issues
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/3035
- [x] Draft launch plan for EP merge post-MVP updates (new/multiple contention claims)
```

**Comment by dfitchett** [comment]
Couple of notes about this work: 
* EP Merge should be able to handle contentions with NEW status without any changes. In fact we already have a [unit test](https://github.com/department-of-veterans-affairs/abd-vro/blob/6d22e47bec16146db6b5544ed48688d179e8e4fc/domain-ee/ee-ep-merge-app/tests/service/test_ep_merge_process.py#L1004) for EP400 that covers a claim with a single new contention.
* `vets-api`: 
  * Contention classification already supports NEW contentions. The eligibility to send requests to EP Merge via `prepare_for_ep_merge!` needs be updated to remove the `increase_only?` criteria. It would also be beneficial to provide metrics on the type (new or CFI) of contentions submitted to EP Merge.

**Comment by dfitchett** [comment]
@nanotone we should put this behind a feature flag so that we can test in staging first.
