### ISSUE TITLE
Create documentation for K8s liveness and Readiness

### ISSUE THREAD

**Issue by ponny-m** [department-of-veterans-affairs/abd-vro#2792]
As a VRO engineer, I want to document the existing Kubernetes liveness and readiness probes for all VRO microservices, so that the team can understand, maintain, and effectively leverage these probes to ensure service reliability and efficiency.

**Acceptance Criteria**
1. The documentation must provide a comprehensive overview of the liveness and readiness probes, including their purposes, differences, and importance in maintaining the health and availability of our microservices.
2. Include detailed descriptions of each probe's configuration within our Kubernetes deployments, specifying the endpoints used, expected responses, and configuration parameters such as initialDelaySeconds, periodSeconds, timeoutSeconds, and failureThreshold. This should also include example YAML snippets for clarity.

**Comment by ponny-m** [comment]
Here is the [documentation](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Kubernetes-Liveness-and-Readiness-Probes) for review

**Comment by meganhicks** [comment]
@Ponnia-M This looks great. Moving to done.
