### ISSUE TITLE
Top Use Cases: Deployment Requests - Prototype, Launch, and Comms

### ISSUE THREAD

**Issue by bianca-rivera** [department-of-veterans-affairs/abd-vro#2795]
Description
--
Based on findings from #2672, brainstorm and test ideas for improvements that can be prototyped and tested within one sprint. Pairing with @nelsestu to ensure we develop a new workflow for deployment request that ensures we are collecting the information needed from our partner teams.

Why
--
To ensure recommendations made are feasible for implementation and mitigate existing partner team pain points and gaps highlighted in research phase

AC
--
Original AC is being split, so that we can accept the parts that are completed and continue with the remaining effort in Sprint B. 
* [x] create discrete paths for partner team deployment requests vs. new feature requests
design and document the new scheduled deployment process
* [x] create slack workflow for scheduled deployment
* [x] create and update documentation of new process and SLAs [#2976](https://github.com/department-of-veterans-affairs/abd-vro/issues/2976)
* [x] Set up 24-hour reminder for Tuesday morning at the beginning of the sprint on #benefits-vro-support

Notes
--
This ticket is referencing deployment requests partner teams make to higher-level environments.

Resources
--
[Mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705504070694/54b4ebecd924afc4261c4292db855c4df49b29df?wid=0-1710780877092)
[GitHub & Slack integration features](https://github.com/integrations/slack?tab=readme-ov-file#deployment-notifications)

**Comment by BerniXiongA6** [comment]
Hi @bianca-rivera -- looks like you've switched sprints for this work, can I remove this ticket from Sprint Z epic? cc: @meganhicks

**Comment by bianca-rivera** [comment]
@BerniXiongA6 @meganhicks I was planning on discussing this later today during our design sync: due to the other tickets I'm working on with finalizing outstanding items for the incident report workflow and the gap we have regarding how we want to use the deployment request workflow given our latest iteration of the deployment policy, I doubt we will have enough time to build, test internally, test with partner teams, develop comms, and launch before the end of the sprint.

Realize I made an executive decision, let me know if we want to have a process for making changes to tickets assigned to the sprint
