### ISSUE TITLE
Max CFI: Block max-ratings calls for conditions other than tinnitus

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#2804]
## User Story
As a user of the vets-api, I want a feature flag that will block all calls to the Max CFI API for all diagnostic codes besides tinnitus.

## Acceptance Criteria
- [x] new feature toggle is added to vets api
- [x] current feature toggle `disability_526_maximum_rating_api` for making requests to VRO can be removed 
- [x] unit test

## Notes about work
- currently, the `disability_526_maximum_rating_api` feature toggle enables sending disability diagnostic codes to VRO Max CFI API to get the corresponding maximum ratings

**Comment by amylai-va** [comment]
@dfitchett how are you thinking we would manage the new feature toggle with the current one?

**Comment by dfitchett** [comment]
So I was thinking that we would have a feature that toggles sending requests for all conditions, but only if the `disability_526_maximum_rating_api` feature toggle is enabled (which it is in all environments already). 

So possible scenarios are:
* new toggle enabled --> requests for max rating send for all conditions
* new toggle disabled (by default) --> requests for max rating only send for tinnitus

**Comment by dfitchett** [comment]
> @dfitchett how are you thinking we would manage the new feature toggle with the current one?

So I was thinking that we remove the old toggle and add a feature that toggles sending requests for all conditions otherwise only for tinnitus.

So possible scenarios are:
* new toggle enabled --> requests for max rating send for all conditions
* new toggle disabled (by default) --> requests for max rating only send for tinnitus
