### ISSUE TITLE
Discovery: Ensure graceful transition when k8s pods are evicted 

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#2816]
**User Story**

As a VRO engineer, I want to understand how to more gracefully handle k8s pod evictions, so that services do not experience downtime during cluster maintenance actions or between deployments.

**Acceptance Criteria**
Answers to questions:
1. If possible to determine, what was the root cause of the small downtime EP Merge app experienced on 04/01? 
2. What conditions can lead to service downtime in the future when transitioning between pods for a service? 
3. How can we correct this from happening? Or ideas for potential solutions. 
4. What monitoring and alerting should we have in place if we cannot immediately correct it?
5. Update documentation: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Incident-Reports 

**Not included in this work**

Execution of any potential solution identified
LHDI conversations, this should be on VRO to solve 

**Notes about work**
- verify version of Kubernetes running in LHDI 
- When cluster maintenance actions are taken by LHDI, all of our pods can be transitioned to new versions within the span of half an hour. Mason's hypothesis is that there is some connections or RabbitMQ messages not being gracefully handled when the pod received an eviction notice from the cluster or that readiness checks might need to be reconfigured so pods really are able to handle a request as soon as they are giving ready status.
- The current monitoring we have around unavailable pods is not sufficient to capture when this is happening necessarily. during pod eviction during LHDI maintenance, we have a spike in unavailable pods as new pods are spun up. We'll have to think through how to monitor this downtime specifically.

**Comment by msnwatson** [comment]
1. It's been a bit too long to determine precisely the root cause issue of the EP Merge app failing during pod transitions, but it is most likely related to issue with graceful shutdown.
2. Any forced pod shutdown prior to completion of any in progress processing of requests can cause similar failures in the future.
3. The path forward for preventing this from happening in the future is to instrument our services with metrics which will allow us to understand the distribution of processing times for requests and messages. Then, we can set the graceful shutdown period for our k8s deployments to be respected during pod transitions.
4. Monitoring will come out of the work to complete the execution of the solution. Alerting can be done on these new metrics if desired, but I'm not sure if it will be necessary.

**Comment by meganhicks** [comment]
Thanks @msnwatson can you own sharing this finding with the EE team on the support channel?
