### ISSUE TITLE
Remove unused code - svc-lighthouse-api

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2818]
As a VRO platform, we aim to remove unused code from svc-lighthouse-api to enhance our performance and simplify maintenance.

AC: 

All unused code in svc-lighthouse-api is removed

**Comment by meganhicks** [comment]
@dfitchett tagging you so you can see your request and track it.

**Comment by msnwatson** [comment]
https://github.com/department-of-veterans-affairs/abd-vro-svc-lighthouse-api repo created and linked on the homepage of the wiki to hold this old code since it is substantial and i don't want to just throw the work away.

**Comment by msnwatson** [comment]
https://github.com/department-of-veterans-affairs/abd-vro/pull/2887
