### ISSUE TITLE
Discovery for flickering integration tests 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2824]
As a member of the VRO development team, I want to ensure that xample-domain and svc-bie-kafka integration tests provide consistent and reliable results, so that we can have confidence in the quality of our software releases. We know that today they do not. We think this could be reporting incorrectly or it may not be working. This ticket is to only do the discovery work for the root cause of the problem. 

AC: 

- Identify the root cause behind the occurrence of the issue. Distinguish whether it's a genuine failure or an error logged erroneously.
- Once the cause is determined, document the findings within this ticket and update the linked ticket with the proposed solution.
- Present the updated ticket during the upcoming backlog refinement session for prioritization.
- timebox to 2 days 

Notes: 
logs are bundled in github. They cannot be ran locally and must be run in github actions.
pair on this, due to the potential complexity 
ensure that the ticket to resolve this issue has an AC mentioning:
"As a VRO engineer, I want to enforce testing of platform code at the point of merging code in any given environment, so that we ensure the reliability of the platform and have a safeguard in place that builds our confidence to enable more frequent, flexible, autonomous deployments by partner teams." - this statement comes from a backlog refinement session where we removed #1962 in favor of adding this AC to the solution of this discovery work.

**Comment by agile-josiah** [comment]
<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGM4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8682e2ce9e36e957570bf2ae8a159d6f91640fe9/Screenshot%202024-04-05%20at%201.02.25%20PM.png" alt="Screenshot 2024-04-05 at 1.02.25 PM.png" />

The following screenshot shows how the connection to rabbitmq initially fails, however the connection succeeds after retrying and the tests are running.

**Comment by agile-josiah** [comment]
- name: "Check for errors in container logs"
        run: |
          if docker logs vro_xample-workflows_1 | grep 'ERROR'; then
            echo "Unexpected ERROR logs in xample-workflows container"
            exit 11
          fi
          if docker logs vro_svc-xample-j_1 | grep 'ERROR\|WARN' | grep -v 'Simulated error'; then
            echo "Unexpected ERROR logs in svc-xample-j container"
            exit 12
          fi

**Comment by agile-josiah** [comment]
The check above in the xample-integration-test.yml is where the false failure is raised. I think having a different or additional check would allow for more fault tolerance if we can't guarantee the rabbitmq container is ready and the rabbitmq service is started accepting connections.

**Comment by chengjie8** [comment]
based on the log and screen shot from Josiah, xample-workflow integration test has timing issue with rabbitmq. It tries to connect to rabbitmq broker before it becomes available.
Solution:
Implement mechanism to check and make sure rabbitmq is available 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXRtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b919e8399e891b29367dd82a684c88e419db086/image.png" alt="image.png" />
Also we have this exception when trying to convert string into number when the string does not contain a numeric value
