### ISSUE TITLE
Discovery on DORA metrics 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2825]
As a member of the VRO development team, I want to integrate DORA (DevOps Research and Assessment) metrics
so that we can measure and improve our software delivery and operational performance. This ticket is just to kick off some basic discovery on what we are able to do, as we do not have a defined way to set this up yet. 

AC: 

- [x] Validate that the Epic linked to this ticket is in sync with your approach on the implementation of the DORA (DevOps Research and Assessment) MVP as outlined.
- [x] Outline the necessary steps to initiate the implementation of DORA metrics
- [x] Schedule a team meeting to present the identified steps and gather feedback for further refinement.
- [x] Timebox the discovery process to a maximum of 3 days, focusing on uncovering essential requirements and considerations before proceeding with implementation.

**Comment by meganhicks** [comment]
1. Can you post the link?

**Comment by tejans24** [comment]
https://coa-solutions.notion.site/DORA-Discovery-Spec-291bb45ff9b0444d81032511cd304717

**Comment by meganhicks** [comment]
I am closing this, although we still need to test with @nelsestu on BIP the technical feasibility. Meeting to be set up by Erik by 5/3/24. 
CC: @BerniXiongA6
