### ISSUE TITLE
 Implement RBAC for `svc-bie-kafka` in our in QA environment

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2847]
Why: Kafka will not be able to connect and receive data. 

**User Story**
As a VRO engineer, I want to update Kafka to use RBAC for authentication and authorization so that we remain compliant. The scope of this ticket is our `dev`, `qa`, and `sandbox` environments. Prod will be handled later, in a separate ticket [#2560].

**Acceptance Criteria**
* Kafka is using RBAC
* Late addition - possibly a new issue - We should ensure that our docs on bie-kafka service have been updated with the RBAC details, as well as any [URL changes](https://github.com/department-of-veterans-affairs/abd-vro/pull/2624#discussion_r1517929249) that we should reflect in the docs.

**Notes about work**
* See documentation here: https://github.com/department-of-veterans-affairs/bip-tooling-confluent/wiki/Streaming-app-authentication-and-authorization-with-Confluent-RBAC
* POCs are Milton Garcia and Darrell Neel
* Slack thread here: https://dsva.slack.com/archives/C04U8GESRT7/p1706727018289089

**Comment by ponny-m** [comment]
Below is a screenshot of a snippet confirming successful connection (Kafka topic messages) in QA environment.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da809cbaddd6356d0fd5b88473656722fbd5a1b1/Screenshot%202024-04-25%20at%201.13.37%E2%80%AFPM.png" alt="Screenshot 2024-04-25 at 1.13.37 PM.png" />
