### ISSUE TITLE
Partner Team Pull Requests

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2856]
As a partner team it is important that I understand the process for submitting a pull request so that I know where to go and how long to anticipate a response. 

AC: 

- [ ] Review definitions in the Teaming Agreement of Slack channels and determine where pull requests should be submitted. https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697222300764/071b9570f3bf4a8a678a547a8d3ccd9410e977df?sender=u739128c1dfc0f4a9293a2519
- [ ]  If updates are necessary, make the revisions and share them to the team.
- [ ]  Develop documentation within the Partner Teams section of the wiki titled "How to make get help from VRO" and outline the procedure for partner teams to submit a pull requests, as well as the SLA
- [ ]  Present a demonstration during the Sprint Review.

Resources
--
[Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705504070694/54b4ebecd924afc4261c4292db855c4df49b29df?wid=0-1710780877092)

**Comment by bianca-rivera** [comment]
content in this ticket consolidated into #2859
