### ISSUE TITLE
[Request]: Production Release for Contention Classification

### ISSUE THREAD

**Issue by lukey-luke** [department-of-veterans-affairs/abd-vro#2861]
### Requesting Team

Contention Classification

### Related product/initiative

Monitoring

### Problem/Need

`develop` branch needs to be deployed to production environment

### Why?

Develop contains new logging statements that are needed for updates to CC datadog dashboard.
Specifically, response time is logged [HERE](https://github.com/department-of-veterans-affairs/abd-vro/blob/develop/domain-cc/cc-app/src/python_src/api.py#L50), which can be used to create a metric from the log.

### Acceptance criteria

1. `develop` is deployed to production
2. CC team is notified in the vro support slack

### Priority

medium

**Comment by meganhicks** [comment]
@lukey-luke  I will bring this up with the team this morning.

**Comment by nelsestu** [comment]
this production deployment was done as part of resolving the outage described in #verified as functional [Investigate why CC Application Went Down](https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/2883). Several days later we verified that this was also Luke's understanding: 
<img width="1818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJ2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32c93ce2cc0bf3a8e0d9a2a0af05319bc02357b6/image.png" alt="image.png" />
