### ISSUE TITLE
Update BIP certs for their QA and Dev envs

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#2881]
BIP team has sent updated .crt and .pem files for VRO to use for their `dev` and `qa` envs. 

**Steps to resolve:**
* Verify with VRO env maps to their dev and qa envs
* Update Kubernetes secrets with files sent by BIP team for each env that needs updates (see mapped envs for BIP dev and test)
* Regenerate truststore, keystore and password for each env using svc-bip-api-certgen.sh script
* Deploy BIP service with the updated values in each env
* Verify BIP connection works
* Pair with Eric or Cheng if assistance or clarity is needed

**AC:**
* BIP certs in all env are up to date
* BIP service in the envs mentioned is fully functional
* Documentation updated

**Comment by meganhicks** [comment]
Megan to set up a call, as the source of the certs appears to be changing and we want to verify.

**Comment by meganhicks** [comment]
confirmed as not needed.
<img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cbe15fa4275e3b922df95e8f81ebe72b4e496ae/image.png" alt="image.png" />
