### ISSUE TITLE
Investigate why CC Application Went Down

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2883]
What: The CC Team reported the following at 10am Monday 4/22:
Good morning, is somebody available to help us look at the CC service? The last logs that show up from friday are for our application shutting down: https://lighthousedi.ddog-gov.com/logs?query=service%3Avro-cc-app%20cluster_name%3Aldx-pr[…]ream&from_ts=1713189911799&to_ts=1713794711799&live=true. There was no traffic or logs over the weekend and there are no corresponding logs in the front end logs, but double checked that the 526 submission logs are still seeing activity.  Thanks for the help with this. 

Why: We need to find out why the CC service was interrupted and fix it 

AC: 

Root cause is understood 
Work to correct it is done as part of this ticket if it is small. If not a subsequent ticket is created. 
The ticket will define how we can get alerted for this moving forward so we can be proactive partners  
Document why on wiki

**Comment by tejans24** [comment]
https://dsva.slack.com/archives/C01Q7979Z7D/p1715876917163889
