### ISSUE TITLE
Make RDS more queryable

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2890]

**Comment by meganhicks** [comment]
@nelsestu feel free to add your notes. Placeholder

**Comment by msnwatson** [comment]
@meganhicks should we add something here to reflect our conversations with LHDI?

**Comment by meganhicks** [comment]
great call out. I have added my message to the team and will close this: 

Sent 6.6.23

Hi CC and EE Teams, 
[@Yurena](https://dsva.slack.com/team/U04L7TKUJQL)
 
[@Mack](https://dsva.slack.com/team/U071H7JSZNV)
 
[@Derek](https://dsva.slack.com/team/U05BLGTQJ03)
 
[@yang (he/him)](https://dsva.slack.com/team/UP84XNUBY)
 
[@Luke Short](https://dsva.slack.com/team/U04NXF130DD)
 
[@Tyler Spangler](https://dsva.slack.com/team/U05QQH3EHSA)

The VRO Team wanted to follow up on a product offering we have been pursuing with LHDI. Specifically, can we make RDS more queryable by offering a tool or access to our AWS console? The CC Team has mentioned that the current queuing tool we offer (RabbitMQ) is insufficient for their use case. They would like to easily review historical data, whereas RabbitMQ is better suited for real-time data processing. Therefore, a different solution is needed.
Additionally, the EE Team mentioned that making RDS more queryable would allow them to access information regarding the number and status of merged jobs directly for the EPMerge App.
We reached out for guidance on how VRO could enable this new offering with  LHDI's support since they own the platform and tools that VRO supports. Here are the key points we received:
Security Concerns: For several security reasons, including maintaining our ATO, we cannot allow any partner teams to directly access our DB. This is a requirement from LHDI. They ultimately own our DB and they only want their direct tenants using it (VRO) Specifically, we cannot give access to our customers to take action on our K8 clusters or namespace. This means directly querying the DB is not possible.
Lack of Tool Support: LHDI offers no tool to fill this need. They mentioned that providing such a service, including managing permissions and access, would be too much maintenance. They strive to offer solutions that benefit all teams, and this would be too heavy a lift for just one team.
Custom Solution: While LHDI suggested we could build and manage a custom solution ourselves, we lack the capacity to support such an offering. Developing custom query templates, managing permissions, maintenance, and security of the tool could be a full-time job for a new team.
Security Protocols: To offer any such solution, we would need to go through extensive security protocols, including a new PTA, PIA, and review with our privacy assessor. Additionally, we would need to work with an internal security team at the VA called WASA, which would run scans on the application to ensure its security.
Given these challenges, our hands are tied, and we feel the only feasible solution is to continue providing one-off customer queries as we have been doing.
To pursue a more permanent solution, we would need the help of the enablement team to push LHDI to prioritize and accept a feature like this, as LHDI mentioned it is not in their current plans. I am happy to discuss this further one on one, in a partner meeting, and with the Enablement Team.
