### ISSUE TITLE
Document Incident Timeline of April 20th 2024 CC Application Outage 

### ISSUE THREAD

**Issue by nelsestu** [department-of-veterans-affairs/abd-vro#2903]
This is a follow up ticket so I don't forget to document the CC application outage over the weekend, which was finally resolved Monday 4/22 after it came to our attention.  Erik acknowledges that he was "on call" during the event, however, some personal life emergencies had pulled his attention elsewhere.

We've been documented partner team incidents here: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Incident-Reports

What: The CC Team reported the following at 10am Monday 4/22:
Good morning, is somebody available to help us look at the CC service? The last logs that show up from friday are for our application shutting down: https://lighthousedi.ddog-gov.com/logs?query=service%3Avro-cc-app%20cluster_name%3Aldx-pr[…]ream&from_ts=1713189911799&to_ts=1713794711799&live=true. There was no traffic or logs over the weekend and there are no corresponding logs in the front end logs, but double checked that the 526 submission logs are still seeing activity.  Thanks for the help with this. 

Why: We need to find out why the CC service was interrupted and fix it 

AC: 

Root cause is understood
Work to correct it is done as part of this ticket if it is small. If not a subsequent ticket is created. 
The ticket will define how we can get alerted for this moving forward so we can be proactive partners  
Document why on wiki

**Comment by meganhicks** [comment]
@nelsestu - root cause is not needed for this. We are just looking for a timeline and description of the incident. After this is done, we have the follow up ticked in this sprint to investigate root cause and that person can update the full details.

**Comment by nelsestu** [comment]
Agreed, I had changed the title to Document Timeline, but that didn't stick, so i've reapplied it.
