### ISSUE TITLE
Implement RBAC for `svc-bie-kafka` in our pre-prod environment

### ISSUE THREAD

**Issue by ponny-m** [department-of-veterans-affairs/abd-vro#2916]
**User Story**
As a VRO engineer, I want to update Kafka to use RBAC for authentication and authorization so that we remain compliant. The scope of this ticket is our **pre-prod** environment. `dev`, `qa`, and `sandbox` were covered in #2530.

**Acceptance Criteria**
* Kafka is using RBAC

**Notes about work**
* See documentation here: https://github.com/department-of-veterans-affairs/bip-tooling-confluent/wiki/Streaming-app-authentication-and-authorization-with-Confluent-RBAC
* POCs are Milton Garcia and Darrell Neel
* Slack thread here: https://dsva.slack.com/archives/C04U8GESRT7/p1706727018289089

**Comment by ponny-m** [comment]
Due to Secrel issues, deployment to Pre-prod is halted.

**Comment by Ponnia-M** [comment]
Due to Secrel issues, deployment to Pre-prod is halted.
