### ISSUE TITLE
Application Monitoring for BIP

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2932]
As a platform maintenance team member responsible for supporting partner teams,
I want to supplement customized monitoring for EMerge Application
so that we have visibility into connectivity issues with BIP.

## Acceptance Criteria:

- [x] A monitor has been created in Datadog that identifies when the application goes down or loses connectivity to BIP
- [x] The recommended monitoring changes have been integrated into the existing dashboard (to streamline platform management)
- [x] Implemented changes have been documented on the VRO team wiki 
- [x] Custom metrics for request latency are created to Datadog 

## What you need to know

I spoke to Derek on the EE Team about this and he mentioned that maybe we could use datadogs synthetic tests to test connectivity throughout the day. 

Out of Scope:
Setting up alerting, as this user story focuses on establishing monitoring capabilities.

## Implementation / Developer Steps (to be filled out by ticket assignee)

**Comment by lisac** [comment]
a preview of the dashboard using mock data:
![Screenshot 2024-06-10 at 7 29 56 PM](https://github.com/department-of-veterans-affairs/abd-vro/assets/943046/8940d37b-6f00-4961-b4ea-44656d9cda16)

**Comment by meganhicks** [comment]
This looks so exciting!

**Comment by lisac** [comment]
status: changes to application code have been approved, however not yet deployed to production. No anticipated blockers for deployment.
Updates to monitors, dashboards, and team wiki: complete.

**Comment by lisac** [comment]
deployed on 6/20.
