### ISSUE TITLE
Create VRO Datadog metrics for successful and failed merge jobs

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#2951]
**User Story**

As a member of the EE team, I want to see a measure of successful and failed merge jobs at the end of the EP Merge workflow, so that I can have a more direct and accurate way to report on EP Merge stats.

**Acceptance Criteria**

1. Create VRO Datadog metric for successful merge jobs
2. Create VRO Datadog metric for failed merge jobs
3. Add these to a VRO Datadog dashboard

**Comment by dfitchett** [comment]
Already completed.
