### ISSUE TITLE
On call Documentation and Deployment Policy 

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#2976]
**What**

Create standard documentation on the team's agreed to deployment policy and communicate it to the partner teams

**Why**
The team should have this documented and does not AND we want to avoid deployment image signatures expiring causing partner teams issues

**Acceptance Criteria**

The documentation should detail responsibilities for the following:

5. Deployments

1. Detail the deployment frequency, 1x per sprint and it must be the same time, talk to the team about this 
2. Outline the deployment policy, what is included in the deployment- everything and include what issues could arise to prevent this - secrel 
3. Communicate to the partner teams and the VRO team when this will be implemented on the VRO-support channel and link to the documentation 
4. Ensure documentation includes the person responsible for this task, as it will be manual 
5. Create a slackbot that reminds everyone when the deployment is 24 hours in advance - For text the bot generates see @bianca-rivera  

**Notes**
Partner teams have agreed that when they deploy to dev, it should be anticipated to go to prod.
Partner teams have requested a deployment cadence and would like this shared with them.
Partner teams have expressed a desire to know the signature deadline for deployments.
Collaborate with @bianca-rivera to create a communication plan for sharing the deployment policy with partner teams

**Comment by meganhicks** [comment]
Bring this to the partner team backlog so that we can align on what is being merged to develop from a process standard. @tejans24 to update by next partner meeting and present it.

**Comment by meganhicks** [comment]
Teja will edit this and present it to the team.

**Comment by meganhicks** [comment]
rewrite this

**Comment by meganhicks** [comment]
break this up into "on call" and deployment policy .

**Comment by bianca-rivera** [comment]
@brostk can you add the documentation you created for this so we can reference for #2672?

**Comment by brostk** [comment]
[VRO Deployment Policy](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Deployment-Policy).
