### ISSUE TITLE
Deployment of CC change to Prod 

### ISSUE THREAD

**Issue by ponny-m** [department-of-veterans-affairs/abd-vro#2977]
The CC team made a [request](https://dsva.slack.com/archives/C01Q7979Z7D/p1715363024915989) to deploy a merged change to Prod environment. 

Acceptance Criteria
- Changes have been tested in either Sandbox or Prod-test before deploying to Prod. 
- Successful deployment to Prod

****Maybe further team discussion is needed before we proceed.**

**Comment by BerniXiongA6** [comment]
Hi @Ponnia-M -- thanks for adding this to Sprint U. Could you point this ticket before Wednesday? I'll be working on a mid-sprint progress to support the VRO team better and having work in progress sized will be very helpful. Thanks! cc: @meganhicks
