### ISSUE TITLE
Implement custom monitoring for BGS

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2980]
As a platform maintenance team member responsible for supporting partner teams,
I want to establish monitoring for the BGS service so when there is an outage or disruption I am proactively aware. 

**Acceptance Criteria:**

- [x] A monitor has been created that detects when BGS loses connectivity or stops working 
- [x] Monitoring changes have been integrated into the existing team dashboard (to streamline platform management)
- [x] Implemented changes have been documented on the team wiki 
- [x] Custom metrics for request latency are created to Datadog 

## What You Need to Know
- Keep metric types consistent between our monitoring efforts. Please chat with Lisa on Ticket #2932 

Out of Scope:
Setting up alerting, as this user story focuses on establishing monitoring capabilities.

**Comment by lisac** [comment]
status: 
- code changes have been submitted ina. PR (#3075) for peer review
- working on monitor and dashboard

**Comment by lisac** [comment]
preview of dashboard, using mock data: ![Screenshot 2024-06-17 at 1 05 31 PM](https://github.com/department-of-veterans-affairs/abd-vro/assets/943046/aad3b858-1457-4236-b1df-1730c388e4ec)

**Comment by lisac** [comment]
status: changes to application code are pending peer code review, after which deployments can take place. No anticipated blockers for deployment.

Updates to monitors, dashboards, and team wiki: complete.

**Comment by BerniXiongA6** [comment]
@chengjie8 will review this per Team Scrum today

**Comment by lisac** [comment]
status: needs a deployment. no anticipated blockers.

**Comment by lisac** [comment]
deployed 7/3. [helm chart inputs](https://dsva.slack.com/archives/C04CA47HV96/p1720028540655619); metrics in [datadog](https://lighthousedi.ddog-gov.com/dashboard/9kd-u35-dxv/vro-data-services-bgs).
