### ISSUE TITLE
Containerize Integration Tests for BGS

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#2999]
**User Story**

As a VRO engineer, I want to containerize and publish images for application integration tests, so that we can run integration test containers in LHDI environments during deployments.

**Acceptance Criteria**

1. BGS integration tests are extracted into their own containers that can be run independently of applications
2. Mock BGS containers are made deployable to LHDI
3. These containers are published to our package repo and integrated with SecRel pipelines for image signing
4. Create a followup ticket to figure out how to use actual VA BGS service in lower environments
5. Create followup tickets to execute the same 4 criteria above for all our other services.

**Not included in this work**

- seed data might not be applicable across all environments so to fix this you might have to coordinate with other teams 
- The changes to helm deployment commands to run integration test containers during the deployment process.

**Notes about work**
- _(links to documentation, resources, code, etc that might inform the person doing the work)_

**Comment by meganhicks** [comment]
Break out BIP and BGS to their own tickets

**Comment by meganhicks** [comment]
break out BIE and domain xamaple

**Comment by msnwatson** [comment]
ummm, so I've realized that I've already completed this ticket (except creating all the followups) and had accidentally started working on the next one because i had forgotten we had drawn a distinction between getting it ready and running the integration tests remotely until right now.

**Comment by msnwatson** [comment]
Followup tickets:
1. https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3166
2. https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3168
3. https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3167
4. https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3165

**Comment by msnwatson** [comment]
Criteria 4 does not seem to be necessary as integration tests are running while interacting with the BGS environment in lower environments currently

**Comment by msnwatson** [comment]
Per discussion from standup on 07/09, I've updated the dependency ticket with information about conversations that need to reach resolution before it should be actively worked on as well as filled out the ticket now that we have decided to complete a full migration to ArgoCD
