### ISSUE TITLE
Create an on-call runbook 

### ISSUE THREAD

**Issue by lisac** [department-of-veterans-affairs/abd-vro#3005]
**User Story**

As a VRO engineer, I want a "how-to" guide for addressing common procedures that one might encounter while on-call. 

**Acceptance Criteria**
- [ ] Includes sections for how to: 
   - deploy the latest code
   - deploy a specific SHA
   - determine the SHA/configuration of recent deployments
   - monitor application health 
- [ ] Stores non-public information on the internal wiki rather than in the `abd-vro` public repo 
- [ ] Receives approval from a team review

**Notes about work**
- follow up to https://github.com/department-of-veterans-affairs/abd-vro/issues/2570
- potentially related past work: https://github.com/department-of-veterans-affairs/abd-vro/issues/1081

**Comment by gabezurita** [comment]
Useful  guide:
https://wa.aws.amazon.com/wellarchitected/2020-07-02T19-33-23/wat.concept.runbook.en.html

@brostk and I already started a runbooks doc that we'll be filling in as I get onboarded to VRO operations:
https://github.com/department-of-veterans-affairs/abd-vro/wiki/On-Call-Runbooks

We linked it under the resources section of the [on call responsibilities doc's resources section](https://github.com/department-of-veterans-affairs/abd-vro/wiki/On-Call-Responsibilities#index-of-resources)
