### ISSUE TITLE
Deployment for EE team by May 28th

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#3007]
- [ ] Coordination with EE team to confirm what testing has been done in dev/qa and how
- [ ] Deploy EE max CFI app to Sandbox, Prod-test
- [ ] Changes have been tested at least in Prod-test before deploying to Prod.
- [ ] Deploy EE app to Prod
- [ ] Get EE's acknowledgement of complete deployment

**Comment by BerniXiongA6** [comment]
Thanks @tejans24 -- will add this to Sprint V epic! cc: @meganhicks

**Comment by dfitchett** [comment]
Max Ratings API is tested in the following ways:
* unit testing (current coverage 88%)
* deployments' endpoints can be tested on the VA intranet for the respective environment
  * GET /health
  * POST /max-ratings with body containing an array of diagnostic codes to get max ratings for: `{"diagnostic_code": [6260]}`
* user testing in `sandbox` (connects to va.gov `staging` environment)
