### ISSUE TITLE
Enhance the Incident Response Plan -Comms Standards

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3015]
As we continue to mature our processes, it's crucial that our incident response plan includes an agreed to approach on how we communicate each incident by severity level so that we have a uniformed approach when it comes to addressing issues. 

AC: 
- [x] The incident response plan will have a comms plan under each level of severity 
- [x] The plan will include how the team agrees to acknowledge the issue using standard phrasing, communicate updates and will include who should be tagged as a standard within those updates
- [x] The plan will define how to document an incident and where to store the documentation
- [x] The plan will define when an issue is done and needs no further communication
- [x] The plan will be shared with the team, adjusted as feedback is received
- [ ] The plan will have an an agreed to start date and be housed maintained on the teams wiki page

**Comment by BerniXiongA6** [comment]
@Ponnia-M -- could you let us know what's the progress on this ticket. Please also follow up with @bianca-rivera -- thanks!

**Comment by BerniXiongA6** [comment]
@Ponnia-M could you let us know when this ticket can be closed? Looks like it's still in Code Review? cc: @meganhicks
