### ISSUE TITLE
 Application Alerting for Xample-workflow and RabbitMQ

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3019]
As a member of the VRO platform team responsible for supporting partner teams, I need to be alerted about any connectivity issues with Xample-workflow and RabbitMQ. This will allow me to proactively notify partner teams about potential interruptions in their services

## Acceptance Criteria:

- [ ] When the monitors for Xample-workflow and RabbitMQ detects a disconnect or significant delay in service there is an alert that is triggered notifying the team. 

## What you need to know
- potentially relevant (?) : https://docs.datadoghq.com/integrations/rabbitmq/?tab=containerized 

## Implementation / Developer Steps (to be filled out by ticket assignee)

**Comment by dfitchett** [comment]
**NOT DOING**

`xample-workflow` was removed from the repository as of PR #3442 as a part of the ticket #3334.
