### ISSUE TITLE
Update Secrel documentation 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3022]
As a member on the VRO team we have the responsibility of being "on call" and when we are on call we have the task of being responsible for Secrel. This ticket is to create a secrel guide that details how the person leading secrel should complete the task to be successful. 

Acceptance Criteria:
- this document should share how a new person joining the team would get familiar with this task 
- it should share how often we run Secrel, what we do when we troubleshoot issues, and how we communicate to the team 
- This should be referenced under the on call responsibilities 
- This should be shared with the team

**Comment by bianca-rivera** [comment]
connected to #2859

**Comment by meganhicks** [comment]
break out this to the dependabot ticket and delete this page-This section of the Wiki is outdated and needs to be updated.
Link: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Team%20Processes
