### ISSUE TITLE
Evidence improvement: Plan next steps

### ISSUE THREAD

**Issue by KimLadin** [department-of-veterans-affairs/abd-vro#3026]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715202002955/0386b43bd8bc813560221e89cb03d29f4b036e2f?sender=uf3d2a9320ea286a502077710

**Comment by mackhowell-nava** [comment]
We completed another session last week to brainstorm "open questions" and "how might we validate/invalidate this idea" stickies...

We split up into two groups -- each group taking 4 of the ideas.
