### ISSUE TITLE
Add feature toggle to enable EP Merge for single-contention new claims

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#3035]
**Acceptance Criteria**

1. Include single-contention new claims in eligible pool for EP400 Merge
2. Put this behind a per-user feature toggle
3. Make sure both feature toggle states have test coverage

**Not included in this work**
- E2E testing

**Comment by nanotone** [comment]
Part of #2785

**Comment by dfitchett** [comment]
Approved the PR 🚀
