### ISSUE TITLE
Develop a migration strategy for ArgoCD

### ISSUE THREAD

**Issue by lisac** [department-of-veterans-affairs/abd-vro#3042]
After establishing `svc-bip-api` as VRO's first app deployable in ArgoCD, we should determine a strategy for rolling out the ArgoCD deployment option for other apps on VRO; and a strategy for deprecating use of non-ArgoCD deployments. Additionally, we should ensure the partner teams have visibility into these changes.

**Acceptance criteria**

- [x] There is a plan for deprecating use of non-ArgoCD deployments that is documented. 
- [x] a decision on when to address https://github.com/department-of-veterans-affairs/abd-vro/issues/3037
- documentation to account for complexities in troubleshooting deployments. ~for example: how does one figure out which platform did the deployment (ArgoCD or non-ArgoCD)?~ This should only be for the VRO Team since partners cannot access Argo. **(Per BX and team: OK to move this criteria out of this ticket and into new ticket for Sprint 1)**
- [x] Share the plan with the team (including the enablement team) and ensure the team is aligned. 
- [x] Any actions we are taking should not impact our partner teams 

**Notes about work**
- related to the completion of #3041 
- consider implementing a [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) on [va-abd-rrd-argocd-applications-vault](https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault) - why: to support partner teams configuring deployments on their own apps while not disrupting affecting apps of other partners

**Comment by lisac** [comment]
To support the rollout, here are placeholder tickets for the remaining apps:
(not in priority order)
- https://github.com/department-of-veterans-affairs/abd-vro/issues/3086
- https://github.com/department-of-veterans-affairs/abd-vro/issues/3087
- https://github.com/department-of-veterans-affairs/abd-vro/issues/3088
- https://github.com/department-of-veterans-affairs/abd-vro/issues/3089
- https://github.com/department-of-veterans-affairs/abd-vro/issues/3090
- https://github.com/department-of-veterans-affairs/abd-vro/issues/3091
- https://github.com/department-of-veterans-affairs/abd-vro/issues/3092
- https://github.com/department-of-veterans-affairs/abd-vro/issues/3093
- https://github.com/department-of-veterans-affairs/abd-vro/issues/3094

**Comment by meganhicks** [comment]
Ponnia I clarified this ticket with the team. They said everything is done accept for AC number 3 and this is what they expect to come out o this work. Please reach out to engineers working on aligning work for more questions: Mason and Lisa.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 -- write up new ticket to finish out AC item 3 above and add other relevant tasks (to bring into Sprint 1 at sprint planning). 

New ticket is #3424 (placed in product backlog for now).
