### ISSUE TITLE
Production release of develop for cc-app due 6/20

### ISSUE THREAD

**Issue by lukey-luke** [department-of-veterans-affairs/abd-vro#3074]
### Requesting Team

Contention Classification

### Problem/Need

Updates to logging covered in this [PR HERE](https://github.com/department-of-veterans-affairs/abd-vro/pull/3072) will enable the contention classification team to better make use of the logs on datadog dashboards.

### Why?

It will enable the contention classification team to better make use of the logs on datadog dashboards.

### Acceptance criteria

`develop` is deployed for the cc-app container

### Priority

The CC team needs this 6/20 and can reach out to Luke or Tyler to get it done.

**Comment by meganhicks** [comment]
Megan:
Is this ticket related to our mentioning the gaps in logging or something else?
Could you provide more details on why this needs to be prioritized urgently?
Can you help us understand if this task can be included in Sprint Y, or does it need to be prioritized for the next sprint?
Your insights will help us allocate resources effectively. Thank you!
New
Anneliese LaTempa (OOO 6/17-6/20)
  2 minutes ago
Something else. We discovered while testing today we want to include the claim id so we can distinguish between single and multi contention claims in our monitoring.
If our stakeholders decide we need this level of monitoring for release, we could potentially not meet our target release date. If the next two sprints are full we wouldn't be able to release before the end of June.
3. Prioritization in the next sprint would be ideal if it's possible to squeeze in.

**Comment by meganhicks** [comment]
@lukey-luke @tyler-spangler6  Please confirm what environment you want this deployed to.

**Comment by lisac** [comment]
update: this logging update has been deployed up to the `prod-test` environment. We plan to deploy to the `production` environment ~1pm ET on 6/20.

**Comment by lisac** [comment]
@lukey-luke this has been done. i'll close this issue at the end of the day unless concerns are raised. thanks!
