### ISSUE TITLE
Configure ArgoCD for Contention Classification (CC)

### ISSUE THREAD

**Issue by lisac** [department-of-veterans-affairs/abd-vro#3092]
**User Story**
As a VRO Engineer, I want `domain-cc` to be deployable through ArgoCD. 

We are close to completing `svc-bip-api` to be deployable in ArgoCD for the non-production cluster (environments: dev, qa, sandbox). In this ticket, we would like to achieve the same for `domain-cc`. 

**Acceptance Criteria**
1. `domain-cc` is deployable to the non-production cluster via ArgoCD
2. deployments of the app from ArgoCD and non-ArgoCD can be run interchangeably
3. Alert partner teams of deployment one day in advance. This is just for lower environments and should not impact how they currently deploy.

**Notes about work**
Much of the work for this ticket should happen in [va-abd-rrd-argocd-applications-vault](https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault).

**Comment by BerniXiongA6** [comment]
HI @Ponnia-M would you be able to comment with the current progress on this ticket? Also, let us know if it will carry over to the next sprint. Thank you!
