### ISSUE TITLE
EP400 handling new claims - E2E testing

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3107]
[Launch Plan](https://docs.google.com/document/d/1xqdjEAuQ0aOIvHOj8szjpgB7jDlSl5kRX5zT9ctPR1Y/edit?usp=sharing)

```[tasklist]
### Tasks
- [x] Deploy to sandbox
- [ ] Perform end to end testing [scenarios](https://docs.google.com/spreadsheets/d/1uKRH8G5jLwosl_D0DbpFP-_SXudgLneiijckauQsG8w/edit?usp=sharing)
```

**Comment by dfitchett** [comment]
Added some tabs for the two different rollouts for Post MVP EP Merge to the scenarios [doc](https://docs.google.com/spreadsheets/d/1uKRH8G5jLwosl_D0DbpFP-_SXudgLneiijckauQsG8w/edit#gid=673590904)

**Comment by mackhowell-nava** [comment]
Completed testing with the 10 different scenarios today -- documented here: https://docs.google.com/spreadsheets/d/1uKRH8G5jLwosl_D0DbpFP-_SXudgLneiijckauQsG8w/edit?gid=664515468#gid=664515468 thanks to @dfitchett 🙌
