### ISSUE TITLE
Create design/research roadmap for current condition evidence

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3109]
It's done when we've filled out and agreed upon the [roadmap for current condition shaping](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718772760338/aacfabb0dcb02c5e88a9291628cfcc77b08fbfb1?sender=uf8b0cb845e6eace74cc32086). 

- [x] Fill in the roadmap 
- [x] Review with FedFriends
- [x] Proceed

**Comment by BerniXiongA6** [comment]
@carodew -- will refine ticket and starting working on
