### ISSUE TITLE
EP400 handling multiple contentions - check in on CC team's dependency

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3111]
- Making a note this sprint to check back in on the dependency we have on the CC team to classify multiple contentions.
- We want to make sure we're ready to begin development next sprint, and we want to be unblocked there.
- See our [launch plan roadmap](https://docs.google.com/spreadsheets/d/1P8vbRyNForqASMTPgp_0rp04lsj3zYp238fPGPvmmLM/edit?usp=sharing)

**Comment by dfitchett** [comment]
CC team has deployed multi contention classification functionality to production
