### ISSUE TITLE
Onboard Katelyn Caillouet

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/abd-vro#3120]
### Onboarding materials and tasks (Katelyn To Do)

- [x] Bookmark and review EE Team onboarding document ([link](https://docs.google.com/document/d/1be-TyyNWz5KMP40tPFXVxo7x7e1TJeQb9RXFEeWNSEE/edit?usp=sharing))
- [x] Bookmark and review EE Team Current Sprint GitHub Board ([link](https://github.com/orgs/department-of-veterans-affairs/projects/878/views/1?filterQuery=sprint%3A%40current+assignee%3A))
- [x] Bookmark and review Mural of mapped ABD Toxic Exposure (EE and VRO) Team Ceremonies ([link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711030739297/11857c665d7bc873155c58d2905332dd0923479b?sender=u8e7018fb9a81bacacad29157))

### Checklist to help new member gain access to EE Team things (Berni To Do)
Github access
- [x] Submit request on behalf of the new team member to [get added to the VA organization](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GitHub) (Katelyn already in VA org on GH)
- [x] Add new team member to the [OCTO-VRO GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/octo-vro/members)

Add to the appropriate user groups in Slack
- [x] @employee-exp-team
- [x] @design_octo_abd

Add to recurring meeting invites
- [x] EE team ceremonies 
- [x] Other recurring meetings 

Add to Benefits Crew
- [x] Slack channel #benefits-onboarding
- [x] GitHub Benefits Portfolio team roster

Access to other tools
- [x] Invite to the ABD Toxic Exposure Team Shared Calendar in Google
- [ ] Request Datadog (VA)
- [x] Request Figma (VA)
- [x] Request Mural (VA)

**Comment by katelyncai** [comment]
Hi @BerniXiongA6! I'm not sure why, but I can't assign myself to this ticket. Think I might be missing permissions to this repository?

**Comment by BerniXiongA6** [comment]
Hi @katelyncai let me investigate access to tools today for you. I'll get back to you.

**Comment by BerniXiongA6** [comment]
@katelyncai I think you should be good to go now... see if you now have write access to this ticket?

**Comment by katelyncai** [comment]
@BerniXiongA6 success! thank you for the access

**Comment by katelyncai** [comment]
@BerniXiongA6 Hi Berni! I believe the only outstanding task on this ticket is Datadog access - I didn't need to use that on my previous team.
