### ISSUE TITLE
 On call Documentation - 2 people should work on this together 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3123]
**What**

Create standard documentation on the team's wiki for what it means to be "on call." Refer to the current on-call tickets to see what the team has agreed to and refine it as necessary.

**Why**
We need better documentation, especially with all the new folks on the team 

**Acceptance Criteria**

The documentation should detail responsibilities for the following:

1. Utilize the incident response documentation and link to the communication standards agreed upon by VRO. Each reported incident must be converted into a ZenHub ticket and included in the Sprint. When creating the ticket, ensure it is linked to the Epic "Incident" and follow the guidance on labeling the root cause of the issue within the Epic.
2. Detail standards for monitoring the benefits-vro-alerts channel, on-call channels, vro-support
3. Detail responsibilities for monitoring Secrel, Dependabot, and deployments. Include links to any relevant documentation.
4. Ensure the "on call" section includes a note about primary and secondary responsibilities.
6. Specify that the primary on-call person is the first point of contact for issues but not necessarily the one who resolves everything. They should enlist the help of the team as needed and be responsible for tracking the completion of all "on call" tasks.
7. create a "on call" index page with existing documentation that we have around the topics above. 

**Notes**
This should be demo'd before marking as done. 
This is for the VRO Team 
look at on call ticket for current agreed to responsibilities 
Bianca can help with what we have that currently be leveraged

**Comment by brostk** [comment]
Wiki page: https://github.com/department-of-veterans-affairs/abd-vro/wiki/On-CallResponsibilities

**Comment by nelsestu** [comment]
at long last i give you the first draft of the [SecRel Getting Started Guide](https://docs.google.com/document/d/1DZ6IEcn8cNCbLHmBpmKG1J2BiU7X9Px_EEJxNjqMuxw/edit?usp=sharing).  Please feel free to enter any edits in Suggestion mode or add any comments.  This document is geared towards onboarding new team members, but it is also increasingly detailed as the reader continues reading.  I am going to move on with other sprint work but will plan to circle back and get this document wrapped up after the team has had time to share feedback.
