### ISSUE TITLE
ArgoCD final steps for partners 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3176]
Once we have team-approved comms for new instructions for partner teams deploying to lower envs is essential to:

Update the partner team deployment guide to reflect the new process.
Demonstrate the new process to partner teams.
Communicate the effective date of the new process to ensure partner teams do not lose current privileges and stay up-to-date with the tools utilized by the VRO platform.

AC: 

1. Deployment guides are updated on the wiki -https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Quick-Deployment-Guide-for-Lower-Environments
   - done
2. Training is scheduled for the partner teams 
   - addressed: shared the change at a partner team sync 8/22 and did a mini demo 
3. A communication plan is put together to announce the change 
   - status: in progress
4. Old GH actions for deploying partner team applications are disabled and corresponding code deleted
   - addressed by #3367
5. Old GH action workflow documentation is removed from the wiki 
   - done: removed in [6bbebe](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Quick-Deployment-Guide-for-Lower-Environments/6bbebe1035f1d6e278ac03a095b117498816e3c0)

Training Ideas: 
Create video and send async or going over this at a partner time meeting

**Comment by lisac** [comment]
note to self: training plan should include reminder of the github teams for [cc](https://github.com/orgs/department-of-veterans-affairs/teams/benefits-contention-classification-engineers) and  [ee](https://github.com/orgs/department-of-veterans-affairs/teams/benefits-employee-exp-engineers).

**Comment by lisac** [comment]
status: drafted wiki material [here](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Quick-Deployment-Guide-for-Lower-Environments#deploying-via-argocd) and moving on to the communication plan.

I plan not to move the wiki material out of draft mode until:
- I've requested+addressed a round of feedback from VRO on the draft wiki material 
- CC app has been migrated https://github.com/department-of-veterans-affairs/abd-vro/issues/3092
- we've merged in https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault/pull/32

**Comment by lisac** [comment]
status: I've developed the materials and asked for a round of feedback from the team. moving this to Code Review, until I can get time with Bianca for further review. 

done:
- updated wiki with feedback about deployment status
- drafted comms in https://dsva.slack.com/docs/T03FECE8V/F07CKR6AX9S

**Comment by meganhicks** [comment]
Lisa let me know if you would like to meet before the partner meeting and want any help.

**Comment by lisac** [comment]
status update on the AC. still expecting to complete by end of Sprint B.

1. Deployment guides are updated on the wiki -https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Quick-Deployment-Guide-for-Lower-Environments: **done**
2. Training is scheduled for the partner teams:  **addressed**: shared the change at a partner team sync 8/22 and did a mini demo
3. A communication plan is put together to announce the change - work with Bianca to get her outline: **in progress**, shared with comms plan with Bianca late today
5. Old GH actions for deploying partner team applications are disabled and corresponding code deleted: 
**in progress**
6. Old GH action workflow documentation is removed from the wiki:  **done**: removed in [6bbebe](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Quick-Deployment-Guide-for-Lower-Environments/6bbebe1035f1d6e278ac03a095b117498816e3c0)

**Comment by lisac** [comment]
status update: 
1. done
2. addressed
3. replaced some language in the planned announcement; planning to post it on Monday
4. done
5. done

**Comment by lisac** [comment]
announcement posted in #benefits-vro-support on 8/27: https://dsva.slack.com/archives/C01Q7979Z7D/p1724801178070689
