### ISSUE TITLE
Update Secrel documentation 

### ISSUE THREAD

**Issue by nelsestu** [department-of-veterans-affairs/abd-vro#3287]
Both while pairing with Kyle on #3123, and during a backlog refinement session, we highlighted the need for updated SecRel documentation, and the desire for this updated documentation to exist as part of the On Call Documentation completed in #3123.  Somehow a ticket was created for Dependabot, but not for SecRel, so I've created this to help track the [SecRel Getting Started Guide](https://docs.google.com/document/d/1DZ6IEcn8cNCbLHmBpmKG1J2BiU7X9Px_EEJxNjqMuxw/edit?usp=drive_link) that is presently under review by the team.  

As a member on the VRO team we have the responsibility of being "on call" and when we are on call we have the task of being responsible for [Secrel](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/workflows/secrel.yml). This ticket is to create a secrel guide that details how the person leading secrel should complete the task to be successful.  There is also a [SecRel Processing Guide](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/SecRel-Processing-Guide) available via the internal wiki.  This resource is still accurate and useful, just not very user friendly. and isn't great at introducing the subject matter for new team members.   

Acceptance Criteria:
- this document should share how a new person joining the team would get familiar with this task 
- it should share how often we run Secrel, what we do when we troubleshoot issues, and how we communicate to the team 
- This should be referenced under the on call responsibilities 
- This should be shared with the team via the SecRel wiki page 
 

https://docs.google.com/document/d/1DZ6IEcn8cNCbLHmBpmKG1J2BiU7X9Px_EEJxNjqMuxw/edit?usp=drive_link

**Comment by meganhicks** [comment]
Wiki page: https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/SecRel-Getting-Started-on-VRO
