### ISSUE TITLE
Partner Team Production Deployment Workflow - Prototype, Soft Launch, and Comms

### ISSUE THREAD

**Issue by nelsestu** [department-of-veterans-affairs/abd-vro#3292]
Description
--
This issue is a continuation of #2795, and is based on findings from #2672. At this point we've designed, documented, and prototyped the scheduled deployment process in Slack workflows.

Why
--
To ensure recommendations made are feasible for implementation and mitigate existing partner team pain points and gaps highlighted in the research phase

AC
--
Please see #2795 for the other half of the overall effort to bring about scheduled deployments 
- [x] Test workflow internally on mock channels for demo purposes: #benefits-vro-support_ and #benefits-vro-on-call_
- [x] Duplicate workflows to real channels for testing purposes
- [x] Complete migration of deployment strategies by rolling over to the new process
- [x] Draft and send official comms message to #benefits-vro-support channel
- [x] 
Notes
--
- This ticket is referencing deployment requests partner teams make to higher-level environments.
- Replacement for [#2795](https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/2795)
- Reference work from [#3042](https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3042)

Outstanding items:

- If a partner team engineer's confidence is low, how do we want to engage with them for additional testing?
  - if still at _Low Confidence_ by Thursday, detour to Opt-out workflow
  -  Follow-up: Ask/remind partner teams 
- Do we want to provide guidance on what testing they should conduct before scheduled deployment? and to which environment?
- What happens if deployment is unsuccessful (i.e. try to deploy on Thursdays, encounter issues, rollback)?
  -  Follow-up: communication to partner teams

Resources
--
[Mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705504070694/54b4ebecd924afc4261c4292db855c4df49b29df?wid=0-1726761811150)
[GitHub & Slack integration features](https://github.com/integrations/slack?tab=readme-ov-file#deployment-notifications)

**Comment by BerniXiongA6** [comment]
Per @bianca-rivera -- this ticket should carry over to a future sprint since it wasn't worked on in Sprint A or B. I'll untag the ticket from Sprint A and notate this on the current Sprint epic.

**Comment by bianca-rivera** [comment]
Following the steps taken with the Incident Report workflow, I updated that documentation of Deployment workflow should be added to the Deployment Policy wiki page

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 -- will roll over to Sprint 1

**Comment by bianca-rivera** [comment]
Expansion of action items based on [16th min notes](https://docs.google.com/document/d/1hyuE2pqbaZRAwVoXm1XEnynnKSBf22ME-Bq7m-vbKhI/edit):

- [ ] **Update Deployment policy wiki page:** 
   - [x] incorporate latest decisions from 16th min notes doc ( @brostk )
  - [ ] delineate VRO vs partner team responsibilities/expectations for process (tuesday-thursday) ( @bianca-rivera )
  - [x] process flow diagram ( @brostk ) 

- [ ] **Update Opt-in/Opt-Out Workflows:** ( @bianca-rivera )
  - [x] integrate opt-in and opt-out via link (TBD whether possible)
  - [x] add comms touchpoints: 1) get validation from partner teams 2) sign off from VRO
 - [ ] **Determine alerts/notifications**: 
    - [ ] determine whether subscribing #-alerts channel to abd-vro repo make sense/works
 --- share updates with VRO team, get feedback ---
    - [ ] come up with and present options of varying levels of notifications to partner teams during Partner Team Time (Thursday) meeting
  - [ ] Get feedback from partner teams:
    - [ ] what type of notifications do partner teams want/need?
    - [ ] cadence/frequency? 
    - [ ] any other type of notification?
