### ISSUE TITLE
Create an issue template for file clean up after a research study

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#3299]
Use #3297 as a baseline to create an issue template.

**Comment by katelyncai** [comment]
Include tasks for updating both equity checker spreadsheets ([EE](https://docs.google.com/spreadsheets/d/1ooJLEU9U72kNBoc1hpc643MfsjlfujOs5LcFjDYOEi0/edit?gid=1622121386#gid=1622121386) and [VA-wide](https://docs.google.com/spreadsheets/d/1pq7TSHZonfpzAQBJj6B2geGHlNUwZEs4DzEvxcRgu0o/edit?gid=1412637962#gid=1412637962)) in template

**Comment by katelyncai** [comment]
Well, that was a wild ride. But I figured it out! Introducing our new [file clean-up template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=Design+research&projects=&template=EE-research-file-clean-up.md&title=Research+Project+Name+-+File+Clean-up). We can make edits to this template [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/EE-research-file-clean-up.md).
Edit: Need to move this to the ABD-VRO repo. @dfitchett graciously volunteered to assist!

**Comment by dfitchett** [comment]
Completed in PR #3445

**Comment by dfitchett** [comment]
@katelyncai New issue template is available for picking on the new issue [page](https://github.com/department-of-veterans-affairs/abd-vro/issues/new/choose).

**Comment by katelyncai** [comment]
> @katelyncai New issue template is available for picking on the new issue [page](https://github.com/department-of-veterans-affairs/abd-vro/issues/new/choose).

Amazing! This is perfect. Thank you for your assistance, @dfitchett!
