### ISSUE TITLE
Understanding RabbitMQ Vulnerabilities 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3306]
As a team responsible for maintaining reliable partner services, we need to monitor RabbitMQ to ensure it is functioning correctly and preventing downstream vulnerabilities. This will allow us to understand potential risks and implement strategies to avoid interruptions or malfunctions in partner services due to RabbitMQ issues.

AC: 

Create a detailed diagram of the current RabbitMQ architecture.
Ensure the diagram accurately represents all interactions with connected services.
Identify and highlight potential vulnerability points within the architecture.
Share the finalized diagram with the team for review and feedback.

**Comment by dfitchett** [comment]
Architectural diagram with considerations, concerns and potential solutions:
<img width="1528" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN05nQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa0572a8b67216e603d0635bf9bd3594b6b93db4/image.png" alt="image.png" />



The original document can be accessed [here](https://drive.google.com/file/d/19Jxab7h9vSC5Y2eZfWIbyjT6L1byyG3b/view?usp=sharing) via drawio.

**Comment by dfitchett** [comment]
Quorum met for reviewers in [slack](https://dsva.slack.com/archives/C04QLHM9LR0/p1723758838569619). Added diagram to wiki [here](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-RabbitMQ-Strategy)

**Comment by BerniXiongA6** [comment]
Hey @dfitchett would you mind sizing this ticket after the fact so I can make sure it gets into the delivery metrics? VRO team uses Small (1), Medium (2), Large (3) to size the tickets, but you're welcome to chat with team members for their input if needed. Thanks!
