### ISSUE TITLE
Investigate ways to automate MTTR

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3325]
Last Sprint, we developed a process for manually tracking and communicating MTTR.
https://github.com/department-of-veterans-affairs/abd-vro/wiki/Metrics 
This ticket is to explore automating that process to eliminate the need for manual effort.

Acceptance Criteria:

Timebox: 3 days
Identify a solution that can:
Automatically calculate and publish the MTTR metric in a public channel (e.g., Slack or Wiki).
Maintain a running average of the metric.
Report the findings in this ticket.

**Comment by brostk** [comment]
Two initial thoughts:

1. Keep this a manual process;
2. create a Java or Python app which spins up, hits PagerDuty's incidents API, and iterates over the results to compute MTTR which gets published out (Google Sheets for visibility?); or
3. as part of the Incident Reporting workflow, we could add items to Slack Lists when incidents are created and closed.

Considerations for option 1:
- Estimated 0/3 Level of Effort to setup, but 3/3 for manual LOE when gathering metrics (still relatively minimal)
- We can manually go into PagerDuty's analytics dashboard and use the UI to view and copy MTTR metrics for a given sprint
- Need to update the table on the metrics wiki, or elsewhere such as a Google Sheet, and then also copy the metrics onto the sprint review slide deck

For option 2:
- Estimated 2/3 LOE to setup (new Java or python app; new github actions workflow), but 1/3 for gathering and reporting metrics.
- [PagerDuty Incidents API](https://developer.pagerduty.com/api-reference/9d0b4b12e36f9-list-incidents) reference demonstrates querying PagerDuty for incidents:
  - [Python library](https://pagerduty.github.io/pdpyras/user_guide.html)
  - no Java library for Incidents; could just set up API access ourselves (not a huge deal)
  - requires a PagerDuty developer account
    - experimenting with one now
    - for VRO Benefits, developer access would need to be granted by admins (doesn't appear that any of us are admins)
  - request parameters to filter on service_ids[] and date_range
- Github action could be configured to run at a set time each sprint to run a service which polls the API and computes MTTR for our service for each priority, then export that data to a Google Sheet
  - [Google Sheets API reference](https://developers.google.com/sheets/api/quickstart/python) (python; Java linked on the sidebar)
    - OAuth looks like it could be difficult to implement - the docs suggest the app, on first run, opens a browser to authenticate using a Google account?  
  - The Sheet could replace the table we have on the Metrics page on the wiki
  - Still need to manually copy sprint metrics into the sprint review slide deck
- Need to compute MTTR ourselves, which introduces room for error in deviating from what PagerDuty is reporting (unlikely)

And for option 3:
- Estimated 1/3 LOE to setup, but 2/3 LOE for gathering and reporting metrics
- Slack lists can have new rows added when an incident is either created or resolved
  - may not align with all incidents in PagerDuty, for example when incidents are created through the UI or created via DataDog or another external service
  - would mean the resulting incident list would be inaccurate
- At the end of each sprint, someone would be responsible for exporting the list as CSV and plugging it into maybe Google Sheets
  - could create a series of formulas to compute MTTR without much manual intervention
  - would likely need some sort of fancy vlookup to pair incidents from creation to resolution to determine duration
  - room for error
- Resulting metrics need to be copied over to the wiki table or a separate sheet, as well as the sprint review slide deck.

---

I would personally lean to option 2 if we're looking to move to an automated process, but we should consider the LOE for getting an app written which connects with two external APIs (PagerDuty and Google Sheets) versus continuing with the manual approach.

**Comment by meganhicks** [comment]
Kyle could we bring this up as a topic in Monday's meeting with our Enablement team? I am curious on what they would be interested in and I would also like to get the teams thoughts. Thanks again
cc: @BerniXiongA6

**Comment by brostk** [comment]
> Kyle could we bring this up as a topic in Monday's meeting with our Enablement team? I am curious on what they would be interested in and I would also like to get the teams thoughts. Thanks again cc: @BerniXiongA6

Sounds great @meganhicks.

**Comment by BerniXiongA6** [comment]
Hi @brostk could I ask you to point this ticket after the fact? Looks like we missed sizing this one. I want to make sure it gets into the delivery metrics. Thank you!

**Comment by brostk** [comment]
> Hi @brostk could I ask you to point this ticket after the fact? Looks like we missed sizing this one. I want to make sure it gets into the delivery metrics. Thank you!

Sure thing, I just set the estimate to 2 points.
