### ISSUE TITLE
Check back in with NWQ and Bob Lawson on expanded merging criteria

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3394]
Notes:

- Might include other claim statuses as eligible -- we worked with Josh on a conservative list initially.

**Comment by nanotone** [comment]
vets-api is currently using the [Lighthouse Benefits Claims API](https://developer.va.gov/explore/api/benefits-claims) for fetching claims data, which means the claim statuses available to us for eligibility determination are:
- PENDING
- **CLAIM_RECEIVED** *
- **INITIAL_REVIEW** *
- EVIDENCE_GATHERING_REVIEW_DECISION
- PREPARATION_FOR_NOTIFICATION
- COMPLETE
- ERRORED
- CANCELED

The two bolded/starred statuses (CLAIM_RECEIVED and INITIAL_REVIEW) are what we currently deem eligible for EP400 Merge.

From perusing the Claims API codebase, these statuses are produced by a [BGSClaimStatusMapper](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/lib/claims_api/bgs_claim_status_mapper.rb) class, which translates values fetched from CorpDB/BGS -- in the parlance of this code, values on the CorpDB/BGS side are sometimes called "phases" or "phase statuses".

A few more observations from reading the code, in hopes of de-mystifying the terms for folks on the VBA side:
- The upstream values EVIDENCE_GATHERING, REVIEW_OF_EVIDENCE, PREPARATION_FOR_DECISION, and PENDING_DECISION_APPROVAL are grouped together and exposed as a single status EVIDENCE_GATHERING_REVIEW_DECISION to consumers. Unfortunately, I don't think there's a way for us, as an API consumer, to disambiguate the grouped status back to the more specific ones.
- CLAIM_RECEIVED encompasses "received" and "open"
- INITIAL_REVIEW encompasses "review" and "under review"
- PREPARATION_FOR_DECISION encompasses "RFD"
- COMPLETE encompasses "clear/cleared"
