### ISSUE TITLE
Workshop Streamlit MVP with team 

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/abd-vro#3440]
## What You Need to Know
- Refer to Product Manager ticket #3418 for background info.
- The purpose of this ticket is for VRO team and VRO Enablement team to sync and review/discuss the MVP product outline so that team members have alignment before beginning the development stage.

## AC 

- [ ] VRO Team members understand the project goals 
- [ ] VRO Team members have identified work we can do right now 
- [ ] The data viz epic is updated to reflect new tickets and those tickets are mapped to future sprints 

## Resources

https://app.mural.co/t/agilesixapplications0942/m/agilesixapplications0942/1727718756386/d2eaedc3ef6b8ed3347c6131c82b56edb4fa0e4d?sender=u739128c1dfc0f4a9293a2519

**Comment by meganhicks** [comment]
The first iteration of the MVP can be found here: https://app.mural.co/t/agilesixapplications0942/m/agilesixapplications0942/1727718756386/d2eaedc3ef6b8ed3347c6131c82b56edb4fa0e4d?sender=u739128c1dfc0f4a9293a2519
