### ISSUE TITLE
Early investigation/technical discovery into Flashes and Special Issues

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3452]
TODO @mackhowell-nava to collect assets here

### Links
- [Product Opportunity Brief](https://docs.google.com/document/d/1jV9ZKV80kLzVd3fodUFeoqsJkiLO7-MU0I-VkitHQw0/edit?usp=sharing) (WIP)
- [Initial Github ticket](https://github.com/orgs/department-of-veterans-affairs/projects/940/views/12?filterQuery=portfolio%3A%22OCTO+Benefits%22+spec&pane=issue&itemId=53440753)

**Comment by nanotone** [comment]
Here's my initial technical discovery on how flashes are applied by va.gov's 526 form:

Basic background - flashes are tags that are set at the Veteran level, which indicate to VBMS users that special care should be taken when doing anything with that Veteran, such as processing claims. Examples include `Agent Orange - Vietnam`, `Formerly Homeless`, and `Priority Processing - Veteran over age 85`. They manifest as a banner that "flashes" near the top of the VBMS UI, hence the name.

Out of the many flashes that could be set by a disability compensation claim, the va.gov 526 form sets four flashes:
- `Homeless`
- `Terminally Ill`
- `Priority Processing - Veteran over age 85`
- `POW`

This happens in two phases:
1. When the Veteran hits the final submit button,
  - A new `Form526Submission` record is [created from the data](https://github.com/department-of-veterans-affairs/vets-api/blob/f76204e/app/models/saved_claim/disability_compensation.rb#L36) that they've entered.
  - The `BGS::DisabilityCompensationFormFlashes` utility class [translates the form data](https://github.com/department-of-veterans-affairs/vets-api/blob/f76204e/lib/bgs/disability_compensation_form_flashes.rb#L30) into the presence or absence of the 4 flashes mentioned above, and this list of flashes gets saved to the `Form526Submission` record. Note that the comment above this method mentions a number of additional flashes that could be translated.
2. After the vets-api sidekiq job has established the claim in CorpDB,
  - The `Form526Submission` performs some "ancillary" jobs, including setting flashes if needed.
  - This is also gated by a `disability_compensation_flashes` feature flag, currently enabled in prod.
  - The BGS SOAP `ClaimantWebService` is used to add flashes. This method takes a bunch of additional data, but 526 only uses the Veteran's SSN and the flash name.

One take-away of this analysis is that the determination of whether any particular flash should be applied is dependent only on the user object (the Veteran) and the 526 form data -- namely, data captured during the Veteran's path through the 526 UI flow. This may explain why va.gov 526 only supports those 4 flashes. Supporting a new flash _may_ require accessing other data sources, and this could be as easy as using an API integration already in vets-api, or as onerous as updating the 526 UI flow (unlikely).

## Addendum

Based on this [Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1722002812846729?thread_ts=1716382860.499509&cid=C04KW0B46N5) and [Github issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89372), it appears that the Lighthouse API for claim establishment (slated to replace EVSS) sets two flashes, `Homeless` and `Hardship`, based solely on the content of the 526 form data. There is most likely some duplication of logic between the vets-api's usage of BGS to set flashes directly, and the Lighthouse API. Whether this logic should be "owned" by one versus the other is open to further discussion.
