### ISSUE TITLE
Update datadog for long-term Max CFI monitoring

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3456]
For context, see the [New Metrics](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1725502245951/7f751e199470fb4355486a21e9045394b18a3503?wid=0-1726181213564&outline=open) section of our Mural.

Goal: Update our Max CFI metrics page in Datadog in conjunction with releasing the feature to 100%

Acceptance Criteria
- Start tracking the metrics proposed by Derek, accounting for any new ones listed we current do not track
- For the metrics with "TOP X" let's shoot for the top 10-15. If seven feels more appropriate, then that's OK too to start. 
- Pull the top diagnostic types from the existing chart in Datadog.
- After we bump to 100%, remove the control group widgets in the Datadog dashboard. Double-check that data isn't coming in still first.

**Comment by dfitchett** [comment]
@nanotone do you want to also remove any old feature flags as part of this ticket?

**Comment by nanotone** [comment]
@dfitchett It would make more sense to remove old feature flags after we're sure we're staying at 100%, so that's why it's mentioned as an AC on #3457.

**Comment by dfitchett** [comment]
Updated the [datadog dashboard](https://vagov.ddog-gov.com/dashboard/j4c-6ve-iit/max-ratings-api-employee-experience-benefits).
