### ISSUE TITLE
Create log of estimated volume of failures

### ISSUE THREAD

**Issue by bianca-rivera** [department-of-veterans-affairs/abd-vro#3476]
What you need to know: 

- Slack thread: [Amy's ask](https://dsva.slack.com/archives/C04PKJ7FQCE/p1726246717781539): if silent failures are discovered, please let @Cory Sohrakoff, @Julie Strothman, and I know. We need to know the estimated volume of failures that have occurred since April 1, 2024, and the estimated volume of failures that have occurred since the launch of the application (even if we no longer have access to those logs).

AC
--
- [ ] Has spent no more than one day on this task
- [ ] Focus on BIP, BGS, and RabbitMQ services and use checklist to identify vulnerabilities: https://docs.google.com/document/d/1OUyEPhxQZEX9quX9w6aMf7ARVa8a2piA/edit  
- [ ] Partner Team Incident Reports has been updated to reflect this information 
- [ ] Has looked as far back as April 1, 2024
- [ ] Has linked the Partner Team Incident Reports page to the Silent Failures mural board ([link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1726600471661/a02b25ba59b6ee71b37007f47b47ed27ab995a10?sender=u144b768a106b68952f414031))

Resources:
- Incidents response wiki ([link](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Incident-Reports))
- VRO Support Slack Channel
-

**Comment by BerniXiongA6** [comment]
@chengjie8 to reach out to @bianca-rivera to move along this ticket

**Comment by meganhicks** [comment]
@chengjie8 Derek is picking this up because it is time sensitive

**Comment by dfitchett** [comment]
After further discussion with Amy and Megan, this ticket is no longer needed. Silent failure logs for partner teams are more their problem to find and report up to their leadership.
