### ISSUE TITLE
Update Datadog user for postgres due Oct 10

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3493]
The Lighthouse team reached out regarding an announcement they made, which you can find here: GitHub link: https://github.com/department-of-veterans-affairs/lighthouse-di-tenant-support/issues/29

Essentially, they corrected a spelling error in the LHDI RDS Datadog value key, and we now need to make the corresponding update on our end

# AC
- [ ] Datadog user in the devtools pod has been updated to reflect the correct spelling
- [ ] ArgoCD repo has been checked for this change to spelling correction
- [ ] Updates have been completed before or by Oct 10, 2024

**Comment by BerniXiongA6** [comment]
Per @Ponnia-M -- see slack thread: https://github.com/department-of-veterans-affairs/lighthouse-di-tenant-support/issues/29

**Comment by ponny-m** [comment]
Since the datadog credentials were created by LHDI and shared in their folder, I don't have permissions to edit this password to the recommended started. I left a comment on the original ticket link above to inform Gabe and Matt about this and waiting on an update.
