### ISSUE TITLE
svc-bip-api: Detect dropped RabbitMQ connection

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3509]
# Summary
Investigate / Implement possible solution for detecting and alerting connection dropped from `svc-bip-api` to RabbitMQ.

**Comment by dfitchett** [comment]
Other tickets created in lieu of using this.

**Comment by dfitchett** [comment]
[Datadog Dashboard](https://lighthousedi.ddog-gov.com/dashboard/imt-ubp-z29/vro-data-services-bip?fromUser=true&refresh_mode=sliding&from_ts=1725227499039&to_ts=1727819499039&live=true)
* Added chart to detect rabbitmq connection drops with EP Merge Job Failures Overlayed
* Added new monitor detecting drop in rabbitmq connection, and sending alert to [#benefits-vro-alerts](https://dsva.slack.com/archives/C044ZL0PKLL) in slack

**Comment by BerniXiongA6** [comment]
Hey @dfitchett could you size this after the fact? I want to make sure we get this captured in the Sprint 2 delivery metrics. thank you!
