### ISSUE TITLE
Consolidate all on-call data and instructions in one location

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3519]
As the VRO team responsible for on-call duties, it is crucial to consolidate all relevant information in one place. This will ensure that onboarding new teammates to this task is as seamless and straightforward as possible

Previous AC

1. Review both the internal and external wikis and consolidate all on-call related information into a single page. 
2. Organize the content in a logical manner based on on-call priorities. 
3. Once completed, post a link to the consolidated page and share with the team in the engineering channel 

New AC: 

Review the list posted by lisa below and finish the effort

**Comment by lisac** [comment]
As part of AC 1, here's an inventory of where we talk about on-call.

There exists a single page overview titled [On Call Responsibilities](https://github.com/department-of-veterans-affairs/abd-vro/wiki/On-Call-Responsibilities). Let's call that the on-call overview wiki page (**OCOWP**).

There are additional pages that describe expectations of the on-call engineer. Many of those are linked to this **OCOWP**. Some are not. The Slack workflows are not linked to the OCOWP, although some of the slack workflows are referenced from wiki pages that ARE linked from the OCOWP.

  

| id | page | linked from OCOWP  ? |
|--|---|----|
| 1 |  wiki: [On Call Responsibilities](https://github.com/department-of-veterans-affairs/abd-vro/wiki/On-Call-Responsibilities)  (aka the **OCOWP**) | n/a |
| 2 | wiki: [Incident response](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Incident-Response) | Yes |
| 3 | wiki: [VRO Deployment Policy](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Deployment-Policy) | Yes |
| 4 | wiki: [Dependabot --> on-call responsibility](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot#on-call-responsibility-for-dependabot) | Yes |
| 5 | wiki: [Metrics](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Metrics) (eg capturing MTTR) | No |
| 6 | wiki: [SecRel Getting Started](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/SecRel-Getting-Started-on-VRO) | No <br/> note: this is in the private repo |
| 7 | wiki: [Post-Incident reviews](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Post%E2%80%90incident-reviews) | No<br/> touched on in [Incident Response: Step 6](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Incident-Response#step-6-post-incident-review) <br/> note: this is in the private repo |
| 8 | slack workflow [Incident Report](https://slack.com/shortcuts/Ft07BZKNEZ9S/35ced244dde8f7953ddef1fccd01bc26) | No<br/> linked from [Incident Response: Catalyst](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Incident-Response#catalyst)
| 9 | slack workflow [Partner Team Production Deployment](https://slack.com/shortcuts/Ft07NJDR2GF3/7b6a63103aca7c5d70acef3cafedf92d)  | No |
| 10 | slack workflow [Opt-Out Production Deployment](https://slack.com/shortcuts/Ft07N69GQLFM/62182a42b38b91cb223878d73c6e4ced)  | No |
|11 | Recurring GH issue for On-call, eg #3384 #3439 #3499 | No |

**Comment by lisac** [comment]
did not complete. removing my assignment and moving ~back to Backlog~ to Sprint Ready.

**Comment by bianca-rivera** [comment]
Note: pair with @bianca-rivera when picking up this ticket to make sure documentation for Incident Response and Deployment workflows are updated or linked accordingly

**Comment by gabezurita** [comment]
@meganhicks and @bianca-rivera, this still seems worth doing as we'll be on-call for a few more sprints. Here's the On-call overview doc for us to use:
https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-On%E2%80%90Call-Overview
