### ISSUE TITLE
work with LHDI on migration of auth tools 10/21 for one call

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3535]
We need to let Tyler know who is on call:

Link to thread:https://dsva.slack.com/archives/C03UBMAP5JQ/p1727458651948099 

Message from Tyler:

LHDI is planning to migrate our authentication tools mid-October.
Because we cannot run the old and new auth methods in parallel, we need to set a hard date to switch fully over in all environments, and then confirm with you that all of your tools are authenticating properly.
Our current plan is to launch the evening of Friday, 10/18.
We would like to be able to Slack one of your engineers on Saturday, 10/19 to confirm the rollover went smoothly. It would be a 5-20 min time commitment.
What we need from you:
Slack ID for your representative engineer
Confirmation that your engineer can be available 10/19 (you can even give us a time window) -or- a proposed different date within a few days of 10/19"

**Comment by ponny-m** [comment]
Confirmed in the slack thread that I will assist on this task **Monday October 21st**.
