### ISSUE TITLE
Evaluate logic for adding new Flashes

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3537]
Given the new flashes we know about, let's research how we might apply them.

See [the updated Mural here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727297726171/6a772263c4577f5697c52cf7eb2055d76e426833?sender=uf3d2a9320ea286a502077710) and the "Prioritization Tables" section for the Flashes we're considering applying.

Acceptance Criteria:
Understand the LOE for implementing the following (new) Flashes:
- ALS
- Hardship
- Purple Heart
- Medal of Honor
- Death in Service
- Emergency Care
- Foreign Claim

![Image](https://github.com/user-attachments/assets/f10fb7b2-4c97-41dd-adaf-340f39315974)

**Comment by nanotone** [comment]
Using [Appendix E. Index of Corporate Flashes and Special Issues](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000179710/Appendix-E-Index-of-Corporate-Flashes-and-Special-Issues%3FarticleViewContext=article_view_related_article#2f) as the starting point for understanding what circumstances should result in flashes being added --

**Amyotrophic Lateral Sclerosis**
>Apply when a claim for benefits involving Amyotrophic Lateral Sclerosis (ALS) is received and remove if the claim is denied due to no diagnosis of ALS.
- Implementation: apply flash when a contention for increase has DC 8017 or a new contention is classified as ALS
  - The classification for ALS is 9007 (Neurological other System), which also includes other conditions like dysphagia, fibromyalgia, migraines, etc. So it is not possible to identify ALS with the current CC API; it would need to return the matching UI term. See https://github.com/department-of-veterans-affairs/abd-vro/issues/3398#issuecomment-2321593481
- Question: How does the flash get removed at claim denial time? Is that something we have to worry about?

**Hardship**
>Use when a claimant states that they are experiencing extreme financial hardship and submits documentation to support the assertion.
>Reference: For more information, see [M21-1, Part X, Subpart i, 1.3.a](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177939/M21-1-Part-X-Subpart-i-Chapter-1-Priority-Processing-Programs-and-Special-Requirements).
- Append the Hardship corporate flash to a claimant’s record when extreme financial hardship has been adequately demonstrated.
- Documentation to support the assertion of extreme financial hardship includes, but is not limited to,
  - an eviction notice or statement of foreclosure
  - notices of past-due utility bills, and/or
  - collection notices from creditors.
- Question: Does va.gov have the capability to collect this documentation at 526 submission time? Or at any point in a va.gov pathway?

**Purple Heart**
**Medal of Honor**
No additional guidance provided by Appendix E.
- Implementation: Purple Heart and Medal of Honor data may be available from the Lighthouse [Veteran Service History and Eligibility API](https://developer.va.gov/explore/api/veteran-service-history-and-eligibility), but I don't see it in the schema. It's worth asking them if any of their upstream data sources provide it. VA Profile is another possibility, although vets-api already has an integration and I don't see any PH/MOH data there.
  - There is a BGS VetRecordService which provides access to fetch Veteran data from CorpDB and BIRLS (a related older VBA database), and both the mock data and WSDL documentation make mention of PH/MOH fields.

**Death In Service**
> Use when a Veteran died in service.
- Question: Does this apply to va.gov at all?
- Implementation: Not sure if there is data specifically for death in service, but Veteran death date data is available from BGS (both the VetRecordService and ClaimantService), and service history data is available from LH, so presumably a simple date comparison would work as well.

**Emergency Care**
> Use when a character of discharge determination is received from the Veterans Health Administration (VHA) under the Secretary’s Emergency Care Mental Health Initiative.
> Reference:  For more information, see [M21-1, Part XIII, Subpart i, 3.B](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000173782/M21-1-Part-XIII-Subpart-i-Chapter-3-Section-B-Healthcare-Eligibility-Determinations-for-Former-Service-Members-Discharged-Under-Other-Than-Honorable-OTH-Conditions).
- If Box 16 of VA Form 20-0986 is checked or if remarks in Box 17 clearly indicate that emergency (as opposed to routine) mental health care is requested
  - 20-0986 is the Eligibility Determination For Character Of Discharge (COD) Request Form
- If the former service member’s COD was deemed dishonorable for VA purposes, but the former service member was found eligible for health care benefits under 38 U.S.C. Chapter 17
- Question: I don't think this applies to any of the va.gov pathways either?
- Implementation: It seems like there would be a lot of procedural complexity to understand here, but character of discharge data should be available from either the LH Veteran Service History API and/or VA Profile.

**Foreign Claim**
> This is a system-generated flash when the claimant resides in a foreign country and automatically removed when the scenario changes.
> Foreign claim flashes are not applied to residents of a U.S. Territory or the Philippines.
- Implementation: Veteran's current address should be available at 526 submission time, so this one should be pretty straightforward.
- Question: We could conceivably also look into removing a Foreign Claim flash if it's already applied when a 526 with a non-foreign address is received. But that may be out of scope.
