### ISSUE TITLE
Onboard Gabriel Zurita to VRO

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/abd-vro#3549]
Welcome, Gabriel! We are excited to have you on the team! 

This ticket lays out some logistical to-dos alongside areas of focus for getting up to speed on the VRO team and our work. 

### To be done for you (by Agile 6)
- ~Get fingerprinted~ (n/a)
- [x] Get invited by your Delivery Manager to DSVA, Lighthouse, and Slack Channels (@vro-team, @vro-eng) -- After you receive favorable SAC adjudication
- [x] Get introduced to #benefits-onboarding channel (to kick off OCTO onboarding steps, cc: Cory S. and Julie S.) and the #benefits-vro team channel  
- [x] Added to recurring team meeting invites   
- [x] Invited to the OCTO Benefits Delivery Team room in the VA Mural Workspace (as a guest)  
- [x] Added to VA Github Org ([form here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new/choose)) 
  - [x] Added to [OCTO-VRO GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/octo-vro/members) to have access to VRO's GitHub repos
  - [x] Add to [VA-ABD-RRD GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/va-abd-rrd/members) to have access to VRO's LHDI deployment environments

###  To do (by you)
- [x] Share your Github username to @BerniXiongA6 so you can be added to the VA Github org and relevant Github teams
- [x] Join relevant [slack channels](https://docs.google.com/spreadsheets/d/1c3e6SVuhVz3q4bh1qf5jj25EmusCd3NVXhDjSIpr9yk/edit#gid=1020923043) -- _you don't have to join ALL these channels; start with the #benefits-vro-* channels and you can expand from there as you get more involved in the work. Feel free to ask the team in #benefits-vro if you're wondering whether to join a particular channel._
    - [x] **Most relevant channels for you**: #benefits-vro (our team channel for coordination across the VRO team), #benefits-vro-engineering (engineering-specific collaboration for the VRO team), #benefits-vro-support (primary channel for collaboration with VRO partner teams building on the platform), #benefits-portfolio (cross-team collaboration channel for all teams in the portfolio) 
- ~Go through Benefits Portfolio onboarding materials and onboarding buddy meetings (see #benefits-onboarding channel in Slack; you'll be tagged there with your onboarding buddy assignments and materials to review)~ (n/a)

- Review the following materials:
    - [x] The [VRO Wiki page](https://github.com/department-of-veterans-affairs/abd-vro/wiki/) then set up a code walkthrough meeting with an engineering team member (you could ask the team at a near future VRO Team Scrum ceremony or on VRO Slack channel)
        - [x] Review other dropdown folders to the right of the [VRO Wiki page](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Amida-Hand-off-Resources)
        ~- [ ] Pair with @chengjie8 and spend time auditing VRO's wiki, making updates, deleting unnecessary pages, and filling in any knowledge gaps.~ Doing this as a follow-on: https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3593
    - [x] The [VRO Engineering Onboarding doc](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Engineer-Onboarding) 
        - [x] This includes the set up of your [local environment](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Local-Setup) and starting to familiarize yourself with the code. Please contact your team for assistance or post any errors you can't figure out on the #benefits-vro-engineering channel.
    - [x] The [VRO Mural page](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697222300764/071b9570f3bf4a8a678a547a8d3ccd9410e977df?sender=ua51760517335df21b3099342) 
    - [x] Watch [this demo](https://lighthouseva.slack.com/files/U02U2PFQT3J/F0549C2H2D6/secrel_pipeline_and_sde.mp4) from the Lighthouse Delivery Infrastructure (LHDI) team on the SecRel pipeline and SD Elements

- Set up short 1:1's with your fellow VRO team members to learn more about what they do/how they support the VRO team:
    - [x] Megan H. @meganhicks (Product Manager)
    - [x] Kyle B. @brostk (Software Engineer)
    - [x] Cheng @chengjie8 (Software Engineer)
    - [x] Ponnia M. @Ponnia-M (DevOps Engineer)
    - [ ] Lisa Chung @lisac  (Software Engineer)
    - [x] Bianca R. @bianca-rivera (UX Designer / Researcher)
    - [x] Derek F. @dfitchett (Shared between EE team and VRO team / Software Engineer Lead)
    - [x] Katelyn C. @katelyncai (Shared between EE team and VRO team / UX Designer / Researcher Lead) 
    - [x] Berni X. @BerniXiongA6 (Shared between EE team and VRO team / Delivery Manager)
- [x] Ask in the daily scrum meeting where you can pair with other engineers
- [x] When you get a VA.gov email address:
    - [x] Add it to your Github account
    - [x] Let Berni know so she can add you to Sharepoint and Okta
    - [x] When you get an Okta account (you'll be notified to your VA email), ask Berni to help you request Datadog access for VA.gov and Datadog access for LHDI (two separate environments)
    - [x] Get access to [PagerDuty](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-PagerDuty)
- [x] Learn how PTO is communicated within our team. There are **three places** where we have to communicate our PTO:
    1. **Slack**
    2. **Outlook calendar** (after VA access has been granted)
    3.  Our **Google Shared Team Calendar** (Berni will add you)
  
- [x] Slack @BerniXiongA6 if any of the items to be done for you are not yet done or are blocking you.

_NOTE: As you review all the material in this ticket, please help us improve it by pointing out what's missing or out-of-date and adding to it with other useful info you come across!_

**Comment by gabezurita** [comment]
Made two follow-on issues to address onboarding and wiki improvements:
* https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3592
* https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3593
