### ISSUE TITLE
Set up Generic Python Project 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3552]
**User Story**: 

As a VRO Platform, we need a base Python project template to kickstart development with pre-configured code quality checks and linting, ensuring that the project maintains high standards from the outset.

Acceptance Criteria:

- [x] Folder Structure: The project should have a well-defined, scalable folder structure to accommodate future development.
  - [x] folders should include unit tests and integration tests   
- [x] Linting/SCA Library: A library for linting and static code analysis (SCA) should be included and configured.
- [x] Type checking the library mypy. should be included and configured.  
- [x] Pre-commit Hooks: Pre-commit hooks must be configured to enforce linting and code quality checks before commits.
  - Not doing, as these can be done on the repo as a whole in `abd-vro` 
- [x] Docker Entrypoint file: A file to be used by Docker Compose file should be provided to enable local development with the required services.
- [x] Hello World App: A simple "Hello World" application should be included to verify that the setup is working end-to-end
- [x] Add to Wiki

**Comment by dfitchett** [comment]
New repo: https://github.com/department-of-veterans-affairs/abd-vro-skeleton-projects

**Comment by dfitchett** [comment]
Added this section in wiki: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Software-Conventions#starter-projects
