### ISSUE TITLE
Structure Single Page App for Streamlit 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3554]
**User Story**: 

As a VRO Platform, we need to structure the application in a way that allows new single-page applications (e.g., contention events, claim events, EP merge data, other BIE events) to be added easily and efficiently.

Acceptance Criteria:

Page Structure:

- [x] There should be a Home Page to serve as the main entry point for the application.
- [x] A second page should link to the CC Page, setting up a framework for future single-page apps.
- [x] No Data Requirements

**Comment by brostk** [comment]
https://docs.streamlit.io/develop/concepts/multipage-apps
