### ISSUE TITLE
BEP aka BGS Testing Support 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3569]
As a VRO Platform Engineer responsible for maintaining the BGS Application, I need to follow the BEP Migration cutover plan to ensure continuous deployment capabilities for the VRO BGS service and maintain the stability of the VRO platform.

NOTES
The BEP Cloud Migration WebTest Cutover Plan: 
**Key Dates and Action Items**

- [x] By 9/20/2024 all WebTest customers must create a plan to remove on prem WebTest from their promotion path
  - NOT DOING, we do not have any automated testing involving this environment. 
- [x] By 9/20/2024 all WebTest customers must provide a testability matrix to use during Cloud WebTest Testing
- [x] Please fill out this form with your matrix attached or linked
- [x] 10/21-11/01/24 Provide testing support during stabilization period
- [x] FY25Q1 Conduct Cloud WebTest regression testing and sign off

AC: 

Complete action items 1-3 and support BEP Testing on 10/21
work with Sarah Flaherty
m: (727) 483 4653
BAH email: flaherty_sarah2@bah.com
VA email: sarah.flaherty2@va.gov
PDF pasted below in comments

**Comment by meganhicks** [comment]
[BEP Cloud Migration WebTest Customer Call 9.24 (1).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d6d468a409547d694f5c75e30e1fcb3506c4a4a/BEP%20Cloud%20Migration%20WebTest%20Customer%20Call%209.24%20%281%29.pdf)

**Comment by dfitchett** [comment]
blocked until DNS cutover on 10/21 for integration / end to end testing.
