### ISSUE TITLE
Incident Reported: RabbitMQ non-prod pods not starting

### ISSUE THREAD

**Issue by ponny-m** [department-of-veterans-affairs/abd-vro#3574]
October 8th, 2024 @ 11:17am
Reported by: Derek Fitchett (VRO)

Description: 
RabbitMQ pods in different envs not starting properly causing disruption in other VRO apps (BIE-Kafka). 

Possible cause:
During investigation of ArgoCD events and RabbitMQ logs, I noticed that this break occurs after making [changes](https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault/pull/125) to env variables to capture the appropriate environments dynamically when setting up our monitors for Rabbitmq on DD. 

Solution:
Fixed the [env syntax](https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault/pull/127) and Rabbitmq pods are back and running. 

Application non-functional: Yes

Blocker: YES

Slack thread in #benefits-vro-engineering: https://dsva.slack.com/archives/C04QLHM9LR0/p1728400645494179

**Comment by BerniXiongA6** [comment]
Hey @Ponnia-M could you point this ticket after the fact so that we can get this captured on the delivery metrics? Thank you!

**Comment by ponny-m** [comment]
@BerniXiongA6 I can't find this ticket on Zenhub to size and sizing isn't a feature on github tickets. Let me know if this can be recreated on Zenhub for metrics purposes.
