### ISSUE TITLE
Upgrade to Secrel to Version 6

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3577]
Luke Strebel
  8:04 AM
:mega: @here, SecRel v6.0.0 was just released as a major upgrade!
The primary feature of this release are the use of new github runners. These runners are much faster! Where v5 runners took 3-6 min (and often longer) to pick up jobs, v6 generally take less than a minute. :sonic-run:
Additionally, SDE Gate check now includes counts by status and the number of tasks remaining to be verified by app assessor.
:bangbang: Changes Required :bangbang:
The old runners will be decommissioned on October 9th after which SecRel v5 will no longer function!
Before this date, teams must update their manifests to reference v6 of the pipeline
:blob-help: Please reach out in #lighthouse-delivery-platform-support if you have any questions for @lighthouse-di-secrel or jump into Office Hours now! (edited) 

Link: https://lighthouseva.slack.com/archives/C0762A6SYCA/p1727276673797699

**Comment by BerniXiongA6** [comment]
Hi @Ponnia-M could you point this ticket after the fact? Thanks!
