### ISSUE TITLE
First pass on LOE for flashes + special issues

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3585]
As we discussed in our ad-hoc refinement meeting today:

- Based on our previous research into [these flashes and special issues](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727297726171/6a772263c4577f5697c52cf7eb2055d76e426833?wid=0-1728495551141&outline=open) tag each one with rough LOE estimate (low/med/high)
- Add any notes/call-outs for each (if needed)

**Comment by dfitchett** [comment]
✅  Added LOE estimate and a few notes to mural.
