### ISSUE TITLE
Follow up on actions items for Enablement Team from VRO workshop

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3686]
The team identified the following questions that need answers in their workshop:

1. Would the Enablement Team like a VRO case study to be documented and saved for the Benefits Portfolio to provide thorough records of the experiment in case of future platform development?
2. Should members of the VRO team migrate all documentation stored in personal Google Drives, or will the VRO wiki also be decommissioned?
3. Would the Enablement Team like the VRO team to conduct a final partner team survey?
4. Does the Enablement, CC, or EE team want any EPmerge or contention data saved before it is deleted?

Acceptance Criteria: 
- [x] These questions have been raised to VRO Enablement Team.
- [x] VRO Enablement feedback has been shared them with the team.

**Comment by meganhicks** [comment]
Update for AC # 4. 
Mack is consulting with his developers about the EPMerge data and will update us soon.
Yurena, Derek, Tyler, and I met to discuss contention events, and the CC Team expressed interest in obtaining one month of data for historical analysis if it’s feasible. They specifically requested all data from August.

**Comment by BerniXiongA6** [comment]
Update for AC # 1: (VRO Case Study)

- Enablement can see value in doing a lighter weight version of what we did for RRD ([SharePoint link](https://dvagov.sharepoint.com/:b:/r/sites/vaabdvro/Shared%20Documents/RRD/RRD%20Project%20History.pdf?csf=1&web=1&e=243DfN))
- If that link doesn't take you directly to the file in the Benefits Portfolio's SharePoint folder, the 22-page Sharepoint document is called "Rapid Ready for Decision (RRD) Project History" that was dated August 2023 and saved in the RRD sub-folder.

**Comment by BerniXiongA6** [comment]
Update for AC # 2: (which VRO documentation to migrate, and will VRO Wiki be decommissioned)

- Engineering documentation, design docs, product briefs, source data for any research efforts, etc. should be moved to Sharepoint if not already there
- Additionally: meeting notes, Streamlit vs. pgAdmin evaluation, project risk documentation, etc. Anything project-related should live in SharePoint or Github
- Per policy, Cory doesn't think the Github repository can be deleted but it can be archived (made read-only) when the transition is complete, so the documentation will live on, but would no longer be able to be edited.

**Comment by BerniXiongA6** [comment]
Update for AC # 3: (final partner team survey)

- The enablement team hasn't discussed this yet -- will get back to us with an opinion once they do

**Comment by BerniXiongA6** [comment]
Update for AC # 4: (EPmerge or contention data to save before deleted)

- Enablement believes any data export should be driven by partner team request

**Comment by meganhicks** [comment]
I have created follow up tickets for AC 1 and 2 in the next sprint. We have also clarified partner team requests and additional tickets have been created.
