### ISSUE TITLE
Verify certs expiring in December and create a plan

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3698]
LHDI has notified Berni and Megan that VRO has certificates due for renewal in December. This ticket is to investigate which certificates need renewal and develop an efficient plan for handling this, considering the VRO decommissioning.

Tasks:

Identify which certificates need to be renewed.
Make a recommendation to the team on how to proceed.
Create tickets for any additional work required.

**Comment by brostk** [comment]
My limited understanding of the team's use of certs makes me think we'll need to verify the expiration on any of our certificates which are used by our apps (bgs-api and bip-api use the same one, bie-kafka I think uses its own; partner teams don't appear to use) and replace any which are set to expire soon, if that's our desired direction.  No or little action may be necessary depending on the timeline of the decommissioning. 

We can verify the expiration using either `keytool -list -keystore keystore.p12 -v` or `openssl pkcs12 -in keystore.p12 -nodes | openssl x509 -noout -enddate` in a pod terminal via Lens.

**Comment by meganhicks** [comment]
Gabriel said he is checking on this on a thread in slack with Berni and I.

**Comment by meganhicks** [comment]
Confirmed these are the certs from LHDI
From Gabriel Villegas:
Here are the certs. Let me know which you want to renew.
va-abd-rrd-prod-tls
va-abd-rrd-dev-tls
va-abd-rrd-prod-test-tls

**Comment by brostk** [comment]
Some notes:

- The above certificates are expiring 12/01/2024
- svc-bgs-api and svc-bip-api share certs
- svc-bie-kafka was created by the bip team, but I can't find references in our code to where the certificate is used
  - this cert in sandbox has been expired in March; need to investigate whether the cert is even used
  - sandbox password worked, but other regions do not; further indication the cert isn't used by the app
- svc-bgs-api's keystore in QA expired 10 months ago, but the pod has been healthy
  - need to investigate whether the cert is even used by the app
- va-abd-rrd-dev-tls will be renewed and shared between bgs-api and bip-api across all lower environments
- [These instructions](https://redesigned-adventure-wgv3p3l.pages.github.io/phase-3-development-and-production-readiness/deploy-your-project-to-dev/manage-tls-certificates/) will be followed to create the certificates, which we will convert to pkcs12 using [these instructions](https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-APIs#pkcs-12-files).  
  - The converted keystore.p12 will be uploaded to Vault for use by our apps
