### ISSUE TITLE
VRO Engineer Onboarding - [ Julius Ahenkora ] 

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/abd-vro#3702]
# Engineer Onboarding Checklist

Welcome to the Virtual Regional Office (VRO) team! We are excited to have you onboard.

This document will streamline your onboarding process and reduce the startup time needed to ramp up on VRO.

*NOTE*: This issue template can be edited [here](https://github.com/department-of-veterans-affairs/abd-vro/issues/templates/edit). As you go through onboarding, you can add other pages or resources to this checklist if you find them helpful. If you encounter broken links or outdated information, please make any necessary updates or ask for help fixing them!

### Onboarding Buddy and Collaboration (After you've received successful SAC adjudication, your Delivery Manager will help you gain access to these)

- [x]  **Get added to the `#benefits-onboarding` Slack channel**.
    - [x]  Complete onboarding procedures in the Slack Canvas.
    - [x]  Provide your role, email, and team for onboarding buddies.
- [x]  **Go through Benefits Portfolio onboarding materials and buddy meetings**.

### Pair Programming and Code Walkthroughs

- [x]  **Set up code walkthrough meetings with engineering team members**.
    - [x]  Ask during scrum ceremonies or on Slack.
- [x]  **Ask to pair with other engineers** during daily scrum meetings.

### Meetings and Communication

- [x]  **Get added to recurring team meetings** (if the Delivery Manager hasn't already invited you) such as:
    - [x] Weekly Team Sync
    - [x] VRO Team Scrum.
    - [x] Biweekly VRO Sprint Planning / Review / Retrospective.
- [x]  **cATO Tool:** After you receive successful SAC adjudication, get the VRO Delivery Manager to grant you access to the tool LHDI uses for the management of VRO’s cATO (TODO: Confirm what this is)
- [x]  **Add yourself to the VRO team roster**: Ensure you’ve been added to the VRO team roster [here](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Virtual-Regional-Office-Overview)
- [x]  **Set up team 1:1s**: See the [VRO team roster](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Virtual-Regional-Office-Overview#-who-is-the-vro-team) for who to set up meetings with (reference team members' Slack profiles for calendar URLs to find available times).
- [x]  **Ask in the VRO Team Scrum meeting** where you can pair with other engineers.

### Slack Channels (After you've received successful SAC adjudication, your Delivery Manager will help you gain access to these)

- [x]  **Join relevant Slack channels**:
    - **Team Coordination**:
        - [#benefits-vro](https://dsva.slack.com/archives/C04PKJ7FQCE)
        - [#benefits-vro-engineering](https://dsva.slack.com/archives/C04QLHM9LR0)
    - **Partner Team Channels**:
        - [#benefits-contention-classification](https://dsva.slack.com/archives/C04AZ8T7XN1)
        - [#benefits-employee-exp](https://dsva.slack.com/archives/C01BVF2A3V0)
    - **On-Call Support Channels**:
        - [#benefits-vro-support](https://dsva.slack.com/archives/C01Q7979Z7D)
        - [#team-abd-vro](https://dsva.slack.com/archives/C03UBMAP5JQ)
        - [`#bep-integration-support2077`](https://dsva.slack.com/archives/C05DUAWDVRQ): private channel, you’ll need to be added.
    - **On-Call Alerts**:
        - [#benefits-vro-on-call](https://dsva.slack.com/archives/C0752RWD9T3)
        - [#benefits-vro-alerts](https://dsva.slack.com/archives/C044ZL0PKLL)
    - **VRO Log Channels**:
        - [#benefits-vro-devops](https://dsva.slack.com/archives/C04CA47HV96)
        - [#benefits-slack-alerts-cc](https://dsva.slack.com/archives/C07M0KK4725)
        - [#benefits-slack-alerts-ee](https://dsva.slack.com/archives/C07M0KMK18R)
        - [#benefits-slack-alerts-platform](https://dsva.slack.com/archives/C07LUFSL9R6)
        - [#benefits-vro-vagov-526s-to-mas](https://dsva.slack.com/archives/C0519PXPUCR)

### Microsoft Teams Channels (After you've received successful SAC adjudication, your Delivery Manager will help you gain access to these)

 Get added to the relevant Microsoft Teams channels:

- [x]  [BIP Microsoft Teams](https://teams.microsoft.com/l/entity/2a527703-1f6f-4559-a332-d8a7d288cd88/_djb2_msteams_prefix_3931627218?context=%7B%22subEntityId%22%3Anull%2C%22channelId%22%3A%2219%3A38316fe7e5bc49e8a984da519a70e1df%40thread.tacv2%22%7D&groupId=007f7821-5d9f-4f4f-b0fc-0e0a24ee625f&tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&allowXTenantAccess=false)
- [x]  [BGS Microsoft Teams](https://teams.microsoft.com/l/channel/19%3A38316fe7e5bc49e8a984da519a70e1df%40thread.tacv2/Product%20-%20BEP%20-%20General?groupId=007f7821-5d9f-4f4f-b0fc-0e0a24ee625f)

### GitHub Access (After you've received successful SAC adjudication, your Delivery Manager will help you gain access to these)

- [x]  **Get added to the [VA GitHub organization](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new/choose)**.
    - [x]  Provide your GitHub username to your Delivery Manager or team lead.
- [x]  **Get added to relevant GitHub teams**:
    - [x]  [OCTO-VRO GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/octo-vro/members) for repo access.
    - [x]  [Benefits VRO Engineers](https://github.com/orgs/department-of-veterans-affairs/teams/benefits-vro-engineers/members) for additional privileges.
    - [x]  [VA-ABD-RRD GitHub team](https://github.com/orgs/department-of-veterans-affairs/teams/va-abd-rrd/members) for deployment environments.
        - [x]  For "dangerous" actions, get added to [VRO-RESTRICTED](https://github.com/orgs/department-of-veterans-affairs/teams/vro-restricted/members).
- [x]  **Set up GitHub permissions**:
    - [x]  Ensure you have the GH permissions to bypass PR requirements and allow force pushes to the `main` branch of `abd-vro`.

---

## Local Environment Setup (After you've received successful SAC adjudication, your Delivery Manager will help you gain access to these)

- [x]  **Set up your [local environment](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Local-Setup)** and test services.
    - [x]  Note any issues and update the Local Setup page.
    - [x]  Seek assistance on the `#benefits-vro-engineering` channel if needed.

---

### VRO Wiki
Note: The [VRO Wiki](https://github.com/department-of-veterans-affairs/abd-vro/wiki) needs to be updated, and various items must be cleaned up. Please look at this [GH issue](https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3593) and [Slack Canvas](https://app.slack.com/client/T03FECE8V) for details (and don't hesitate to help clean-up as you onboard). The below docs are up-to-date and should suffice for onboarding:
- [x]  [Team Overview](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Virtual-Regional-Office-Overview#-who-is-the-vro-team).
- [x]  [VRO-Priorities](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-priorities) - the essential item here is the [VRO Roadmap Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692641350848/759d1c27c77f2dfe4ad238487352154f6eb0d06a).
- [x]  [VRO Engineer Overview](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Engineer-Overview).

### Murals

- [x]  **VA's Benefit Portfolio Organigram**: [Mural Link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678236223248/ef60b22feff4aa22c594256683b81988abc1f181?sender=u5e5c57ecc5136069f64f2819).
- [x]  **VRO's Working Agreements**: [Mural Link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697222300764/071b9570f3bf4a8a678a547a8d3ccd9410e977df?sender=u5e5c57ecc5136069f64f2819).

### Videos

- [x]  **Watch**:
    - [x]  ["The Way We Work" presentation](https://us06web.zoom.us/rec/share/sHRSblAbF229tQpj7-Nqmmdi7Zb5bWclCd0lqMMdGAttuaJZDByZy8C7vi1BO9Mo.7XuVLn108mwIpnQj?startTime=1680030182000).
- [x]  **Optional**:
    - [x]  [LHDI Team Demo](https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1681327320119849?thread_ts=1681304404.488959&cid=C03UA9MV1EH) on SecRel pipeline and SD Elements. Note: this requires being added to the LHDI Slack instance. May be outdated.
---

### VA Email and Tools (After you've received successful SAC adjudication, your Delivery Manager will help you gain access to these)

- [x]  **When you receive your [VA.gov](http://va.gov/) email address**:
    - [x]  **Add it to your GitHub account** via [settings](https://github.com/settings/emails).
    - [x]  **Inform your Delivery Manager** for SharePoint and Okta access.
    - [x]  **Request Datadog access** for VA.gov ([instructions](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog)) 
    - [x] **Request Datadog access** LHDI ([instructions](https://redesigned-adventure-wgv3p3l.pages.github.io/phase-3-development-and-production-readiness/configure-and-use-observability-tools/request-lhdi-datadog-access/#get-datadog-access)).
        - [x]  **Datadog Monitoring**: Review [DataDog Monitoring](https://github.com/department-of-veterans-affairs/abd-vro/wiki/DataDog-monitoring).
- [x]  **Access VA's Citrix Access Gateway (CAG)**:
    - [x]  Request copy-and-paste permissions via [this article](https://yourit.va.gov/va?id=kb_article_view_yourit&sys_id=f96381201ba6a99048a36242604bcbcb&table=kb_knowledge).
- [x]  Get added to [SDE for LHDI](https://sde.lighthouse.va.gov/bunits/va/abd-vro/abd-vro/tasks/phase/activities/).

### PagerDuty and On-Call Rotation [NOTE: This step might be skipped given the shifting priorities of VRO Team, please check with Delivery Manager before starting these tasks]

- [x]  **When ready to join on-call rotation**:
    - [x]  Request a PagerDuty account in [`#vfs-platform-support`](https://dsva.slack.com/archives/CBU0KDSB1).
    - [x]  Request to be added to the `VRO Benefits` team.
    - [x]  **On-Call Responsibilities**: Review [On-Call Responsibilities](https://github.com/department-of-veterans-affairs/abd-vro/wiki/On-Call-Responsibilities).

### PTO Communication

- [x]  **Understand PTO communication** within the team:
    - [x]  **Slack**: Notify appropriate channels.
    - [x]  **Google Shared Team Calendar**: The Delivery Manager will add you to this calendar. Be sure to keep your PTO on here.

---

## Conclusion

As you go through the onboarding process, please don't hesitate to contact your team members for help. If any items are blocking you, please notify your Delivery Manager or mention it in the `#benefits-vro-engineering` Slack channel.

We're excited to have you on the team and look forward to collaborating with you!

**Comment by jahenkor-navapbc** [comment]
Updated Local Environment Instructions:
https://dsva.slack.com/archives/C04QLHM9LR0/p1733440262755129
Also updated the Wiki Page with revised Mac instructions. https://github.com/department-of-veterans-affairs/abd-vro/wiki/Local-Setup
