### ISSUE TITLE
August Contention Data for the CC Team

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3715]
As a data analyst on the CC Team, I need a full copy of August contention event data for historical analysis before the VRO team decommissions their RDS instance as part of the project decommissioning process.

Acceptance Criteria (AC):

Retrieve all contention event data for the month of August. Refer to the following links for guidance: https://spacelift.io/blog/kubectl-cp and https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/AWS-RDS-Integration#access-vro-rds-postgres-dbinstance
Ensure the data pull can be exported as a CSV file and is saved to the VA SharePoint in a location agreed upon by Tyler Spangler.

**Comment by meganhicks** [comment]
@PaulKBaumann Tyler told old reports were saved here: https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?fromShare=true&ga=1&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FVRO%20%2D%20Virtual%20Regional%20Office%2FEngineering%2FVRO&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72

**Comment by meganhicks** [comment]
open ticket with LHDI:https://github.com/department-of-veterans-affairs/lighthouse-di-tenant-support/issues/130

**Comment by BerniXiongA6** [comment]
cc: @Joe-cox17 for visibility and awareness (this is the ticket that @PaulKBaumann  is working on that's blocked by LHDI support. The LHDI support ticket with their updates is shared in the previous comment. Paul's on it, but if you could help be another set of eyes (along with VRO Product) since you now have GitHub access. Thank you! cc: @meganhicks @amylai-va

**Comment by brostk** [comment]
August contention data uploaded to [Sharepoint](https://dvagov.sharepoint.com/:u:/r/sites/vaabdvro/Shared%20Documents/Contention%20Classification/Datasets/Contention%20Event%20Data%20From%20VRO/bie_contention_event_202408.csv.zip?csf=1&web=1&e=qTsoAx); waiting on final confirmation from Tyler before marking this ticket Done.
