### ISSUE TITLE
Document EPMerge Plan and seek alignment and add tickets for work

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3723]
As the VRO team responsible for the VRO platform decommission project, we need to develop a clear and concise plan detailing when and how we will shut down the EPMerge application.

Acceptance Criteria:

- Identify the tasks VRO needs to complete to shut down the application.
- Identify the tasks required from the EE teams.
- Create a rough timeline for VRO team tasks.
- Establish a decommission date.
- Seek alignment from EE, VRO, and Enablement Team on plan 
- create stories for VRO tasks 

On 11/12, VRO met with EE and VRO stakeholders, and the following decisions were made:

- EE would like a copy of all EPMerge data currently stored in RDS. Save it as a CSV file, and upload it to SharePoint.
- EE will develop documentation outlining what a reactivated EPMerge application would entail if the VA decides to reincorporate it into the benefits portfolio.
- VRO will send Mack the Sharepoint link to add all documentation to the same spot as the data VRO saves on their behalf. 
- EE will also be responsible for communicating all changes to stakeholders impacted by the shutdown.
- The BEP group informed us that when we stop calling their services our account should automatically lock. We need to notify them anyways when this is completed so they can decommission the application and service assignments. 
- The Enablement Team recently shared that they might want to implement this in a different space. Let’s keep this in mind as we develop our plan to shut it down in our space.

**Comment by dfitchett** [comment]
Tasks to complete shutdown:
- (EE) #3754
- (EE) #3755

Once traffic stopped:
- (VRO) #3735
- (VRO) #3757
- (EE) #3758
- (EE or VRO) #3759

Any time:
- (EE) #3760

**Note: All tasks above are included in the [Sprint Goal - EPMerge](https://github.com/department-of-veterans-affairs/abd-vro/issues/3751) epic**

**Comment by dfitchett** [comment]
Plan documented. Work on other tasks can begin upon the completion of #3754 and #3755.
