### ISSUE TITLE
Collect Project documentation and save it to sharepoint

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3734]
Reach out to all team members and collect all project-related documentation, including engineering documentation, design documents, product briefs, research source data, Streamlit vs. pgAdmin evaluation, and project risk documentation. Organize these documents and save them to the VRO SharePoint for centralized access and reference. 

AC: 
All project related documents that exist on gdrive are moved to sharepoint and saved here: https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx

Notes: 
This should be more formal project related documentation

**Comment by dfitchett** [comment]
@meganhicks Could we discuss how to tackle this?

**Comment by meganhicks** [comment]
I am going to chat with @brostk about it.

**Comment by brostk** [comment]
There was an [existing, empty archive folder](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/VRO%20-%20Virtual%20Regional%20Office/VRO-RRD%20Archive?csf=1&web=1&e=QY1Ba7) in the VRO Sharepoint space so I've begun uploading documents there.  So far I have:

- `Data Visibility.docx` and `Streamlit Product Brief.docx` from @meganhicks 
- a collection of various VRO architecture, design, and other notes from @dfitchett 
- a collection of design and research notes from @bianca-rivera 

I'll keep the ticket as "In Progress" while I continue gathering and uploading documentation.

**Comment by brostk** [comment]
A bulk of the files from the [VRO Team](https://drive.google.com/drive/folders/1bnzbTOU72i4kxjSRw-kd83cLefhPd6ra) folder on GDrive were also [uploaded](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/VRO%20-%20Virtual%20Regional%20Office/VRO-RRD%20Archive/VRO%20Team?csf=1&web=1&e=gIQUgQ) under the same archive folder as above.  Marking this ticket closed, though there may be additional documents which will be migrated as they are discovered.
