### ISSUE TITLE
Create requests for CC and EE Collaboration Cycle kick off

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3746]
Work with the EE and CC teams to complete one form per team, per application (MaxCFI and CC Application), to initiate the collaboration cycle. This serves as the first step in migrating these applications to the platform team.

Form found here:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request%2Csitewide+CAIA&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D

Acceptance Criteria (AC):

- A form is completed for the CC Application with input from the CC Team, and a team member is designated to shepherd the process.
- The designated individual will oversee follow-up tasks, ensure they are converted into user stories, and coordinate scheduling the necessary meetings.
- A form is completed for the MaxCFI Application with input from the EE Team, and a team member is designated to shepherd the process.
- The designated individual will be responsible for follow-up tasks, converting them into user stories, and ensuring the appropriate meetings are scheduled.

Notes: 

The platform team has not approved the CC application yet. Doing this work will depend on their approval.

**Comment by meganhicks** [comment]
This has been done for MaxCFI: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98677

**Comment by gabezurita** [comment]
This has been done for the CC Team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/99068
