### ISSUE TITLE
BIE: Remove Argo CD deployments

### ISSUE THREAD

**Issue by geoffrey-nava** [department-of-veterans-affairs/abd-vro#3762]
**Acceptance Criteria**

1. Charts and deployment files are removed from [deploy/svc-bie-kafka](https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault/tree/main/deploy/svc-bie-kafka)
2. `config.json` removed from [apps/svc-bie-kafka](https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault/tree/main/apps/svc-bie-kafka)
3. Verify deployment is removed from ArgoCD
  * If there are any orphaned deployments: In Lens: click any orphaned pods, and there's a property called "Controlled By"; follow that stack and delete the Deployment (it won't have a parent).

BLOCKED BY:
* pending enablement team buy-in from #3766 
* pending BIE team buy-in from #3764

**Comment by bianca-rivera** [comment]
[See latest message from BIE team](https://github.com/department-of-veterans-affairs/abd-vro/issues/3764#issuecomment-2501071157) (@BerniXiongA6)
