### ISSUE TITLE
Notify BIE team

### ISSUE THREAD

**Issue by geoffrey-nava** [department-of-veterans-affairs/abd-vro#3764]
Notify Darrell Neel, Stephen Quick, and Mohietosh Ogill via the slack channel. 

https://dsva.slack.com/archives/C04U8GESRT7

Give them a chance to provide any objections, and if there are any detail them here. Additionally include the slack thread as a link on this ticket.

**Comment by BerniXiongA6** [comment]
Berni contacted BIE Team via email and in Slack (replying to messages previously sent by Megan Hicks / Darrell Neel, BIP Solutions Support ART) of VRO Team's plan to shut down BIE-Kafka service within the current sprint (sprint ending 12/2/2024). See Slack thread reply: https://dsva.slack.com/archives/C04U8GESRT7/p1732573454689229?thread_ts=1730740797.475409&cid=C04U8GESRT7
