### ISSUE TITLE
BIP: Update documentation in Wiki

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#3778]
**Acceptance Criteria**

Ensure Documentation is up to date:
* [BIP APIs](https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-APIs) - to be updated by @brostk 
* [BIP Claims API](https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-Claims-API) - to be updated by @dfitchett

**Comment by BerniXiongA6** [comment]
@dfitchett to update ticket
