### ISSUE TITLE
Streamlit: Remove ArgoCD Deployment

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#3824]
**Acceptance Criteria**
- `config.json` removed from [apps/streamlit](https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault/tree/main/apps/streamlit)
- Verify deployment is removed from ArgoCD
- Verify deployment is removed from Lens (manually delete if necessary)

**Comment by brostk** [comment]
config.json has been removed and deployments are confirmed to have been removed from Argo and Lens.
