### ISSUE TITLE
Streamlit: Github Actions / CI cleanup

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#3825]
### Description

Specific GitHub workflows or test runs within the `abd-vro` repository are associated with shutdown services. These workflows and tests should be commented out to avoid unnecessary execution and dependable/security updates.

---

### Acceptance Criteria

1. **Code Changes**  
   - Identify all GitHub workflows or test runs related to the disabled or inactive services.  
   - Comment out the code for these workflows/tests to prevent their execution.

2. **Documentation**  
   - Add clear comments above the commented-out code explaining:
     - Why the workflows/tests are being disabled.
     - Any conditions required to re-enable the workflows/tests in the future.

**Comment by BerniXiongA6** [comment]
PR: https://github.com/orgs/department-of-veterans-affairs/projects/871/views/1?pane=issue&itemId=89584118&issue=department-of-veterans-affairs%7Cabd-vro%7C3823

**Comment by geoffrey-nava** [comment]
After reviewing with Derek, we determined there is no work required for Streamlit. Closing this issue.
