### ISSUE TITLE
Make the disability-max-ratings-api repository public

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/abd-vro#3837]
Is this a platform support request?

## Blockers
This issue blocks:
https://github.com/department-of-veterans-affairs/abd-vro/issues/3845
https://github.com/department-of-veterans-affairs/disability-max-ratings-api/pull/5

## AC
- [x] [disability-max-ratings-api](https://github.com/department-of-veterans-affairs/disability-max-ratings-api/) is a public repo

**Comment by gabezurita** [comment]
@dfitchett and @meganhicks this blocks:
* https://github.com/department-of-veterans-affairs/abd-vro/issues/3845
* https://github.com/department-of-veterans-affairs/disability-max-ratings-api/pull/5

**Comment by meganhicks** [comment]
Thanks for the update

**Comment by dfitchett** [comment]
Submitted github platform ticket:
* https://github.com/department-of-veterans-affairs/github-user-requests/issues/25153

**Comment by dfitchett** [comment]
Requirements for repo update: https://department-of-veterans-affairs.github.io/github-handbook/guides/ghec/public-repositories

**Comment by meganhicks** [comment]
pending approval

**Comment by dfitchett** [comment]
Approved.
