### ISSUE TITLE
Snyk setup: Address any vulnerabilities found, and optimize configuration for easier process in future

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#384]
**User Story**

As a VRO engineer, I want to be able to easily identify and address vulnerabilities identified by Snyk scans, so that VRO code is secure and the software maintains continuous ATO.

**Acceptance Criteria**

1. Snyk scans are configured on VRO and any vulnerabilities blocking initial ATO have been addressed
2. Snyk is setup to optimize the process for future deployments

**Comment by yoomlam** [comment]
This includes addressing issues and making improvements related to VRO running through the SecRel pipeline, which runs Snyk and Aqua scans.

**Comment by yoomlam** [comment]
[Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates) has been enabled, and VRO dependencies (for Java, Python, and GH Actions) are currently up-to-date. On a [weekly basis](https://github.com/department-of-veterans-affairs/abd-vro/pull/376/files) or when we [manually run it](https://github.com/department-of-veterans-affairs/abd-vro/network/updates), it will automatically create PRs to upgrade library versions (like [these](https://github.com/department-of-veterans-affairs/abd-vro/pulls?q=is%3Apr+label%3Adependencies+is%3Aclosed)).
Having this will help keep VRO code patched against vulnerabilities and will reduce the work in resolving SecRel alerts, required for deploying to production.

and addressing its known problems: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot#known-problems

**Comment by yoomlam** [comment]
Updating to ensure [SecRel continues to pass](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions)

**Comment by dianagriffin** [comment]
Closing as done, with the knowledge that we'll continue to make incremental improvements
