### ISSUE TITLE
Add metrics and logs for flashes

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3841]
see notes from sprint goals here: https://docs.google.com/document/d/1yuMNUxspvYwGgXKmmx-VdWlZIG-rfD_8HwaamwIi11A/edit?tab=t.0#heading=h.jfkzqdyzdxsr

**Comment by dfitchett** [comment]
PR: 
* https://github.com/department-of-veterans-affairs/vets-api/pull/19630
