### ISSUE TITLE
For iMVP launch, add single issue hypertension claims to vets-api<>MAS claim handoff integration (non-prod)

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#387]
**User Story**

Add single issue hypertension claims to the existing vets-api<>MAS claim handoff integration, so that we are ready to test hypertension claims via this integration according to MAS' development timeline: dev complete 10/7, unit test/UAT complete 10/14. 

**This will not go to prod until the full Integrated MVP is ready to ship.**

All single issue hypertension claims submitted on va.gov (including new claims and claims for increase) should be passed to the MAS endpoint after being established in EVSS, with the exception of:
- claims with pending EPs
- claims for increase where the contention was previously denied. (see: https://github.com/department-of-veterans-affairs/abd-vro/issues/244)
These exceptions should match the existing logic for the claim handoff endpoint, and may not require any additional development.

Note that we do **not** need to map a contention classification, because by the time this goes to production we will have switched our process so that MAS will be classifying contention instead of relying on our mapping.

**Acceptance Criteria**

1. Single issue hypertension claims submitted on va.gov are detected by vets-api, established, and passed to the MAS claim handoff endpoint _in non-prod only_, enabling integration testing.
2. Hypertension claims with pending EPs, and claims for increase where the contention was previously denied, are excluded from being passed to the endpoint. 

**Not included in this work**

This work will not ship to production yet. This effort enables integration testing, but will be bundled into the Integrated MVP launch in ~December.

**Comment by dianagriffin** [comment]
Tentatively assigning to @nanotone, but feel free to trade this off if someone else is able/available to work on it

**Comment by nanotone** [comment]
@dianagriffin The incoming HTN claims for increase are currently also being sent to VRO 1.0 -- this means we're going to start notifying MAS of some claims that already have an attached ARSD?

**Comment by dianagriffin** [comment]
@nanotone No, that's why it's important that this stops at non-prod for the time being!

> This work will not ship to production yet. This effort enables integration testing, but will be bundled into the Integrated MVP launch in ~December.

With the Integrated MVP launch in December, we'll cutover from having HTN claims sent to VRO 1.0 directly from vets-api, and will turn on this new workflow where HTN claims go from vets-api > MAS > VRO iMVP

**Comment by nanotone** [comment]
@dianagriffin Then, does it make sense to use a single feature flag to toggle whether to use VRO 1.0 or MAS? That way, the cutover will be simple and seamless. The downside would be less fine-grained control over the flow in staging/UAT, but it sounds like we might not mind.

**Comment by dianagriffin** [comment]
@nanotone really good question! In terms of controlling the flow of claims (`vets-api -> VRO` vs. `vets-api -> MAS`) I think a single feature flag probably makes sense, but would love @yoomlam's thoughts on this as well. 

I'm not sure I'm grasping this downside: 
> less fine-grained control over the flow in staging/UAT
can you say more about that? Or what alternative might give us more fine-grained control?

**Comment by nanotone** [comment]
I could probably have worded that more clearly; let me try a metaphor. Think of this as two levers we can pull to affect the flow for a single-issue HTN claim for increase:
- it could be sent through VRO 1.0 (which may generate/upload an ASRD, etc) and
- after submission to EVSS, its Claim ID could be forwarded to MAS.

For deploying to prod in December, it's best to hook up the two levers so that pulling the MAS one will un-pull the VRO 1.0 one. But this means we can't have both levers (or neither) pulled, if for whatever reason we want that in staging/UAT. But, I don't know if that would ever be desirable?

**Comment by yoomlam** [comment]
Initial response offering general guidelines:
* If we're doing incremental deploys (e.g., to non-prod), it may be useful to have more fine-grain control.
* If we're doing a big cutover in Dec, a single lever is better to avoid any race-conditions involved in toggling multiple levers.

I haven't seen the product timeline yet and I haven't assessed when we'll need to pull each lever.

**Comment by dianagriffin** [comment]
Confirming from our chat: the more fine-grained ability to toggle _on_ sending single issue HTN claims to MAS and separately toggle _off_ sending single issue HTN through RRD processing in VRO 1.0 will be beneficial for testing in non-prod environments, so that's what we want to go with.
