### ISSUE TITLE
Begin process to establish and test VRO connectivity with EVSS non-prod environments

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#389]
**User Story**

Work with EVSS points of contact (currently, Michael Harlow) to follow their process for establishing and testing EVSS non-prod connectivity for VRO, so that VRO can access EVSS doc upload functionality. Document any parts of the process that would be beneficial to have documented in future.

**Acceptance Criteria**

- Process of establishing and testing EVSS non-prod connectivity is underway and being tracked towards completion.
- Documentation has been created in cases where it has future value. (Up to engineers' discretion what those cases are)

**Not included in this work**

This ticket is just for connectivity, and does not include any of the development to use the EVSS doc upload functionality.

**Notes about work**
See [Slack thread](https://dsva.slack.com/archives/C1VBAHWQL/p1663702082044159) Premal started for reference.

**Comment by yoomlam** [comment]
Add findings to [Integrations: EVSS](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Integrations%3A-EVSS), linked from https://github.com/department-of-veterans-affairs/abd-vro/wiki/External-APIs#evss

**Comment by cweagans** [comment]
Alrighty, I _finally_ have at least _some_ news here: I was able to verify that the hostname for the EVSS service resolves properly from the nonprod environment on LHDI. I was also able to verify that there is a network path (but only with ping).

Based on our call this morning about EVSS authentication, it sounds like there is an IP-based ACL that we'll need to be added to. I've asked for a documented list of egress IPs from the LHDI support channel and haven't received that yet, but once I do, I think we can hand that off to the EVSS folks and we'll be all set.

**Comment by nanotone** [comment]
@cweagans Would it be worth trying to get as far as a TCP handshake (on port 444, was it?) -- or just wait to be added to the ACL?

**Comment by cweagans** [comment]
I believe we agreed to close this during our last sprint planning. Please re-open if I'm wrong.
