### ISSUE TITLE
Rhinitis/Sinusitis/OSA/PC RRD: assemble sample data

### ISSUE THREAD

**Issue by KimLadin** [department-of-veterans-affairs/abd-vro#402]
Pull sample data (ARSD + Lighthouse) for:
Rhinitis
Sinusitis
Obstructive Sleep Apnea
Prostate Cancer

2-3 claims per condition
Include at least one claim that has both Rhinitis and Sinusitis
Would also be good to have more overlaps in the respiratory claims

**Comment by amylai-nava** [comment]
@KimLadin I'm going to close this ticket since you have pulled ARSDs for these conditions ✅ and we're not going to pull LH data anymore 🚫.
