### ISSUE TITLE
Assume no pending EP on last retry

### ISSUE THREAD

**Issue by erogray** [department-of-veterans-affairs/abd-vro#41]
**Current**: 

- When RRD checks EVSS for pending EPs and there’s no response, the claim will ramp off after 11 retries.

**Desired**:

- In the scenario above, RRD assumes there’s no pending EP and continues with RRD processing after 11 retries.

**Assumption**:

- Assuming the issue is rare, it would be better to proceed assuming there is no pending EP — because there is a chance of RRD-ing the claim and that benefit is greater than the risk of letting through an occasional EP400.
- Questions
    - Can we establish a RRD claim through EVSS if there is a pending EP? Or would the EVSS request fail? Current hypothesis is that we won’t be able to establish it
    - If we do RRD and it fails at EVSS, we can use the undo RRD code, and offramp reason of “EP exists”

**Slack thread**: [https://dsva.slack.com/archives/C03296QM2GG/p1650992933290119?thread_ts=1650987048.270949&cid=C03296QM2GG](https://dsva.slack.com/archives/C03296QM2GG/p1650992933290119?thread_ts=1650987048.270949&cid=C03296QM2GG)

**Comment by amylai-nava** [comment]
Closing since this ticket is related to RRD in vets-api and is no longer applicable. cc: @dianagriffin
