### ISSUE TITLE
IncomingClaims: VRO receives hypertension CFI claims from MAS/VBAAP

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#428]
**User Story**

As MAS (a VRO client), I want to send single-issue hypertension CFI (claims for increase) and presumptive (new) claims to VRO, so that VRO can fast-track the claim if possible.

This ticket only provides the API endpoint and quick claim checks in order to return a response.

Requires integration: proxy VRO API through Lighthouse API so that MAS (external to VA's network) can call VRO (which has a non-static IP within LHDI) -- https://developer.va.gov/api-publishing (contact Premal to initiate this)

**Acceptance Criteria**

* VBAAP will send single-issue hypertension CFI (claims for increase) and presumptive (new) claims to VRO
* VRO checks if claim is within scope (shown as an `inScope?` decision point in [the workflow diagram](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-v2-Roadmap#workflow-diagram)).
  - "within scope" for VRO = claim is single-issue hypertension, INCREASE or NEW
  ```
  diagnosticCode: 7101 (hypertension)
  disabilityActionType: "INCREASE" or "NEW"
  ```
  - 11/16/2022 UPDATE: removed `disabilityClassificationCode: 3460 (hypertension) or 3370 (high blood pressure)`
  * If not in scope, VRO ignores it and sends Slack notification to channel `#benefits-vro-alerts`. Preferably respond to VBAAP with an error message.
     * Consider creating an `offrampClaim` Camel route, where claims can be fed whenever VRO cannot fast-track the claim for whatever reason. The route should use the [Slack component](https://camel.apache.org/components/3.18.x/slack-component.html) to send the Slack notification, and then route the claim to the `CompleteProcessing` component (described in #431) to double-check the claim and send it downstream.
     * When a claim is offramped, that offramp status and `offrampReason` should be saved to the DB. When #431 is implemented, consider saving to the DB once in the `CompleteProcessing` component.
  * If claim is within scope, it checks for 3 "anchors" - data elements that should already be set for claims coming from VBAAP:
     * claim's "station" (specifically `temporary station of jurisdiction` (TSOJ)) is set to `398`
     * claim's contention has special issue `Rating Decision Review - Level 1`
     * claim's contention has special issue `RRD`
     * If these are not present, send a Slack notification to channel `#benefits-vro-alerts` with details and stop processing. Preferably respond to VBAAP with an error message.
        - send an email to Slack: https://dsva.slack.com/archives/C044ZL0PKLL/p1664816140072679
* For only single-issue hypertension CFI claims (not NEW claims) with sufficient data, VRO queries and assesses health data and generates a PDF, i.e., it routes the claim to the existing `assessclaimdc7101` and `pdfgenerator`, and then to the new `CompleteProcessing` component.

**Not included in this work**

A note about things that should not be considered necessary.

This ticket only provides the API endpoint and quick claim checks in order to return a response. Hypertension CFI claims processing (such as querying or assessing health data or generating a PDF) is already implemented. 

Will be implemented in different tickets:
* processing of hypertension **presumptives**
* uploading PDF to eFolder
* ordering exam
* etc.

**Notes about work**
- proposed VBAAP API Spec: https://gist.github.com/rajesh-Krishnasamy/ed169256ff17f51dc07cb671f450c5ce
- For traceability: this user story corresponds to:
   - "VRO claim notification endpoint: VRO builds an endpoint to receive claim and Veteran data from APCAS to kick off automation"
   - "Automation eligibility logic: Add check for automation eligible claim types to VRO logic"

**Comment by yoomlam** [comment]
When VBAAP sends the ICN to VRO, VRO should store that ICN as part of the Veteran DB record, along with something like an `icnTimestamp` (which indicates when the ICN was provided). The reason is that a Veteran's ICN can change over time, and hence VRO cannot rely on the same ICN being valid for the long term. VRO should NOT be seen as the source-of-truth for the Veteran's ICN, so we should make that more explicit with this `icnTimestamp` DB field.

**Comment by dianagriffin** [comment]
@emilytheis For reference, this is actually the ticket that implements the diagnostic codes mentioned in my comment on #446, which you just mentioned we may need to update based on those codes being out of date

**Comment by dianagriffin** [comment]
copying over from #446 : 
> Small learning re: @dianagriffin and @nanotone comment is that these two classification codes (3460 and 3370) are old, deprecated codes that are really only used by va.gov, and being rejected by VBMS and not used by VBA. So going forward we shouldn't use them as cornerstones of our logic.
> 
> The way one would identify new hypertension claims would be those with a contention name of "Hypertension" or "high blood pressure." I am working with another team to ensure those are classified with the correct, up-to-date classification of "979 (Hearts, Veins, Arteries). That classification code is too generic of a filter to identify hypertension claims, since it is also used for many other heart conditions.
> 
> This is a little bit tricker because contention names can be anything. Since MAS is actually doing the identifying of which claims are eligible from both the mail portal and va.gov, I think this doesn't really affect our decisions now. But those classification codes are not the way MAS would be identifying them.

**Comment by yoomlam** [comment]
I interpret this as:
- VRO doesn't need to double check the `disabilityClassificationCode`
- I suggest VRO store the `disabilityClassificationCode`, along with the `diagnosticCode` and `disabilityActionType` in the DB, so we can review their values over time.

**Comment by dianagriffin** [comment]
@rajesh-Krishnasamy See above comments for updates based on the `disabilityClassificationCode` issue Emily mentioned in our meeting today. (Requirements have also been updated in the ticket description)
