### ISSUE TITLE
Mark claim "RFD" to enable appropriate adjudicator assignment

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#430]
**User Story**

After VRO has processed a claim for fast-tracking, VRO needs to mark the claim as RFD (ready for decision) to enable appropriate adjudicator assignment.

Requires integration with a benefits service system, we're still trying to work out which system ([likely BGS/BIP](https://github.com/department-of-veterans-affairs/abd-vro/wiki/External-APIs#bam-shared-services) (contact Premal/Yoom/Yang/Alex? -- see ticket #388)

**Acceptance Criteria**

1. When there is sufficient health data to fast-track claim, VRO marks it as ready-for-(fast-tracking)-decision (`RFD`)
2. After a PDF is generated and uploaded and the claim is fast-trackable, use a `benefitsSharedServices` microservice to mark the claim RFD.
   - Consider creating a Camel component called something like `CompleteProcessing`, where a claim is sent after an exam was ordered or a PDF was generated (configured as a Camel route). The component would check if the claim is fast-trackable (i.e., there is sufficient health evidence `sufficientForFastTracking=true`), or simply if a `markAsRFD` flag is true, and call the microservice to mark the claim RFD.
   - (In ticket #431, this `CompleteProcessing` will do other things to wrap up the claim for downstream processing. Those other things will also require the `benefitsSharedServices` microservice.)

**Not included in this work**

A note about things that should not be considered necessary.
A client for benefits shared services (encapsulated in a `benefitsSharedServices` microservice) will be needed, but only setting the RFD endpoint is needed. All other Shared Services endpoints are out of scope.

**Notes about work**
- For traceability: this user story corresponds to:
   - "Mark claim "RFD" to enable appropriate adjudicator assignment"

**Comment by dianagriffin** [comment]
@yoomlam It would be ideal if we could go to production with this ticket applying RFD to V1.0 claims as soon as feasible,  _before_ we deliver the full iMVP workflow and integrations. Would we need to implement it any differently to enable that?

**Comment by yoomlam** [comment]
We have several options to deploy a "Mark claims RFD" capability before VRO v2:
1. Implement it in RRD only using vets-api's existing integrations with BGS/VBMS. This would be done outside of and independently of VRO development. This would be the expedient option.
2. Implement and deploy VRO v1.1 that has a mark-claim-RFD API endpoint and mark-claim-RFD functionality. Update RRD to call VRO's endpoint on fast-tracked claims to mark as RFD, after RRD establishes the claim.

**Comment by dianagriffin** [comment]
Am I correct in understanding that neither of those 2 options would provide direct scaffolding for how mark-claim-RFD would be built in VRO iMVP? As in, this would add scope that doesn't get us closer to iMVP?

**Comment by yoomlam** [comment]
Option 2 would be the same mark-claim-RFD functionality as would be implemented in the iMVP. The additional work would be adding a mark-claim-RFD API endpoint for RRD to call.

**Comment by dianagriffin** [comment]
Got it, good to know that's an option. I'm reluctant to add any scope, but will discuss with @amylai-nava @emilytheis in case the trade-off to get RRD claims marked RFD sooner than iMVP may be worth it.

**Comment by dianagriffin** [comment]
> After a PDF is generated and uploaded and the claim is fast-trackable, use a benefitsSharedServices microservice to mark the claim RFD.

@yoomlam not sure it matters but double checking the order of operations here: the workflow diagram in Mural has PDF generation happening _after_ the claim is marked RFD, whereas this states the PDF should be generated first. Is it the ticket or the diagram that should be updated?

**Comment by yoomlam** [comment]
If you look at the [Workflow diagram](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-v2-Roadmap#workflow-diagram), the PDF generation happens first. Mark RFD occurs during the `CompleteProcessing` stage, where station and special issues are also checked/set/unset, which also uses `benefitsSharedServices`. 
Reasoning:
1. Determining if a claim should be marked RFD should happen near the end when all VRO activity is complete, in case we change the criteria for marking a claim RFD. 
2. There's no need to mark it RFD before VRO is almost complete, and may not make since to mark RFD (ready for decision by a user) if VRO still has things to do on the claim.
3. Interactions with `benefitsSharedServices` is consolidated in the `CompleteProcessing` stage, allowing for possible optimizations such as making fewer calls to `benefitsSharedServices`.

**Comment by rajesh-Krishnasamy** [comment]
Sample Request, based on the discussion.

Endpoint:
=========
/files Upload a file with associated provider data

curl -X 'POST' \
  '<baseURL>/api/v1/rest/files' \
  -H 'accept: application/json' \
  -H 'X-Folder-URI: VETERAN:FILENUMBER:<ID>' \
  -H 'Content-Type: multipart/form-data' \
  -F 'payload={
  "contentName": "VAMC_<Contention Name>_Rapid_Decision_Evidence--ccyymmdd.pdf",
"providerData": {
  "contentSource": "VRO",
  "documentTypeId": 1489,
  "dateVaReceivedDocument": "ccyyy-mm-dd"
}
}' \
  -F 'file=@VAMC_Asthma_Rapid_Decision_Evidence--ccyymmdd.pdf;type=application/pdf'

**Comment by dianagriffin** [comment]
@rajesh-Krishnasamy I think that comment was meant for #431 rather than this ticket?
