### ISSUE TITLE
VRO handles PDF upload to eFolder

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#432]
**User Story**

After VRO generates a PDF, VRO uploads the PDF to eFolder.

Requires integration: [EVSS](https://github.com/department-of-veterans-affairs/abd-vro/wiki/External-APIs#evss) (see ticket #389)

**Acceptance Criteria**

1. After VRO generates a PDF, VRO uploads the PDF to eFolder using an `uploadPdf` microservice (the PDF should appear in eFolder or VBMS).
2. The `uploadPdf` microservice will initially use an EVSS client, which should sets the doc type as "ARSD" (Automated Review Summary Document).
   - Consider creating a Camel component called something like `UploadSummaryDoc`, where a claim is sent after a PDF is generated (configured as a Camel route). The component would call the `uploadPdf` microservice. Having a separate Camel component allows for easier testing and more control (and separation of concerns) to for example reroute the PDF for inspection before it is uploaded.
   - (In other tickets, the EVSS client will be replaced with a client that uses Lighthouse Document Services, expected to be released in Jan 2023 or later.)
3. (For OCTO to do) For claims that VRO is processing, RRD does not process them (no data assessment or upload of summary PDF) -- put this behind a `use_vro_imvp` feature flag, which will be enabled once VRO IMVP is deployed.
4. VRO saves to the DB the id, status, location, etc. (enough data for us to track down the PDF in eFolder) of the uploaded PDF.
 
**Not included in this work**

A note about things that should not be considered necessary.
* A client for EVSS will be needed, but only the uploading the document endpoint is needed for this ticket. All other endpoints are out of scope.
* The PDF will need to be updated to the ARSD (Automated Review Summary Document) design, to be done in a separate ticket.

**Notes about work**
- For traceability: this user story corresponds to:
   - "PDF upload with "ARSD" doctype: VRO handles PDF upload to eFolder and sets doc type as "ARSD"; remove PDF upload from RRD"

**Comment by dianagriffin** [comment]
> For OCTO to do) For claims that VRO is processing, RRD does not process them (no data assessment or upload of summary PDF) -- put this behind a use_vro_imvp feature flag, which will be enabled once VRO IMVP is deployed.

@yoomlam @nanotone I believe the necessary feature flag will be put in place by Yang's work on #492 (ie. a feature flag to pass claims to the MAS claim handoff endpoint instead of processing them through RRD in vets-api). Is that understanding correct?

**Comment by yoomlam** [comment]
I only see notification-related changes in Yang's PR. I'll let @nanotone clarify if we need to update code so that
> RRD does not process them (no data assessment or upload of summary PDF)

**Comment by rajesh-Krishnasamy** [comment]
Please clarify that we must upload the evidence using the following API. Wherever I was unsure, I substituted ??? for the values.

Claim Evidence API:
===================
The Claim Evidence Application Programming Interface (API) is file service for handling the storage and management of files supporting VA benefit claims. It serves as a modernized point of entry to files previously only accessible through VBMS eFolder. It is designed for easier implementation by consuming systems, but also with the ability to eventually replace the eFolder logic within VBMS.

Endpoint:
=========
/files Upload a file with associated provider data

curl -X 'POST' \
  'https://editor.swagger.io/api/v1/rest/files' \
  -H 'accept: application/json' \
  -H 'X-Folder-URI: VETERAN:FILENUMBER:987267855' \
  -H 'Content-Type: multipart/form-data' \
  -F 'payload={
  "contentName": "VAMC_Asthma_Rapid_Decision_Evidence--20221027.pdf",
  "providerData": {
    "contentSource": "?????",
    "claimantFirstName": "John",
    "claimantMiddleInitial": "M",
    "claimantLastName": "Smith",
    "claimantSsn": "123456789",
    "benefitTypeId": ??,
    "documentTypeId": ???,
    "dateVaReceivedDocument": "2022-02-01",
    "subject": "subject",
    "contentions": [
      "contention1"
    ],
    "alternativeDocumentTypeIds": [
      ????
    ],
    "actionable": false,
    "associatedClaimIds": [
      "11234"
    ],
    "notes": "[This is a note for a document, These replace editing the document summary]",
    "payeeCode": "??",
    "endProductCode": "????",
    "regionalProcessingOffice": "???",
    "facilityCode": "???",
    "claimantParticipantId": "000000000",
    "sourceComment": "source comment",
    "claimantDateOfBirth": "2022-01-01"
  }
}' \
  -F 'file=@VAMC_Asthma_Rapid_Decision_Evidence--20221027.pdf;type=application/pdf'

**Comment by yoomlam** [comment]
Based on [this thread](https://dsva.slack.com/archives/C1VBAHWQL/p1662659771674139), ARSD (`Automated Review Summary Document`) probably maps to `documentTypeId` of `L1489` according to [this vets-api code](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/evss_claim_document.rb#L52).

If it helps, @nanotone could explore vets-api code and see what values have been used in prod.

**Comment by dianagriffin** [comment]
@nanotone we'd love your help looking at current values used in prod; Amy/I will reach out in slack about it.

**Comment by yoomlam** [comment]
> @yoomlam for my understanding, is that still true if we're not using EVSS? I'm assuming yes, but I'm also not 100% clear on which pieces of data are EVSS-isms vs standard identifiers that apply across different APIs.

Good point! I'm not sure, so someone should confirm against the Claims Evidence API.
