### ISSUE TITLE
Parse OCR annotation data

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#436]
**User Story**

To assess a claim for fast-tracking, VRO needs to parse OCR (including NLP) results from MAS/VBAAP's processing of Veteran documents.

Uses the OCR data from #433

**Acceptance Criteria**

1. The existing `getExtractedHealthData` microservice (from #433):
   * parses the OCR annotations payload into a general VRO `HealthData` model
2. The general `HealthData` model should be able to represent from both health data from Lighthouse Patient Health and VBAAP's OCR annotations. Only data relevant for VRO's claim assessment and PDF generation needs to be modeled; all other data can be ignored.
3. The `GetHealthData` Camel component outputs the claim and `HealthData` for routing to the appropriate data assessor (i.e., `assessclaimdc7101` for hypertension claims)

**Not included in this work**

A note about things that should not be considered necessary.
* Actual usage of the OCR payload is out of scope, i.e., `assessclaimdc7101` does not need to consider OCR-derived health data for this ticket.

**Notes about work**
- For traceability: this user story corresponds to:
   - "VRO parses OCR results data"

**Comment by ENeal49** [comment]
Per Rajesh Krishnasamy with Amida, ticket can be closed since he doesn't have access to Github.
