### ISSUE TITLE
Use OCR data when assessing sufficient health evidence

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#447]
**User Story**

VRO uses OCR data when assessing sufficient health evidence, so that it uses all health data available to the VA.

Dependent on #436, which is dependent on #433.

**Acceptance Criteria**

1. VRO uses OCR data when assessing sufficient health evidence
2. Qualifications for sufficiency using both OCR and Lighthouse health data:
* For NEW and INCREASE claims -- refer to [linked diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1653424407090/46c1aff7e984db50fc9a436b5f647199b31f14a8?wid=0-1664838091145)
  * If there is sufficient health data `sufficientForFastTracking=true` (used and implemented in #430), else `sufficientForFastTracking=false` (used and implemented in #435).
  * If there is some error in reading or interpreting the health data, then `sufficientForFastTracking=null` with `offrampReason=assessorError` or better descriptor.

Determining sufficiency:
* For INCREASE claims, sufficiency is met:
  * If there are at least 4 BP readings in the past year
* For NEW claims, sufficiency is met:
   * If at least 1 hypertension condition is found
     * then 
       * if at least 2 BP readings (elevated or not) are found in the past 2 years, `sufficientForFastTracking=true`
       * else `sufficientForFastTracking=false` (exam will be ordered)
     * else (no hypertension condition is found)
       * if at least 2 **elevated** BP readings are found in the past 2 years, `sufficientForFastTracking=true`
       * else `sufficientForFastTracking=null` with `offrampReason=insufficientHealthDataToOrderExam` (no exam is ordered b/c there's very little or no health evidence data)
  * In summary:
    * Scenario where an exam would be ordered:
      * If at least 1 hypertension condition is found + at least 2 BP readings (elevated or not) are NOT found
    * Scenarios where a claim has sufficient data (and will be set to Ready for Decision (RFD)):
      * If at least 1 hypertension condition is found + at least 2 BP readings (elevated or not) are found
      * If no hypertension condition is found + at least 2 **elevated** BP readings are found 
    * Scenarios where a claim would be offramped:
      * If no hypertension condition is found + no **elevated** BP readings are found

Definitions
  * "hypertension condition" = This data comes from the `Condition` endpoint of the Lighthouse Patient Health API. A hypertension condition is defined by condition data with a ICD-10 code of `I10` or an ICD-9 code of `401.*` (no constraints on the clinical status or onset date), and a `Condition.category` field values of 'encounter diagnosis' or 'problem'.
  * "BP readings" = This data comes from OCR data and the `Observation` endpoint of the Lighthouse Patient Health API.  Elevated BP readings are considered to be readings above 160/100 (systolic/diastolic). 

**Not included in this work**

A note about things that should not be considered necessary.

**Notes about work**
- For traceability: this user story corresponds to:
   - "VRO uses OCR data when assessing sufficient health evidence"

**Comment by dianagriffin** [comment]
Assigning to @amylai-nava to help fill in the qualifications for sufficiency, pending outcomes from the discussions about the logic that you currently have in the works

**Comment by ENeal49** [comment]
Per Rajesh Krishnasamy with Amida, ticket can be closed since he doesn't have access to Github.
