### ISSUE TITLE
Incorporate health evidence from OCR data into the evidence summary document

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#448]
**User Story**

VRO uses health evidence from OCR data when generating evidence summary document, so that it presents to RVSRs all relevant health data available to the VA.

Dependent on the "iMVP" and "Presumptive" ARSD PDF designs.

**Acceptance Criteria**

1. VRO uses OCR data when generating the evidence summary document (a.k.a., "iMVP" and "Presumptive" ARSD PDF)
2. new PDF template for the "iMVP" ARSD PDF design (for CFI claims)
3. new PDF template for the "Presumptive" ARSD PDF design (for new claims)
4. existing PDF template for RRD still works for the RRD endpoints
5. The pdf generator microservice will have a new parameter to choose the PDF template to be used

**Not included in this work**

A note about things that should not be considered necessary.

**Notes about work**
- For traceability: this user story corresponds to:
   - "VRO uses health evidence from OCR data when generating evidence summary document"
   - "Add presumptive eligibility to evidence summary for single-issue presumptive hypertension"
- Detailed PDF requirements: [link](https://docs.google.com/document/d/1oSmrpquL98KoNzMAKITcUiCIaG4fXTcSmir0VJwsQsI/edit?usp=sharing)
- Design: [link](https://docs.google.com/document/d/1RAu4IW8N9OtBVsLh9InOu3pSsUnqa-sgHV99C9CGDu0/edit?usp=sharing)
- VA Logo: [link](https://dsva.slack.com/archives/C01Q7979Z7D/p1668093396443599?thread_ts=1667939829.828849&cid=C01Q7979Z7D)
- Interim type styles: [link](https://dsva.slack.com/archives/C01Q7979Z7D/p1668715983957409?thread_ts=1668455287.286959&cid=C01Q7979Z7D)

**Comment by amylai-nava** [comment]
### Initial template build suggestion

- Create PDF in page size (8.5 x 14" legal) with page numbers 
- Create block with veteran name, file number, and date of summary generation
- Create clickable table of contents
- Build “Schedular Evidence for Hypertension” data table
- Build “Other Medical Evidence for Hypertension” data table 
- Build “Relevant Documents Unavailable for Review” data table
- Formatting and font can be easily modified
- Additional PDF sections and data tables will be incorporated as the design is finalized

[Design prototype](https://docs.google.com/document/d/1k2HdwrqcYZxPdgF02JfKairv6ESwFzFxP0RYuhY1x9Y/edit?usp=sharing) (google doc) can be used for general guidance.
