### ISSUE TITLE
Notify a Slack channel and email addresses of form 526 submissions on va.gov (needed by 10/17)

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#491]
***Target production deployment by 10/14***

**User Story**

- As a designated claim assistant, I want to receive email notifications about newly submitted 526 forms from va.gov, so that I can classify the contention and set the PACT Act special issue as appropriate.
- As a VRO team member, I want to track newly submitted 526 forms from va.gov in a Slack channel so that I have visibility into claims being passed to the MAS claim handoff endpoint

The emails and slack channel should be notified of all form 526 submissions on va.gov after claim establishment, excluding:
- single issue hypertension claims for increase
- claims with pending EPs
- claims where @decision_code is "NOTSVCCON" (See https://github.com/department-of-veterans-affairs/abd-vro/issues/2440)

The notifications should use the same format and include the same information as the notifications currently being tracked in #rrd-to-mas-tracking.

**Acceptance Criteria**

1. Create a new slack channel #va-gov-to-MAS-tracking 
2. Notify the above slack channel plus a set of email addresses (@emilytheis will provide the list) when new 526s are submitted on va.gov, after claim establishment
3. Single issue hypertension claims for increase, as well as claims with pending EPs and claims where @decision_code is "NOTSVCCON" are excluded from these notifications
4. The notifications have the same format and information as the notifications in #rrd-to-mas-tracking

**Not included in this work**

This ticket covers listening for 526 submissions and notifying slack/email when those claims are established, but does not include passing those claims to the MAS Claims Handoff endpoint, which will be handled in a separate ticket.  

**Notes about work**
- Relevant [slack thread](https://dsva.slack.com/archives/C03JRKKD11B/p1664465285664379)

**Comment by dianagriffin** [comment]
@emilytheis Could you review this ticket overall, and especially to confirm:
- it makes sense to create a new slack channel rather than add to #rrd-to-mas-tracking? (I don't think it matters too much, but thought maybe it would be helpful to have a distinction between when we're tracking and passing all 526s to MAS from the prior state of tracking passing the 4 specific contentions)
- it makes sense to exclude the two cases listed in the ticket?

**Comment by ENeal49** [comment]
blocked - need email address from Emily (she's in offsite)
