### ISSUE TITLE
Pass all va.gov submitted 526s to the MAS claims handoff endpoint

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#492]
**User Story**

- For all the claims detected and tracked in https://github.com/department-of-veterans-affairs/abd-vro/issues/491, pass the claim to the MAS claim handoff endpoint after establishment, so that MAS can take downstream actions to apply the "PACT Act" special issue where applicable and run automation where applicable.
- For the claim types that were previously being tracked in #rrd-to-mas-tracking and passed to the MAS claim handoff endpoint, remove the functionality that applies a contention classification code when passing these claims to EVSS for establishment. Ie. these claims should be treated the same as any other va.gov 526 submission, without contention classification being applied by RRD.
- For single issue asthma claims for increase that were previously being processed by RRD automation in VRO, stop applying RRD automation and start passing them along with the other 526 submissions to the MAS claims handoff endpoint after claim establishment (with no additional RRD processing applied).

**Acceptance Criteria**

1. All va.gov-submitted 526 forms are established as claims and passed to the MAS claim handoff endpoint without contention classification being applied by RRD, with the exception of claims with pending EPs and claims where @decision_code is "NOTSVCCON".
2. [Claim types](https://github.com/department-of-veterans-affairs/abd-vro/issues/30) that are currently being passed in production to the claims handoff endpoint no longer have contention classification applied via RRD code, and are treated the same as any other 526 submission from va.gov
3. Single issue asthma claims for increase are no longer sent to VRO via RRD, and are now treated the same as any other 526 submission from va.gov
4. Put this behind a feature flag that we can turn on after integration testing with MAS and getting the green light from and OCTO and VBA perspective. 

**Not included in this work**

Tracking and notifying a slack channel and set of emails about the va.gov submitted 526 forms is covered in https://github.com/department-of-veterans-affairs/abd-vro/issues/491

**Comment by dianagriffin** [comment]
@emilytheis Could you give this ticket a quick review for accuracy as well, please & thanks!

**Comment by nanotone** [comment]
Leaving an implementation note to point out that turning off the asthma-to-VRO flow should be as simple as disabling the `rrd_asthma_compensation` feature flag, which we used back in March to turn on asthma.

**Comment by nanotone** [comment]
Awaiting peer review before merging.
