### ISSUE TITLE
Flip the feature flag to turn on vets-api <> VRO integration for VRO V1.0 launch

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#508]
**User Story**

After:
- VRO receives ATO authorization
- End-to-end testing has confirmed production readiness
- VRO V1.0 has been deployed to production
- Emily & Premal have given the green light 

...Then:
- turn ON the feature flag(s) to start passing single issue **hypertension** claims for increase to VRO
- turn OFF the feature flag to pass single issue **asthma** claims for increase to VRO

...so that VRO V1.0 is officially live in production with single issue hypertension claims for increase.

**Acceptance Criteria**

1. Feature flag for the vets-api <> VRO integration (`rrd_call_vro_service `) is turned on following completion of the pre-requisites listed above
2. Successful processing of a claim has been confirmed by verifying a processed claim in VBMS prod

**Comment by ENeal49** [comment]
Blocked due to pending ATO approval.

**Comment by ENeal49** [comment]
PIA approved.

**Comment by nanotone** [comment]
Waiting for successful end-to-end testing and confirmation of vets-api <> VRO integration in prod.

Updated the issue description to mention that the Flipper toggle to enable is `rrd_call_vro_service`.
