### ISSUE TITLE
Document VRO DevOps information and procedures/policies

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/abd-vro#515]
* Research current processes/policies
* Document them in the wiki

**Comment by yoomlam** [comment]
Specifically, #641

**Comment by ENeal49** [comment]
OCTO DevOps needs to work on this; moving to backlog.

**Comment by dianagriffin** [comment]
@ENeal49 @yoomlam @ahay-agile6 I propose that we close this ticket. It seems like a broad placeholder that covers #641 as well as the outputs of the Amida handoff for devops items. @ahay-agile6 I imagine you'll end up identifying specific documentation tasks from pairing with Ryan for the handoff, and that those could be captured in new tickets. Does that sound right to y'all?
