### ISSUE TITLE
Onboarding for SecRel and Dependabot

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/abd-vro#516]

**Comment by yoomlam** [comment]
[Slack thread](https://dsva.slack.com/archives/C031RRFCHV1/p1665511358346379)

Tasks:
- document Dependabot procedures and policies on the [Dependabot](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot) wiki
- update [Secure Release process](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process) procedures wiki page
- take over maintenance of Dependabot and SecRel workflow

**Comment by sethdarragile6** [comment]
STATUS (per @dianagriffin 's request)

- update [Secure Release process](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process) procedures wiki page

Started creating a more official document [here](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/SecRel-Processing-Guide-(DRAFT)), which (for the most part) the only thing left to do on is to fill out with steps and screenshots I have in other google docs and slack threads.

- document Dependabot procedures and policies on the [Dependabot](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot) wiki

Besides gently updating any existing documentation on the wiki as needed, I'd like to create a "Dependabot Processing Guide" in a similar vein as the SecRel one above, using in part the above mentioned [Slack thread](https://dsva.slack.com/archives/C031RRFCHV1/p1665511358346379)

- take over maintenance of Dependabot and SecRel workflow

This task is more-or-less in play (though I'll likely be needing help along the way). The goal here is once I've wrapped up documenting, it should be in a state where anyone can take over that process.
