### ISSUE TITLE
Wrap up iMVP research

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#558]
clean up files and final documentation for iMVP research

- [x] add to [research index](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit)
- [x] clean up PII in transcripts
- [x] add to participant tracker
- [x] File organization if needed

**Comment by lydiahooper** [comment]
I don't think there's PII in the transcripts bc there was none in the PDFs

Also I think Sudeepti did some file org in Sharepoint, but not sure if it's needed elsewhere as well?

Once the report is in more final form, I can add to the research index

**Comment by carodew** [comment]
I like to remove the RVSR's name, which is usually a pretty quick find/replace function, so that if we captured them saying something wrong or making a mistake it doesn't come back to haunt them if the docs got out.
