### ISSUE TITLE
Remove unused RRD feature toggles

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#576]
Go through all of the following `rrd_`-prefixed feature toggles in vets-api, and for each one consider whether it should be enshrined (either on or off) as we approach iMVP day.

- rrd_asthma_compensation
- rrd_asthma_release_pdf
- rrd_hypertension_compensation
- rrd_add_special_issue
- rrd_mas_disability_tracking
- rrd_mas_all_claims_tracking
- rrd_mas_notification
- rrd_mas_all_claims_notification
- rrd_hypertension_mas_notification
- rrd_call_vro_service
- rrd_new_pact_related_disability

**Acceptance Criteria**

1. For flags that can be set in stone, either open a PR to do so (one PR for multiple flags is fine) or open a ticket to do it later
2. For flags that we still need to be toggle-able, document when we plan to use it, or why we'd want to keep it around despite no concrete plans. A comment on this ticket would be fine.

**Comment by dianagriffin** [comment]
@nanotone I've labeled this low-priority for Sprint I, but acknowledge it will become higher priority the closer we get to iMVP release.

**Comment by dianagriffin** [comment]
Moving this into Sprint I and removing low-priority tag (although it's not yet _high_ priority either)

**Comment by nanotone** [comment]
## Broad contention-specific controls

- **rrd_asthma_compensation** ✅ 🔜 ❌ 
  - determines whether asthma should be diverted to the RRD/VRO flow. Turn off soon, then remove.
- **rrd_asthma_release_pdf** :x:
  - used when we were first launching the asthma pdf. Controls whether the pdf gets included in the final EVSS submission, or just gets uploaded to S3 for inspection
- **rrd_hypertension_compensation** ✅
  - determines whether HTN should be diverted to the RRD/VRO flow. Turn off for iMVP, I think.

## MAS

- **rrd_mas_disability_tracking** :x:
  - messages [#rrd-to-mas-tracking](https://dsva.slack.com/archives/C03FWHHGNBX) about eligible claims with "MAS-related" contentions (apnea, rhinitis, etc). We don't really care to be notified of these anymore. That channel is still occasionally useful for tracking failures.
- **rrd_mas_all_claims_tracking** ✅ 🔜 ❌ 
  - messages [#rrd-to-mas-all-claims](https://dsva.slack.com/archives/C046LCN145P) of _all_ eligible claims (subject to specific exceptions). We don't really use that high-volume channel, but this was pretty recent.
- **rrd_mas_notification** :x:
  - includes eligible claims with "MAS-related" contentions (apnea, rhinitis, etc) in the forward-to-MAS bucket. Superceded by the next one 👇 
- **rrd_mas_all_claims_notification** ✅
  - includes _all_ eligible claims (subject to specific exceptions) in the forward-to-MAS bucket. Also turns _off_ insertion of classification codes, which we do want to enshrine and ❌
- **rrd_hypertension_mas_notification** ✅
  - includes single-issue HTN CFI in the forward-to-MAS bucket. Currently off, so this is one of those specific exceptions. Turn on for iMVP launch.

## Other, mostly routing-related

- **rrd_add_special_issue** :x:
  - determines whether RRD/VRO'd claims get a special issue added, to enable specialty routing. We haven't needed this in months.
- **rrd_call_vro_service** ✅
  - determines whether RRD-diverted claims get sent to VRO instead of classic RRD. Turn on for MVP (VRO 1.0) launch, then remove once we have no RRD-diverted claims.
- **rrd_new_pact_related_disability** :x:
  - messages [#hypertension-claims-tracking](https://dsva.slack.com/archives/C03RDNXPFDL) about PACT-related claims for presumptive prototyping. We want to archive that channel anyway.

**Comment by dianagriffin** [comment]
Based on discussion with @nanotone 
- We believe we should turn off **rrd_asthma_compensation** now, but I will confirm
- To turn off flow of HTN after testing MVP launch, we will turn off **rrd_hypertension_compensation** and turn on **rrd_hypertension_mas_notification**
- **rrd_mas_disability_tracking** can be turned off and then removed
- **rrd_call_vro_service** we will turn this off after the post prod-deployment testing phase for MVP launch, although it won't matter because hypertension will be turned off anyway

**Comment by nanotone** [comment]
**rrd_asthma_compensation** has been turned off after [confirmation](https://dsva.slack.com/archives/C01BVF2A3V0/p1669223573469269?thread_ts=1669223565.065349&cid=C01BVF2A3V0).

**Comment by nanotone** [comment]
Now that initial MVP launch has been running smoothly for a few days, we are turning it off until iMVP. **rrd_hypertension_compensation** is off, and **rrd_hypertension_mas_notification** is on. [Slack thread](https://dsva.slack.com/archives/C01Q7979Z7D/p1669912895872679)
