### ISSUE TITLE
Investigate the option for VRO to use an alternative service instead of EVSS for document upload capability

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#579]
**User Story**

Based on investigation from #389 we believe that either using the BAM Claim Evidence API or connecting directly to the VBMS soap api may be the more expedient and feasible option for accessing document upload capabilities. We need to investigate and validate our options. 

Progress and results of this investigation should be shared in the #benefits-virtual-regional-office channel, tagging Rajesh, so that the Amida team is kept in the loop while they are continuing to investigate/test EVSS integration in parallel. 

**Acceptance Criteria**

1. Connectivity with BAM/BIP Claim Evidence API and/or the VBMS soap api has been investigated/tested deeply enough to determine its feasibility for VRO's document upload needs and the rough timeline/LOE it would take to integrate with it from VRO.
2. A recommendation has been made on whether or not to pursue either solution for doc uploading in iMVP.

**Not included in this work**

If the recommendation is to pursue VBMS or Claim Evidence API integration, this ticket does not include the actual implementation of that integration from VRO.

**Notes about work**
- #389 
- [slack thread](https://dsva.slack.com/archives/C03JRKKD11B/p1666625873141359)

**Comment by ENeal49** [comment]
Blocked - Development for Amida is blocked until they have decision on solution.

**Comment by dianagriffin** [comment]
@ENeal49 I'm wondering if we should remove the blocked label on this ticket, since although this is a blocking dependency for the Amida team's development, the work for our team to do the investigation covered by this ticket is not blocked -- does that make sense?

**Comment by ENeal49** [comment]
yes, removed

**Comment by dianagriffin** [comment]
@dianagriffin note to self as a reminder to let Michael Harlow know if/when we confirm we can use BIP instead of EVSS

**Comment by dianagriffin** [comment]
I'm closing this ticket as we've confirmed the Claim Evidence API's doc upload capabilities and have requests for access underway with the BIA team.
