### ISSUE TITLE
Support connection of VRO preprod environment with other VA preprod environments

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#581]
**User Story**

In collaboration with Amida (Ryan Plemons) and the MAS/IBM team (Narayanan Alavandar / Raymond Chu), connect the network between the newly created VRO pre-prod environment and other VA pre-prod environments so VRO can call systems with pre-prod data. 

The LHDI team has set up a new prod namespace to enable VRO to have a pre-prod environment with prod-like data that can connect to the ProdTest environment MAS uses. 
- Premal will have info to share from LHDI about next steps on the new env
- Diana can help coordinate an initial meeting with us, Amida, MAS/IBM to discuss the environment mapping needs

**Acceptance Criteria**

1. Network is connected between VRO pre-prod and other relevant VA system environments
2. Connections have been documented on the wiki, as well as where to go if we need to update something

**Not included in this work**

- Test user creation/setup

**Comment by ENeal49** [comment]
depend on preprod environments (Ryan with Amida has been working on it)

**Comment by dianagriffin** [comment]
@ENeal49 I'm going to close this ticket as Amida will be owning the [remaining steps](https://dsva.slack.com/archives/C01Q7979Z7D/p1672778602839409?thread_ts=1670951265.674709&cid=C01Q7979Z7D) to set up the preprod environment. Premal and I will support from a coordination perspective but I don't anticipate any hands-on work needed from our engineers.

**Comment by ENeal49** [comment]
@dianagriffin Closing under sprint k.
