### ISSUE TITLE
Remove rrd_new_pact_related_disability feature toggle and archive the #hypertension-claims-tracking slack channel

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#596]
**Acceptance Criteria**
- [x] The OCTO team is no longer being notified in the `#hypertension-claims-tracking` Slack channel of new hypertension claims that are submitted on VA.gov.
- [x] The Slack channel is archived by @amylai-nava 

**More about this work**
* The Slack notifications were set up as part of prototyping in vets-api for the presumptives work stream. Since RRD support for presumptive claims is being built in VRO, we no longer need the notifications in Slack.
* Original GH issue: [#176](https://github.com/department-of-veterans-affairs/abd-vro/issues/176)
* Duplicate of: https://github.com/department-of-veterans-affairs/abd-vro/issues/782

**Comment by dianagriffin** [comment]
- It's the Ruby code in vets-api
- potentially has some tests that would need to be removed
- @amylai-nava will archive the slack channel after this ticket is complete
