### ISSUE TITLE
Design different states for service connection section

### ISSUE THREAD

**Issue by shannonkford** [department-of-veterans-affairs/abd-vro#632]
# Overview # 
For iMVP, the presumptive service connection section (likely to be renamed) has been designed for the case in which the claimed contention is matched to hypertension and the AO flash has been found. Further detailed design is needed to accommodate other possible states that could happen in future iterations. Some of these include the following:

- No flash is found, but service keywords are found through OCR
- No flash and no keywords are found (likely to result in a non-RRD-able claim, so may not be valid)
- Service data is found through other systems
- A condition has multiple presumptive cohorts or time periods that may apply (for example, lymphoma)
- A condition has multiple possible DC codes (for example, asthma)

This is not an all-inclusive list. The states may change based on how the feature evolves over time.

### Links and resources
- [Slack conversation about related DC complications when there are more than one potentially related DC](https://dsva.slack.com/archives/C03C8661PAP/p1666301061538599)

**Comment by shannonkford** [comment]
# Example comments # 

- Hypertension is presumptive under 3.309(a) and 3.309(e)
- Lymphoma and other lymphatic cancers qualify under both pre PACT AO and PACT SWA and multiple dates would need to be addressed

**Comment by amylai-nava** [comment]
@shannonkford @KimLadin, this ticket was in our backlog and seems relevant for multi-issue claims, so I moved it to our Hypertension project board for refinement.
