### ISSUE TITLE
Document different VRO envs and their mapping to other systems' envs

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#641]
Sync up with Amida and their intended uses for the various envs. Document how VRO's different environments (`dev`, `qa`, `sandbox`, `prod-test`, `prod`, etc.) match up with other systems' environments. on the [Development-environments](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Development-environments) and [Deploying VRO](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Deploying-VRO
) wiki pages.
  - [LHDI's 4 initial namespaces (aka VRO environments)](https://animated-carnival-57b3e7f5.pages.github.io/container-platform/#team-namespaces-and-resources); describe how to create custom namespaces
  - [Slack thread](https://dsva.slack.com/archives/C03JRKKD11B/p1667416225212939?thread_ts=1667411869.377839&cid=C03JRKKD11B)
  - Diana's diagram in Slack (screenshot of a Mural) - Note in prodTest (for MAS and VRO end-to-end testing), LH prod and eFolder prod are being used as read-only data sources
  - [OAuth CCG for only sandbox and prod](https://dsva.slack.com/archives/C01Q7979Z7D/p1667490237314129?thread_ts=1666794837.297659&cid=C01Q7979Z7D)
  - Which API keys and other secrets do we have and for which environments (e.g., LH health API key for prod)? How do we update them?

**Comment by yoomlam** [comment]
Also document who approves deployment to certain envs (i.e., `prod-test` and `prod`) in [Deploying VRO](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Deploying-VRO) wiki page or a separate page. @emilytheis @dianagriffin

**Comment by yoomlam** [comment]
I added [VRO v1 Testing section](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Development-environments#vro-v1-testing), along with a VRO v2 Testing section.

@sethdarragile6 You'll likely want to contribute or provide feedback on the results of this ticket, as SecRel and security scans are involved.

**Comment by yoomlam** [comment]
Reason for higher story point: information gathering, verification, and coordination

**Comment by dianagriffin** [comment]
Premal created a draft environment mapping spreadsheet [in sharepoint here](https://dvagov.sharepoint.com/:i:/r/sites/vaabdvro/Shared%20Documents/VRO%20-%20Virtual%20Regional%20Office/VBMS_environments.png?csf=1&web=1&e=I4c3NZ) -- I'm assuming this info should get added to the wiki as part of this ticket

**Comment by pshahVA** [comment]
For full disclosure I got this from MAS

**Comment by ENeal49** [comment]
Amida documenting but OCTO will need to review and have oversight to ensure everything included.

**Comment by ENeal49** [comment]
Document what environments we want to connect to for our sandbox, prodtest and production environments. We've talked this through a long time ago with 
[@Emily Theis](https://dsva.slack.com/team/U01V6J7FA7N)
The connections are in the [spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/VRO%20-%20Virtual%20Regional%20Office/VRO%20Integrated%20MVP%20Schedule%20+%20Task%20Tracker.xlsx?d=w6b9a256e6ffb4a86b0171a5943d52a1f&csf=1&web=1&e=DVXXpF) in the second tab.

**Comment by yoomlam** [comment]
The assignee should confirm those connections in LHDI EKS and document where to look for the connection configurations.

**Comment by dianagriffin** [comment]
Inputs for updating the wiki documentation: 
- [spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/VRO%20-%20Virtual%20Regional%20Office/VRO%20Integrated%20MVP%20Schedule%20+%20Task%20Tracker.xlsx?d=w6b9a256e6ffb4a86b0171a5943d52a1f&csf=1&web=1&e=DVXXpF) 
- - compare to this diagram about end to end testing: https://dsva.slack.com/archives/C03JRKKD11B/p1667417082773049?thread_ts=1667411869.377839&cid=C03JRKKD11B (Note in prodTest (for MAS and VRO end-to-end testing), LH prod and eFolder prod are being used as read-only data sources)
- describe how to create custom namespaces (Diana can document the request process for this)
- Which API keys and other secrets do we have and for which environments (e.g., LH health API key for prod)? How do we update them? --> will need Ryan's input on this one.

**Comment by dianagriffin** [comment]
@ahay-agile6 After chatting with @yoomlam we realized that one next step that you could take on this ticket is to document and link to configuration settings for each VRO environment mapping.
- you can create a new section on [this page](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Development-environments) to add it (we'll clean up the page structure later)
- You'll have to collaborate with Ryan to get this information, as well as linking to some external documentation (like Lighthouse DI, for example)
Let us know if you have questions!

**Comment by dianagriffin** [comment]
@ahay-agile6 cc/ @ENeal49 I've removed the "high priority" label from this ticket as the elements of this work that are priority for supporting iMVP testing are being coordinated separately with MAS and Amida. 

The overall documentation is still an internal priority that overlaps with knowledge transfer and handoff from Amida, and should continue to be a priority for our sprint.

**Comment by dianagriffin** [comment]
Closing as covered by #1029
