### ISSUE TITLE
Document SD Elements

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#643]
Document SD Elements; accomplished milestones (e.g., ~170 items satisfied on Oct 2022 for VRO v1 deployment) and intentions  (e.g., N items to be satisfied in Dec 2022 for VRO v2)
  - contact Todd Pritts for details
  - [Slack thread](https://dsva.slack.com/archives/C031RRFCHV1/p1667489870977299?thread_ts=1667410784.729799&cid=C031RRFCHV1)

**Comment by sethdarragile6** [comment]
@tpritts-amida @yoomlam my document for this is [here](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#sd-elements)

[slack thread](https://dsva.slack.com/archives/C01Q7979Z7D/p1670630323875479)

**Comment by yoomlam** [comment]
@sethdarragile6 Looks great! Small feedback:

> Inherited - app team and app assessor determined that the requirement is handled completely by DI, SecRel or another organizational entity where no * effort on the app team is necessary

Typo: extra `*` ?

> A point person on the app team (i.e. the eng lead) assigns an Incomplete countermeasure to another member of the team (or themselves)

The point person could be you Seth, so remove `(i.e. the eng lead)` or change it to `(e.g., the eng lead)`

"app assessor" needs to be defined -- ask Rob for a definition. Does the assessor need to be someone on the SecRel team? Describe how the "app team" contacts the assessor.

**Comment by sethdarragile6** [comment]
> 

@yoomlam I've [addressed](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process/_compare/24fbafd0624db41a50bd64c41de09c019260157e...ddf2b0b3925e42431bb83ec7fa6ff6a25c90607b) your feedback, please re-review

**Comment by yoomlam** [comment]
@sethdarragile6 Great!
