### ISSUE TITLE
Increase timeout for va.gov / MAS claim handoff

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#660]
As part of the deployment of all claims hand-off to MAS (#580), the MAS team recommended increasing the timeout for our HTTP client to 120 seconds. See this [Slack thread](https://lighthouseva.slack.com/archives/C0309PZT20Z/p1667833158557319) for context.

**Notes about work**
Yoom did some really great initial research [in that thread](https://lighthouseva.slack.com/archives/C0309PZT20Z/p1667854297857299?thread_ts=1667833158.557319&cid=C0309PZT20Z) on where the timeout in Faraday comes from. Pasting it here:
- I don't see a relevant timeout setting in https://github.com/department-of-veterans-affairs/vets-api#L1100
- I don't see a timeout being set in the [MailAutomation client](https://github.com/department-of-veterans-affairs/vets-api/blob/92bd22c9ddd0a61888eccf5e65f37b99c3cadfbf/lib/mail_automation/client.rb#L7) (compared to [other API clients](https://github.com/department-of-veterans-affairs/vets-api/blob/532481dc554053f10307d26a99bc8c49b98467cb/lib/carma/client/mule_soft_client.rb#L49)), so it's probably using the default timeout
- Looking at the client's[ parent class Common::Client::Base](https://github.com/department-of-veterans-affairs/vets-api/blob/d25a599c2ffd930b869a49795d81e18dd165342c/lib/common/client/base.rb#L100) and [MailAutomation::Configuration](https://github.com/department-of-veterans-affairs/vets-api/blob/92bd22c9ddd0a61888eccf5e65f37b99c3cadfbf/lib/mail_automation/configuration.rb#L17), I don't see a default timeout being set, so it's probably using [Faraday's default timeout of 60 seconds](https://github.com/lostisland/faraday/issues/708#issuecomment-477614664), which is actually Net::HTTP's default timeout

**Comment by dianagriffin** [comment]
@nanotone could you add story points to this one? I'm making an assumption it's relatively small but that may just be wishful thinking. I've marked it as high priority under that assumption, thinking that if it's quick we should just get it out of the way since it looks like timeouts won't be uncommon at the 1min threshold -- but we might reassess priority if the lift is at all significant.

**Comment by nanotone** [comment]
I'm calling it a 2 -- small but not trivial.

We discussed in OCTO eng huddle the pros and cons of doing this, the primary downside being that vets-api workers might sometimes get bogged down with longer waits due to the increased timeout. I'm still inclined to do it, since it's likely much easier than waiting for the MAS API to decouple from waiting on BGS, and there are a bunch of reasons that vets-api won't be affected that much.

**Comment by nanotone** [comment]
Noting here that vets-api's common client does declare its own default timeouts, not in the client code but in its configuration: [15 seconds each for open() and read()](https://github.com/department-of-veterans-affairs/vets-api/blob/d25a599c2ffd930b869a49795d81e18dd165342c/lib/common/client/configuration/base.rb#L42-L43).

I'm going to leave the open timeout as-is (we haven't seen any evidence of slow opens), and bump the read timeout up to 120 seconds. I'll also hook it up to app settings, so we don't have to keep changing the code if we need further tweaks.
