### ISSUE TITLE
Wrap up SecRel and Dependabot documentation

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/abd-vro#662]
Some documentation tasks from [this ticket](https://github.com/department-of-veterans-affairs/abd-vro/issues/516) didn't quite get completed - need a little more time to wrap them up.

**Comment by sethdarragile6** [comment]
I've made some incremental progress on [this documentation](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/SecRel-Processing-Guide-(DRAFT)#secrel-processing-guide). Hoping to get all this to review state either today or tomorrow.

**Comment by sethdarragile6** [comment]
@yoomlam please have a look at [this](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/SecRel-Processing-Guide-(DRAFT)), let me know your thoughts. I've indicated places I'd like to fill out more, but the basic structure/template I was shooting for is more or less complete. As I mentioned on the [original ticket](https://github.com/department-of-veterans-affairs/abd-vro/issues/516), I have yet to complete the Dependabot guide- I'm aiming to crank that out tomorrow in basic form.

**Comment by yoomlam** [comment]
Looks great! See my edits [here](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/SecRel-Processing-Guide-(DRAFT)/_history) -- check two revisions checkboxes then click the "Compare revisions" button.

Tip to save time: don't add screenshots if you're able to describe it in words.

**Comment by sethdarragile6** [comment]
@yoomlam I've (finally) 
1. added the [Dependabot Processing Guide](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot#dependabot-processing-guide) to the existing Dependabot guide
2. added some key info to the [SecRel Processing Guide](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/SecRel-Processing-Guide), and
3. removed some now-redundant info from the [Secure Release process](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process) wiki page

Kindly review for any glaring omissions. Still a work in progress, but I think it's a solid base that I can chip at over time. Thanks for your patience

**Comment by yoomlam** [comment]
RE: the [Dependabot Processing Guide](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Dependabot#dependabot-processing-guide)
Looks great! Some suggestions:
- Deciding to accept the update, Step 1: SecRel needs to be manually run against the PR branch. It only runs automatically for the `develop` branch
- Step 4, the X-API-Key field: the test key values may change, best to link to the file on the `develop` branch
- Step 4, Test various endpoints: link to https://github.com/department-of-veterans-affairs/abd-vro/wiki/Testing-using-Swagger-UI
- "it's recommended to start a brand new PR": not sure I agree. GH tracks the history and every commit on the PR. I don't really see a problem with adding to the existing PR
- "tag(ging) @ au2" -- I try to not identify specific people so the documentation doesn't become outdated. Anyone can approve, especially if they worked on the relevant module

**Comment by yoomlam** [comment]
Let's call this Done.
