### ISSUE TITLE
Brainstorming on how to onboard asthma team

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#785]
– What information do they need to know? 
– What systems do they need access to? (how long does it take to get that access?) 
– Who is responsible for what part of onboarding? 
– How do we know when onboarding is done? 
– What does success look like?

**Comment by dianagriffin** [comment]
@carodew It may be implicit but to say it out loud: happy to pair on this. :)

**Comment by carodew** [comment]
I wonder if this ticket is moot due to there not being a new asthma team, and due to convos with Emily in Slack. Alternative: we could update it with new information.
