### ISSUE TITLE
Document risk of expanding to all ROs without training plan

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#786]
as discussed in retro

**Comment by carodew** [comment]
We discussed this risk in the stakeholder sync and are working on getting more information on the types of training being offered, I wonder if we can call this ticket done?

**Comment by lydiahooper** [comment]
That makes sense to me - It's been "documented"

**Comment by amylai-nava** [comment]
@carodew @lydiahooper I'm cleaning up the board and will mark this as done. Also [linking the notes](https://dsva.slack.com/archives/C01AXBZA3QR/p1671145811973659?thread_ts=1671115484.966659&cid=C01AXBZA3QR) about the different types of trainings.
