### ISSUE TITLE
Revamp Engineering Onboarding materials

### ISSUE THREAD

**Issue by ENeal49** [department-of-veterans-affairs/abd-vro#798]
Action items
- ???

Is this ready for me to work on?
Which document should I edit?

**Comment by yoomlam** [comment]
Created new Engineer Onboarding doc: https://docs.google.com/document/d/1SnJOqDtlb2UkO9DNczZHCVTTQURiCvp81hBJhrlv6Xs/edit?usp=sharing

[Requested a review](https://dsva.slack.com/archives/C031RRFCHV1/p1670366963243359) from other engineers
