### ISSUE TITLE
Create sample dataset from existing APIs

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/abd-vro#819]
As a team member of Product, Design or Research team, I would like to see sample datasets that are available for the current APIs to get a better understanding of the data that is available via these APIs and sample values for specific valuesets. This would allow us to potentially create some metrics around RVSRs touch time, cycle time, etc to understand how the ABD automation is changing the time taken during various claim processing stages.

Acceptance Criteria:
- 10 sample records for each API
- From non-prod environment (which environment would have the best quality data)
- Can we get linked data? Not critical
- List of APIs in scope
  - [Lighthouse Patient Health API](https://developer.va.gov/explore/health/docs/fhir?version=current)
  - [VBMS data via BIP API](https://dsva.slack.com/archives/C031RRFCHV1/p1664985813321919?thread_ts=1664982022.251799&cid=C031RRFCHV1)
  - [VBMS data via Lighthouse Veteran Verification V2 API ](https://dsva.slack.com/archives/C031RRFCHV1/p1668721458382549?thread_ts=1668708810.870479&cid=C031RRFCHV1)
  
Other Information -
  - [VRO data via MAS](https://gist.github.com/rajesh-Krishnasamy/ed169256ff17f51dc07cb671f450c5ce) - not required for this ticket. There is information on Sharepoint at - TBD

**Comment by dianagriffin** [comment]
> [VRO data via MAS](https://gist.github.com/rajesh-Krishnasamy/ed169256ff17f51dc07cb671f450c5ce)
- Sharepoint [overview on the annotation data structure](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/VRO%20-%20Virtual%20Regional%20Office/VRO%20Integrations/MAS%20Integrations/eFolder%20OCR%20Data%20Integration/Sample%20MAS%20OCR%20results%20JSON%20data.docx?d=w5adb5db41b0f4c59b4db7e1c705ba0d2&csf=1&web=1&e=KZZSSW)
- The gist linked above is a good source of truth for the claim and Veteran data that will be received when MAS notifies VRO of a claim, but as a quick summary, that data includes:
   - Veteran: SSN, DOB, First Name, Last Name, list of veteran flashes, + participantID
   - Claim: Benefit Claim Id, Claim Submission DateTime, Claim Submission Source, Contention
Name, Diagnostic Code (if available), Disability Action Type, ratedDisabilityId (only
applicable for increases)
