### ISSUE TITLE
Investigate deployment failures preventing removal of <helm del>

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#827]
See [slack thread](https://dsva.slack.com/archives/C04CA47HV96/p1670967573383859?thread_ts=1670944450.514279&cid=C04CA47HV96) for details. 

**Acceptance Criteria**

1. Remove `helm del` without causing deployment failures, or make an alternative recommendation for handling this issue

**Comment by yoomlam** [comment]
Not a priority until we have an OCTO DevOps person since we have a temporary functional solution.

**Comment by yoomlam** [comment]
This may be resolved as a result of #1186
