### ISSUE TITLE
Add onboarding materials to content audit spreadsheet

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/abd-vro#867]
Related to #835

## Resources
[Content audit spreadsheet](https://docs.google.com/spreadsheets/d/1WS5tYO2IzEF6Jk_Du06tTrjxndKAZvjw3aK--THZJ3w/edit?userstoinvite=rakshinda.aslam@agile6.com&actionButton=1#gid=0)

**Comment by lydiahooper** [comment]
Spreadsheet with inventory: https://docs.google.com/spreadsheets/d/1WS5tYO2IzEF6Jk_Du06tTrjxndKAZvjw3aK--THZJ3w/edit?usp=sharing

**Comment by carodew** [comment]
I'm declaring this done, I think we have enough in the content audit to be useful.
