### ISSUE TITLE
Upgrade SecRel to 4.1

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/abd-vro#888]
**Description**

A release candidate for major version 4.0.0 has [been released](https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1672771142066839).

Follow-up for #801 

**Acceptance Criteria**

1. Upgrade to SecRel 4.1.0
2. ~~More testing/tweaking of secrel4prs.yml generally, aiming for  about 8 minutes at PR time~~ (see #1005 )
3. Replacing secrel.yml with secrel4.yml, making it our "defacto" secrel scan and PR check
4. Update wiki documentation as needed ~~(e.g., since "Snyk results post to [Snyk.io](http://snyk.io/) instead of Github Security Center", remove any references to the Security Center)~~

**Comment by sethdarragile6** [comment]
Moved to Backlog, waiting on resolution of Aqua issues with SecRel 4 by the LH SecRel team

**Comment by yoomlam** [comment]
https://dsva.slack.com/archives/C03UA9MV1EH/p1675107172862209
> Teams must migrate to v4.0.0 by Feb 14th

**Comment by yoomlam** [comment]
Implemented. Waiting for @sethdarragile6 to investigate Aqua alerts resulting from the using SecRel 4.

**Comment by yoomlam** [comment]
Merged #1033. 
TODO: Once it's working consistently, disable SecRel 3 workflow.

**Comment by yoomlam** [comment]
@sethdarragile6 I've update some documentation to note that it's for SecRel 3. Can you update/add wiki documentation for SecRel 4?

**Comment by yoomlam** [comment]
Given [this news](https://dsva.slack.com/archives/C03UA9MV1EH/p1675889032166609), we should upgrade to 4.1 after Feb 14th -- so this ticket will carryover to next sprint. However we can continue with documentation for SecRel 4 mentioned above.

**Comment by dianagriffin** [comment]
@sethdarragile6 I think this issue was accidentally closed, so I'm reopening it based on it being in progress; correct me if I've misunderstood where it's at!

**Comment by sethdarragile6** [comment]
@dianagriffin you did the right thing, thank you! I believe this happened because I tried creating a branch from the issue itself, a newish beta feature, apparently. It would seem that by virtue of associating that branch to this issue, GH automagically closed the ticket when Yoom merged the branch into develop. I won't be creating branches this way again, I hate this sort of thing in most cases. Anyways, sorry for the confusion!

**Comment by yoomlam** [comment]
[Slack](https://dsva.slack.com/archives/C01Q7979Z7D/p1676504857730259?thread_ts=1676503886.646189&cid=C01Q7979Z7D): SecRel 4 doesn't create release images like SecRel 3 does, so we need to publish the release images then have SecRel 4 sign them. I'll work on this today.

**Comment by yoomlam** [comment]
GH Releases should now [works with SecRel 4](https://github.com/department-of-veterans-affairs/abd-vro/pull/1131#issuecomment-1435075129). I've disabled [SecRel 3](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/workflows/secrel.yml) so that any signed images are only coming from the [SecRel 4 workflow](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/workflows/secrel4.yml). If all goes well throughout Feb, we can delete the SecRel 3 workflow.
