### ISSUE TITLE
Create research ops documentation for onboarding / VRO (MVP)

### ISSUE THREAD

**Issue by shannonkford** [department-of-veterans-affairs/abd-vro#889]
Document processes and policies for doing research with claims adjudicators and other user groups so that onboarding teams know how we work through research projects and how to recruit users for studies, handle sensitive data, etc.

- [x] Initial draft
- [x] Review by design team members
- [ ] Second draft
- [ ] Review by broader team
- [ ] Finalize MVP version

Creating as a simple document for MVP.

**Comment by amylai-nava** [comment]
I'm marking this done for Narwhal. @shannonkford can you link the doc, pretty please? 🙂
