### ISSUE TITLE
Software conventions for Queue resilience architecture

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#900]
As a result of #565, we came to the agreement that VRO's reliance on RabbitMQ's auto-ack feature is suitable for our current iMVP needs, but a more configurable, extensible, and decoupled-from-RabbitMQ solution is desired for the future.

To get up to speed technically, see the Github comment thread starting with @nanotone's [recommendation on that ticket](https://github.com/department-of-veterans-affairs/abd-vro/issues/565#issuecomment-1346912814).

This ticket captures the research, distillation, and technical buy-in required to produce and document software conventions which serves two purposes:
- be a roadmap for Product & Engineering to write tickets (ready to refine) for implementing this "next-gen" solution
- be a reference document for engineers working on those tickets, or future engineers seeking to understand the architecture

**Acceptance Criteria** 
- Software conventions documentation is updated with guidelines that encourage RabbitMQ message resilience

References:
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/RabbitMQ-Microservice-reliability
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/Software-Conventions
- https://github.com/department-of-veterans-affairs/abd-vro/wiki/MAS-Integration---Camel-Routes

**Comment by yoomlam** [comment]
Based on https://github.com/department-of-veterans-affairs/abd-vro/issues/565#issuecomment-1351821588, I updated https://github.com/department-of-veterans-affairs/abd-vro/wiki/Software-Conventions -- [specific changes](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Software-Conventions/_compare/424762c8e03bc9e42e98f5963b1e1ab9cddee4b2...1e169bbaa35569985cab966e6fd1cf1b417060e2)

**Comment by msnwatson** [comment]
Changes LGTM
