### ISSUE TITLE
iMVP RFD and PDF logic changes

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#905]
**This ticket includes a list of small modifications to the iMVP RFD and PDF logic:**

- [x] **For the iMVP PDF for NEW and CFI hypertension claims**: If no observation date is available from OCR, input "no associated date" in the PDF rather than leaving it blank. 

  * @carodew @amylai-nava to confirm whether we input "no associated date" or leave the field blank. Note: it's possible that "Non-confident date: 12/**/2018" might come through the OCR data so we would need to account for that too from a column width perspective. **`update: confirmed that no associated date and non-confident date: mm/dd/yyyy should be displayed`**

- [x] **For NEW hypertension claims:** When checking whether there is the presence of a `hypertension condition` in Lighthouse to use to assess if there is sufficient evidence to mark the claim as RFD, only check for the presence of **encounter diagnoses**. Do not check for the presence of **problem list items.** 

  * @jbregstone will confirm what the current state of the logic is. **`update: confirmed on 1/11 that the logic has been updated`**
  * Original ticket for reference: https://github.com/department-of-veterans-affairs/abd-vro/issues/447#top

- [x]  **For NEW and CFI hypertension claims**: at minimum, 3 BP readings are needed to mark the claim RFD. Specifically:
  * For CFI, at minimum 3 BP readings are needed from the past year
  * For NEW claims where a HTN encounter diagnosis is present: at minimum, 3 BP readings in the last 2 years
  * For NEW claims where no HTN encounter diagnosis is found: at minimum, 3 BP readings in the last 2 years and one must be elevated (at or above 160/100)
  * **`update: Merged in #949 `**

![imvp-logic-1 12](https://user-images.githubusercontent.com/90278110/212431509-72fdc4b8-b067-4876-8b24-85b09860d991.png)

Relevant slack threads:
* https://dsva.slack.com/archives/C01Q7979Z7D/p1672172009573269
* https://dsva.slack.com/archives/C01Q7979Z7D/p1672858639904759

**Comment by carodew** [comment]
Here's a link to the [mock up in Figma](https://www.figma.com/file/gENy7VJcPxq35DmqCit5av/iMVP-designs?node-id=106%3A196&t=62f3lMnxIZqcYTnx-1). I'm waiting for a response from the rest of the design team regarding how they're planning to handle it in Next Gen just to ensure consistency.

**Comment by carodew** [comment]
Update – what's in the mock up is consistent with ARSD, and Next Gen hasn't designed for this scenario yet, so I think we're good to move forward from the design perspective.
