### ISSUE TITLE
GitHub Actions: Send a "Failure" message to Slack on any SecRel failure

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/abd-vro#927]
**User Story**

As an ABD-VRO developer, I want a Slack message sent about any failure of a SecRel scan, so that I (or anyone on the team) can take action and remediate immediately.

Currently, when a [SecRel scan](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/workflows/secrel.yml) [fails](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/3887624721), an email is sent out to the `abd-vro` outlook.com email account informing of the failure, with a direct link in the email to the particular run that failed. If the recipient of the email is not immediately notified of the failure for whatever reason, remediation of the SecRel finding could be delayed. By instead (or additionally) notifying on an open Slack channel, the chances of quicker remediation is improved. This would also help to reduce the dependency on just one single developer to quickly respond to SecRel findings going forward.

**Acceptance Criteria**

1. When a SecRel scan fails, notify the `#benefits-vro-devops` Slack channel of the failure, with a [link](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/workflows/secrel.yml) to the SecRel workflow page
2. (optional/nice-to-have) The notification provides a direct link to the failing run, such as [this](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/3887624721)

**Not included in this work**

For a first pass, we would send these notifications to the same Slack channel (`#benefits-vro-devops` ) as all other current build notifications. This will get noisy, so eventually we will likely want to send these notifications to a _separate_ Slack channel. This ticket will not address that, since we need to agree on a proper naming convention for ALL current and future automated Slack notifications. 

**Notes about work**
- [slack thread](https://dsva.slack.com/archives/C031RRFCHV1/p1673388204330409) that was the genesis of this ticket

**Comment by yoomlam** [comment]
Take a look at `.github/workflows/deploy-unsigned.yml` for reference.
