### ISSUE TITLE
Fix inconsistent recovery of app-1 container from rabbitmq restarts

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/abd-vro#959]
**User Story**

As a VRO developer, I want my calls to endpoints on the app-1 container to consistently recover when rabbitmq restarts, so that the overall system is resilient.

**Description**

When stopping and restarting the rabbitmq container, calls to endpoints will generally recover within a short time- but not always. Generally it seems that the longer rabbitmq is down, the less likely the system will recover- however, it's frustratingly hit or miss. Sometimes a quick restart of rabbitmq will return a timeout from the endpoints, but then the very next call will be successful. Other times, it will never return anything but timeouts- until you restart the app-1 container, which always seems to repair things.

**Steps to Reproduce (erm, some of the time)**

1. With all containers up and running in a healthy state, restart the `rabbitmq` container. Sometimes a quick restart will trigger this, but maybe stopping, then waiting for 5-15 minutes, then starting it up again will repro this more consistently 🤷‍♂️
2. Via swagger, PostMan or curl, POST to the `/v1/full-health-data-assessment` endpoint with 'diagnosticCode: "7101" or "6602"'. I used the default JSON from swagger, whose curl command is:
`curl -X POST "http://localhost:8080/v1/full-health-data-assessment" -H  "accept: application/json" -H  "X-API-Key: test-key-01" -H  "Content-Type: application/json" -d "{\"veteranIcn\":\"9000682\",\"diagnosticCode\":\"7101\",\"claimSubmissionId\":\"1234\",\"disabilityActionType\":\"NEW\"}"`
3. After hanging for 1 minute, a 500 is returned with the JSON response:
`{
  "claimSubmissionId": "1234",
  "message": "The OUT message was not received within: 60000 millis due reply message with correlationID: Camel-9DC219E44F72529-0000000000000007 not received on destination: amq.gen-eis9Gd7-rKgqJ4lcjHPQsg. Exchange[9DC219E44F72529-0000000000000006]"
}`

At this point (if the issue is repro'd) repeated calls to the endpoint will fail indefinitely until the app-1 container is restarted

**Acceptance Criteria**

1. Restarting the rabbitmq container should not require a restart of the app-1 container

**Notes about work**

Related to #527

**Comment by yoomlam** [comment]
low probability but if it happens, it will halt VRO.
