### ISSUE TITLE
Design QA for iMVP end-to-end testing

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#978]
We need to test that the PDF that is generated for iMVP is rendering correctly as we test with prod data. Design testing will likely start Monday January 30. We will review PDFs generated from the list of main testing scenarios and check off the design scenarios as we find them. If there are any gaps at the end, we may need to request specific test users to test for remaining design scenarios. 

## Activities

- [x] identify design testing scenarios and add to spreadsheet
- [x] C to attempt logging into prodtest environment (A to send her the links) 
  - **update: Amy or Diana can send the PDFs to C**
- [x] C to review PDFs once end-to-end testing begins!

## Open questions 
- How do we want to track design bugs? 
  - **update: In the [MAS-VRO Test Coordination Sheet](https://dsva.slack.com/archives/C0309PZT20Z/p1675110530377589) in Teams**
- Amy to follow up on how we would request additional test users for specific design scenarios (if not covered by the above)
  -  **update: We would coordinate with MAS**

## Links 
[Test Scenarios (Sharepoint)](https://dsva.slack.com/archives/C01Q7979Z7D/p1674260411823439?thread_ts=1674171275.802109&cid=C01Q7979Z7D)

**Comment by carodew** [comment]
tagging @amylai-nava for awareness.

**Comment by amylai-nava** [comment]
Closing as completed!
