### ISSUE TITLE
Set up DataDog charts and alerts for VRO in support of partner teams

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#998]
### User story
As a VRO engineer, I want to have a monitoring service in place for the VRO platform so that I can discover and respond to service issues as expediently as possible. 

### Context

LHDI provides [DataDog monitoring service](https://animated-carnival-57b3e7f5.pages.github.io/platform-tools/datadog/). Given that it is the LHDI-preferred tool, the starting assumption for this ticket is that DataDog should be enabled and set it up for VRO team to monitor our platform services. If, in the course of working on this ticket, it is determined that Datadog does not meet our team's needs, please surface for discussion with the team so that we can discuss the possibility of exploring other solutions. 

See comment thread for prior investigation/efforts towards setting up Datadog. For reference, a number of other teams building on LHDI have recently worked on similar Datadog setup efforts -- see #lighthouse-delivery-platform-support for recent relevant threads, and don't hesitate to reach out to those folks for advice. We shouldn't need to reinvent the wheel on this!

### Acceptance Criteria
1. In preparation for supporting partner teams, a monitoring service is enabled and set up for the VRO team to:
   - monitor resource usage in case they need to be increased
   - quickly identify crashed microservices or down services
   - check the health of VRO

**Comment by ahay-agile6** [comment]
1. access to Datadog at the VA: https://animated-carnival-57b3e7f5.pages.github.io/platform-tools/datadog/

**Comment by yoomlam** [comment]
[Get permission](https://dsva.slack.com/archives/C03UA9MV1EH/p1676043849752639) to set up monitors/alerts.

**Comment by nanotone** [comment]
Making a note here that the first 2 steps @ahay-agile6 posted -- creating/activating your DOTS Okta account -- are relevant to VRO, because LHDI Datadog also uses DOTS Okta. But step 3 diverges; LHDI Datadog is separate from va.gov Datadog.

**Comment by dianagriffin** [comment]
@dianagriffin note to self: update this ticket with requirements for desired monitoring related to error scenarios (see #1314 )

**Comment by dianagriffin** [comment]
Notes from backlog refinement discussion of this ticket:
- we have access to logs of each container
- K8s keeps track of how many times it restarts things; without Datadog it's a matter of someone regularly looking at K8s
- requires access; could wait until Raghu/Mason have access
- what we miss without Datadog is history (e.g. CPU usage and such)

**Comment by dianagriffin** [comment]
@dianagriffin create a separate ticket to cover working with CC to understand their initial monitoring needs

**Comment by dianagriffin** [comment]
For reference, there are a lot of other teams working on similar efforts -- see #lighthouse-delivery-platform-support for recent relevant threads

**Comment by dianagriffin** [comment]
@tcraghu will start out on this ticket and identify the steps/approach to complete this ticket. When access becomes an issue on 5/25, others can pair to help complete those steps.

**Comment by tcraghu** [comment]
Add VRO dashboard for datadog

**Comment by msnwatson** [comment]
I have reviewed the the "VRO on LHDI" dashboard and it seems to satisfy a great deal of the acceptance requirements for this ticket already.

I created a new logging view at https://lighthousedi.ddog-gov.com/logs?saved-view-id=948 which has all of the logs across all of our deployment environments. 

I also created a new monitor at https://lighthousedi.ddog-gov.com/monitors/134374 which will alert members of the team via email if there are any kubernetes pods that become unavailable
